Modify `disc` to add `disc` alternate (vinyl/record) icon
lucide-icons/lucide pull request #1014
Opened 2023-04-04 16:47 UTC by danielbayley

2023-04-04 16:57 UTC, karsa-mistmere commented
@danielbayley: the alternate icon violates the guidelines.

2023-04-05 05:57 UTC, karsa-mistmere commented
Nice fix, @danielbayley 😊
At first, I wasn't sure how it would work with variable stroke width, but I think it looks perfectly fine anywhere between 1 and 3 pixels.

2023-04-05 05:59 UTC, karsa-mistmere approved these changes

2023-04-05 22:06 UTC, jguddas requested changes

2023-04-05 22:06 UTC, jguddas commented on icons/disc-2.svg
> +  <polygon points="12,12 12,12 12,12" />
```suggestion
  <line x1="12" y1="12" x2="12" y2="12.01"/>
```

2023-04-12 18:48 UTC, ericfennis approved these changes

2023-04-12 18:49 UTC, merged