Add `messages-square` icon
lucide-icons/lucide pull request #1030
Opened 2023-04-10 12:20 UTC by danielbayley

2023-04-12 10:32 UTC, karsa-mistmere commented
Nice!

I actually have a few drafts for this which are pretty similar (heck, the smaller speech bubble is literally identical), but I actually prefer yours, as it's more consistent with the existing `message-square` icon:
![image](https://user-images.githubusercontent.com/17746067/231431762-0003de7d-1c80-4ce9-a351-30459d8a7297.png)

2023-04-12 10:32 UTC, karsa-mistmere approved these changes

2023-04-12 10:33 UTC, karsa-mistmere commented on icons/messages-square.json
> +    "conversation"
```suggestion
    "conversation",
    "copy",
    "multiple"
```

2023-04-12 17:36 UTC, danielbayley commented
> Nice!
> 
> I actually have a few drafts for this which are pretty similar (heck, the smaller speech bubble is almost identical), but I actually prefer yours, as it's more consistent with the existing `message-square` icon: ![image](https://user-images.githubusercontent.com/17746067/231431762-0003de7d-1c80-4ce9-a351-30459d8a7297.png)

I do like the last 2 though… Maybe add one as an alternate?

2023-04-14 20:57 UTC, ericfennis commented
I prefer the last one. The best use case for this one is I think a "conversation" which is more two message balloons on each site talking to each other. The current proposal is I think a bit off

2023-04-16 16:24 UTC, ericfennis requested changes

2023-04-16 16:24 UTC, ericfennis commented on icons/messages-square.svg
> +  <path d="M18 9h2c1.1 0 2 .9 2 2v10l-4-4h-6c-1.1 0-2-.9-2-2" />
I think we could use a bit more of the canvas, the icons will look better on 100% scale. The message balloon looks a bit squished now.

Suggestion improvement (right): 
<img width="57" alt="image" src="https://user-images.githubusercontent.com/11825403/232326420-5fa241cc-9fcd-4245-8c8e-13ea3d3133be.png">


```suggestion
  <path d="M14 9a2 2 0 0 1-2 2H6l-4 4V4c0-1.1.9-2 2-2h8a2 2 0 0 1 2 2v5Z" />
  <path d="M18 9h2a2 2 0 0 1 2 2v11l-4-4h-6a2 2 0 0 1-2-2v-1" />
```

2023-04-20 14:02 UTC, ericfennis approved these changes
Nice work!! LGTM

2023-04-20 14:02 UTC, merged