Realign baseline/add additional `case-*` icons
lucide-icons/lucide pull request #1041
Opened 2023-04-11 10:49 UTC by danielbayley

* camelCase
* snake_case
* kebab-case

2023-04-11 10:58 UTC, karsa-mistmere commented
I think it would be better for consistency to have kebab and snake case to use the same letter shapes, maybe something like this (3px radius for both instead of 4px for one and 2px for the other):
![image](https://user-images.githubusercontent.com/17746067/231139818-418ea56a-45c7-412d-bda8-e3244f8d7663.png)

Not sure about the use cases for these though. Where does VSCode use icons like this?
(I'm guessing that's where these originate from :D )

2023-04-27 16:58 UTC, karsa-mistmere requested changes

2023-04-27 16:58 UTC, karsa-mistmere commented on icons/case-snake.svg
> +  <line x1="17" x2="17" y1="8" y2="15" />
```suggestion
  <path d="M7 10v5" />
  <circle cx="4.5" cy="12.5" r="2.5" />
  <path d="M11 15h2" />
  <circle cx="19.5" cy="12.5" r="2.5" />
  <path d="M17 8v7" />
```

2023-04-27 16:58 UTC, karsa-mistmere commented on icons/case-kebab.svg
> +  <line x1="17" x2="17" y1="8" y2="15" />
```suggestion
  <circle cx="4.5" cy="12.5" r="2.5" />
  <path d="M7 10v5" />
  <path d="M11 12h2" />
  <circle cx="19.5" cy="12.5" r="2.5" />
  <path d="M17 8v7" />
```

2023-04-27 16:58 UTC, karsa-mistmere commented on icons/case-camel.svg
> +  <path d="M14 11h4.5c1.1 0 2 .9 2 2s-.9 2-2 2H14v-4z" />
```suggestion
  <circle cx="7" cy="12" r="3" />
  <path d="M10 9v6" />
  <path d="M14 11h4.5a2 2 0 0 1 0 4H14V7h4a2 2 0 0 1 0 4" />
```

2023-04-27 17:03 UTC, karsa-mistmere approved these changes

2023-04-27 17:11 UTC, jguddas commented
What about PASCAL_CASE?

2023-04-27 17:26 UTC, karsa-mistmere commented
Do you mean PascalCase? 🤔

2023-04-27 21:56 UTC, danielbayley commented
> What about *PascalCase?

@jguddas Would/could that be covered by https://lucide.dev/icons?search=case-upper? Difficult to express with only 2 letters…

2023-04-28 07:31 UTC, karsa-mistmere commented
> > What about *SCREAMING_SNAKE_CASE?
> 
> @jguddas Would/could that be covered by https://lucide.dev/icons?search=case-upper? Difficult to express with only 2 letters…

I think @jguddas meant an icon depicting `A_B` (or some other letters), which is `UPPER_SNAKE_CASE`, also known as `SCREAMING_SNAKE_CASE`

2023-04-28 17:39 UTC, danielbayley commented
> I think @jguddas meant an icon depicting … `UPPER_SNAKE_CASE`

I see. Well that one is a bit tricky because the upper case B can’t be made any smaller… But see what you think of my latest `push`ed changes… @jguddas @karsa-mistmere

2023-05-10 08:01 UTC, ericfennis approved these changes

2023-05-10 13:31 UTC, jguddas commented
How about making them all align to the same baseline rather than just entering them vertically?

2023-05-10 17:27 UTC, danielbayley commented
> How about making them all align to the same baseline rather than just entering them vertically?

@jguddas @karsa-mistmere Fixed.

2023-07-09 15:59 UTC, jguddas approved these changes

2023-07-13 09:24 UTC, karsa-mistmere reviewed
`case-snake-upper` sticks out like a sore thumb because of the different letter `A` shape, but I'm not sure how it could be fixed. :/

2023-07-13 15:05 UTC, jguddas commented
> `case-snake-upper` sticks out like a sore thumb because of the different letter `A` shape, but I'm not sure how it could be fixed. :/

We could change all the other A's to match :man_shrugging:

2023-07-14 09:40 UTC, danielbayley commented
> `case-snake-upper` sticks out like a sore thumb because of the different letter `A` shape, but I'm not sure how it could be fixed. :/

@karsa-mistmere @jguddas What about something like these…?

![preview](https://github.com/lucide-icons/lucide/assets/7797479/e6def77c-1492-439f-8528-492d984efa07)

2023-07-14 10:52 UTC, jguddas commented
> > `case-snake-upper` sticks out like a sore thumb because of the different letter `A` shape, but I'm not sure how it could be fixed. :/
> 
> Karsa Jakob Guddas What about something like these…?
> 
> ![preview](https://user-images.githubusercontent.com/7797479/253535148-e6def77c-1492-439f-8528-492d984efa07.svg)

Looks terrible IMO.

2023-07-14 12:56 UTC, jguddas commented
camel and lower case are also feel inconsistent.

2023-12-15 09:50 UTC, merged