Add `*-dot` icons
lucide-icons/lucide pull request #1042
Opened 2023-04-11 12:23 UTC by danielbayley

Correspond to `debug-step-*` _[codicons](https://microsoft.github.io/vscode-codicons/dist/codicon.html)_

2023-04-12 06:26 UTC, karsa-mistmere requested changes

2023-04-12 06:26 UTC, karsa-mistmere commented on icons/arrow-down-dot.json
Feels a bit incomplete and the names will clash should we decide to add other variations.
I'd suggest to go for a naming scheme like `arrow-up-from-dot` vs. `arrow-down-to-dot`.

2023-04-12 06:39 UTC, danielbayley commented on icons/arrow-down-dot.json
> Feels a bit incomplete

What’s missing?

2023-04-12 06:41 UTC, karsa-mistmere commented on icons/arrow-down-dot.json
What I meant by incomplete is that I could easily see how someone out there at some point might also want any other variation of `arrow-(up|down)-(from|to)-dot`, so we should make sure the current names won't clash with adding these later on.

2023-04-14 06:10 UTC, karsa-mistmere commented on icons/dot.json
> +    "step",
```suggestion
    "interpunct",
    "interpoint",
    "middot",
    "step",
```

2023-04-16 16:44 UTC, ericfennis approved these changes

2023-05-03 13:23 UTC, karsa-mistmere approved these changes

2023-05-03 13:23 UTC, merged