Add generic `window` icon
lucide-icons/lucide pull request #1045
Opened 2023-04-11 14:55 UTC by danielbayley

2023-04-11 15:00 UTC, karsa-mistmere commented
Hm, this looks a bit more like what `panel-top` should be.

This are two `window` icons from my drafts, I'd envision something more like this for an application window:
![image](https://user-images.githubusercontent.com/17746067/231204134-ce464c80-1010-4817-8058-5056444332cb.png)

2023-04-11 15:02 UTC, danielbayley commented
> Hm, this looks a bit more like what `panel-top` should be.

Yeah I was just thinking to close and add to that instead…

> This are two `window` icons from my drafts, I'd envision something more like this for an application window

But maybe keep open for app `window` vs `panel`…?

2023-04-12 09:02 UTC, karsa-mistmere requested changes

2023-04-12 09:02 UTC, karsa-mistmere commented on icons/window-mac.json
> +    "design",
```suggestion
    "design",
    "files",
```

2023-04-12 09:02 UTC, karsa-mistmere commented on icons/window.json
> +    "design",
```suggestion
    "design",
    "files",
```

2023-04-12 09:02 UTC, karsa-mistmere commented on icons/window-mac.json
> +    "application"
```suggestion
    "application",
    "executable"
```

2023-04-12 09:02 UTC, karsa-mistmere commented on icons/window.json
> +    "application"
```suggestion
    "application",
    "executable"
```

2023-04-14 06:08 UTC, karsa-mistmere requested changes
Both of these are currently off center, but I'm not sure about them anyways.

I know they're essentially my designs but there's a reason I haven't submitted them yet, I would love to see someone's fresh take on this.

2023-04-16 19:11 UTC, ericfennis commented
Are two variants not too specific? Can't we just design one for the same use case? 
Maybe it is just me but the Mac variant is not really recognizable as an application window.

2023-04-17 16:52 UTC, danielbayley commented
> Maybe it is just me but the Mac variant is not really recognizable as an application window.

I mean to a mac user (speaking as a longterm one, exclusively) it’s pretty much iconic as an app window…

2023-04-25 11:53 UTC, ericfennis commented
@karsa-mistmere Nice, yeah think this will do for both Mac and Windows users. Btw I am a Mac user as well.

2023-04-25 17:18 UTC, karsa-mistmere commented on icons/app-window.svg
> +  <line x1="10" x2="10" y1="5" y2="9" />
Let's make this a bit taller, like the Github icon is.
```suggestion
  <rect x="2" y="4" width="20" height="16" rx="2" />
  <path d="M10 4v4" />
  <path d="M2 8h20" />
  <path d="M6 4v4" />
```

2023-04-25 17:46 UTC, jguddas approved these changes

2023-04-25 17:49 UTC, merged