Add `list-restart` icon
lucide-icons/lucide pull request #1053
Opened 2023-04-12 13:13 UTC by danielbayley

Doubles as `debug-restart-frame` from [codicons](https://microsoft.github.io/vscode-codicons/dist/codicon.html)

2023-04-15 18:32 UTC, jguddas commented on icons/list-restart.svg
> +  <path d="m11 16 2.5-2.5c1-1 2.3-1.5 3.5-1.5 2.8 0 5 2.2 5 5s-2.2 5-5 5c-1.6 0-3.1-.8-4-2" />
```suggestion
   <path d="m11 16 2.5-2.5A5.02 5.02 0 1 1 13 20"/>
```

2023-04-16 19:15 UTC, ericfennis requested changes
Can you use the same refresh icon from `database-backup`?

2023-04-16 20:27 UTC, karsa-mistmere commented
> Can you use the same refresh icon from `database-backup`?

@ericfennis: There's a related PR, definitely let's keep them consistent. https://github.com/lucide-icons/lucide/pull/1051

2023-04-18 11:56 UTC, danielbayley commented
> > Can you use the same refresh icon from `database-backup`?
> 
> @ericfennis: There's a related PR, definitely let's keep them consistent. #1051

I think Illustrator has given me slightly different points (which I’ll fix) but essentially it is the same arrow…?

See also comment: https://github.com/lucide-icons/lucide/pull/1051#discussion_r1169919139

2023-04-28 08:20 UTC, ericfennis commented
Currently duplicates changes from #1121.

2023-04-29 13:51 UTC, danielbayley commented
> Currently duplicates changes from #1121.

@ericfennis Fixed. Not sure what happened there…

2023-05-03 06:26 UTC, karsa-mistmere commented on icons/list-restart.svg
> +  <path d="M12 18c.9 1.2 2.3 2 4 2 2.8 0 5-2.2 5-5 0-1.2-.4-2.3-1.3-3.2-1.8-1.8-4.6-1.8-6.4 0L11 14" />
Same optimization as in #1051
```suggestion
  <path d="M13 20a5 5 0 0 0 9-3 4.5 4.5 0 0 0-4.5-4.5c-1.33 0-2.54.54-3.41 1.41L12 16" />
```

2023-05-03 13:40 UTC, merged