Add `file-code-2` icon
lucide-icons/lucide pull request #1058
Opened 2023-04-12 22:30 UTC by danielbayley

2023-04-21 18:41 UTC, ericfennis requested changes
Nice icon, left some code suggestions.

2023-04-21 18:41 UTC, ericfennis commented on icons/file-code-2.svg
> +  <path d="M14.5 2H6c-1.1 0-2 .9-2 2v16c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V7.5L14.5 2z" />
This path should be the same as the other file icons.
```suggestion
 <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z" />
```

2023-04-21 18:42 UTC, karsa-mistmere commented
Just an idea: maybe if we add this, let's rename the current `file-code` to `file-code-2` and add this one as `file-code`, so that the layouts are consistent (no suffix => contents inside, `-2` suffix => contents to the side).

2023-04-21 19:00 UTC, danielbayley commented
> Just an idea: maybe if we add this, let's rename the current `file-code` to `file-code-2` and add this one as `file-code`, so that the layouts are consistent (no suffix => contents inside, `-2` suffix => contents to the side).

Yeah I noticed this inconsistency also… Would this require adding an alias in this particular case?

2023-04-21 19:17 UTC, karsa-mistmere commented
No, we can't add an alias for a name that will already taken.

2023-04-27 04:20 UTC, karsa-mistmere requested changes

2023-04-27 04:20 UTC, karsa-mistmere commented on icons/file-code-2.json
> +    "coding"
```suggestion
    "development"
```

2023-04-27 04:20 UTC, karsa-mistmere commented on icons/file-code.json
> +    "plist"
Why not add all these tags to the other version?

2023-05-03 14:40 UTC, merged