Add `rows` icon
lucide-icons/lucide pull request #1059
Opened 2023-04-12 22:43 UTC by danielbayley

https://lucide.dev/icons?search=columns

2023-04-13 05:04 UTC, karsa-mistmere requested changes
Yeah, this is a no brainer, although I think both icons should also have the `layout` category, and definitely some extra tags.

2023-04-13 05:04 UTC, karsa-mistmere commented on icons/rows.json
> +    "text"
```suggestion
    "text",
    "layout"
```

2023-04-13 05:04 UTC, karsa-mistmere commented on icons/rows.json
> +    "layout"
```suggestion
    "layout",
    "lines",
    "queue",
    "series",
    "list",
    "vertical",
    "horizontal"
```
(vertically listed items that have a horizontal orientation that's why both)

2023-04-14 17:11 UTC, danielbayley commented
> Icon

Moved to #1003…

2023-04-25 10:39 UTC, jguddas approved these changes

2023-04-25 10:53 UTC, karsa-mistmere approved these changes
LGTM!

2023-04-28 07:26 UTC, karsa-mistmere commented
This was closed automatically because of #1003

2023-04-28 08:17 UTC, ericfennis approved these changes

2023-04-28 08:17 UTC, merged