Add [`un`]`fold` icons
lucide-icons/lucide pull request #1060
Opened 2023-04-12 23:30 UTC by danielbayley

2023-04-13 05:20 UTC, karsa-mistmere commented on icons/fold.svg
These should use the same dotted line as our flip icons: https://lucide.dev/icons?search=flip

Maybe we should also add both orientations too.

2023-04-14 06:01 UTC, karsa-mistmere requested changes
I think these should probably go to the `layout` category. Other than that LGTM.

2023-04-14 06:01 UTC, karsa-mistmere commented on icons/fold-vertical.json
> +    "arrows"
```suggestion
    "arrows",
    "layout"
```

2023-04-14 06:01 UTC, karsa-mistmere commented on icons/unfold-horizontal.json
> +    "arrows"
```suggestion
    "arrows",
    "layout"
```

2023-04-14 06:01 UTC, karsa-mistmere commented on icons/unfold-vertical.json
> +    "arrows"
```suggestion
    "arrows",
    "layout"
```

2023-04-27 16:26 UTC, karsa-mistmere requested changes

2023-04-27 16:26 UTC, karsa-mistmere commented on icons/fold-horizontal.svg
> +  <polyline points="5,15 8,12 5,9" />
```suggestion
  <path d="M2 12h6" />
  <path d="M22 12h-6" />
  <path d="M12 2v2" />
  <path d="M12 8v2" />
  <path d="M12 14v2" />
  <path d="M12 20v2" />
  <path d="m19 9-3 3 3 3" />
  <path d="m5 15 3-3-3-3" />
```

2023-04-27 16:26 UTC, karsa-mistmere commented on icons/fold-vertical.svg
> +  <line x1="12" x2="12" y1="22" y2="16" />
```suggestion
  <path d="M12 22v-6" />
  <path d="M12 8V2" />
  <path d="M4 12H2" />
  <path d="M10 12H8" />
  <path d="M16 12h-2" />
  <path d="M22 12h-2" />
  <path d="m15 19-3-3-3 3" />
  <path d="m15 5-3 3-3-3" />
```

2023-04-27 16:26 UTC, karsa-mistmere commented on icons/unfold-horizontal.svg
> +  <polyline points="19,15 22,12 19,9" />
```suggestion
  <path d="M16 12h6" />
  <path d="M8 12H2" />
  <path d="M12 2v2" />
  <path d="M12 8v2" />
  <path d="M12 14v2" />
  <path d="M12 20v2" />
  <path d="m19 15 3-3-3-3" />
  <path d="m5 9-3 3 3 3" />
```

2023-04-27 16:26 UTC, karsa-mistmere commented on icons/unfold-vertical.svg
> +  <line x1="12" x2="12" y1="22" y2="16" />
```suggestion
  <path d="M12 22v-6" />
  <path d="M12 8V2" />
  <path d="M4 12H2" />
  <path d="M10 12H8" />
  <path d="M16 12h-2" />
  <path d="M22 12h-2" />
  <path d="m15 19-3 3-3-3" />
  <path d="m15 5-3-3-3 3" />
```

2023-04-27 16:52 UTC, karsa-mistmere approved these changes

2023-04-29 09:05 UTC, ericfennis approved these changes

2023-04-29 09:06 UTC, merged