Add/rename `braces`/`brackets`/`parenthesis` icons and improve `braces`/`json` metadata
lucide-icons/lucide pull request #1063
Opened 2023-04-13 12:26 UTC by danielbayley

2023-04-13 14:48 UTC, karsa-mistmere commented on icons/parenthesis.svg
This should probably be `parentheses` (with parenthesis as a tag)

2023-04-15 18:30 UTC, jguddas commented on icons/curly-braces.svg
> +  <path d="M16 19h1c1.1 0 2-.9 2-2v-3c0-1.1.9-2 2-2-1.1 0-2-.9-2-2V7c0-1.1-.9-2-2-2h-1" />
```suggestion
  <path d="M8 5H7a2 2 0 0 0-2 2v3a2 2 0 0 1-2 2 2 2 0 0 1 2 2v3a2 2 0 0 0 2 2h1"/>
  <path d="M16 19h1a2 2 0 0 0 2-2v-3a2 2 0 0 1 2-2 2 2 0 0 1-2-2V7a2 2 0 0 0-2-2h-1"/>
```

2023-04-15 18:30 UTC, jguddas commented on icons/square-brackets.svg
> +  <polyline points="16,5.1 21,5.1 21,19 16,19" />
```suggestion
  <path d="M16 5.1h5V19h-5"/>
  <path d="M8 19H3V5.1h5"/>
```

2023-04-17 17:53 UTC, ericfennis approved these changes
Nice work, love these icons!

2023-04-17 18:04 UTC, karsa-mistmere commented
I still think these are way too small.

Top row current, bottom row with this change, correlate these with most monospace fonts: https://fonts.google.com/?preview.text=%3C%7B%7D%3E&preview.text_type=custom&category=Monospace

![image](https://user-images.githubusercontent.com/17746067/232571861-cf47a254-7d76-4600-a129-6afdada44c97.png)

Chevrons and braces usually have a ratio much closer to our current version.

2023-04-18 14:06 UTC, danielbayley commented
> correlate these with most monospace fonts:
> …
> Chevrons and braces usually have a ratio much closer to our current version.

Some of those do have equal height though…

Since this is an icon font (nobody is going to be using Lucide for _actually coding_ (I hope! 😅) I’m not sure trying to match (most, but not all) existing monospace font proportions is a more important goal than having them look nice and consistent as a set…

@karsa-mistmere So are you pushing for the elongated versions, or saying just `curly-braces` should be, with the others smaller (or just chevrons) or some other combination…?

On a related note: should `chevrons-left-right` and `code` really be 2 separate icons?

2023-04-19 18:32 UTC, karsa-mistmere commented
> I’m not sure trying to match (most, but not all) existing monospace font proportions is a more important goal than having them look nice and consistent as a set…

You know, that's exactly my point: I don't think they're going to look consistent at all if their ratios are utterly unlike 99.9% of real life examples. :)

I've done some research:

* [Fontawesome](https://fontawesome.com/search?q=code)
  ![image](https://user-images.githubusercontent.com/17746067/233165768-d338805d-421c-4c4f-8ea8-1e3dadc47da0.png)
* [Material Icons](https://fonts.google.com/icons)
  ![image](https://user-images.githubusercontent.com/17746067/233165816-12e4c179-42d7-40ca-b146-9bf89288ee1e.png)
* [Codicons](https://microsoft.github.io/vscode-codicons/dist/codicon.html)
  ![image](https://user-images.githubusercontent.com/17746067/233165881-8c269869-617b-4136-91aa-0ef7937a0042.png)
* [Bootstrap icons](https://icons.getbootstrap.com/?q=code)
  ![image](https://user-images.githubusercontent.com/17746067/233167217-c7305b14-68da-4987-adbd-3c3977706148.png)
* [Remix Icon](https://remixicon.com/)
  ![image](https://user-images.githubusercontent.com/17746067/233165990-2cb17a27-4380-4775-8486-6184a8a738ef.png)
* [Phosphor Icons](https://phosphoricons.com/)
  ![image](https://user-images.githubusercontent.com/17746067/233166428-951790f6-ff99-41c4-a0ee-e8149c56b799.png)
* [Tabler icons](https://tablericons.com/)
  ![image](https://user-images.githubusercontent.com/17746067/233166804-122749a7-1453-41be-9e2a-751f134322f9.png)
* [Unicons](https://iconscout.com/unicons/explore/line)
  ![image](https://user-images.githubusercontent.com/17746067/233167035-74901e9c-c48c-4be8-ae4e-296d76a86c45.png)

Most have ratios pretty similar to what we currently have, and _in every single one of them_ the curly braces are taller if only by a little.

2023-04-19 18:41 UTC, karsa-mistmere commented
> On a related note: should `chevrons-left-right` and `code` really be 2 separate icons?

Ouch. That's a tough nut, and something we should probably investigate further.

Maybe `chevrons-*` icons should match the base chevron size, but I'm not entirely sure. It might be more consistent, but it's maybe somewhat less balanced:
![image](https://user-images.githubusercontent.com/17746067/233169668-2e27d0aa-53e7-4bea-9de5-4650b22a17f7.png)

2023-04-19 18:43 UTC, jguddas commented
> > On a related note: should chevrons-left-right and code really be 2 separate icons?

Should those be icons at all :wink:

2023-04-21 15:26 UTC, danielbayley commented
@karsa-mistmere Ok, so just `push`ed those changes… You can see how they are modelled here:

<img width="930" alt="Untitled" src="https://user-images.githubusercontent.com/7797479/233674613-67fc6145-1b9a-4b4f-8584-1dc4d28599fc.png">

<img width="374" alt="Untitled" src="https://user-images.githubusercontent.com/7797479/233675086-93364716-92b1-488a-96a3-f6bd853dc0b8.png">

The `chevrons-*`/`code` thing can be dealt with in a separate PR if necessary…

2023-04-21 15:29 UTC, karsa-mistmere requested changes

2023-04-21 15:29 UTC, karsa-mistmere commented on icons/square-brackets.svg
> +  <polyline points="16 3 19 3 19 21 16 21" />
```suggestion
  <path d="M16 3h3v18h-3" />
  <path d="M8 21H5V3h3" />
```

2023-04-21 15:29 UTC, karsa-mistmere commented on icons/parentheses.svg
> +  <path d="M16 3c5.3 5 5.3 13 0 18" />
Just a minor pixel perfection fix.
```suggestion
  <path d="M8 21A12.13 12.13 0 0 1 8 3" />
  <path d="M16 3a12.13 12.13 0 0 1 0 18" />
```

2023-04-21 15:29 UTC, karsa-mistmere commented on icons/square-brackets.json
> +    "development",
```suggestion
    "development",
```

2023-04-21 15:31 UTC, danielbayley commented
What do we think about this set being called simply `brackets`, `parentheses` and `braces` (with the latter being renamed from the current `curly-braces`, and `curly` moved to a `tag`)?

2023-04-21 15:45 UTC, karsa-mistmere commented
> What do we think about this set being called simply `brackets`, `parentheses` and `braces` (with the latter being renamed from the current `curly-braces`, and `curly` moved to a `tag`)?

Yeah, that would definitely work for me, but let's wait for @ericfennis' input first.

---

And for now something completely different: why are you using force push? 🤔 

![image](https://user-images.githubusercontent.com/17746067/233678725-c31f73eb-259e-4191-b952-8513212cc6f1.png)

I keep running into the error above because of these, and I think it's generally not a good idea anyway, since with force pushes, we're losing some of the commit history and history about changes made.

It's not a super big deal per se, but it certainly makes it harder to review your pull requests, since by the time I get to some notifications, the respective changes will have already been overwritten, so if it's not absolutely necessary, I would very much appreciate it if you just used regular pushes. 😅

2023-04-21 16:17 UTC, karsa-mistmere commented
We're force squashing them anyway, but while they're a work in progress, it's better to see all the revisions. :)
![image](https://user-images.githubusercontent.com/17746067/233685532-592397b3-e9de-46ed-86c2-18beb4648e11.png)

2023-04-21 16:25 UTC, danielbayley commented
> We're force squashing them anyway, but while they're a work in progress, it's better to see all the revisions. :)

Ok, cool.

2023-04-21 17:20 UTC, danielbayley commented
What do we think about these for `bracket-dot` and `bracket-error` (from codicons)… too much?

<img width="132" alt="Untitled" src="https://user-images.githubusercontent.com/7797479/233696559-91ef7ebc-8ecf-4057-a33b-32000b79043a.png">

2023-04-21 17:50 UTC, karsa-mistmere commented
@danielbayley: Not totally sure, but in either case, `braces-dot` should use the same dot as `bell-dot` will, or the other way around.

2023-04-27 21:00 UTC, ericfennis commented
@danielbayley @karsa-mistmere I'm ok with renaming them. These are the official names. But we maybe should aliases for backwards compatibility.

2023-04-27 22:31 UTC, danielbayley commented
> @danielbayley @karsa-mistmere I'm ok with renaming them. These are the official names. But we maybe should aliases for backwards compatibility.

Done.

2023-04-28 04:07 UTC, karsa-mistmere commented on icons/parentheses.json
> +    "formula"
```suggestion
    "formula",
    "function"
```

2023-04-28 04:08 UTC, karsa-mistmere approved these changes

2023-05-01 16:58 UTC, ericfennis approved these changes

2023-05-01 16:58 UTC, merged