Add `bell-dot` icon and refine `bell-*` icons
lucide-icons/lucide pull request #1064
Opened 2023-04-13 14:41 UTC by danielbayley

2023-04-13 16:39 UTC, danielbayley commented
> Hey @danielbayley, Can you provide these alternative at a 100% view?

Sure:

<img width="221" alt="Untitled" src="https://user-images.githubusercontent.com/7797479/231827123-437cce82-f4ed-4fa9-9c8b-49ffb07abd26.png">

2023-04-13 16:46 UTC, karsa-mistmere commented
Let's first wait for @ericfennis' two cents on this, to me the 3rd row looks the most balanced.

2023-04-15 18:28 UTC, jguddas commented on icons/bell-dot.svg
> +  <circle cx="18" cy="6" r="3" />
```suggestion
  <circle cx="18" cy="6" r="3"/>
  <path d="M18.6 13a7.4 7.4 0 0 0 2.4 4H3s3-2 3-9a6.1 6.1 0 0 1 6.3-6"/>
  <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"/>
```

2023-04-15 18:28 UTC, jguddas commented on icons/bell-minus.svg
> +  <path d="M21 6h-6" />
```suggestion
  <path d="M18.1 10a9.3 9.3 0 0 0 2.9 7H3s3-2 3-9a6 6 0 0 1 7.7-5.8"/>
  <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"/>
  <path d="M21 6h-6"/>
```

2023-04-15 18:28 UTC, jguddas commented on icons/bell-off.svg
> +  <path d="M10.3 21c.3.6 1 1 1.7 1s1.4-.4 1.7-1" />
```suggestion
  <path d="M8.7 3A6.02 6.02 0 0 1 18 8a21.3 21.3 0 0 0 .6 5"/>
  <path d="M17 17H3s3-2 3-9a4.67 4.67 0 0 1 .3-1.7"/>
  <path d="m2 2 20 20"/>
  <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"/>
```

2023-04-17 17:56 UTC, ericfennis approved these changes
I agree with @karsa-mistmere, LGTM!

2023-04-19 19:36 UTC, karsa-mistmere requested changes
Some optimizations could still be done.

2023-04-19 19:36 UTC, karsa-mistmere commented on icons/bell.svg
> +  <path d="M10.3 21c.3.6 1 1 1.7 1s1.4-.4 1.7-1" />
```suggestion
  <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9"/>
  <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"/>
```

2023-04-19 19:36 UTC, karsa-mistmere commented on icons/bell-ring.svg
> +  <path d="M22 8c0-2.3-.8-4.3-2-6" />
```suggestion
  <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9"/>
  <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"/>
  <path d="M4 2C2.8 3.7 2 5.7 2 8"/>
  <path d="M22 8c0-2.3-.8-4.3-2-6"/>
```

2023-04-19 19:36 UTC, karsa-mistmere commented on icons/bell-plus.svg
> +  <line x1="15" x2="21" y1="8" y2="8" />
```suggestion
  <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"/>
  <path d="M15 8h6"/>
  <path d="M18 5v6"/>
```

2023-04-19 19:36 UTC, karsa-mistmere commented on icons/bell-off.svg
> +  <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
```suggestion
  <path d="M8.7 3A6 6 0 0 1 18 8a21.3 21.3 0 0 0 .6 5"/>
  <path d="M17 17H3s3-2 3-9a4.67 4.67 0 0 1 .3-1.7"/>
  <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"/>
  <path d="m2 2 20 20"/>
```

2023-04-19 19:36 UTC, karsa-mistmere commented on icons/bell-minus.svg
> +  <line x1="15" x2="21" y1="8" y2="8" />
```suggestion
  <path d="M18.4 12c.8 3.8 2.6 5 2.6 5H3s3-2 3-9c0-3.3 2.7-6 6-6 1.8 0 3.4.8 4.5 2" />
  <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"/>
  <path d="M15 8h6"/>
```

2023-04-19 19:36 UTC, karsa-mistmere commented on icons/bell-dot.svg
> +  <circle cx="18" cy="8" r="3" />
```suggestion
  <path d="M19.4 14.9C20.2 16.4 21 17 21 17H3s3-2 3-9c0-3.3 2.7-6 6-6 .7 0 1.3.1 1.9.3" />
  <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"/>
  <circle cx="18" cy="8" r="3" />
```

2023-04-27 16:35 UTC, karsa-mistmere approved these changes

2023-04-27 21:03 UTC, ericfennis approved these changes

2023-04-27 21:03 UTC, merged