Add `circuit-board` icon
lucide-icons/lucide pull request #1065
Opened 2023-04-13 15:55 UTC by danielbayley

2023-04-13 16:03 UTC, karsa-mistmere commented
It's nice, but a bit heavy in comparison to `square`. 🤔 
We don't have it in writing yet, but in #650 we've drafted that icons should aim to have a similar visual weight.

2023-04-13 16:37 UTC, danielbayley commented
> It's nice, but a bit heavy in comparison to `square`.

I did try to get it into `square`… But there just isn’t sufficient space for 2 _vias_ without violating the _2px between elements_ rule.

2023-04-15 18:21 UTC, jguddas commented
Something like ![icon](https://user-images.githubusercontent.com/25524993/232246781-879833ee-f292-4acc-890c-a1d012af0e2f.svg) or ![icon (1)](https://user-images.githubusercontent.com/25524993/232246820-555a2b30-414e-4c42-9792-713e7298b6f6.svg) would work in the smaller square, with 2 wires and the 2px rule.

2023-04-16 09:40 UTC, danielbayley commented
> Something like ![icon](https://user-images.githubusercontent.com/25524993/232246781-879833ee-f292-4acc-890c-a1d012af0e2f.svg) or ![icon (1)](https://user-images.githubusercontent.com/25524993/232246820-555a2b30-414e-4c42-9792-713e7298b6f6.svg) would work in the smaller square, with 2 wires and the 2px rule.

I really like the second one actually…

2023-04-16 10:05 UTC, jguddas commented on icons/circuit-board.svg
> +  <path d="M7 21v-4c0-1.1.9-2 2-2h3.5" />
```suggestion
  <circle cx="14.5" cy="15" r="2" />
  <circle cx="9" cy="9" r="2" />
  <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />
  <path d="M11 9h4a2 2 0 0 0 2-2V3" />
  <path d="M7 21v-4a2 2 0 0 1 2-2h3.5" />
```

2023-04-16 12:34 UTC, karsa-mistmere approved these changes

2023-04-17 17:51 UTC, ericfennis requested changes
Some elements are not correctly aligned on the pixel grid.
<img width="518" alt="image" src="https://user-images.githubusercontent.com/11825403/232568609-f7942cf4-310f-47d2-8b62-3a3066f5d496.png">

2023-04-17 18:41 UTC, danielbayley commented
> Some elements are not correctly aligned on the pixel grid. <img alt="image" width="518" src="https://user-images.githubusercontent.com/11825403/232568609-f7942cf4-310f-47d2-8b62-3a3066f5d496.png">

Not sure why exactly, but Illustrator keeps randomly adding decimal values to things if/when I paste between VS Code… So annoying! Fixed anyway…

2023-04-18 07:04 UTC, ericfennis approved these changes
Nice work!

2023-04-18 07:04 UTC, merged