Add `pocket-knife` icon
lucide-icons/lucide pull request #1140
Opened 2023-04-22 00:06 UTC by danielbayley

Alternative:

<img width="41" alt="Untitled" src="https://user-images.githubusercontent.com/7797479/233750916-d963eaf3-5c15-41ad-9119-8d15fb293566.png">

2023-04-22 07:47 UTC, jguddas requested changes

2023-04-22 07:47 UTC, jguddas commented on icons/pocket-knife.svg
> +  <rect width="6" height="20" x="9" y="2" rx="3" />
The body needs to be bigger as to not violate the 2px rule
```suggestion
  <rect x="8" y="2" width="8" height="20" ry="4" />
```

2023-04-22 07:47 UTC, jguddas commented on icons/pocket-knife.svg
> +  <path d="M12 19h0" />
```suggestion
  <path d="M12 6h.01" />
  <path d="M12 18h.01" />
```

2023-04-22 07:48 UTC, jguddas commented
Very cute, not sure about the use case but I'm a fan :+1:

2023-04-22 11:03 UTC, karsa-mistmere commented
Really not sure about this, the original proposal definitely violated the 2px gap guideline, on the other hand, this new one doesn't quite look like a pocket knife any more. 🤷‍♂️

2023-04-22 11:09 UTC, karsa-mistmere commented
Not convinced about this, but maybe something similar?
![image](https://user-images.githubusercontent.com/17746067/233780724-514cc641-a7f5-4284-9bcf-1c86a3ba22d6.png)

As usually, our [required icon request input](https://github.com/lucide-icons/lucide/issues/new?assignees=&labels=%F0%9F%99%8C+icon+request&template=icon_request.md) would be really helpful here (use cases & similar icons).

2023-04-25 04:34 UTC, karsa-mistmere commented
I think let's go for just `pocket-knife-2` out of the two, it's more legible and fits the "multi tool" use case better.

2023-05-03 14:38 UTC, karsa-mistmere commented on icons/pocket-knife.svg
> +  <path d="M18 12v10h0c2.2 0 4-1.8 4-4V6" />
Some optimization + fixes for mismatched paths.
```suggestion
  <path d="M18 6h.01" />
  <path d="M6 18h.01" />
  <path d="M20.83 8.83a4 4 0 0 0-5.66-5.66l-12 12a4 4 0 1 0 5.66 5.66Z" />
  <path d="M3 2 2 3l2 2-2 2 2 2-2 2 2.67 2.67" />
  <path d="M18 11.66V22a4 4 0 0 0 4-4V6" />
```

2023-05-03 16:00 UTC, karsa-mistmere approved these changes

2023-05-03 20:32 UTC, danielbayley commented
> In @karsa-mistmere s version the corkscrew has more swoosh, I like swooshieness.

@jguddas Swooshy enough…?

2023-06-04 15:22 UTC, ericfennis approved these changes

2023-06-04 15:23 UTC, merged