new lock/unlock icons
lucide-icons/lucide pull request #1199
Opened 2023-05-01 14:12 UTC by cd16b

2023-05-01 16:21 UTC, jguddas requested changes

2023-05-01 16:21 UTC, jguddas commented on icons/lock-2.svg
> +</svg>
```suggestion
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <circle cx="12" cy="15.5" r="1" />
  <rect x="4" y="10" width="16" height="11" rx="2" />
  <path d="M8 10V5s0-2 4-2 4 2 4 2v5" />
</svg>
```

2023-05-01 16:21 UTC, jguddas commented on icons/unlock-2.svg
> +</svg>
```suggestion
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <circle cx="12" cy="15.5" r="1" />
  <rect x="4" y="10" width="16" height="11" rx="2" />
  <path d="M8 10V5s0-2 4-2 4 2 4 2" />
</svg>
```

2023-05-03 12:14 UTC, karsa-mistmere commented
Not sure about the shackle shape, the current, more geometric style fits the icon set better.

2023-05-03 12:14 UTC, closed without merging