Refine/add `message`[`-*`] icons
lucide-icons/lucide pull request #1208
Opened 2023-05-03 10:15 UTC by danielbayley

2023-05-03 15:35 UTC, ericfennis approved these changes
Nice LGTM!

2023-05-06 05:34 UTC, karsa-mistmere requested changes

2023-05-06 05:34 UTC, karsa-mistmere commented on icons/message-circle-question.svg
The question mark is off the grid.

2023-05-06 05:34 UTC, karsa-mistmere commented on icons/message-square-diff.svg
Not sure about this one, it doesn't look like a diff sign, more like the bottom half of the bubble is dashed for some reason. Can you try an alternate design here?

2023-05-06 05:34 UTC, karsa-mistmere commented on icons/message-square-warning.svg
This one looks out of proportion, if we can't fit a taller exclamation mark somehow (e.g. file-warning) let's just drop it.

2023-05-06 07:49 UTC, jguddas commented
How does it look compared to other circular icons?

2023-05-06 15:11 UTC, danielbayley commented on icons/message-circle-question.svg
Ok, uses the existing `?` now. Although I think all the question marks might need looking at in a separate PR…

2023-05-06 15:11 UTC, danielbayley commented on icons/message-square-diff.svg
Oops, meant to use the existing `path` from `file-diff`, this was a bit shorter for some reason…

2023-05-06 15:11 UTC, danielbayley commented on icons/message-square-warning.svg
That seems drastic; I think it looks recognisable enough as what it is… But anyway, possible alternatives:

<img width="92" alt="Untitled" src="https://user-images.githubusercontent.com/7797479/236632132-87cc1523-990d-49bd-a9fe-dbbafd4dd720.png">

<img width="253" alt="Untitled" src="https://user-images.githubusercontent.com/7797479/236632366-aaf56bbe-6e21-4951-a91f-e215a8c2eef3.png">

2023-05-06 15:22 UTC, jguddas commented
What about giving the first row a try, than we have more cohesion with the other circular icons?
 ![image](https://user-images.githubusercontent.com/25524993/236632939-5f3db5ea-d3cd-4b51-b795-d90e1e229a74.png)

2023-05-06 15:24 UTC, danielbayley commented
> How does it look compared to other circular icons?

@jguddas Isn’t that what the new [Preview cohesion](https://github.com/lucide-icons/lucide/pull/1208#issuecomment-1532775971) is for…? :) Nice improvement by the way! Is it selecting icons at random to compare? (I haven’t looked over the code…) If not, I think `circle`[`-`something] should be in there, obviously based on this…

Anyway, the message `circle` is larger than it was before, but 1px less radius than `circle` to accommodate the pointer, bottom left…

2023-05-06 15:41 UTC, jguddas commented
> > How does it look compared to other circular icons?
> 
> @jguddas Isn’t that what the new [Preview cohesion](https://github.com/lucide-icons/lucide/pull/1208#issuecomment-1532775971) is for…? :) Nice improvement by the way! Is it selecting icons at random to compare? (I haven’t looked over the code…) If not, I think `circle`[`-`something] should be in there, obviously based on this…
> 
> Anyway, the message `circle` is larger than it was before, but 1px less radius than `circle` to accommodate the pointer, bottom left…

It still feels a bit small to me.

The cohesion preview has square icons in the first row and random icons in the last row.

2023-05-06 16:03 UTC, danielbayley commented
> What about giving the first row a try

<img width="227" alt="Untitled" src="https://user-images.githubusercontent.com/7797479/236634546-c85af4d1-de19-42c2-b8fd-ebad9191fa3f.png">

<img width="503" alt="Untitled" src="https://user-images.githubusercontent.com/7797479/236634580-8bf4012d-4881-4b97-9dc7-1c67a09c4e22.png">

> It still feels a bit small to me.

Well bigger than they were… I just think the pointer gets a bit too drowned out by the full 20x20 circle…

> And we should really take a look at the question mark for all icons where it is used.

Yeah, as mentioned https://github.com/lucide-icons/lucide/pull/1208#discussion_r1186709729, I think that’s for a separate PR though…

2023-05-06 16:05 UTC, jguddas commented
@karsa-mistmere you are the expert here, I prefer the bigger one, what do you think?

2023-06-25 08:12 UTC, ericfennis commented
@danielbayley Can you rebase the branch?

2023-06-25 10:21 UTC, danielbayley commented
> @danielbayley Can you rebase the branch?

Done…

2023-08-04 08:50 UTC, ericfennis approved these changes

2023-08-06 21:18 UTC, danielbayley commented
I also have these, which I think are nicer than the current `circle-message-*` variants…

![preview](https://github.com/lucide-icons/lucide/assets/7797479/de916cc4-a66f-414a-a534-0bf2f2f067b8)

What do you guys think? @ericfennis @karsa-mistmere @jguddas

2023-08-12 19:22 UTC, jguddas commented
> I also have these, which I think are nicer than the current circle-message-* variants…

Yeah, those are awesome, could be the default so `message`, and the circle variant is `message-circle`.

2023-08-12 19:49 UTC, danielbayley commented
> Yeah, those are awesome, could be the default so `message`, and the circle variant is `message-circle`.

3 variants seems like overkill though… I would vote these as default `message` and `massage-square`, dropping the current `message-circle`s…

What do you guys think of that?

2023-08-13 08:06 UTC, karsa-mistmere commented
> What do you guys think? @ericfennis @karsa-mistmere @jguddas

To be honest, I very much prefer the existing ones - I think those two (message-square and message-circle) are pretty well-established shapes, and while this one does look nice it is much less universal and I think the reduced dimensions will eventually prove to be just a bit too tight (e.g. the back/forward variants are already pretty dense as compared to what would be ideal).

2023-08-13 09:39 UTC, ericfennis commented
I also prefer the existing ones. So I agree with @karsa-mistmere on this.

2023-08-13 15:50 UTC, danielbayley commented
> reduced dimensions will eventually prove to be just a bit too tight 

@karsa-mistmere There is actually _more_ space, horizontally… For example, I can’t fit the nice `voicemail`/note variant into `message-square`, or even the current iteration of `message-circle` (see also https://github.com/lucide-icons/lucide/pull/1208#issuecomment-1537171887.

What do we think of @jguddas suggestion to add them simply as `message`?

Seems a shame to waste them…

2023-08-13 19:02 UTC, karsa-mistmere commented
Sidenote: I did think of maybe "fixing" `message-square`'s visual weight and centre of gravity instead, but I'm not convinced of this either, the previous shape just feels better.
![image](https://github.com/lucide-icons/lucide/assets/17746067/c758290f-6bd2-4d63-a131-edf1736ee532)
![image](https://github.com/lucide-icons/lucide/assets/17746067/3f8628ac-8dc9-4573-99af-456b2efc2e1f)

2023-08-18 00:58 UTC, danielbayley commented
> Sidenote: I did think of maybe "fixing" `message-square`'s visual weight and centre of gravity instead, but I'm not convinced of this either, the previous shape just feels better.

@karsa-mistmere Maybe slightly—they are nice—but also feels like it technically ought to be the same width as https://lucide.dev/icons/rectangle-horizontal. These don’t look bad… and the extra space does afford `message-square-voicemail`, which would be a nice addition. See what you guys think… cc: @jguddas @ericfennis 

![preview](https://github.com/lucide-icons/lucide/assets/7797479/7494fa25-8e34-4357-a88e-d31293abc955)

2023-11-06 10:27 UTC, ericfennis requested changes
Nice I think this one is almost good to go.
I've doubts about use-cases for `message-dot`.
And `message-square-text-quote` is a bit hard to see on 100%. Probably `message-square-quote` is better suited for this usecase.

Can you remove `message-square-text-quote`? And provide a use-case for `message-dot`? I do not approve `active` states to use dots.

2023-12-13 20:13 UTC, ericfennis approved these changes

2023-12-13 20:14 UTC, merged