feat: improved folders
lucide-icons/lucide pull request #1223
Opened 2023-05-06 13:58 UTC by jguddas

2023-05-08 20:56 UTC, ericfennis approved these changes
Nice changes, looks perfect to me!

2023-05-09 08:41 UTC, karsa-mistmere requested changes

2023-05-09 08:41 UTC, karsa-mistmere commented on icons/folder-symlink.svg
Not sure about this one, it's not consistent with `file-symlink` and changes the meaning a bit too much imo.

2023-05-09 08:41 UTC, karsa-mistmere commented on icons/folder-heart.svg
The heart shape fell victim to overoptimization and is not pixel perfect anymore.

2023-05-09 08:41 UTC, karsa-mistmere commented on icons/folder-output.svg
Also not consistent with `file-output`.

2023-07-17 09:59 UTC, jguddas commented
@karsa-mistmere do you want me to drop the files that you added comments to?

2023-07-17 10:15 UTC, karsa-mistmere reviewed
> @karsa-mistmere do you want me to drop the files that you added comments to?

Not necessarily, but all of those issues need to be addressed in some way:

* `folder-heart`: the icon could definitely be better optimized, but that needs some tweaking for heart, for which I've added a suggestion
* `folder-symlink`: either file-symlink will have to be updated to match, or `folder-symlink` needs to remain consistent with `file-symlink` (optimisation aside)
* the same is true for `folder-output` and `file-output`: I'm fine with either design but I think it would need to be consistent throughout all file and folder icons, this affects a **_lot_** of icons, namely `file-code/archive/audio/check-2/code-2/cog/digit/heart/input/json-2/key-2/lock-2/plus-2/minus-2/search/type-2/video-2/volume/x-2`.

2023-07-17 10:15 UTC, karsa-mistmere commented on icons/folder-heart.svg
> +  <path d="M21.1 17.5a2.5 2.5 0 1 0-3.26-3.79l-.34.39-.3-.4a2.5 2.5 0 1 0-3.29 3.75L17.5 21Z" />
This is the best I could do that didn't affect the shape and size too much:
```suggestion
  <path d="M13.9 17.45c-1.2-1.2-1.14-2.8-.2-3.73a2.43 2.43 0 0 1 3.44 0l.36.34.34-.34a2.43 2.43 0 0 1 3.45-.01v0c.95.95 1 2.53-.2 3.74L17.5 21Z" />
```

2023-10-18 07:25 UTC, ericfennis commented
@jguddas Can you rebase this PR and take a look at the comments from @karsa-mistmere ?

2023-10-18 08:29 UTC, karsa-mistmere approved these changes

2023-10-20 07:27 UTC, merged