Add `layout-list-check` icon
lucide-icons/lucide pull request #1232
Opened 2023-05-08 10:24 UTC by danielbayley

`tasklist` from octicons: https://primer.style/design/foundations/icons/tasklist-16, used right here 👆🏼

<img width="464" alt="Untitled" src="https://user-images.githubusercontent.com/7797479/236800668-00af489c-24f4-488f-9c3b-70544b3e2fc1.png">

2023-05-08 15:32 UTC, jguddas commented
What about changing the layout list from 4 to 3 lines?

2023-05-08 15:44 UTC, danielbayley commented
> What about changing the layout list from 4 to 3 lines?

Fine with me, although it’s currently modelled on https://lucide.dev/icon/layout-list

2023-05-08 15:54 UTC, jguddas commented
> > What about changing the layout list from 4 to 3 lines?
> 
> Fine with me, although it’s currently modelled on https://lucide.dev/icon/layout-list

We would need to change it for all the layout lists, but then we have it consistent with the rest of the list icons.

2023-05-08 16:51 UTC, danielbayley commented
> We would need to change it for all the layout lists, but then we have it consistent with the rest of the list icons.

`push`ed…

2023-05-08 17:18 UTC, jguddas approved these changes

2023-05-08 19:18 UTC, karsa-mistmere commented
I think this use case is already covered by https://lucide.dev/icon/list-checks?search=Todo

2023-05-09 08:47 UTC, karsa-mistmere commented
@ericfennis: That one's maybe a bit too tiny though, maybe we could replace that with a pair of these (2nd & 3rd)?
![image](https://user-images.githubusercontent.com/17746067/237044274-516766f9-8324-44a0-809d-afd0c613ec3f.png)
`list-todo` & `list-checks`

These would maybe match `list-ordered` more.

2023-05-16 19:15 UTC, danielbayley commented
@karsa-mistmere @jguddas @ericfennis Implemented…

2023-05-17 07:23 UTC, karsa-mistmere commented on icons/layout-list.svg
I'm not in favour of this change, I think `layout-list` should be consistent with other grid and layout icons, not the list icons and this would break that.

2023-05-17 07:26 UTC, karsa-mistmere requested changes
The other two should however be more consistent with other list icons, e.g.:
![image](https://github.com/lucide-icons/lucide/assets/17746067/93848472-8356-4cc5-a53f-b5c6e3460ff7)

I also added these as suggestions.

2023-05-17 07:26 UTC, karsa-mistmere commented on icons/list-todo.svg
> +  <path d="M14 18h7" />
```suggestion
  <rect x="3" y="5" width="6" height="6" rx="1" />
  <path d="m3 17 2 2 4-4" />
  <path d="M13 6h8" />
  <path d="M13 12h8" />
  <path d="M13 18h8" />
```

2023-05-17 07:26 UTC, karsa-mistmere commented on icons/list-checks.svg
> +  <path d="M14 18h7" />
```suggestion
  <path d="m3 17 2 2 4-4" />
  <path d="m3 7 2 2 4-4" />
  <path d="M13 6h8" />
  <path d="M13 12h8" />
  <path d="M13 18h8" />
```

2023-05-17 22:01 UTC, ericfennis commented
I'm don't we should change the layout-list icon. Layout list is used for card lists with images or something else. Now it is turned into a list with check boxes.

2023-05-18 07:35 UTC, jguddas commented
What about something like this for `layout-list`? ![circle (6)](https://github.com/lucide-icons/lucide/assets/25524993/219b1bf5-fbbf-4517-9971-cd6f03bc7c06)

2023-05-18 12:14 UTC, karsa-mistmere commented
> What about something like this for `layout-list`? ![circle (6)](https://user-images.githubusercontent.com/25524993/239172008-219b1bf5-fbbf-4517-9971-cd6f03bc7c06.svg)

@jguddas: This would still be very inconsistent with `grid` and other `layout-*` icons.

@danielbayley: Since Eric and I both agree, let's keep `layout-list` as it is, the others are good to go.

2023-05-23 16:11 UTC, ericfennis approved these changes

2023-06-23 06:01 UTC, karsa-mistmere approved these changes

2023-06-23 06:02 UTC, merged