Refine/add `scissors`[`-square`] icon
lucide-icons/lucide pull request #1266
Opened 2023-05-11 20:22 UTC by danielbayley

2023-05-11 20:42 UTC, jguddas commented
You might not be able to cut with them, but they do look cute and that's all that counts.

Don't know if the square version works with 3px stroke width 🤔

2023-05-11 20:47 UTC, jguddas commented
gap could be smaller <img width="129" alt="image" src="https://github.com/lucide-icons/lucide/assets/25524993/1783f769-d70a-4375-9262-148edcf49fa7">

2023-05-11 21:14 UTC, danielbayley commented
> gap could be smaller

I’m pretty sure the gap was a violation before… I opted to prioritise snapping to the grid, should I not?

2023-05-11 22:13 UTC, jguddas commented
> I opted to prioritise snapping to the grid, should I not?

@karsa-mistmere what do you think?

My feeling tends more towards snapping.

2023-06-21 07:23 UTC, ericfennis approved these changes
@danielbayley Love these ones!
Nice work

2023-06-21 14:41 UTC, danielbayley commented
See also latest `push` https://github.com/lucide-icons/lucide/pull/1266#issue-1706498056

2023-06-23 06:28 UTC, karsa-mistmere commented
> > I opted to prioritise snapping to the grid, should I not?
> 
> @karsa-mistmere what do you think?
> 
> My feeling tends more towards snapping.

Ah yes, the ever so present negative space issue we keep running into. 😆 

![image](https://github.com/lucide-icons/lucide/assets/17746067/964ccaee-83c3-4498-a964-90dc8753d8b1) 
![image](https://github.com/lucide-icons/lucide/assets/17746067/a5c9a024-0a12-4b36-b441-7748db925151)

Column no.1: snapping to grid
Column no.2: exactly 2px gap
Column no.3: exactly 1px gap
Column no.4: current version

Rows are at 1, 2 and 3px stroke width respectively.

I think that:
- at 1px stroke width col.3 looks best.
- at 2px stroke width col.4 does.
- at 3px stroke width col.1 does

Therefore: I think we should stick with col.2 where all three look equally mediocre. :D

2023-06-23 11:28 UTC, danielbayley commented
> a gap of exactly 2px as opposed to snapping to the grid

@karsa-mistmere Done.

2023-07-13 08:02 UTC, karsa-mistmere requested changes

2023-07-13 08:02 UTC, karsa-mistmere commented on icons/scissors.svg
> +  <path d="M20 4 8.2 15.8" />
There seems to be an issue with optimisation:

Original outline:
![image](https://github.com/lucide-icons/lucide/assets/17746067/f7acaf9e-80b5-4495-a81c-87af4c36957a)

New outline:
![image](https://github.com/lucide-icons/lucide/assets/17746067/a371be0c-f412-4ebe-957f-59a10e41d852)
(note gaps)

2023-07-13 08:02 UTC, karsa-mistmere commented on icons/scissors-line-dashed.svg
> +</svg>
All of these could also do with an extra decimal of precision:
![image](https://github.com/lucide-icons/lucide/assets/17746067/33dfb823-3067-4543-9002-6fc83920b3a4)

2023-07-17 08:01 UTC, karsa-mistmere requested changes

2023-07-17 08:01 UTC, karsa-mistmere commented on icons/scissors-square-dashed-bottom.svg
This one still has some misaligned paths.

2023-07-17 08:01 UTC, karsa-mistmere commented on icons/scissors-square.svg
Also has some misaligned paths.

2023-07-17 12:55 UTC, karsa-mistmere approved these changes

2023-07-17 17:56 UTC, ericfennis approved these changes

2023-07-17 17:57 UTC, merged