Add `swatch-book` icon/improve `palette`/`brush` icons metadata
lucide-icons/lucide pull request #1280
Opened 2023-05-16 10:50 UTC by danielbayley

2023-05-16 13:37 UTC, karsa-mistmere commented on icons/swatch-book.svg
> +  <path d="M6 18h.01" />
I agree with @jguddas, let's keep it simple.
```suggestion
  <path d="M11 17a4 4 0 0 1-8 0V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2Z" />
  <path d="M16.7 13H19a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2H7" />
  <path d="M 7 17h0.01" />
  <path d="m11 8 2.3-2.3a2.4 2.4 0 0 1 3.404.004L18.6 7.6a2.4 2.4 0 0 1 .026 3.434L9.9 19.8" />
```

It's also maybe a bit too large and definitely not optimized enough:
![image](https://github.com/lucide-icons/lucide/assets/17746067/36bfd44f-6393-448d-9c2c-f26af6043ae8)
![image](https://github.com/lucide-icons/lucide/assets/17746067/376e2e75-2004-42d1-88c9-6718e7dd4bb2)

2023-05-16 14:48 UTC, jguddas commented on icons/color-wheel.svg
> +  <circle cx="12" cy="12" r="4" />
```suggestion
  <circle cx="12" cy="12" r="10" />
  <circle cx="12" cy="12" r="4" />
  <path d="M12 2v6" />
  <path d="m14.8 9.2 4.3-4.3" />
  <path d="M16 12h6" />
  <path d="m14.9 14.8 4.2 4.3" />
  <path d="M12 16v6" />
  <path d="m4.9 19.1 4.3-4.3" />
  <path d="M2 12h6" />
  <path d="m4.9 4.9 4.3 4.3" />
```

2023-05-17 07:20 UTC, karsa-mistmere commented
Not sure about the name and use case for color wheel, I mean it's not going to be very colourful, is it? 😄

2023-06-06 19:39 UTC, danielbayley commented
> Not sure about the name and use case for color wheel, I mean it's not going to be very colourful, is it? 😄

@karsa-mistmere Ha depends how you render it… But no, it was meant more as an icon for the tool, rather than the actual thing itself (in the same vein as `spray-can`/`pipette` et al… I’ve dropped it for now in this PR, but will need something like it for another project at some point…

2023-06-08 11:33 UTC, ericfennis approved these changes

2023-06-24 06:04 UTC, danielbayley commented on icons/eclipse.json
> +    "development",
> This again feels a bit like a brand icon in disguise, not in favour of this approach.

@karsa-mistmere What brand? 🤷🏻‍♂️ I had no idea! 😅

As mentioned https://github.com/lucide-icons/lucide/pull/1280#issue-1711764461, it’s was taken _directly_ from https://lucide.dev/icons/sun-moon, and scaled up… and is primarily meant to be a nice dark/light mode toggle icon.

2023-06-24 06:18 UTC, danielbayley commented on icons/paint-roller.svg
> not sure if you have any alts.

@karsa-mistmere Just these…

![preview](https://github.com/lucide-icons/lucide/assets/7797479/4ed6ecb2-56ed-48fb-9242-5ca0359243c4)

> feels a bit unbalanced

It’s a very asymmetric object, so it would be… I definitely think the handle should be on the right.

2023-07-13 07:55 UTC, karsa-mistmere commented on icons/paint-roller.svg
Update: Google Docs uses an icon that's virtually identical to my design:
![image](https://github.com/lucide-icons/lucide/assets/17746067/b9ee1227-b1cb-45de-bb48-73e0e214958f)

We could use either orientation, but I very strongly feel that the handle and the roller should be vertically aligned:
![paint-roller](https://github.com/lucide-icons/lucide/assets/17746067/91b9c3f0-c2cb-46fd-87c3-f427f63bedf4) ![paint-roller-flip](https://github.com/lucide-icons/lucide/assets/17746067/146e546b-de40-43be-9b16-93fecdc8baff)

2023-07-17 06:41 UTC, karsa-mistmere requested changes

2023-07-17 06:41 UTC, karsa-mistmere commented on icons/aperture-2.svg
> +  <path d="m9.2 9.2-6.4 6.3" />
We would need an extra point of precision here:
![image](https://github.com/lucide-icons/lucide/assets/17746067/214ea11b-9dd2-43cd-a4c3-a31d8cdace34)

On the other hand, I'm not sure about this icon to begin with, I really don't want to add any more `foobar-2` type of icons unless absolutely necessary, and while it's a bit dense, I find the current aperture icon much more readily recognisable.

2023-07-17 06:41 UTC, karsa-mistmere commented on icons/aperture.svg
> +  <path d="M9.7 16 4 6.1" />
This one's also overoptimised and the lines and the circles don't align anymore:
```suggestion
  <path d="m14.31 8 5.74 9.94" />
  <path d="M9.69 8h11.48" />
  <path d="m7.38 12 5.74-9.94" />
  <path d="M9.69 16 3.95 6.06" />
  <path d="M14.31 16H2.83" />
  <path d="m16.62 12-5.74 9.94" />
```

2023-07-17 06:41 UTC, karsa-mistmere commented on icons/contrast-2.svg
While I actually prefer this to the current contrast icon - although to be fair, neither works great without any fills - I think we should better name this `circle-line-vertical` and add contrast as a tag only.

2023-07-17 15:41 UTC, danielbayley commented on icons/contrast-2.svg
> I actually prefer this to the current contrast icon

@karsa-mistmere Same, although I think `yin-yang` in https://github.com/lucide-icons/lucide/pull/1394#issuecomment-1605272523 is also a good way to represent contrast, especially without fills…

> I think we should better name this circle-line-vertical and add contrast as a tag only.

Done.

2023-08-25 09:53 UTC, karsa-mistmere requested changes

2023-08-25 09:53 UTC, karsa-mistmere commented on icons/aperture-2.svg
Can we come up with a better name for this that sets it apart?

2024-01-16 14:31 UTC, ericfennis commented
Use cases: 
- `aperture-2`, same as aperture, not sure why we need another one.
- `blend`, In a design program blending 2 colors.
- `circle-line-vertical`, unknown
- `eclipse`, In an application for a dark mode toggle.
- `paint-roller`, In a design program, paint something with a color
- `swatch-book`, color book in application

2024-01-16 14:33 UTC, ericfennis commented
I've removed `circle-line-vertical` and `aperture-2`, due to weak use cases. These can be added to the `lab` branch tho

2024-01-16 14:42 UTC, merged

2024-01-16 15:49 UTC, danielbayley commented on icons/aperture-2.svg
@karsa-mistmere `aperture-simple`?

2024-01-16 15:50 UTC, danielbayley commented
> `circle-line-vertical`, unknown

@ericfennis Another way to represent contrast, or also another dark mode toggle…