Add speech icon
lucide-icons/lucide pull request #1337
Opened 2023-06-05 17:34 UTC by AirOne01

**LEET NICE**

Solves #1329 

Designs available [here](https://www.figma.com/file/cWJVxf9Kc19LcGpANpj5Ah/Lucide?type=design&node-id=0%3A1&t=edUivCN0FdULvIKH-1).

![designs](https://github.com/lucide-icons/lucide/assets/21955960/1558408e-39c2-479c-9c7b-d8c92cd8213b)

From those, I went with icon 1.

2023-06-05 18:00 UTC, jguddas requested changes

2023-06-05 18:00 UTC, jguddas commented on icons/speech.svg
> +</svg>
There is also a bit of an issue with the gap being less than 2px, but I have no clue how to fix it :man_shrugging: 

https://github.com/lucide-icons/lucide/assets/25524993/3e688929-502e-4d58-9e18-c937499d5e33

https://lucide-site-git-feat-added-edit-page-jguddas.vercel.app/edit?PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMy41IDIyIDUgMTZjLjQtMS4yLjItMi0uMi0yLjlsLS44LTFjLS43LS42LTEuNS0yLTEuNS00LjEgMC0yIDEuMi02IDYtNiA1LjMgMCA2IDMgNiA1djVjMCAyLTEgMy0zIDNhMiAyIDAgMCAwLTIgMnY1IiAvPgogIDxwYXRoIGQ9Ik0xNCAxOWE0LjUgNC41IDAgMCAwIDQuNS00LjUiIC8+CiAgPHBhdGggZD0iTTIxLjUgMTQuNWMwIDQtMy41IDcuNS03LjUgNy41IiAvPgo8L3N2Zz4=

2023-06-05 20:16 UTC, AirOne01 commented on icons/speech.svg
> +</svg>
I had no idea as well so I just made the PR anyways. My second icon is a failed attempt at fixing this 🤷‍♂️

2023-06-05 22:25 UTC, AirOne01 commented on icons/speech.svg
> +</svg>
Made two new versions:

| |
| --- |
| ![image](https://github.com/lucide-icons/lucide/assets/21955960/923d818c-a04a-4778-aa62-e9fb974c3d5e) |
| ![image](https://github.com/lucide-icons/lucide/assets/21955960/41b03624-90ed-4c62-a964-c6143123ef40) |

I think no. 4 looks more impactful but I'd stay on number 3 (closes more on the feeling of feather). Making my changes.

2023-06-05 22:36 UTC, AirOne01 commented
I also used the tool you link to make proper SVG this time. Couldn't find a way (pretty) to make this padding exactly 2px though.

2023-06-05 22:38 UTC, jguddas commented
Mr. cool wearing a hat ![icon (82)](https://github.com/lucide-icons/lucide/assets/25524993/c2bb7691-b60b-446f-a6ef-d7e8d4018556)

2023-06-06 00:31 UTC, karsa-mistmere commented
Nice concept, although I feel like the head shape might be a bit too blobby, how about [something a bit more geometric](https://lucide-site-git-feat-added-edit-page-jguddas.vercel.app/edit?PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJtMiAxOSAuMy0uOGEyNi4wNyAyNi4wNyAwIDAgMCAxLjAzMS00LjUxNyAzLjU1IDMuNTUgMCAwIDAtLjU1Mi0yLjEyNkE3LjMzIDcuMzMgMCAwIDEgMiA4YTYgNiAwIDEgMSAxMiAwdjNhMyAzIDAgMCAxLTMgM2gtMWExIDEgMCAwIDAtMSAxdjQiIC8+CiAgPHBhdGggZD0iTTEzIDE4YTUgNSAwIDAgMCA1LTUiIC8+CiAgPHBhdGggZD0iTTIyIDEzYzAgNC43NjUtNC4yMzUgOS05IDkiIC8+Cjwvc3ZnPg==)?

2023-06-06 00:52 UTC, karsa-mistmere commented
Another alt w/ maybe more traditionally placed sound waves:
![speech](https://github.com/lucide-icons/lucide/assets/17746067/58092d70-0e08-41d2-a96c-e56f630fec12)
https://lucide-site-git-feat-added-edit-page-jguddas.vercel.app/edit?PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNOC44IDIwdi00LjFsMS45LjJhMi4zIDIuMyAwIDAgMCAyLjE2NC0yLjFWOC4zQTUuMzcgNS4zNyAwIDAgMCAyIDguMjVjMCAyLjguNjU2IDMuMDU0IDEgNC41NWE1Ljc3IDUuNzcgMCAwIDEgLjAyOSAyLjc1OEwyIDIwIiAvPgogIDxwYXRoIGQ9Ik0xOS44IDE3LjhhNy41IDcuNSAwIDAgMCAuMDAzLTEwLjYwMyIgLz4KICA8cGF0aCBkPSJNMTcgMTVhMy41IDMuNSAwIDAgMC0uMDI1LTQuOTc1IiAvPgo8L3N2Zz4=

2023-06-07 07:58 UTC, AirOne01 commented
This is way better, thanks! I'll make my changes when I'm off work.

2023-09-13 19:05 UTC, merged