Add `notebook`/`pad` icons
lucide-icons/lucide pull request #1363
Opened 2023-06-13 12:56 UTC by danielbayley

2023-06-13 20:59 UTC, jguddas approved these changes

2023-07-17 12:25 UTC, karsa-mistmere requested changes

2023-07-17 12:25 UTC, karsa-mistmere commented on icons/notebook-dashed.svg
This feels a bit more like some kind of transformer circuit. 🤔

2023-07-17 12:25 UTC, karsa-mistmere commented on icons/notebook-pencil.svg
Something like this (using the pencil shape from `file-/clipboard-/folder-edit`) would feel more trivial to me:
![image](https://github.com/lucide-icons/lucide/assets/17746067/cfa7d54f-dbc4-44cf-89a0-35c78ba1dceb)

2023-07-19 18:04 UTC, karsa-mistmere commented on icons/notebook-pencil.svg
I see that you've renamed this one, on the other hand, maybe if `edit` icons are renamed `pen` and `pencil` in #1286, `*-edit` icons should follow suit as `*-pen`?... 🤔

@ericfennis, what do you think?

2023-07-19 18:28 UTC, danielbayley commented on icons/notebook-pencil.svg
> `*-edit` icons should follow suit as `*-pen`?

Yeah, I also did think that…

2023-07-19 19:39 UTC, jguddas approved these changes

2024-01-06 23:16 UTC, merged