Add/optimise/improve building icons
lucide-icons/lucide pull request #1404
Opened 2023-06-27 20:49 UTC by danielbayley

2023-06-27 21:02 UTC, jguddas commented
They look cute 🥰

Here some inspiration for more building types https://wiki.openstreetmap.org/wiki/Key:shelter_type

2023-06-29 18:29 UTC, jguddas commented
- Colosseum is not what I would have guessed by looking at it.
- Floor plan is also hard to identify.
- Windmill is rotationally symmetrical (Not as bad but for hate symbol avoidance).

2023-07-03 19:10 UTC, karsa-mistmere commented on icons/windmill.svg
The central dot doesn't have sufficient gap.
![image](https://github.com/lucide-icons/lucide/assets/17746067/4954dcdd-30af-446e-afbb-183ac8400628)

Maybe something like this?
![image](https://github.com/lucide-icons/lucide/assets/17746067/ca082272-a328-448f-835c-da1d49efb580)

2023-07-04 08:50 UTC, karsa-mistmere commented on icons/windmill.svg
Or something a bit less hate symbol-ish:
![image](https://github.com/lucide-icons/lucide/assets/17746067/ad2c1ba8-6eaf-44e8-aa7c-32c322a05140)

2023-07-13 12:05 UTC, danielbayley commented on icons/colosseum.svg
Also thought about calling it, or something similar, `ruins`… The thinking here being to be able to distinguish between ancient and modern tourist attractions in e.g the use case of maps/travel, or more generically just to represent ‘history’… What do you think? @karsa-mistmere

2023-07-13 14:14 UTC, danielbayley commented on icons/farm.svg
> Maybe just barn is enough for the "farm" use case?

Well in the use case of maps—`barn` being a subset of `farm`—I don’t think it covers potentially acres of fields, and all of the potential other stuff… In the use case of e.g travel/property site, are you looking at the whole farm, or just the barn… They are different things.

> maybe remove the outline

Maybe, although having drawn this effectively from visual memory—forgetting where else I had come across something similar—I managed to find it was AirBnB… So I mean, if it’s good enough for them…

<img width="114" alt="Screenshot 2023-07-13 at 12 40 58 pm" src="https://github.com/lucide-icons/lucide/assets/7797479/a1c151a6-609a-429e-8615-0e61beb6cf3c">
<br/>
<br/>

I don’t think just parallel stripes alone represent land/field*s* as well as some of them being at right angles to each other… Thinking of the Bank of America logo for example:

![image](https://github.com/lucide-icons/lucide/assets/7797479/01dbdd72-064c-4d0e-8c50-8d6c4cca92b1)

Anyway, see what you think of these options…? @karsa-mistmere @ericfennis 

![preview](https://github.com/lucide-icons/lucide/assets/7797479/6b7762d8-ee0b-45e0-abe6-d3cb36f0d1b0)

2023-07-13 14:45 UTC, karsa-mistmere commented on icons/farm.svg
I think one of these should work fine:
![image](https://github.com/lucide-icons/lucide/assets/17746067/848ae65c-4d5b-49d7-a15e-148400c0fe65)

(Note rounding of door to allow for a 2px gap).

2023-07-13 17:51 UTC, danielbayley commented on icons/farm.svg
> (Note rounding of door to allow for a 2px gap).

@karsa-mistmere Good catch, but just lowered it a bit instead, since it could also possibly be a barn, it being rounded seems odd…

2023-07-13 20:40 UTC, danielbayley commented on icons/windmill.svg
> less hate symbol-ish:

Oh that again 😅 Don’t let those bastards have a monopoly on anything resembling _that_ shape! Trying to go off what windmills _actually_ look like here… See also https://lucide.dev/icons/fan

> Maybe something like this?

@karsa-mistmere See latest `push`…

2023-07-24 05:38 UTC, karsa-mistmere commented on icons/doorbell.svg
I think this one feels a bit too much like a rotated `banknote`, however, I believe most of this icon's use cases should already be covered by `bell-electric`, see https://github.com/lucide-icons/lucide/pull/1392#discussion_r1271762791

2023-08-28 21:54 UTC, karsa-mistmere requested changes

2023-08-28 21:54 UTC, karsa-mistmere commented on icons/cabin.svg
> +  <path d="M14 18h6" />
The roof is a bit over-optimised:
```suggestion
  <path d="M2.6 10.4a2.12 2.12 0 1 0 3.02 2.98L12 7l6.4 6.4a2.12 2.12 0 1 0 2.979-3.021L13.7 2.7a2.4 2.4 0 0 0-3.404.004Z" />
  <path d="M14 22v-7a2 2 0 0 0-4 0v7" />
  <path d="M14 14h6v6a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-6h6" />
  <path d="M4 18h6" />
  <path d="M14 18h6" />
```

2023-08-28 21:54 UTC, karsa-mistmere commented on icons/floor-plan.svg
What are the use cases for this one?

2023-08-28 21:54 UTC, karsa-mistmere commented on icons/house-manor.svg
> +  <path d="M10 22v-5a2 2 0 1 1 4 0v5" />
The roof does not scale particularly well: 
![image](https://github.com/lucide-icons/lucide/assets/17746067/3d18f596-e432-4752-a90e-00db2c579b61)

2023-08-28 21:54 UTC, karsa-mistmere commented on icons/house-roof.svg
> +  <path d="M14 22v-6a2 2 0 0 0-4 0v6" />
Also a bit over-optimised:
```suggestion
  <path d="M2.6 10.4a2.12 2.12 0 1 0 3.02 2.98L12 7l6.4 6.4a2.12 2.12 0 1 0 2.979-3.021L13.7 2.7a2.4 2.4 0 0 0-3.404.004Z" />
  <path d="M20 14v6a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-6" />
  <path d="M14 22v-6a2 2 0 0 0-4 0v6" />
```

2023-08-28 21:54 UTC, karsa-mistmere commented on icons/house-roof-off.svg
> +  <path d="M4 14v6a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2" />
This one has a 2px padding design guideline violation.

2023-12-22 12:52 UTC, merged