Add transport icon
lucide-icons/lucide pull request #1412
Opened 2023-06-29 05:00 UTC by danielbayley

2023-07-07 12:12 UTC, ericfennis commented on icons/traffic-lights.svg
> +<svg
Not sure about the design of this one. On first sight for me I didn't recognized it as a traffic light.

2023-07-07 12:12 UTC, ericfennis commented on icons/train-track.svg
> +<svg
Can we try to make a less dense variant? Looks a bit dense to me.

2023-07-07 12:12 UTC, ericfennis commented on icons/train.svg
> +  <path d="M8 4.1V7a4 4 0 0 0 8 0V4.1" />
Maybe add this one as `train-highspeed`?

2023-07-17 09:28 UTC, karsa-mistmere requested changes

2023-07-17 09:28 UTC, karsa-mistmere commented on icons/car-front.svg
I really like some of the design choices in this PR, however, I feel like some of them feel a bit off-brand compared to existing vehicle icons. Going back to some of my drafts in #609, I tried to amalgamate the your car and mine into a single icon, LMKWYT:
![image](https://github.com/lucide-icons/lucide/assets/17746067/aa91c2c5-ab9e-4df0-977f-cb8ab39bdff5)

![car-front](https://github.com/lucide-icons/lucide/assets/17746067/d713e731-0eaf-4bec-be87-8122b42abd92)

(train icon for comparison)

2023-07-17 09:28 UTC, karsa-mistmere commented on icons/car-taxi.svg
The top feels a bit off, since it's very large compared to the car itself.

---

Here's an idea, although while strictly speaking, it has a guideline violation, but we do have a virtually identical element in [at least one](https://lucide.dev/icons/microscope) existing icon:
![car-taxi](https://github.com/lucide-icons/lucide/assets/17746067/84ed37b0-dc66-452e-9af6-c9e1b5d1715e)

@ericfennis?

2023-07-17 09:28 UTC, karsa-mistmere commented on icons/car.svg
I only just now understand the motivation behind changing `bus`, but I think instead of decreasing the size of car (blue), we should instead make it larger (green):
![image](https://github.com/lucide-icons/lucide/assets/17746067/e3b5cd23-94de-4ba9-a49f-432c2a9830bf)

2023-07-17 09:28 UTC, karsa-mistmere commented on icons/coach.svg
Feels a bit narrow, how about adding something like this as `bus-front` instead?

![bus-front](https://github.com/lucide-icons/lucide/assets/17746067/033c80cf-8f88-4aea-94c8-6f0d7ca51419)

2023-07-17 09:28 UTC, karsa-mistmere commented on icons/parking-meter.svg
Super cute. 😊

2023-07-17 09:28 UTC, karsa-mistmere commented on icons/tractor.svg
> +  <path d="M17 5c-.6 0-1 .4-1 1v5" />
Also super cute, but I think the exhaust pipe will need to be moved 1px to the right:
```suggestion
  <path d="M18 5c-.6 0-1 .4-1 1v5.57" />
```

![image](https://github.com/lucide-icons/lucide/assets/17746067/309a855c-4d9e-4220-aac5-8798ebe3f2ed)

2023-07-17 09:28 UTC, karsa-mistmere commented on icons/traffic-cone.svg
Both are cute, but I think one traffic cone should be enough, I think the other one is much more readily recognisable, this one looks a bit too much like some kind of headwear.

2023-07-17 09:28 UTC, karsa-mistmere commented on icons/train-high-speed.svg
Looks cute, but it's maybe a bit too small as compared to `train`?
![image](https://github.com/lucide-icons/lucide/assets/17746067/d45cc0d0-d48e-4cb3-a161-29bf037b646c)

2023-07-17 09:28 UTC, karsa-mistmere commented on icons/truck.svg
I'll let this comment hang here until we resolve the changes to `car` first as a note to also keep this one consistent.

2023-07-17 17:29 UTC, ericfennis commented on icons/car-taxi.svg
I see @danielbayley already adjusted it. I the latest change looks better.

2023-07-18 08:00 UTC, karsa-mistmere commented on icons/car-taxi.svg
@ericfennis I don't see any recent change.

I think the taxi sign definitely shouldn't be just as tall as the windscreen, if the guidelines do not allow for anything better, I'd vote to just drop this one until we can come up with something that is.

2023-07-18 21:45 UTC, danielbayley commented on icons/car-taxi.svg
@karsa-mistmere Nice! I like that much better actually…

2023-07-19 00:46 UTC, danielbayley commented on icons/train-high-speed.svg
@karsa-mistmere It’s the same size…

<img width="343" alt="Untitled" src="https://github.com/lucide-icons/lucide/assets/7797479/baca8dc1-2370-4f59-8bbb-1e915144a970">

2023-07-19 02:03 UTC, danielbayley commented on icons/car-front.svg
> some of my drafts in https://github.com/lucide-icons/lucide/issues/609

Nice, again I had not seen any of those! 😅

2023-07-19 02:05 UTC, danielbayley commented on icons/coach.svg
> Feels a bit narrow

@karsa-mistmere Well `coach` should appear much taller than `car`, but have adjusted down a bit…

> how about adding something like this as `bus-front` instead?

I don’t think the divide would/should be there… But something like this maybe?

![preview](https://github.com/lucide-icons/lucide/assets/7797479/23fcdd93-412f-413a-b14c-d5376af0e2bd)

2023-07-19 10:49 UTC, karsa-mistmere commented on icons/train-high-speed-tunnel.svg
Nice! So much cuter than my version. ^_^

2023-07-19 10:54 UTC, karsa-mistmere commented on icons/train-high-speed.svg
Nice, I think the new one works pretty darned well, good job, @danielbayley.

2023-07-19 11:26 UTC, danielbayley commented on icons/train-high-speed-tunnel.svg
@karsa-mistmere Should it be called just `train-tunnel`?

2023-07-19 11:40 UTC, karsa-mistmere commented on icons/car-front.svg
> +  <path d="m3 8 2 2s1.4-3.4 1.6-4.1c.2-.5.8-.9 1.4-.9h8c.6 0 1.2.4 1.4.9.2.7 1.6 4.1 1.6 4.1l2-2" />
```suggestion
  <path d="m21 8-2 2-1.5-3.7A2 2 0 0 0 15.646 5H8.4a2 2 0 0 0-1.903 1.257L5 10 3 8" />
```

2023-07-19 11:40 UTC, karsa-mistmere commented on icons/car-taxi.svg
> +  <path d="m3 9 2 2s1.4-3.4 1.6-4.1c.2-.5.8-.9 1.4-.9h8c.6 0 1.2.4 1.4.9.2.7 1.6 4.1 1.6 4.1l2-2" />
```suggestion
  <path d="m21 9-2 2-1.5-3.7A2 2 0 0 0 15.646 6H8.4a2 2 0 0 0-1.903 1.257L5 11 3 9" />
```

2023-07-19 11:40 UTC, karsa-mistmere commented on icons/car.svg
> +  <path d="M2 11h9c1.1 0 2.7-.2 3.5-.5L16 10" />
This one feels a bit out of place, how about making it a bit more geometric?
```suggestion
  <path d="M2 11h12.2a2 2 0 0 0 1.386-.586L16 10" />
```

![image](https://github.com/lucide-icons/lucide/assets/17746067/79966ca0-81a9-47d0-999e-81d0cf3ee124)

2023-07-19 11:42 UTC, karsa-mistmere commented on icons/train-high-speed-tunnel.svg
I think I'd go for `train-front` for the existing one and `subway-front` for this new one.
We'd still need `train` though, as being discussed in #639 & #330

2023-07-19 12:40 UTC, danielbayley commented on icons/train-high-speed-tunnel.svg
> `train-front` for the existing one

@karsa-mistmere Which one do you mean exactly?

> `subway-front` for this new one.

Hmm, I don’t think it would make sense to call _this_ one (high-speed train) `subway-*`, because the aerodynamic/modern design of it is specifically for fast travel above ground. I think if anything, the existing https://lucide.dev/icons/train (if we are not calling it `tram`) looks more like an old subway train (at least the ones in London are very old and shit, anyway 😅).

I agree with @ericfennis as mentioned in https://github.com/lucide-icons/lucide/pull/639#issuecomment-1120224809, that the (currently missing from this PR, feel free to add it…) steam train (e.g from #330) should be called `locomotive`.

2023-07-19 12:43 UTC, karsa-mistmere commented on icons/train-high-speed-tunnel.svg
OK, I think `train-tunnel-front` would also be fine. :)

2023-07-19 17:51 UTC, ericfennis commented
Hmm, I'm a bit doubting the new designs for the car and the bus. Not sure if the lines will add something. I think keeping it simple is better. But maybe that is me, more opinions on this are welcome.

2023-07-27 14:49 UTC, ericfennis requested changes
Ok I think it's time to prioritize the list a bit. This PR is also getting bigger and bigger.
Overal the designs are really good!
To merge this I accept the following icons for this PR. I wrote some notes for the icons I rejected for now, if you don't agree with some of my notes. Please consider opening new issue or discussion to discuss this. So we can merge this one for now.

- [ ] bus-school-front, I think the design is too similar to `coach-front`. Probably for the use case of this, `coach-front` will do the job fine.
- [x] bus
- [x] cable-car
- [ ] car-electric-front, The use case of this icon is really good. I like to see a separate issue with some more variations for this one, because I think this deserves some more exploration.
- [x] car-front
- [ ] car-sports-front, not sure about the design and the use case. Maybe a bit too specific.
- [x] car-taxi-front
- [x] car
- [ ] coach-front-2, One icon of this one is fine
- [x] coach-front, maybe call this `bus-front` ?
- [x] m-square
- [x] parking-meter
- [x] rail-symbol
- [x] ship-wheel
- [x] tractor
- [x] traffic-cone
- [ ] train-front-tunnel, not sure about the use case.
- [x] train-front
- [x] train-track
- [x] tram-front
- [x] truck

2023-07-27 15:11 UTC, danielbayley commented
@ericfennis Ok, made most of those changes, and moved the others to a separate PR for discussion…

> - [ ] train-front-tunnel, not sure about the use case.

Maps, for one…

2023-07-27 16:02 UTC, karsa-mistmere commented
> @ericfennis Ok, made most of those changes, and moved the others to a separate PR for discussion…
> 
> > * [ ]  train-front-tunnel, not sure about the use case.
> 
> Maps, for one…

Yes, to signify subways in trip planning / public transport schedule apps, I thought this would be a no brainer to add. 😅

2023-07-27 21:28 UTC, ericfennis approved these changes

2023-08-07 09:07 UTC, ericfennis commented
@karsa-mistmere True but it doesn't look like a subway icon, more a highspeed train in a tunnel.

2023-08-07 09:21 UTC, merged

2023-08-07 13:18 UTC, danielbayley commented
> @karsa-mistmere True but it doesn't look like a subway icon, more a highspeed train in a tunnel.

@ericfennis It can be either :)

2023-10-30 19:25 UTC, MeChamaDeCarinha commented
Traffic cone is missing on lucide-react
![image](https://github.com/lucide-icons/lucide/assets/100491426/0d1f0628-6e0a-4ccb-adde-aa31f8d4b8e1)

2023-10-30 20:07 UTC, karsa-mistmere commented
> Traffic cone is missing on lucide-react
> ![image](https://user-images.githubusercontent.com/100491426/279173064-0d1f0628-6e0a-4ccb-adde-aa31f8d4b8e1.png)

Which version of `lucide-react` are you on?

2023-10-31 00:20 UTC, MeChamaDeCarinha commented
> > Traffic cone is missing on lucide-react
> > ![image](https://user-images.githubusercontent.com/100491426/279173064-0d1f0628-6e0a-4ccb-adde-aa31f8d4b8e1.png)
> 
> Which version of `lucide-react` are you on?

0.264.0

2023-10-31 04:57 UTC, karsa-mistmere commented
> > > Traffic cone is missing on lucide-react
> > > ![image](https://user-images.githubusercontent.com/100491426/279173064-0d1f0628-6e0a-4ccb-adde-aa31f8d4b8e1.png)
> > 
> > 
> > Which version of `lucide-react` are you on?
> 
> 0.264.0

That explains it then, since these icons were only added in v0.265.0:
![IMG_2654](https://github.com/lucide-icons/lucide/assets/17746067/d9f5f575-5192-4428-a7bb-650917005654)