Add forward and backward overlap icons
lucide-icons/lucide pull request #1425
Opened 2023-07-10 11:22 UTC by james-yeoman

I'm not an artist in the slightest, but by using `copy` as a base, I was able to get these icons looking serviceable.

These icons may need to be measured in something more capable, since I used [svgviewer](https://www.svgviewer.dev), which doesn't have pixel measurement capabilities. It's also not the best for dimensional accuracy, as you can see from this screenshot.

<details>
<summary>Collapsible screenshot and svg code from svgviewer</summary>

![image](https://github.com/lucide-icons/lucide/assets/117744792/c7138911-e450-456b-b781-4001044599a1)

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-bring-to-front">
  
  <rect width="24" height="24" x="0" y="0" stroke-width="1" stroke="red" />
  
  <rect width="8" height="8" x="8" y="8" rx="2" ry="2"/>
  <path d="M 4 10 c -1 0 -2 -1 -2 -2 v -4 c 0 -1 1 -2 2 -2 h 4 c 1 0 2 1 2 2"/>
  <path d="M 14 20 c 0 1 1 2 2 2 h 4 c 1 0 2 -1 2 -2 v -4 c 0 -1 -1 -2 -2 -2"/>
</svg>

<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-send-to-back">
  
  <rect width="24" height="24" x="0" y="0" stroke-width="1" stroke="red" />
  
  <rect width="8" height="8" x="2" y="2" rx="2" ry="2" />
  <rect width="8" height="8" x="14" y="14" rx="2" ry="2" />
  <path d="M 7 14 v 1 c 0 1 1 2 2 2 h 1" />
  <path d="M 14 7 h 1 c 1 0 2 1 2 2 v 1" />
</svg>

<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-copy">
  
  <rect width="24" height="24" x="0" y="0" stroke-width="1" stroke="red" />
  
  <rect width="14" height="14" x="8" y="8" rx="2" ry="2"/>
  <path d="M 4 16 c -1.1 0 -2 -.9 -2 -2 V 4 c 0 -1.1 .9 -2 2 -2 h 10 c 1.1 0 2 .9 2 2"/>
</svg>

```
</details>

When eyeballing the icons, the spacing looks the same as the `copy` icon, and so should be design guide compliant. That said, can someone please verify in something like Illustrator or another capable program?

2023-07-10 11:24 UTC, james-yeoman commented
Ooh, I didn't know about that workflow. The icon x-rays confirm that the spacing is within the design guide!

2023-07-11 12:06 UTC, jguddas requested changes
I fixed some things using https://lucide-site-git-feat-added-edit-page-jguddas.vercel.app/edit .

2023-07-11 12:06 UTC, jguddas commented on icons/bring-to-front.svg
> +  <path d="M4 10c-1 0-2-1-2-2V4c0-1 1-2 2-2h4c1 0 2 1 2 2m4 16c0 1 1 2 2 2h4c1 0 2-1 2-2v-4c0-1-1-2-2-2" />
```suggestion
  <rect x="8" y="8" width="8" height="8" rx="2" />
  <path d="M4 10a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2" />
  <path d="M14 20a2 2 0 0 0 2 2h4a2 2 0 0 0 2-2v-4a2 2 0 0 0-2-2" />
```

2023-07-11 12:06 UTC, jguddas commented on icons/send-to-back.svg
> +  <path d="M7 14v1c0 1 1 2 2 2h1m4-10h1c1 0 2 1 2 2v1" />
```suggestion
  <rect x="14" y="14" width="8" height="8" rx="2" />
  <rect x="2" y="2" width="8" height="8" rx="2" />
  <path d="M7 14v1a2 2 0 0 0 2 2h1" />
  <path d="M14 7h1a2 2 0 0 1 2 2v1" />
```

2023-07-11 12:08 UTC, james-yeoman commented on icons/send-to-back.svg
> +  <path d="M7 14v1c0 1 1 2 2 2h1m4-10h1c1 0 2 1 2 2v1" />
ditto

2023-07-13 09:44 UTC, james-yeoman commented
Is there anything left that needs tweaking? Or is this just waiting on a release candidate?

2023-07-13 10:38 UTC, jguddas reviewed
I think the icons are good 👍 

@karsa-mistmere, @ericfennis what do you think?

2023-07-13 10:38 UTC, jguddas commented on icons/bring-to-front.json
> +  ],
```suggestion
  "contributors": [
    "james-yeoman",
    "jguddas"
  ],
```

2023-07-13 10:38 UTC, jguddas commented on icons/bring-to-front.json
> +  ],
```suggestion
  "tags": [
    "bring",
    "send",
    "move",
    "over",
    "forward",
    "front",
    "layer"
  ],
```

2023-07-13 10:38 UTC, jguddas commented on icons/send-to-back.json
> +  ],
```suggestion
  "contributors": [
    "james-yeoman",
    "jguddas"
  ],
```

2023-07-13 10:38 UTC, jguddas commented on icons/send-to-back.json
> +  ],
```suggestion
  "tags": [
    "bring",
    "send",
    "move",
    "over",
    "back",
    "backwards",
    "layer"
  ],
```

2023-07-13 10:43 UTC, jguddas approved these changes

2023-07-17 07:46 UTC, karsa-mistmere approved these changes

2023-07-18 07:56 UTC, ericfennis approved these changes
Nice work @james-yeoman !!

2023-07-18 07:56 UTC, merged