Refine [`pencil-`]`ruler` icons
lucide-icons/lucide pull request #1442
Opened 2023-07-18 13:41 UTC by danielbayley

2023-07-18 13:57 UTC, karsa-mistmere requested changes

2023-07-18 13:57 UTC, karsa-mistmere commented on icons/ruler.svg
> +  <path d="m17.5 15.5 2-2" />
There's a slight loss of precision here:
```suggestion
  <path d="M21.3 15.3a2.4 2.4 0 0 1 0 3.4l-2.6 2.6a2.4 2.4 0 0 1-3.4 0L2.7 8.7a2.41 2.41 0 0 1 0-3.4l2.6-2.6a2.41 2.41 0 0 1 3.4 0Z" />
  <path d="m14.5 12.5 2-2" />
  <path d="m11.5 9.5 2-2" />
  <path d="m8.5 6.5 2-2" />
  <path d="m17.5 15.5 2-2" />
```

2023-07-18 13:57 UTC, karsa-mistmere commented on icons/pencil-ruler.svg
> +  <path d="M7.5 20.5 2 22l1.5-5.5L17 3a2.76 2.76 0 1 1 4.3 3.7Z" />
```suggestion
  <path d="m2 22 5.5-1.5L21.17 6.83a2.82 2.82 0 0 0-4-4L3.5 16.5Z" />
```

2023-07-19 17:37 UTC, ericfennis approved these changes

2023-07-21 07:47 UTC, karsa-mistmere approved these changes

2023-07-21 07:47 UTC, merged