Add `glasses-`[`aviator`/`rectangle`/`cat eye`] icons and rename past glasses icon
lucide-icons/lucide pull request #1480
Opened 2023-08-05 10:54 UTC by hibatillah

### Add new types glasses
- `glasses-aviator`
- `glasses-rectangle`
- `glasses-cateye`

### Rename past glasses icon
from `glasses` to `glasses-round`, because of the use of the type for glasses

2023-08-05 11:02 UTC, hibatillah commented
there's problem with the icons, i dont know how to fix it. pls help!

2023-08-08 06:39 UTC, karsa-mistmere requested changes

2023-08-08 06:39 UTC, karsa-mistmere commented on icons/glasses-round.json
If we rename this, we would need to add an alias to this JSON file for backwards compatibility.

2023-08-08 06:39 UTC, karsa-mistmere commented on icons/glasses-rectangle.svg
> +  <path d="M2.5 13L5 7C5.7 5.7 6.4 5 8 5" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
Hi @hibatillah,

When contributing, it's best to allow the pre commit hooks to run, for that to happen, you need to run `pnpm install`.
Alternatively, you can use either [SVGOMG](https://jakearchibald.github.io/svgomg/) to optimize your icon and then @jguddas's awesome (although admittedly still in beta) edit tool: https://github.com/lucide-icons/lucide/pull/1022

What you should end up with is something like this (i.e. no explicit stroke or fill attributes on any path elements):
```suggestion
  <rect x="14" y="13" width="8" height="5" rx="1" />
  <rect x="2" y="13" width="8" height="5" rx="1" />
  <path d="M10 15h4" />
  <path d="M21.5 13 19 7c-.7-1.3-1.5-2-3-2" />
  <path d="M2.5 13 5 7c.7-1.3 1.4-2 3-2" />
```

2023-08-08 06:39 UTC, karsa-mistmere commented on icons/glasses-aviator.svg
> +  <path d="M3 12L5.5 6C6.2 4.7 6.9 4 8.5 4" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
```suggestion
  <path d="M10 15h4" />
  <path d="M2 13a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v2a4 4 0 0 1-4 4H5a3 3 0 0 1-3-3Z" />
  <path d="M22 13a1 1 0 0 0-1-1h-6a1 1 0 0 0-1 1v2a4 4 0 0 0 4 4h1a3 3 0 0 0 3-3Z" />
  <path d="m21 12-2.5-6c-.7-1.3-1.5-2-3-2" />
  <path d="m3 12 2.5-6c.7-1.3 1.4-2 3-2" />
```

2023-08-08 06:39 UTC, karsa-mistmere commented on icons/glasses-cateye.svg
> +  <path d="M2.5 13L5 7C5.7 5.7 6.4 5 8 5" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
```suggestion
  <path d="M10 15h4" />
  <path d="M2 13h6a2 2 0 0 1 2 2v3a1 1 0 0 1-1 1H5a3 3 0 0 1-3-3Z" />
  <path d="M22 13h-6a2 2 0 0 0-2 2v3a1 1 0 0 0 1 1h4a3 3 0 0 0 3-3Z" />
  <path d="M21.5 13 19 7c-.7-1.3-1.5-2-3-2" />
  <path d="M2.5 13 5 7c.7-1.3 1.4-2 3-2" />
```

2023-08-12 18:36 UTC, jguddas commented
Not to be that guy but there needs to be a description of the uniq use case for each of those icons.

2023-12-26 02:59 UTC, closed without merging