Optimise `box`/`package` icons
lucide-icons/lucide pull request #1481
Opened 2023-08-06 10:25 UTC by danielbayley

2023-08-12 18:35 UTC, jguddas approved these changes

2023-08-13 08:20 UTC, karsa-mistmere requested changes

2023-08-13 08:20 UTC, karsa-mistmere commented on icons/package-check.svg
> +  <path d="m7.5 4.3 9 5.1" />
I think we could do with an extra point of precision here as usual:
```suggestion
  <path d="m7.5 4.27 9 5.15" />
```

2023-08-13 08:20 UTC, karsa-mistmere commented on icons/package-minus.svg
> +  <path d="m7.5 4.3 9 5.1" />
```suggestion
  <path d="m7.5 4.27 9 5.15" />
```

2023-08-13 08:20 UTC, karsa-mistmere commented on icons/package-plus.svg
> +  <path d="m7.5 4.3 9 5.1" />
```suggestion
  <path d="m7.5 4.27 9 5.15" />
```

2023-08-13 08:20 UTC, karsa-mistmere commented on icons/package-search.svg
> +  <path d="m7.5 4.3 9 5.1" />
```suggestion
  <path d="m7.5 4.27 9 5.15" />
```

2023-08-13 08:20 UTC, karsa-mistmere commented on icons/package-x.svg
> +  <path d="m7.5 4.3 9 5.1" />
```suggestion
  <path d="m7.5 4.27 9 5.15" />
```

2023-08-13 08:20 UTC, karsa-mistmere commented on icons/package.svg
> +  <path d="m7.5 4.3 9 5.1" />
```suggestion
  <path d="m7.5 4.27 9 5.15" />
```

2023-08-13 14:23 UTC, danielbayley commented
@karsa-mistmere `commit`ted…

What do we thing of extending the tape down the side? https://github.com/lucide-icons/lucide/pull/1481#issue-1838147006 cc: @jguddas @ericfennis

2023-08-13 14:55 UTC, jguddas commented
> What do we thing of extending the tape down the side?

:-1: KISS

2023-08-15 17:33 UTC, ericfennis commented
Nope, lets keep it simple!

2023-08-15 17:34 UTC, ericfennis approved these changes

2023-08-15 17:34 UTC, merged