Refine `radio-tower`/optimise/add `airdrop`/Apple/mac/iOS related icons
lucide-icons/lucide pull request #1514
Opened 2023-08-16 21:25 UTC by danielbayley

`airdrop` is missing, considering we already have https://lucide.dev/icons/airplay.

2023-08-28 17:04 UTC, karsa-mistmere requested changes

2023-08-28 17:04 UTC, karsa-mistmere commented on icons/radio-tower.svg
> +  <path d="M7.8 4.8c-2.1 2.1-2.3 5.4-.6 7.8" />
```suggestion
  <path d="M4.93 16.07A10 10 0 0 1 4.86 2" />
  <path d="M7.76 4.76a6 6 0 0 0-.59 7.8" />
```

2023-08-28 17:04 UTC, karsa-mistmere commented on icons/podcast.svg
>    <path d="M17 18.5a9 9 0 1 0-10 0" />
```suggestion
  <path d="M16.85 18.58a9 9 0 1 0-9.7 0" />
```

2023-08-29 13:19 UTC, karsa-mistmere commented
AirDrop and AirPlay are Apple trademarks, not only will AirDrop not be added, AirPlay will also be removed.

2024-01-05 11:23 UTC, ericfennis commented
Maybe not a bad idea @danielbayley

2024-01-17 18:47 UTC, ericfennis commented on icons/radio-tower.svg
> +  <path d="M4.93 16.07A10 10 0 0 1 4.86 2" />
This one is adding more code right?

2024-03-06 19:29 UTC, merged