feat: Add transport icons
lucide-icons/lucide pull request #152
Opened 2020-12-02 23:08 UTC by ahtohbi4

Add `bike`, `bus` and `car` icons and update `truck` icon

<img width="673" alt="icon transport" src="https://user-images.githubusercontent.com/3686790/100942436-6e385f80-350c-11eb-9eff-738dab52e081.png">

2020-12-03 05:54 UTC, locness3 approved these changes

2020-12-03 08:17 UTC, ericfennis requested changes
Small additions

2020-12-03 08:17 UTC, ericfennis commented on tags.json
> +  "car": ["car", "transport", "trip"],
```suggestion
  "car": ["vehicle", "transport", "trip"],
```

2020-12-03 08:17 UTC, ericfennis commented on tags.json
> +  "bus": ["bus", "transport", "trip"],
```suggestion
  "bus": ["bus", "vehicle", "transport", "trip"],
```

2020-12-03 08:17 UTC, ericfennis commented on tags.json
> +  "bike": ["bike", "transport", "trip"],
```suggestion
  "bike": ["bicycle", "transport", "trip"],
```

2020-12-03 16:09 UTC, locness3 commented on tags.json
> +  "bus": ["bus", "transport", "trip"],
Should remove the bus tag here qs well

2020-12-04 07:54 UTC, Andreto commented on icons/bus.svg
> +  <path d="M19 17h2l.64-2.54a6 6 0 000-2.92l-1.07-4.27A3 3 0 0017.66 5H4a2 2 0 00-2 2v10h2m10 0h-4"/>
```suggestion
  <path d="M19 17h2l.64-2.54a6 6 0 000-2.92l-1.07-4.27A3 3 0 0017.66 5H4a2 2 0 00-2 2v10h2m10 0h-4" />
```

2020-12-04 07:54 UTC, Andreto commented on icons/car.svg
> +  <path d="M14 16H9m10 0h3v-3.15a1 1 0 00-.84-.99L16 11l-2.7-3.6a1 1 0 00-.8-.4H5.24a2 2 0 00-1.8 1.1l-.8 1.63A6 6 0 002 12.42V16h2"/>
```suggestion
  <path d="M14 16H9m10 0h3v-3.15a1 1 0 00-.84-.99L16 11l-2.7-3.6a1 1 0 00-.8-.4H5.24a2 2 0 00-1.8 1.1l-.8 1.63A6 6 0 002 12.42V16h2" />
```

2020-12-04 07:54 UTC, Andreto commented on icons/truck.svg
> +  <path d="M10 17h4V5H2v12h3M20 17h2v-3.34a4 4 0 00-1.17-2.83L19 9h-5v8h1"/>
```suggestion
  <path d="M10 17h4V5H2v12h3M20 17h2v-3.34a4 4 0 00-1.17-2.83L19 9h-5v8h1" />
```

2020-12-30 19:08 UTC, ericfennis approved these changes

2020-12-31 15:03 UTC, merged