Changed the exemple of dynamic icons using NextJS
lucide-icons/lucide pull request #1580
Opened 2023-09-27 14:25 UTC by morrisseybr

This pr resolves the issue #1576.

2023-10-30 08:22 UTC, dani-z commented
Tried this locally, but unfortunately, it crashed my app. Are you sure this works with Next 13+ App router? Here's my error 
<img width="1039" alt="image" src="https://github.com/lucide-icons/lucide/assets/394966/621703c1-40c1-4a12-9bc7-214f0e9b6bfd">

2023-11-16 11:51 UTC, morrisseybr commented
> Tried this locally, but unfortunately, it crashed my app. Are you sure this works with Next 13+ App router? Here's my error <img alt="image" width="1039" src="https://user-images.githubusercontent.com/394966/278984066-621703c1-40c1-4a12-9bc7-214f0e9b6bfd.png">

Can you show your implementation and the use of the example that you are doing?

2023-11-16 15:47 UTC, jguddas approved these changes
👍 from me.

IMO we should remove the `dynamicIconImports` file, it's an antipattern and only leads to performance bottlenecks and flickering.

And hey, you can do this other ways such as described by your change here.

2023-11-23 23:37 UTC, KajSzy commented
> > Tried this locally, but unfortunately, it crashed my app. Are you sure this works with Next 13+ App router? Here's my error <img alt="image" width="1039" src="https://user-images.githubusercontent.com/394966/278984066-621703c1-40c1-4a12-9bc7-214f0e9b6bfd.png">
> 
> Can you show your implementation and the use of the example that you are doing?

I think his issue is that `dynamicIconImports` uses kebab-case icon names, while your apporach requires PascalCase
I've stumbled at exactly the same issue in my project that I very recently moved from non-optimized generic component to the one using `dynamicIconImports` ;)
But as reported in issue the slowness of dev server brought me here

2023-12-13 02:09 UTC, bernatfortet commented
@KajSzy converting the name to pascal case solved my issue. Dev server is super fast now. Thanks!

2023-12-15 23:11 UTC, ben519 commented
@morrisseybr this only works client-side. Any idea how to make it work within a Server Component?

2024-02-12 17:54 UTC, ericfennis requested changes

2024-02-12 17:54 UTC, ericfennis commented on docs/guide/packages/lucide-react.md
We should make separate sections for the App router and pages router.

Pages router should use the docs like it was before.

And create a new section specially targeting the App Router.
With this code example:
```tsx
import { LucideProps, icons } from 'lucide-react';

interface IconProps extends LucideProps {
  name: keyof typeof icons;
}

const Icon = ({ name, ...props }: IconProps) => {
  const LucideIcon = icons[name];

  return <LucideIcon {...props} />;
};

export default Icon;
```

2025-01-24 15:36 UTC, closed without merging