Added globe-lock icon
lucide-icons/lucide pull request #1587
Opened 2023-10-06 06:42 UTC by karsa-mistmere

## What is the purpose of this pull request?
- [x] New Icon

### Description
Added a globe-lock icon

### Icon use case
* VPN
* Secure connection
* Internet security
* Password/digital identity protection
* Privacy mode
* Data encryption

### Alternative icon designs
No viable alternates were made.

## Icon Design Checklist

### Concept
- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license
- [x] I've based them on the following Lucide icons: `globe-2` and `file-lock`

### Naming
- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design
- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to two points of precision.

## Before Submitting
- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

2023-10-06 06:44 UTC, jguddas commented
Why not have the lock in the bottom right corner?

2023-10-06 06:46 UTC, karsa-mistmere commented
> Why not have the lock in the bottom right corner?

Because I tried that and found that it looked pretty damn awful compared to this. :D 
(Hence no _viable_ alternatives).

![image](https://github.com/lucide-icons/lucide/assets/17746067/3999edc1-a4d5-4f6f-9de7-49fc2fa29e91)

2023-10-06 09:37 UTC, jguddas commented
> > Why not have the lock in the bottom right corner?
> 
> Because I tried that and found that it looked pretty damn awful compared to this. :D (Hence the "no _viable_ alternatives").
> 
> ![image](https://user-images.githubusercontent.com/17746067/273126404-3999edc1-a4d5-4f6f-9de7-49fc2fa29e91.png)

True, I would be fine with changes to the `globe` icon if that helps.

2023-10-06 09:47 UTC, ericfennis commented
@karsa-mistmere Really nice icon!
The lock in the right bottom looks a bit better to me.

2023-10-10 07:10 UTC, karsa-mistmere commented
![image](https://github.com/lucide-icons/lucide/assets/17746067/d788f0f8-a2fe-473c-9ea5-bf217c867341)

2023-10-10 10:43 UTC, karsa-mistmere commented
![image](https://github.com/lucide-icons/lucide/assets/17746067/0f8be46b-2a27-4b6c-a64e-78660632a015)

Not sure what you mean?

2023-10-13 13:18 UTC, ericfennis commented
@jguddas I think you can better post the changed SVG.

2023-10-13 13:21 UTC, jguddas commented
![icon (19)](https://github.com/lucide-icons/lucide/assets/25524993/ae95f002-b7c4-4f2b-8d9e-947407ea6b7d)

https://lucide-site-git-feat-added-edit-page-jguddas.vercel.app/edit?PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8Y2lyY2xlIGN4PSIxMiIgY3k9IjEyIiByPSIxMCIgLz4KICA8cGF0aCBkPSJNMjEuNSAxNUgxN2EyIDIgMCAwIDAtMiAydjQuNSIgLz4KICA8cGF0aCBkPSJNMi4yIDEwSDRhMiAyIDAgMCAxIDIgMnYxYTIgMiAwIDAgMCAyIDIgMiAyIDAgMCAxIDIgMnY0LjgiIC8+CiAgPHBhdGggZD0iTTUuNCA0LjVBMyAzIDAgMCAwIDggN2EyIDIgMCAwIDEgMiAydi41YTIgMiAwIDEgMCA0IDBWOWEyIDIgMCAwIDEgMi0yaDQuNyIgLz4KPC9zdmc+

2023-10-13 13:23 UTC, karsa-mistmere commented
Here's a 100% comparison of all three versions:
![image](https://github.com/lucide-icons/lucide/assets/17746067/558e93bb-b4f5-47c5-824c-138c9b3a97dd)

2023-10-13 18:37 UTC, ericfennis commented
The second row looks the best to me. 

I don't know but it feels a bit nicer with the lock on the bottom. Maybe because the flat bottom side?

What do you think?

2023-10-13 18:41 UTC, karsa-mistmere commented
That's exactly why the first row looks better to me, it has slightly better centre of gravity. :)

2023-10-13 19:41 UTC, jguddas commented on icons/globe-lock.svg
> +  <rect width="8" height="5" x="14" y="6" rx="1" />
![icon - 2023-10-13T213723 981](https://github.com/lucide-icons/lucide/assets/25524993/3f58eb6c-5a85-45df-b006-5eab54b33785)

```suggestion
  <path d="M14 22v-4a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1h-9" />
  <path d="M15.7 9.5A15.3 15.3 0 0 0 12 2a14.5 14.5 0 0 0 0 20 10 10 0 1 1 9.862-11.658" />
  <path d="M20 17v-2a2 2 0 1 0-4 0v2" />
  <path d="M2 12h10.9" />
```

2023-10-17 19:32 UTC, ericfennis commented
@karsa-mistmere I'm ok with that!
@jguddas Do you have a final opinion on this?

2023-10-17 19:36 UTC, jguddas commented
> @karsa-mistmere I'm ok with that!
> @jguddas Do you have a final opinion on this?

What about my proposal, based on globe?

I'm not a super big fan of any of the proposals including mine, quite a lot of compromises.

I definitely think the name has to change if we want to base it on globe-2 rather than globe.

2023-10-18 08:13 UTC, ericfennis commented
I think the first and second row looks a bit more balanced. Some gaps between some continents looks a bit too big.

I agree on renaming this icon and `globe-2` to `earth` as we discussed in discord.

2023-10-18 08:34 UTC, jguddas commented
+1 for row 2

2023-10-18 08:35 UTC, karsa-mistmere commented
> > What about my proposal, based on globe?
>
> I think the first and second row looks a bit more balanced. Some gaps between some continents looks a bit too big.

I think @jguddas means this one: 
![image](https://github.com/lucide-icons/lucide/assets/17746067/6e1cfa99-842b-44ee-b530-35a8de65a120)

I made two very similar ones, but I'm not a fan of these, the paths are just too broken up:
![image](https://github.com/lucide-icons/lucide/assets/17746067/e8ce27c4-bf6d-4c60-8c0f-fede2fecae7d)

2023-12-14 15:52 UTC, jguddas commented
I don't feel 100% about either option, what about ‘lab‘ing it?

2023-12-24 12:20 UTC, ericfennis commented
@jguddas Hmm I think the usecase is a valid usecase. I think we just need to agree on the styling.
@karsa-mistmere Can you make a decision, or do you want me to make the decision?

2023-12-24 12:26 UTC, karsa-mistmere commented
> @jguddas Hmm I think the usecase is a valid usecase. I think we just need to agree on the styling. @karsa-mistmere Can you make a decision, or do you want me to make the decision?

I still prefer my original design, since it means we don't have to also update `globe` to match, and I very much prefer our current globe icon to any of the proposed alternates.

2023-12-24 12:54 UTC, jguddas commented
I just think it's cramped and not all that pretty.

2024-01-17 18:54 UTC, ericfennis requested changes
Ok I want to move on with this one.
I'm ok with the current design, and I think we should move forward.
I think we should rename `globe-2` to `earth` and call this one `earth-lock`.
I also think we should add the other `globe-lock` design. With the `globe` icon in the background.

2024-02-25 10:52 UTC, jguddas commented
I think it should be `planet-earth` so we keep our selves open for the material type earth.

2024-02-25 10:56 UTC, karsa-mistmere commented
> I think it should be `planet-earth` so we keep our selves open for the material type earth.

Do you mean this one?
<img width="67" alt="image" src="https://github.com/lucide-icons/lucide/assets/17746067/4c80c3d5-d037-4152-9645-baa46f7ef9cc">

2024-02-25 11:08 UTC, jguddas commented
> > I think it should be `planet-earth` so we keep our selves open for the material type earth.
> 
> Do you mean this one? <img alt="image" width="67" src="https://private-user-images.githubusercontent.com/17746067/307585071-4c80c3d5-d037-4152-9645-baa46f7ef9cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NTk1MzgsIm5iZiI6MTcwODg1OTIzOCwicGF0aCI6Ii8xNzc0NjA2Ny8zMDc1ODUwNzEtNGM4MGMzZDUtZDAzNy00MTUyLTk2NDUtYmFhNDZmN2VmOWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDExMDcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyY2VhNzdmYTg0ZDllZDE2NTE3MjNlNjdhZTI5OTY5NzRlZTNhNTMxZWUyZWU0MDEyMjc1NjAwMTZlZDAzOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HMI-Pw5Ik1QvAq7TO-IRjnOkaOCNpUdkCVB2nTluQC0">

I mean just instead of calling it `earth` we should call it `planet-earth` and `planet-earth-lock`

2024-02-25 11:22 UTC, karsa-mistmere commented
> > > I think it should be `planet-earth` so we keep our selves open for the material type earth.
> > 
> > 
> > Do you mean this one? <img alt="image" width="67" src="https://private-user-images.githubusercontent.com/17746067/307585071-4c80c3d5-d037-4152-9645-baa46f7ef9cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NTk1MzgsIm5iZiI6MTcwODg1OTIzOCwicGF0aCI6Ii8xNzc0NjA2Ny8zMDc1ODUwNzEtNGM4MGMzZDUtZDAzNy00MTUyLTk2NDUtYmFhNDZmN2VmOWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDExMDcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyY2VhNzdmYTg0ZDllZDE2NTE3MjNlNjdhZTI5OTY5NzRlZTNhNTMxZWUyZWU0MDEyMjc1NjAwMTZlZDAzOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HMI-Pw5Ik1QvAq7TO-IRjnOkaOCNpUdkCVB2nTluQC0">
> 
> I mean just instead of calling it `earth` we should call it `planet-earth` and `planet-earth-lock`

Yeah, but what exactly do you mean keep ourselves open for "the material type earth"?

2024-02-25 13:06 UTC, jguddas commented
> > > > I think it should be `planet-earth` so we keep our selves open for the material type earth.
> > > 
> > > 
> > > Do you mean this one? <img alt="image" width="67" src="https://private-user-images.githubusercontent.com/17746067/307585071-4c80c3d5-d037-4152-9645-baa46f7ef9cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NTk1MzgsIm5iZiI6MTcwODg1OTIzOCwicGF0aCI6Ii8xNzc0NjA2Ny8zMDc1ODUwNzEtNGM4MGMzZDUtZDAzNy00MTUyLTk2NDUtYmFhNDZmN2VmOWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDExMDcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyY2VhNzdmYTg0ZDllZDE2NTE3MjNlNjdhZTI5OTY5NzRlZTNhNTMxZWUyZWU0MDEyMjc1NjAwMTZlZDAzOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HMI-Pw5Ik1QvAq7TO-IRjnOkaOCNpUdkCVB2nTluQC0">
> > 
> > 
> > I mean just instead of calling it `earth` we should call it `planet-earth` and `planet-earth-lock`
> 
> Yeah, but what exactly do you mean keep ourselves open for "the material type earth"?

https://www.thesaurus.com/browse/earth

2024-02-25 13:09 UTC, karsa-mistmere commented
> > > > > I think it should be `planet-earth` so we keep our selves open for the material type earth.
> > > > 
> > > > 
> > > > Do you mean this one? <img alt="image" width="67" src="https://private-user-images.githubusercontent.com/17746067/307585071-4c80c3d5-d037-4152-9645-baa46f7ef9cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NTk1MzgsIm5iZiI6MTcwODg1OTIzOCwicGF0aCI6Ii8xNzc0NjA2Ny8zMDc1ODUwNzEtNGM4MGMzZDUtZDAzNy00MTUyLTk2NDUtYmFhNDZmN2VmOWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDExMDcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyY2VhNzdmYTg0ZDllZDE2NTE3MjNlNjdhZTI5OTY5NzRlZTNhNTMxZWUyZWU0MDEyMjc1NjAwMTZlZDAzOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HMI-Pw5Ik1QvAq7TO-IRjnOkaOCNpUdkCVB2nTluQC0">
> > > 
> > > 
> > > I mean just instead of calling it `earth` we should call it `planet-earth` and `planet-earth-lock`
> > 
> > 
> > Yeah, but what exactly do you mean keep ourselves open for "the material type earth"?
> 
> https://www.thesaurus.com/browse/earth

Haha, I totally thought you meant Material as in https://m3.material.io/styles/icons/overview

If and when we add this as an icon, `soil` or `ground` would be much more obvious choices for a name, so I think we're in the clear.

2024-02-25 18:25 UTC, jguddas approved these changes

2024-02-26 08:52 UTC, ericfennis approved these changes

2024-02-26 08:53 UTC, merged