New icons: user-search and user-search-2
lucide-icons/lucide pull request #1620
Opened 2023-10-19 02:39 UTC by jmsv

## What is the purpose of this pull request?

- [x] New Icon
- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other:

### Description

New icons:
- `user-search`
- `user-search-2`

### Icon use case 

- Searching for users
- Recruitment

### Alternative icon designs 

## Icon Design Checklist 

### Concept 

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [ ] The icons are solely my own creation.
- [ ] The icons were originally created in #<issueNumber> by @<githubUser>
- [x] I've based them on the following Lucide icons: `user-check`, `user-plus`, `user-x` etc. + corresponding `-2` variations, plus `search`
- [ ] I've based them on the following design: 

### Naming 

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design 

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to two points of precision.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

2023-10-19 07:20 UTC, jguddas commented
![icon (21)](https://github.com/lucide-icons/lucide/assets/25524993/3f066d5e-648a-44cb-8434-5738402211f1)
https://lucide-site-git-feat-added-edit-page-jguddas.vercel.app/edit?PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8Y2lyY2xlIGN4PSIxMCIgY3k9IjciIHI9IjQiIC8+CiAgPGNpcmNsZSBjeD0iMTciIGN5PSIxNyIgcj0iMyIgLz4KICA8cGF0aCBkPSJtMjEgMjEtMS45LTEuOSIgLz4KICA8cGF0aCBkPSJNMTAuMyAxNUg3YTQgNCAwIDAgMC00IDR2MiIgLz4KPC9zdmc+=

2023-10-19 14:23 UTC, jmsv commented
@jguddas that looks good, did that exist somewhere already? missed it if so

had a go at making a similar version for the `user-2` style:

![icon (1)](https://github.com/lucide-icons/lucide/assets/14852491/0b3edea2-4ffc-43e3-b382-c89ae10a9858)

2023-10-19 14:29 UTC, jmsv commented
updated this PR with the new icons, looks much better, thanks for having a look!

2023-10-21 13:46 UTC, jguddas requested changes
It's based on an existing icon, so it should inherit the contributors.

2023-10-21 13:46 UTC, jguddas commented on icons/user-search.json
> +    "jmsv"
```suggestion
    "jmsv",
    "jguddas",
    "colebemis",
    "csandman",
    "ericfennis",
    "karsa-mistmere"
```

2023-10-21 13:46 UTC, jguddas commented on icons/user-search-2.json
> +    "jmsv"
```suggestion
    "jmsv",
    "karsa-mistmere"
```

2023-10-21 14:28 UTC, jmsv commented
> It's based on an existing icon, so it should inherit the contributors.

gotcha, missed that – fixed

2023-10-26 13:48 UTC, jguddas reviewed
`user-search-2` violates naming guidelines, icons should not end with `-2`.

I highly recommend creating one PR per icon.

2023-10-26 14:04 UTC, jguddas commented
IMO adding icons with the same use case but with different styles is something we should avoid, it works against having one consistent feel across all icons.

So 👍 for `user-search` and 👎 for `user-search-2` from me.

2023-10-26 15:24 UTC, jmsv commented
Thanks for having a look @jguddas and @karsa-mistmere ❤️ 

---

> I highly recommend creating one PR per icon.

From [CONTRIBUTING.md](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md):

> If you want submit multiple icons, please separate the icons and group them. That makes reviewing the icons easier and keep the thread clean and scoped. So don't submit multiple icons in one PR that have noting to do with each other. So for example don't create one PR with icons: arrow-up, bicycle, arrow-down. Seperate them by two PRs; 'pr-01' arrow, arrow-down and 'pr-02' bicycle.

As-per these guidelines I think I was correct in making this one PR.

---

Re the `user*-2` naming I'm aware that the [Naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions) advise against `-2` for "what makes the alternate unique" but I opted for naming consistency instead – I agree with @karsa-mistmere that it makes more sense than deviating.

I like the sound of `user-round-*`! Should take into account though that this would be a breaking change for anyone currently using `user*-2` icons.

---

As for what to do with this PR, it looks like the options are:

1. Keep the `user-search-2` name for now
2. Rename `user-search-2` to `user-round-search`
3. Remove `user-search-2` entirely

Option 2 isn't ideal since it introduces naming inconsistency, and option 3 isn't ideal since it _also_ introduces inconsistency considering every other `user-*` icon has a `-2` variant.

Hoping we can go with option 1 but let me know what you think

2023-10-26 16:19 UTC, karsa-mistmere commented
We can add backwards compatible aliases for current `user-*-2` icons.

2023-10-26 16:24 UTC, jmsv commented
> We can add backwards compatible aliases for current `user-*-2` icons.

Ah, awesome! I'd be happy to have a go at setting that up

2023-10-26 17:35 UTC, jguddas commented
> > We can add backwards compatible aliases for current `user-*-2` icons.
> 
> Ah, awesome! I'd be happy to have a go at setting that up

If you are up for it, you can give my new `renameIcon.sh` script a try.

https://github.com/lucide-icons/lucide/pull/1630

## How to use it

Make sure you have the [gh cli](https://cli.github.com/) installed.

Don't think this will work on Windows.

```bash
gh pr checkout 1630 # go to my PR with the new rename script
./scripts/renameIcon.sh user-2 user-round # run the script
git checkout main # go back to main
git checkout -b rename/user-2-to-user-round # create a new branch
git commit -m 'Renamed user-2 to user-round' # commit the changes
gh pr create --title 'Renamed user-2 to user-round' # create a pull request
git checkout main # go back to main
```

2023-10-26 19:32 UTC, jmsv commented
Done! #1638

2023-12-15 10:45 UTC, ericfennis approved these changes

2023-12-15 11:21 UTC, merged