Optimized and closed gap in `paint-bucket` icon
lucide-icons/lucide pull request #1649
Opened 2023-10-28 17:24 UTC by jguddas

## What is the purpose of this pull request?

- [ ] New Icon
- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [x] Other: Optimization

2023-10-30 13:59 UTC, karsa-mistmere requested changes

2023-10-30 13:59 UTC, karsa-mistmere commented on icons/paint-bucket.svg
> +  <path d="m19 11-8-8-8.6 8.6a2 2 0 0 0 0 2.8l5.2 5.2c.8.8 2 .8 2.8 0Z" />
This path reaches outside our 1px padding box. My go-to method with 45deg corners is to just round them using a 2.41 radius which results in perfectly grid-aligned lines and corners:
```suggestion
  <path d="m19 11-8.3 8.3a2.4 2.4 0 0 1-3.4 0l-4.6-4.6a2.41 2.41 0 0 1 0-3.4L11 3Z" />
```

2023-10-30 13:59 UTC, karsa-mistmere commented on icons/paint-bucket.svg
> +  <path d="M1.85 13H17" />
Fixing the path above also means we can simplify this further:
```suggestion
  <path d="M2 13h15" />
```

2023-12-08 11:39 UTC, ericfennis commented
Hmm with the changes from @karsa-mistmere is now adding more code. So I think we should not do this one.

2023-12-08 11:39 UTC, closed without merging