fix export IconNode type
lucide-icons/lucide pull request #1656
Opened 2023-10-31 12:04 UTC by Sukomal07

fixes #1654

2023-11-01 07:34 UTC, ericfennis requested changes
I've just tested this. Unfortunately this is not going to work, since these inputs are used to bundle. In the bottom of this file we bundle the types, and that can be only one file.


So what we should do is export the types in: `packages/lucide/src/lucide.ts`.
Put this line at the bottom and this is solved.
```ts
/*
 Types exports.
*/
export * from './types';
```

2023-11-01 07:34 UTC, ericfennis commented on packages/lucide/rollup.config.mjs
> +const inputs = ['src/lucide.ts', 'src/types.ts'];
Please revert this.

2023-11-01 14:35 UTC, Sukomal07 commented
@ericfennis done

2023-11-01 14:53 UTC, ericfennis approved these changes
Awesome work!

2023-11-01 14:53 UTC, merged

2023-11-01 14:57 UTC, Sukomal07 commented
> Awesome work!

Thanks for help

2023-11-02 11:11 UTC, olaf-k commented
that was fast, thanks a lot guys!