remove extra space in svg class attribute
lucide-icons/lucide pull request #1703
Opened 2023-11-27 15:17 UTC by Sukomal07

fixes #1701

2023-11-27 19:05 UTC, ericfennis commented
Conflicts

2023-11-28 16:47 UTC, Sukomal07 commented
> Conflicts

resolved

2023-11-28 17:45 UTC, jguddas requested changes

2023-11-28 17:45 UTC, jguddas commented on packages/lucide-react/src/createLucideIcon.ts
> +          ...((Array.isArray(children) ? children : [children]) || []),
`Array.isArray(children) ? children : [children]` is always `truthy`.

```suggestion
          ...(Array.isArray(children) ? children : [children]),
```

2023-11-28 19:59 UTC, ericfennis approved these changes
Awesome!

2023-11-28 19:59 UTC, merged