Add caption icons
lucide-icons/lucide pull request #1799
Opened 2024-01-13 02:56 UTC by DefaultLP

## What is the purpose of this pull request?

- [x] New Icon
- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other:

### Description
This PR adds two new icons. One for captions and one for disabled captions.
(Now with actually 2px corner radius...)

<img width="80" alt="inkscape_jHkPsnRJ0D" src="https://github.com/lucide-icons/lucide/assets/29122114/738fadf9-1f17-4a1f-9471-91f50cf89715">

Additionally, this PR adds the "multimedia" category to the subtitles icon. Same as these captions.

### Icon use case
Is it useful for any application that deals with videos. Whether that be streaming or editing, having an icon that represents one of the three major components of internet videos is always a good idea. 

I mainly did this because I needed a subtitles/captions icon that had an off/disabled variant since I'm building a SvelteKit UI that works with videos.

### Alternative icon designs

Off/disabled variant
<img width="80" alt="inkscape_ShBHixQJuk" src="https://github.com/lucide-icons/lucide/assets/29122114/d822a1ff-999e-4dad-9d5d-d15e359d9990">

## Icon Design Checklist

### Concept
- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license
- [ ] The icons are solely my own creation.
- [ ] The icons were originally created in #<issueNumber> by @<githubUser>
- [x] I've based them on the following Lucide icons: subtitles
- [ ] I've based them on the following design: 

### Naming
- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design
- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to two points of precision.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

2024-01-13 09:38 UTC, ericfennis requested changes
Nice icon, the design is perfect.
The SVG code needs some formatting. And the meta json files as well, I gave some suggestions.

I think we should replace the current `subtitles` icon, with these ones.

2024-01-13 09:38 UTC, ericfennis commented on icons/captions-off.json
> +  ],
```suggestion
    "DefaultLP"
  ],
  "tags": [
    "closed captions",
	  "subtitles",
	  "subhead",
	  "transcription",
	  "transcribe",
	  "dialogue",
    "accessibility"
  ],
```

2024-01-13 09:38 UTC, ericfennis commented on icons/captions.json
> +  ],
```suggestion
  "contributors": [
    "DefaultLP"
  ],
  "tags": [
     "closed captions",
	  "subtitles",
	  "subhead",
	  "transcription",
	  "transcribe",
	  "dialogue",
    "accessibility"
  ],
```

2024-01-13 09:38 UTC, ericfennis commented on icons/captions.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide luci
Can you make sure the formatting is correctly done?

2024-01-13 09:38 UTC, ericfennis commented on icons/captions-off.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide luci
This file need some formatting, see other icons as example.
Or see the lining errors to guide you.

2024-01-13 09:57 UTC, DefaultLP commented
I now changed all files to reflect the feedback.

Although the SVG formatting was an incredibly stupid error on my part, since I used the SVG I downloaded from the icons library as reference, instead of the ones from the repository...

2024-01-13 14:44 UTC, DefaultLP commented
So sorry for that. I'm usually not such a pain to work with

2024-01-13 15:34 UTC, jguddas commented
The off variant has a bunch of gap violations and should use arcs for the corners.

This would work ![icon (36)](https://github.com/lucide-icons/lucide/assets/25524993/f9891218-c57b-487d-8edf-77a40b14421a)

https://lucide-studio.vercel.app/?value=%3Csvg++xmlns=%22http://www.w3.org/2000/svg%22++width=%2224%22++height=%2224%22++viewBox=%220+0+24+24%22++fill=%22none%22++stroke=%22currentColor%22++stroke-width=%222%22++stroke-linecap=%22round%22++stroke-linejoin=%22round%22%3E++%3Cpath+d=%22M10.5+5H19a2+2+0+0+1+2+2v8.5%22+/%3E++%3Cpath+d=%22M17+11h-.5%22+/%3E++%3Cpath+d=%22M19+19H5a2+2+0+0+1-2-2V7a2+2+0+0+1+2-2%22+/%3E++%3Cpath+d=%22m2+2+20+20%22+/%3E++%3Cpath+d=%22M7+11h4%22+/%3E++%3Cpath+d=%22M7+15h2.5%22+/%3E%3C/svg%3E

2024-01-13 15:54 UTC, DefaultLP commented
Well and now I know what gap violations are. What a productive day.

2024-01-16 14:51 UTC, ericfennis requested changes

2024-01-16 14:51 UTC, ericfennis commented on icons/captions-off.json
> +    "defaultlp"
Your name should be exactly the same as in you Github URL like. So it should be:
```suggestion
    "DefaultLP"
```

2024-01-16 14:51 UTC, ericfennis commented on icons/captions.json
> +    "defaultlp"
Same here:
```suggestion
    "DefaultLP"
```

2024-01-16 14:51 UTC, ericfennis commented on icons/captions.json
> +  ]
We should remove the `subtitles` icon and add it as an alias.
```suggestion
  ],
  "aliases": [
    "subtitles"
  ]
```

2024-01-16 14:51 UTC, ericfennis commented on icons/subtitles.json
>      "accessibility"
Can you remove this file along with the SVG file?

2024-01-16 20:17 UTC, jguddas commented
My vote, keep them both and just rename the `subtitels` icon to `message-square-text`.

2024-01-17 19:01 UTC, jguddas commented
We can add the alias there.

2024-01-17 19:01 UTC, ericfennis approved these changes
Nice work @DefaultLP !

2024-01-17 19:02 UTC, DefaultLP commented
Well, thank you for putting up with me!

2024-02-05 18:34 UTC, merged