Add `electric-truck` icon
lucide-icons/lucide pull request #1803
Opened 2024-01-14 10:52 UTC by LienMaas

## What is the purpose of this pull request?

- [x] New Icon
- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other:

### Description

Adds an icon for electric trucks
![image](https://github.com/lucide-icons/lucide/assets/47668108/87e9d514-c062-4d16-b40c-69a073cb73bc)

### Icon use case 

Makes it possible to distinguish between regular and electric trucks.

### Alternative icon designs 

## Icon Design Checklist 

### Concept 

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [ ] The icons are solely my own creation.
- [ ] The icons were originally created in #<issueNumber> by @<githubUser>
- [x] I've based them on the following Lucide icons: truck 
- [ ] I've based them on the following design: 

### Naming 

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design 

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to two points of precision.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

2024-01-16 14:43 UTC, ericfennis commented
@LienMaas Can we try to make a variant with the zap a bit bigger?
On 100% scale the zap looks a bit small.

2024-01-16 17:04 UTC, danielbayley commented
@LienMaas It should also be centred in the van I think. See also #1460, for consistency…

2024-01-16 17:14 UTC, LienMaas commented
@danielbayley I tried putting the zap in the middle, but the zap had to be really small to not violate the 2px rule.

This way I can definetly make the zap a bit bigger

2024-01-16 17:41 UTC, danielbayley commented
> I tried putting the zap in the middle, but the zap had to be really small to not violate the 2px rule.
> This way I can definetly make the zap a bit bigger

@LienMaas Yeah I meant something a bit like this…

![preview](https://github.com/lucide-icons/lucide/assets/7797479/c1a9363a-deae-4d1d-937a-b78b39279320)

2024-01-16 20:07 UTC, jguddas commented
> > I tried putting the zap in the middle, but the zap had to be really small to not violate the 2px rule.
> > This way I can definetly make the zap a bit bigger
> 
> @LienMaas Yeah I meant something a bit like this…
> 
> ![preview](https://private-user-images.githubusercontent.com/7797479/297142382-c1a9363a-deae-4d1d-937a-b78b39279320.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MzU5NDEsIm5iZiI6MTcwNTQzNTY0MSwicGF0aCI6Ii83Nzk3NDc5LzI5NzE0MjM4Mi1jMWE5MzYzYS1kZWFlLTRkMWQtOTM3YS1iNzhiMzkyNzkzMjAuc3ZnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTZUMjAwNzIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Nzk1OTM4MGZkMjFiMTc0Y2RjNTgxMWNiMDUzMjZjZjg5YmYyODVhMjNmYjBkNGQ1NGNkZDA1MDBlNGYxYzVlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SfV7HRMyj9Hy8mLREtBxWxdhrOMDSq3aeu8AM7NzKGc)

I like it, here is the studio link.

https://lucide-studio.vercel.app/?value=%3Csvg++xmlns=%22http://www.w3.org/2000/svg%22++width=%2224%22++height=%2224%22++viewBox=%220+0+24+24%22++fill=%22none%22++stroke=%22currentColor%22++stroke-width=%222%22++stroke-linecap=%22round%22++stroke-linejoin=%22round%22%3E++%3Cpath+d=%22M12+5h1a1+1+0+0+1+1+1v11%22+/%3E++%3Cpath+d=%22M14+8h4l4+4v4a1+1+0+0+1-1+1h-2%22+/%3E++%3Cpath+d=%22M15+17H9%22+/%3E++%3Cpath+d=%22M3.2+5H3a1+1+0+0+0-1+1v10a1+1+0+0+0+1+1h2%22+/%3E++%3Cpath+d=%22M8+5+6+8h4l-2+3%22+/%3E++%3Ccircle+cx=%2217%22+cy=%2217%22+r=%222%22+/%3E++%3Ccircle+cx=%227%22+cy=%2217%22+r=%222%22+/%3E%3C/svg%3E

2024-01-22 17:13 UTC, ericfennis commented
Related to PR #1819, this could affect this icon's design.

2024-01-31 07:37 UTC, ericfennis requested changes
Should be using the new truck icon, see #1838

2024-05-18 19:45 UTC, jguddas commented on icons/truck-electric.svg
> +  <path d="M17 20a2 2 0 1 0 0-4 2 2 0 0 0 0 4M7 20a2 2 0 1 0 0-4 2 2 0 0 0 0 4" />
```suggestion
  <path d="M12 6h1a1 1 0 0 1 1 1v11" />
  <path d="M14 9h3.172a2 2 0 0 1 1.414.586l2.828 2.828A2 2 0 0 1 22 13.828V17a1 1 0 0 1-1 1h-2" />
  <path d="M15 18H9" />
  <path d="M3.2 6H3a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h2" />
  <path d="M8 6 6.518 8.223A.5.5 0 0 0 6.934 9h2.132a.5.5 0 0 1 .416.777L8 12" />
  <circle cx="17" cy="18" r="2" />
  <circle cx="7" cy="18" r="2" />
```
![icon (55)](https://github.com/lucide-icons/lucide/assets/25524993/bb2d43b9-19d9-44ea-a4d8-a46cf8a795d9)


<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M12+6h1a1+1+0+0+1+1+1v11%22+/%3E%3Cpath+d=%22M14+9h3.172a2+2+0+0+1+1.414.586l2.828+2.828A2+2+0+0+1+22+13.828V17a1+1+0+0+1-1+1h-2%22+/%3E%3Cpath+d=%22M15+18H9%22+/%3E%3Cpath+d=%22M3.2+6H3a1+1+0+0+0-1+1v10a1+1+0+0+0+1+1h2%22+/%3E%3Cpath+d=%22M8+6+6.518+8.223A.5.5+0+0+0+6.934+9h2.132a.5.5+0+0+1+.416.777L8+12%22+/%3E%3Ccircle+cx=%2217%22+cy=%2218%22+r=%222%22+/%3E%3Ccircle+cx=%227%22+cy=%2218%22+r=%222%22+/%3E"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTIgNmgxYTEgMSAwIDAgMSAxIDF2MTEiIC8+CiAgPHBhdGggZD0iTTE0IDloMy4xNzJhMiAyIDAgMCAxIDEuNDE0LjU4NmwyLjgyOCAyLjgyOEEyIDIgMCAwIDEgMjIgMTMuODI4VjE3YTEgMSAwIDAgMS0xIDFoLTIiIC8+CiAgPHBhdGggZD0iTTE1IDE4SDkiIC8+CiAgPHBhdGggZD0iTTMuMiA2SDNhMSAxIDAgMCAwLTEgMXYxMGExIDEgMCAwIDAgMSAxaDIiIC8+CiAgPHBhdGggZD0iTTggNiA2LjUxOCA4LjIyM0EuNS41IDAgMCAwIDYuOTM0IDloMi4xMzJhLjUuNSAwIDAgMSAuNDE2Ljc3N0w4IDEyIiAvPgogIDxjaXJjbGUgY3g9IjE3IiBjeT0iMTgiIHI9IjIiIC8+CiAgPGNpcmNsZSBjeD0iNyIgY3k9IjE4IiByPSIyIiAvPgo8L3N2Zz4=.svg"/><br/>Open lucide studio</a>

2024-05-18 19:45 UTC, jguddas commented on icons/truck-electric.json
> +    "lienmaas"
```suggestion
    "LienMaas"
```

2024-05-18 19:45 UTC, jguddas commented on icons/truck-electric.json
> +    "lienmaas"
Also add the people who are in the truck icon contributors field.

2024-07-19 08:14 UTC, ericfennis commented
I think we should maybe go for the original design concept where the zap is in the corner. Because it is centered and with gap in the top it looks a bit if something is wrong with the truck. Like a crack 😄

2024-07-26 10:17 UTC, ericfennis commented
@LienMaas Looks more like it. But there should be 1px spacing with the canvas.

2025-04-18 13:06 UTC, ericfennis commented
@AnnaSasDev I've applied your suggestion

2025-04-18 13:07 UTC, ericfennis approved these changes

2025-04-18 14:55 UTC, jguddas approved these changes

2025-04-18 14:58 UTC, merged