Add terminal-2 icon
lucide-icons/lucide pull request #181
Opened 2021-01-27 15:55 UTC by mittalyashu

| Preview |
| --- |
| <img width="557" alt="CleanShot 2021-01-27 at 21 22 26@2x" src="https://user-images.githubusercontent.com/29014463/106017018-09514e00-60e6-11eb-82d9-a4ea205c98d1.png"> |

2021-01-27 17:42 UTC, locness3 commented
`terminal-square`?

2021-01-28 03:58 UTC, mittalyashu commented
What about `terminal-app`?

2021-02-07 17:00 UTC, mittalyashu commented
any updates on this PR?

2021-02-12 16:08 UTC, ericfennis approved these changes

2021-02-17 12:09 UTC, ericfennis requested changes
@mittalyashu Can you try to use the basic square shape?
![image](https://user-images.githubusercontent.com/11825403/108202419-5b9ff080-7121-11eb-9761-4dc15788093e.png)

2021-04-01 18:48 UTC, ericfennis commented on icons/terminal-square.svg
> +  <path d="M19 3H5a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2V5a2 2 0 00-2-2z" />
shorter with rect element
```suggestion
  <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />
```

2021-04-01 18:48 UTC, merged