fix: Add the license banner inside of the script tag instead of an HTML comment
lucide-icons/lucide pull request #1811
Opened 2024-01-17 17:07 UTC by AdrianGonz97

Fixes https://github.com/lucide-icons/lucide/pull/1707#issuecomment-1894976168

## What is the purpose of this pull request?

- [ ] New Icon
- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other:

### Description
It turns out that HTML comments in Svelte files turn into whitespace during SSR, but *not* in CSR. This leads to an extra whitespace appearing during initial renders, followed by the whitespace disappearing during hydration. 

Here's a small demo:
![img](https://i.imgur.com/XLRfTlu.gif)

This is certainly more of a bug on Svelte's end, but a fix for now is to move the banner inside of the script tag instead. 

---

I rearranged the build scripts to inject the banner during icon creation instead (just for svelte files, other file types will have the banner appended at the end of the build) to keep it simple and avoid having to do any fancy string manipulations.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

2024-01-17 17:37 UTC, jguddas requested changes

2024-01-17 17:37 UTC, jguddas commented on packages/lucide-svelte/scripts/license.mjs
> +}
```suggestion
export function getJSBanner() {
  return `/**
 * @license ${pkg.name} v${pkg.version} - ${pkg.license}
 *
 * This source code is licensed under the ${pkg.license} license.
 * See the LICENSE file in the root directory of this source tree.
 */
`;
}
```

2024-01-17 17:56 UTC, jguddas approved these changes

2024-01-17 18:42 UTC, ericfennis requested changes

2024-01-17 18:42 UTC, ericfennis commented on packages/lucide-svelte/scripts/appendLicense.mjs
>      const blockCommentRegex = /\/\*\*[\s\S]*?\*\//;
We need to change this regex, this now also matches with the license block comment which results in twice adding the license block comment. 

Here is the correct new regex:
``` suggestion
    const blockCommentRegex = /\/\*\*\n\s\*\s(@component\s@name)[\s\S]*?\*\//;
```

2024-01-17 18:42 UTC, ericfennis commented on packages/lucide-svelte/scripts/appendLicense.mjs
> -import { getCurrentDirPath } from '../../../scripts/helpers.mjs';
I think we can better rename this to `appendBlockComments.mjs`. I've also added other block comments for the icon components.

2024-01-29 18:47 UTC, ericfennis approved these changes
Awesome!

2024-01-29 18:48 UTC, merged

2024-02-01 03:00 UTC, isker commented
It's fixed for me. Thank you!