Adds `handshake` icon
lucide-icons/lucide pull request #1835
Opened 2024-01-30 10:03 UTC by karsa-mistmere

closes #608 

Also see: https://github.com/lucide-icons/lucide/issues/119 and https://github.com/feathericons/feather/issues/444 and https://github.com/feathericons/feather/issues/486

## What is the purpose of this pull request?
- [x] New Icon

### Description
Adds handshake icon to represent businesses, deals, partnerships etc.

### Icon use case 
As above.

### Alternative icon designs
See #608 

## Icon Design Checklist

### Concept
- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [x] The icons are solely my own creation.

### Naming 

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design 

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to two points of precision.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

2024-01-30 10:04 UTC, jguddas commented
I'm not a fan, I feel like it's very hard to identify.

2024-01-30 11:37 UTC, karsa-mistmere commented
> I'm not a fan, I feel like it's very hard to identify.

I made this alternate design but it feels a bit clunky:
![image](https://github.com/lucide-icons/lucide/assets/17746067/04bd6b2a-80b8-4b4e-aa2c-aad688791ff5)

2024-01-30 19:29 UTC, jguddas commented
> > I'm not a fan, I feel like it's very hard to identify.
> 
> I made this alternate design but it feels a bit clunky: ![image](https://private-user-images.githubusercontent.com/17746067/300791123-04bd6b2a-80b8-4b4e-aa2c-aad688791ff5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NDMxOTAsIm5iZiI6MTcwNjY0Mjg5MCwicGF0aCI6Ii8xNzc0NjA2Ny8zMDA3OTExMjMtMDRiZDZiMmEtODBiOC00YjRlLWFhMmMtYWFkNjg4NzkxZmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDE5MjgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMjZlM2RhYmYyM2FkZmQ5MDA5YmUwMDgzMTYwMDIxYjg3NWFhYjM4ZGIwMGU3NTRmYzg1OTdlMDA4YjI0MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IR-HbU7hgfyLm2mnpXsR540rzol3bpa2O2hko2_nH2s)

Feels better, but yes a bit clunky.

2024-01-31 08:04 UTC, ericfennis commented
@karsa-mistmere Can you post a 100% scale version? 
The current `hand` also looks a bit clunky when it is larger than 100%

2024-01-31 09:09 UTC, karsa-mistmere commented
![image](https://github.com/lucide-icons/lucide/assets/17746067/92b334b4-ed94-4b07-8fdf-cfb470cd3d4b)

2024-01-31 09:32 UTC, ericfennis commented
@karsa-mistmere Hmm looks not "bad", it's quite recognizable in comparison with the icon in the PR. 
But not perfect yet, can you maybe send the SVG? I want to give it a try.

2024-01-31 14:17 UTC, ericfennis commented
@karsa-mistmere @jguddas I've adjusted a bit (left from karse, second one adjusted by me). 
I've reduced the length of the fingers a bit. And created a curve in the thumb like the `hearth-hands` icon
To me, this variant of the `handshake` is more in line with our other hand icons.

<img width="473" alt="image" src="https://github.com/lucide-icons/lucide/assets/11825403/aa2732d3-c6d9-4f7b-ac67-dda20dab7ebc">

100%:
![handshake](https://github.com/lucide-icons/lucide/assets/11825403/2539db61-34c6-48ae-8e87-0587bca7b62c)

2024-01-31 21:49 UTC, karsa-mistmere commented
> @karsa-mistmere @jguddas I've adjusted a bit (left from karse, second one adjusted by me). I've reduced the length of the fingers a bit. And created a curve in the thumb like the `hearth-hands` icon To me, this variant of the `handshake` is more in line with our other hand icons.
> 
> <img alt="image" width="473" src="https://private-user-images.githubusercontent.com/11825403/301190177-aa2732d3-c6d9-4f7b-ac67-dda20dab7ebc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3Mzc5NTMsIm5iZiI6MTcwNjczNzY1MywicGF0aCI6Ii8xMTgyNTQwMy8zMDExOTAxNzctYWEyNzMyZDMtYzZkOS00ZjdiLWFjNjctZGRhMjBkYWI3ZWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDIxNDczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkN2RlZjRmMzUwZjEzMGUzZGUxOTAwZDI3MTZkNmVlYWJiMTJkNTFiZjBkOTA2MGE3M2NjMTgyZmE1Mjc3YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NERMrbMVO_UAC7mAugDJmhPCchuVnz5BrzHGJWdi3VA">
> 100%: ![handshake](https://private-user-images.githubusercontent.com/11825403/301190308-2539db61-34c6-48ae-8e87-0587bca7b62c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3Mzc5NTMsIm5iZiI6MTcwNjczNzY1MywicGF0aCI6Ii8xMTgyNTQwMy8zMDExOTAzMDgtMjUzOWRiNjEtMzRjNi00OGFlLThlODctMDU4N2JjYTdiNjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDIxNDczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiODk5YTU5MWNkNmMyNWQ4OGI3OTEwNjU3ZTYxYjE1MDk0ZGM2ZjA5MTY5NjZlNjBkYzk2MmI0YWMwNTA4ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QRpZkWGfrIWvqVMeOvllvqy5sQnR7hNB3FB0ti5kHLw)

I really like this one, especially how it works together with `heart-handshake`, can you update the PR with it?

2024-02-01 08:56 UTC, ericfennis commented
@karsa-mistmere Updated!

2024-02-01 09:22 UTC, karsa-mistmere commented
Should we also update `heart-handshake` to match this orientation? 🤔

![image](https://github.com/lucide-icons/lucide/assets/17746067/3313f6aa-5ade-4a78-adff-683e9b85fc5b)

2024-02-01 09:42 UTC, ericfennis commented
Hmm, I was looking at what [Google](https://www.google.com/search?q=handshake+icon&oq=handshake+icon&sourceid=chrome&ie=UTF-8) gives me back as a `handshake` icon.
I suggest mirroring the `handshake` icon to be more conventional

2024-02-01 10:42 UTC, karsa-mistmere commented
> Hmm, I was looking at what [Google](https://www.google.com/search?q=handshake+icon&oq=handshake+icon&sourceid=chrome&ie=UTF-8) gives me back as a `handshake` icon. I suggest mirroring the `handshake` icon to be more conventional

Done!

2024-02-01 11:31 UTC, jguddas requested changes

2024-02-01 11:31 UTC, jguddas commented on icons/handshake.json
> +    "karsa-mistmere"
```suggestion
    "karsa-mistmere",
    "ericfennis"
```

2024-02-01 11:40 UTC, jguddas commented
What about updating the handshake heart to use the same round fingers?

![icon (37) 1](https://github.com/lucide-icons/lucide/assets/25524993/efdc0a9c-8783-4b6f-9cc4-6ea229d818f1)

2024-02-01 11:44 UTC, karsa-mistmere commented
> What about updating the handshake heart to use the same round fingers?
> 
> ![icon (37) 1](https://private-user-images.githubusercontent.com/25524993/301491584-efdc0a9c-8783-4b6f-9cc4-6ea229d818f1.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3ODgwOTMsIm5iZiI6MTcwNjc4Nzc5MywicGF0aCI6Ii8yNTUyNDk5My8zMDE0OTE1ODQtZWZkYzBhOWMtODc4My00YjZmLTljYzQtNmVhMjI5ZDgxOGYxLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDExNDMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MTE1ZDQxYTRlOGQyMDFjM2I5Y2E4ZDQxYzEzMjg0NDRhZWJhMDUxODBhZWUzODg5YWY0NDBkMDkyNjQ3YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XUnu7OKbR4NVZrc1Or9YCz76kqIcWikmwGBwPJ1pYjw)

I've tried something similar, but does this not make it look like a regular (albeit rounded) handshake as opposed to a heart as intended?

2024-02-01 13:06 UTC, ericfennis approved these changes

2024-02-01 15:37 UTC, merged