Add `square-root`icon
lucide-icons/lucide pull request #1847
Opened 2024-02-03 09:45 UTC by smnandre

## What is the purpose of this pull request?
- [x] New Icon 
- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other:

### Description

Add a "square root" icon, in two formats like the other math operators

### Icon use case 

* Buttons for calculator
* Section/tags for sorting math lessons

## Icon Design Checklist

### Concept 
- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license
- [x] The icons are solely my own creation.
- [ ] The icons were originally created in #<issueNumber> by @<githubUser>
- [x] I've based them on the following Lucide icons: activity, percent-square
- [ ] I've based them on the following design: 

### Naming 

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design 

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to two points of precision.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

2024-02-03 13:11 UTC, jguddas commented
The square-root feels a bit big.

2024-02-03 13:45 UTC, smnandre commented
> The square-root feels a bit big.

On both icons ? Do you prefer like this ? 

<img width="744" alt="square-root-smaller" src="https://github.com/lucide-icons/lucide/assets/1359581/84052fac-b1e3-4e89-829c-641238a58c12">

2024-02-03 15:16 UTC, gruckion commented
I like it

2024-02-03 16:54 UTC, smnandre commented
<img width="1269" alt="Capture d’écran 2024-02-03 à 17 50 03" src="https://github.com/lucide-icons/lucide/assets/1359581/078fc48e-7ce9-4a8a-9e1d-6590dcd3c424">
<img width="1521" alt="Capture d’écran 2024-02-03 à 17 46 39" src="https://github.com/lucide-icons/lucide/assets/1359581/ec82a82b-14ea-4669-81fa-d4a52dbdf5fb">

2024-02-03 21:10 UTC, jguddas requested changes

2024-02-03 21:10 UTC, jguddas commented on icons/square-root-square.svg
> +  <path d="M7 12h2l2 5 2-10h4"/>
```suggestion
  <path d="M7 12h2l2 5 2-10h4" />
  <rect x="3" y="3" width="18" height="18" rx="2" />
```

2024-02-03 21:14 UTC, jguddas commented
And the name should be `radical` instead of `square-root`.

https://en.wikipedia.org/wiki/Radical_symbol

Besides the IMO better fitting name, it also doesn't mess with the group name `square`.

2024-02-03 21:32 UTC, smnandre commented on icons/square-root-square.svg
> +  <path d="M7 12h2l2 5 2-10h4"/>
Thank you @jguddas

2024-02-03 21:53 UTC, jguddas approved these changes

2024-02-04 07:55 UTC, karsa-mistmere commented
Nice work!

I think one final thing is in order: `radical-square` should be `square-radical` instead.
(Something that in the near future will be added to our naming guidelines).

2024-02-05 22:53 UTC, smnandre commented
> Nice work!
Thank you (and all the feedback!)
 
> I think one final thing is in order: `radical-square` should be `square-radical` instead. (Something that in the near future will be added to our naming guidelines).

Ok! (i looked other icons, but said to myself it would be better if inversed, so... perfect :) )

2024-02-06 07:56 UTC, karsa-mistmere approved these changes

2024-02-06 08:55 UTC, smnandre commented
Not sure to understand the linter message

> Contributors have changed!
> 
> Don't add people who have only performed automatic optimizations.
> 
> +}

Is there something i should do there ?

2024-02-07 07:33 UTC, jguddas approved these changes

2024-02-08 16:16 UTC, ericfennis approved these changes

2024-02-08 20:33 UTC, danielbayley commented
@smnandre Nice, I have almost identical in my drafts… Should plain `radical` not also be horizontally centred though?

> I think one final thing is in order: `radical-square` should be `square-radical` instead. (Something that in the near future will be added to our naming guidelines).

@karsa-mistmere My line of thinking with previous naming was the other way around… The reasoning being that in a sorted list, having to search through _many_ `square-*` icons would be much less user friendly than having them more grouped by `name-square`… What do you think? cc: @ericfennis @jguddas

2024-02-10 02:44 UTC, smnandre commented
> @smnandre Nice, I have almost identical in my drafts… Should plain `radical` not also be horizontally centred though?

It was an attempt to improve a bit the readability of the shape... all my respect for spotting it :) 

<img width="1618" alt="Capture d’écran 2024-02-10 à 03 39 39" src="https://github.com/lucide-icons/lucide/assets/1359581/a2fb4ef6-1c86-4646-9025-f300c24e524a">


Before(svg) ![before](https://github.com/lucide-icons/lucide/assets/1359581/f18b8f5b-c969-4534-832e-fae89855c205) 
After(svg) ![after](https://github.com/lucide-icons/lucide/assets/1359581/0fac2894-da8e-4e2f-b716-3add36e8f466) 

So you prefer the centered one ? @danielbayley 

For the name tell me, and i'll change the names :)

2024-02-10 09:03 UTC, karsa-mistmere commented
I've been thinking that possibly we should also consider consistency with `activity` and keep the lower end 1px below the base line, this would also improve vertical centering. 🤔
![image](https://github.com/lucide-icons/lucide/assets/17746067/609d226c-3a08-4463-892f-77bc07e19417)
<img width="995" alt="image" src="https://github.com/lucide-icons/lucide/assets/17746067/46fb15d4-e744-4eef-b724-4b0245ec3bac">

2024-02-10 09:12 UTC, smnandre commented
> I've been thinking that possibly we should also consider consistency with `activity` and keep the lower end 1px below the base line, this would also improve vertical centering. 🤔

I tried to be as aligned as possible with the other mathematical symbols, the ones that probably would be near this one: cf https://github.com/lucide-icons/lucide/pull/1847#issuecomment-1925394067

2024-02-10 12:25 UTC, danielbayley commented
> For the name tell me, and i'll change the names :)

The order needs to be agreed, and codified into the guidelines, as @karsa-mistmere mentioned…

2024-02-10 18:50 UTC, karsa-mistmere commented
> The order needs to be agreed, and codified into the guidelines, as @karsa-mistmere mentioned…

I'm pretty sure, @ericfennis, @jguddas and I have already agreed upon `square-*` vs. `*-square`, we just haven't had time to put it in writing yet. So `square-radical` is definitely the way to go.

2024-02-10 21:02 UTC, smnandre commented
Ok so i don't have to re-rename them! Tell me if you need anything else :)

2024-02-10 21:16 UTC, jguddas approved these changes

2024-02-11 08:52 UTC, karsa-mistmere commented on icons/radical.svg
> +  <path d="M3 12h4l3 8 3-16h7" />
I think we should add an extra pixel of height to the bottom both to better match `activity` and to adjust the centre of gravity vertically:
```suggestion
  <path d="M3 12h4l3 9 4-17h7" />
```

2024-02-11 11:36 UTC, danielbayley commented
> I'm pretty sure, @ericfennis, @jguddas and I have already agreed upon `square-*` vs. `*-square`

@karsa-mistmere Ah ok, where can I catch up on the reasoning, was there an issue?

2024-02-11 12:04 UTC, jguddas commented
> > I'm pretty sure, @ericfennis, @jguddas and I have already agreed upon `square-*` vs. `*-square`
> 
> @karsa-mistmere Ah ok, where can I catch up on the reasoning, was there an issue?

#1874

2024-02-11 13:46 UTC, karsa-mistmere commented
> @karsa-mistmere Ah ok, where can I catch up on the reasoning, was there an issue?

Originally, there was some discussion in https://github.com/lucide-icons/lucide/pull/1638 regarding this matter, most of the reasoning for why we went with what we did is there, on Discord we just formalized this decision into [some kind of rule](https://github.com/lucide-icons/lucide/pull/1874) that would be easy to follow by our contributors and hopefully result in reasonably consistent names.

2024-02-11 16:55 UTC, smnandre commented
Is there something more i can do on this one ? :)

2024-02-11 22:41 UTC, karsa-mistmere approved these changes

2024-02-11 22:42 UTC, merged