Update icon names to match naming guidelines no. 7 to 9
lucide-icons/lucide pull request #1906
Opened 2024-02-22 08:30 UTC by karsa-mistmere

## What is the purpose of this pull request?
- [x] Bug fix

### Description
Our naming guidelines were updated in #1874, but a lot of icons don't yet match the new official naming scheme, this PR updates most (if not all) of these icons, while also adding backward compatible aliases.

A `renamePattern` helper script was also created that helps streamline these batched renames, e.g. most of the hard work was done via running:
```bash
pnpm renamePattern "^([a-z-]+)-(square|circle|diamond|octagon|hexagon|triangle)$" "\2-\1"
```

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

2024-02-23 09:41 UTC, ericfennis requested changes
Excellent work @karsa-mistmere ! 
I've some suggestions for some renaming

2024-02-23 09:41 UTC, ericfennis commented on icons/circle-arrow-down-left-from.json
Not sure about this name, the `from` word seems a bit superfluous. Maybe `circle-arrow-down-left-out`?

2024-02-23 09:41 UTC, ericfennis commented on icons/laptop-abstract.json
Hmm, this name feels weird, because a lot of our icons are abstract forms of objects. But I've no idea what is a better name. 😕

2024-02-23 09:41 UTC, ericfennis commented on icons/square-arrow-down-left-from.json
See my first comment

2024-02-23 09:41 UTC, ericfennis commented on icons/square-arrow-up-left-from.json
See my first comment

2024-02-23 09:41 UTC, ericfennis commented on icons/square-arrow-up-right-from.json
See my first comment

2024-02-23 09:41 UTC, ericfennis commented on icons/square-check-small.json
I think the name of `square-check` should be named `square-check-big` instead of naming this one "small". Most of the `square-*` icons are just inside the square. This also makes it more consistent with other `check` icons that are mostly inside shapes.

So my suggestion rename this one too: `square-check` and the other `check-square`  to `square-check-big`

Same for the `circle-check` icons

2024-02-23 09:41 UTC, ericfennis commented on icons/wallet-abstract.json
Same as `laptop-abstract`, not sure about the `abstract` word. What about `square-wallet`?

2024-02-23 09:41 UTC, ericfennis commented on icons/wand-magicians.json
What about `wand-sparkles`?

2024-02-23 09:45 UTC, karsa-mistmere commented on icons/square-check-small.json
I did think about that, but that would switch current usages though.

2024-02-23 09:47 UTC, karsa-mistmere commented on icons/wallet-abstract.json
It's not in a square though, is it? 🙃

`wallet-square` would also be weird, since the other `wallet` icon is also rectangular.

2024-02-23 10:07 UTC, karsa-mistmere commented on icons/circle-percent.json
It's just GitHub acting up, I'm afraid, the renames were done correctly.

2024-02-23 10:15 UTC, karsa-mistmere commented on icons/circle-arrow-down-left-from.json
Renamed as such, thanks for the suggestion, it's much clearer this way.

2024-02-25 10:49 UTC, jguddas commented on icons/laptop-abstract.json
Maybe `laptop-minimal` or something

2024-02-25 10:52 UTC, karsa-mistmere commented on icons/laptop-abstract.json
I'm okay with that, wbu @ericfennis?

2024-02-28 15:41 UTC, ericfennis commented on icons/laptop-abstract.json
Yeah oke with that, seems a better name.

2024-02-28 15:41 UTC, ericfennis commented on icons/wallet-abstract.json
You right, maybe also with the `minimal` word, `wallet-minimal`?

2024-02-28 17:33 UTC, karsa-mistmere commented on icons/wallet-abstract.json
Done, I simply ran the command below. :)
```bash
pnpm renamePattern '^(.+)-abstract$' '\1-minimal' --add-alias=false
```

2024-03-08 15:47 UTC, ericfennis approved these changes

2024-03-08 15:55 UTC, merged