add webcam icon
lucide-icons/lucide pull request #192
Opened 2021-02-02 10:30 UTC by mittalyashu

| Preview |
| --- |
| <img width="712" alt="CleanShot 2021-02-02 at 15 56 56@2x" src="https://user-images.githubusercontent.com/29014463/106587518-bb1dce00-656f-11eb-9102-fe6e14a27b94.png"> |

2021-02-02 10:30 UTC, mittalyashu commented
@ericfennis or 

```svg
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <path d="M12 18C14.1217 18 16.1566 17.1571 17.6569 15.6569C19.1571 14.1566 20 12.1217 20 10C20 7.87827 19.1571 5.84344 17.6569 4.34315C16.1566 2.84285 14.1217 2 12 2C9.87827 2 7.84344 2.84285 6.34315 4.34315C4.84285 5.84344 4 7.87827 4 10C4 12.1217 4.84285 14.1566 6.34315 15.6569C7.84344 17.1571 9.87827 18 12 18ZM12 18V22M7 22H12M12 22H17"/>
  <path d="M12 13C12.7956 13 13.5587 12.6839 14.1213 12.1213C14.6839 11.5587 15 10.7956 15 10C15 9.20435 14.6839 8.44129 14.1213 7.87868C13.5587 7.31607 12.7956 7 12 7C11.2044 7 10.4413 7.31607 9.87868 7.87868C9.31607 8.44129 9 9.20435 9 10C9 10.7956 9.31607 11.5587 9.87868 12.1213C10.4413 12.6839 11.2044 13 12 13V13Z"/>
</svg>
```

2021-02-02 20:19 UTC, ericfennis requested changes
Here some refactoring, change it to basic shapes

2021-02-02 20:19 UTC, ericfennis commented on icons/webcam.svg
> +  <path d="M12 13C12.7956 13 13.5587 12.6839 14.1213 12.1213C14.6839 11.5587 15 10.7956 15 10C15 9.20435 14.6839 8.44129 14.1213 7.87868C13.5587 7.31607 12.7956 7 12 7C11.2044 7 10.4413 7.31607 9.878
```suggestion
  <circle cx="12" cy="10" r="8"  />
  <circle cx="12" cy="10" r="3"  />
  <path d="M12 22V18M7 22H12H7ZM17 22H12H17Z"  />
```

2021-02-03 07:40 UTC, ericfennis approved these changes

2021-02-04 18:08 UTC, merged