feat(icons): added keyboard-off
lucide-icons/lucide pull request #1963
Opened 2024-03-08 18:08 UTC by Diottodev

## What is the purpose of this pull request?

- [x] New Icon
- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other:

### Description
The opposite of `keyboard` icon

### Icon use case 
The purpose of this icon is to represent closing/disabling/hiding virtual keyboards

### Alternative icon designs 

## Icon Design Checklist 

### Concept 

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [ ] The icons are solely my own creation.
- [ ] The icons were originally created in #<issueNumber> by @<githubUser>
- [x] I've based them on the following Lucide icons: keyboard
- [ ] I've based them on the following design: 

### Naming 

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design 

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to two points of precision.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

2024-03-08 18:19 UTC, karsa-mistmere commented
Doesn't follow the style of other `-off` icons, there should be a 2px gap of empty space right of the line.

2024-03-08 18:49 UTC, dan1xk commented
this is very useful!

2024-03-14 07:58 UTC, ericfennis requested changes
Nice icon!!
The metadata should be updated

2024-03-14 07:58 UTC, ericfennis commented on icons/keyboard-off.json
> +    "unkeys"
This should include at least all the tags from the `keyboard` icon. And maybe we can think of some more.

2024-03-14 07:58 UTC, ericfennis commented on icons/keyboard-off.json
> +    "devices"
Same here, the categories should be based on categories from the `keyboard`  icon.

2024-03-22 15:33 UTC, ericfennis approved these changes

2024-03-22 17:03 UTC, jguddas approved these changes

2024-04-09 07:20 UTC, merged