feat(icons): added mouse off icon
lucide-icons/lucide pull request #2020
Opened 2024-03-27 14:49 UTC by karsa-mistmere

closes #2007

## What is the purpose of this pull request?
- [x] New Icon

## Icon Design Checklist 

### Concept 

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [x] I've based them on the following Lucide icons: `mouse`

### Naming 

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design 

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to three points of precision.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

2024-03-27 14:54 UTC, jguddas requested changes
Let me debug why my optimization script is not merging the arcs correctly and come back with a simplified version.

2024-03-27 15:20 UTC, jguddas requested changes

2024-03-27 15:20 UTC, jguddas commented on icons/mouse-off.svg
> +  <path d="M19 13.343V9a7 7 0 0 0-7-7 7 7 0 0 0-3.44.902" />
```suggestion
  <path d="M18.218 18.218A7 7 0 0 1 5 15V9a7 7 0 0 1 .782-3.218" />
  <path d="M19 13.343V9A7 7 0 0 0 8.56 2.902" />
```

2024-03-28 14:14 UTC, jguddas approved these changes

2024-04-01 09:14 UTC, ericfennis approved these changes

2024-04-01 09:14 UTC, merged