feat(icons): add section symbol
lucide-icons/lucide pull request #2045
Opened 2024-04-04 06:35 UTC by gurtt

## What is the purpose of this pull request?

- [x] New Icon
- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other:

### Description

Adds a section symbol icon (§).

### Icon use case 

This icon adds to the current set of of document formatting marks including `pilcrow` and `dot`. It is used:
* to denote sections of a document
* to make reference to sections of other documents, especially in legal texts
* to refer to the justice system in general

### Alternative icon designs 

## Icon Design Checklist 

### Concept 

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [x] The icons are solely my own creation.
- [ ] The icons were originally created in #<issueNumber> by @<githubUser>
- [ ] I've based them on the following Lucide icons: 
- [ ] I've based them on the following design: 

### Naming 

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design 

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to three points of precision.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

2024-04-06 22:09 UTC, jguddas requested changes

2024-04-06 22:09 UTC, jguddas commented on icons/section.svg
> +  <path d="M12 9C9.792 9 8 7.656 8 6s1.792-3 4-3 4 1.344 4 3" />
```suggestion
  <path d="M12 15a4 3 0 1 1-4 3" />
  <path d="M16 6a4 3 0 1 0-4 3" />
```

2024-04-10 06:42 UTC, ericfennis approved these changes
Nice work!

2024-04-10 07:40 UTC, karsa-mistmere commented
I'm not super thrilled about the curvature at these parts, I feel like it should be more fluid. 🤔
<img width="291" alt="image" src="https://github.com/lucide-icons/lucide/assets/17746067/48390843-279d-49e3-8df0-e42ab848fd2b">

2024-05-13 08:08 UTC, karsa-mistmere requested changes

2024-05-13 08:08 UTC, karsa-mistmere commented on icons/section.json
> +    "gurtt"
```suggestion
    "gurtt",
    "karsa-mistmere"
```

2024-05-13 08:08 UTC, karsa-mistmere commented on icons/section.svg
> +  <ellipse cx="12" cy="12" rx="4" ry="3" />
```suggestion
  <path d="M16 5a4 3 0 0 0-8 0c0 4 8 3 8 7a4 3 0 0 1-8 0" />
  <path d="M8 19a4 3 0 0 0 8 0c0-4-8-3-8-7a4 3 0 0 1 8 0" />
```

2024-05-13 13:27 UTC, jguddas approved these changes

2024-05-30 02:09 UTC, closed without merging