add shield alert, check & close icon
lucide-icons/lucide pull request #208
Opened 2021-02-03 17:15 UTC by mittalyashu

| `shield-check` | `shield-alert` | `shield-close` |
| --- | --- | --- |
| <img width="459" alt="CleanShot 2021-02-03 at 22 41 28@2x" src="https://user-images.githubusercontent.com/29014463/106783614-7b3f0f80-6671-11eb-9740-b60c527c3207.png"> | <img width="452" alt="CleanShot 2021-02-03 at 22 41 24@2x" src="https://user-images.githubusercontent.com/29014463/106783673-88f49500-6671-11eb-9d8b-d9c420fd4b98.png"> | <img width="447" alt="CleanShot 2021-02-03 at 22 41 20@2x" src="https://user-images.githubusercontent.com/29014463/106783683-8d20b280-6671-11eb-9990-6fdce560a2d9.png"> |

2021-02-03 17:31 UTC, locness3 approved these changes

2021-02-04 18:06 UTC, ericfennis approved these changes

2021-02-04 18:47 UTC, ericfennis requested changes

2021-02-04 18:47 UTC, ericfennis commented on icons/shield-close.svg
> +  <path d="M9 9l6 6" />
I think the x looks a bit better with a smaller one. 
```suggestion
  <line x1="9.5" y1="9" x2="14.5" y2="14" />
  <line x1="14.5" y1="9" x2="9.5" y2="14" />
```
![image](https://user-images.githubusercontent.com/11825403/106940307-b00a9f80-6721-11eb-8523-9168c16d784a.png)

P.S. Can you rename this icon to `shield-x`?

2021-02-07 10:24 UTC, ericfennis approved these changes

2021-02-07 10:24 UTC, merged