fix(icons): redesigned `home` icon
lucide-icons/lucide pull request #2116
Opened 2024-05-02 17:06 UTC by jguddas

## What is the purpose of this pull request?
- [x] Other: Icon update

### Description
Redesigned `home` icon

## Before Submitting
- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

2024-05-03 07:17 UTC, karsa-mistmere commented on icons/home.svg
This one looks weird when scaled up:
<img width="270" alt="image" src="https://github.com/lucide-icons/lucide/assets/17746067/88f25e88-8703-4382-8e68-afbbb59c5f9c">

2024-05-03 07:18 UTC, karsa-mistmere commented on icons/home.svg
There's also some weird artefact, at the bottom left corner:
<img width="336" alt="image" src="https://github.com/lucide-icons/lucide/assets/17746067/845b5323-6218-4d42-8ef8-fa83df2d1099">

2024-05-03 07:25 UTC, jguddas commented
What makes the curved door feel weird to you @karsa-mistmere?
Looks pretty neat at 12x to me.
![Frame](https://github.com/lucide-icons/lucide/assets/25524993/0df2f881-0fa5-44cb-8a8d-f73ee7f2938c)

2024-05-03 07:28 UTC, karsa-mistmere requested changes

2024-05-03 07:28 UTC, karsa-mistmere commented on icons/home.svg
> +  <rect x="9" y="12" width="6" height="9" rx="1" />
Shouldn't the top corner also be rounded?

```suggestion
  <path d="M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8" />
  <path d="M3 9.923a2 2 0 0 1 .709-1.451l7-5.999a2 2 0 0 1 2.582 0l7 5.999A2 2 0 0 1 21 10.001V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2.001z" />
```

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M15+21v-8a1+1+0+0+0-1-1h-4a1+1+0+0+0-1+1v8%22+/%3E%3Cpath+d=%22M3+9.923a2+2+0+0+1+.709-1.451l7-5.999a2+2+0+0+1+2.582+0l7+5.999A2+2+0+0+1+21+10.001V19a2+2+0+0+1-2+2H5a2+2+0+0+1-2-2.001z%22+/%3E&name=image"><img alt="icons" width="400" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTUgMjF2LThhMSAxIDAgMCAwLTEtMWgtNGExIDEgMCAwIDAtMSAxdjgiIC8+CiAgPHBhdGggZD0iTTMgOS45MjNhMiAyIDAgMCAxIC43MDktMS40NTFsNy01Ljk5OWEyIDIgMCAwIDEgMi41ODIgMGw3IDUuOTk5QTIgMiAwIDAgMSAyMSAxMC4wMDFWMTlhMiAyIDAgMCAxLTIgMkg1YTIgMiAwIDAgMS0yLTIuMDAxeiIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>

![image](https://github.com/lucide-icons/lucide/assets/17746067/5f3282be-7ce9-48d9-9389-85524942a680)

2024-05-03 07:28 UTC, karsa-mistmere commented
Also up for discussion: should we rename this to `house`?

2024-05-03 07:31 UTC, karsa-mistmere commented
> What makes the curved door feel weird to you @karsa-mistmere? Looks pretty neat at 12x to me. ![Frame](https://private-user-images.githubusercontent.com/25524993/327680324-0df2f881-0fa5-44cb-8a8d-f73ee7f2938c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MjE3MzEsIm5iZiI6MTcxNDcyMTQzMSwicGF0aCI6Ii8yNTUyNDk5My8zMjc2ODAzMjQtMGRmMmY4ODEtMGZhNS00NGNiLThhOGQtZjczZWU3ZjI5MzhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDA3MzAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4YTMyMjRhMmJjYzliNjc0NWQzOGJiOTY5Nzc0N2VlMjUwZjMwNWU4NGUwZGE2OTg4OGMyNTAwYjdjNDkwZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N-RJFLYhRvi3ZZ_ez5XA0DlfTI1Vs4SfshMPCF3XMuc)

To me that looks awful, I very much prefer this:

![image](https://github.com/lucide-icons/lucide/assets/17746067/2c6eb085-afc5-45d4-a717-09b13a2ec77b)

2024-05-03 10:19 UTC, ericfennis commented
Can we also take a look at #1841 before we merge this one.

Other related issues:
- #2098 
- #1855

2024-05-03 15:58 UTC, karsa-mistmere commented
> Can we also take a look at #1841 before we merge this one.
> 
> Other related issues:
> 
> * [[Icon Request] "Home Plus" icon #2098](https://github.com/lucide-icons/lucide/issues/2098)
> * [[Icon Request]: Energy Autarky for house #1855](https://github.com/lucide-icons/lucide/issues/1855)

@jguddas already designed this very cute icon at #2123 for the autarky use case

As for `home-plus` (or should it not be `house-plus`?), I think these are our best candidates:
![image](https://github.com/lucide-icons/lucide/assets/17746067/57d948e3-f3ef-408d-b5f9-e36a8cf5971d)

None of them spark joy, but it should definitely not be the last one.

2024-05-03 16:00 UTC, jguddas commented
> > Can we also take a look at #1841 before we merge this one.
> > Other related issues:
> > 
> > * [[Icon Request] "Home Plus" icon #2098](https://github.com/lucide-icons/lucide/issues/2098)
> > * [[Icon Request]: Energy Autarky for house #1855](https://github.com/lucide-icons/lucide/issues/1855)
> 
> @jguddas already designed this very cute icon at #2123 for the autarky use case
> 
> As for `home-plus` (or should it not be `house-plus`?), I think these are our best candidates: ![image](https://private-user-images.githubusercontent.com/17746067/327813333-57d948e3-f3ef-408d-b5f9-e36a8cf5971d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NTIyNzYsIm5iZiI6MTcxNDc1MTk3NiwicGF0aCI6Ii8xNzc0NjA2Ny8zMjc4MTMzMzMtNTdkOTQ4ZTMtZjNlZi00MDhkLWI1ZjktZTM2YThjZjU5NzFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDE1NTkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1OTY4N2NjMGI0MjcwZDRjNDAzMTg1MjU0M2MwOGI3NTZkNjY4ZWFlOTEzZmMyMjM0M2M5NDdjMzI4NDRkNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jP-iw2IHOSjaHgJjPEbpZWASuehUw285WnxLTU9BHwU)
> 
> None of them spark joy, but it should definitely not be the last one.

The second one with the plus in the roof looks nice.

2024-06-02 08:44 UTC, ericfennis commented
@karsa-mistmere @jguddas I vote as well for the second one!

2024-06-02 09:55 UTC, karsa-mistmere commented
> Also up for discussion: should we rename this to house?

This still bugs me, I feel like `house` is what's depicted and `home` is a use case.

2024-06-06 09:07 UTC, karsa-mistmere approved these changes

2024-06-13 08:27 UTC, karsa-mistmere commented
> > Also up for discussion: should we rename this to house?
> 
> This still bugs me, I feel like `house` is what's depicted and `home` is a use case, so as per naming convention no. 4, this should be `house`, not `home`.

@ericfennis & @jguddas: still waiting for your two cents on this.

---

Here's the finalized `house-plus`/`home-plus` icon:

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M13.22+2.416a2+2+0+0+0-2.511.057l-7+5.999A2+2+0+0+0+3+10v9a2+2+0+0+0+2+2h14a2+2+0+0+0+2-2v-7.354%22+/%3E%3Cpath+d=%22M15+21v-8a1+1+0+0+0-1-1h-4a1+1+0+0+0-1+1v8%22+/%3E%3Cpath+d=%22M15+6h6%22+/%3E%3Cpath+d=%22M18+3v6%22+/%3E&name=image"><img alt="icons" width="400" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTMuMjIgMi40MTZhMiAyIDAgMCAwLTIuNTExLjA1N2wtNyA1Ljk5OUEyIDIgMCAwIDAgMyAxMHY5YTIgMiAwIDAgMCAyIDJoMTRhMiAyIDAgMCAwIDItMnYtNy4zNTQiIC8+CiAgPHBhdGggZD0iTTE1IDIxdi04YTEgMSAwIDAgMC0xLTFoLTRhMSAxIDAgMCAwLTEgMXY4IiAvPgogIDxwYXRoIGQ9Ik0xNSA2aDYiIC8+CiAgPHBhdGggZD0iTTE4IDN2NiIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>

2024-06-13 08:31 UTC, jguddas commented
I vote for keeping it home.

2024-06-14 14:28 UTC, ericfennis commented
@karsa-mistmere is right here. If we want to be consistent with renaming, we should rename this to `house`.

2024-06-21 10:52 UTC, ericfennis approved these changes

2024-06-21 10:52 UTC, merged