feat(icons): added `podium` icon
lucide-icons/lucide pull request #2124
Opened 2024-05-03 14:46 UTC by jguddas

closes #2110 

## What is the purpose of this pull request?

- [x] New Icon
- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other:

### Description

### Icon use case 

### Alternative icon designs 

## Icon Design Checklist 

### Concept 

- [ ] I have provided valid use cases for each icon.
- [ ] I have not added any a brand or logo icon.
- [ ] I have not used any hate symbols.
- [ ] I have not included any religious or political imagery.

### Author, credits & license

- [ ] The icons are solely my own creation.
- [ ] The icons were originally created in #<issueNumber> by @<githubUser>
- [ ] I've based them on the following Lucide icons: 
- [ ] I've based them on the following design: 

### Naming 

- [ ] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [ ] I've named icons by what they are rather than their use case.
- [ ] I've provided meta JSON files in `icons/[iconName].json`.

### Design 

- [ ] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [ ] I've made sure that the icons look sharp on low DPI displays.
- [ ] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [ ] I've made sure that the icons are visually centered.
- [ ] I've correctly optimized all icons to three points of precision.

## Before Submitting 

- [ ] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [ ] I've checked if there was an existing PR that solves the same issue.

2024-05-03 15:20 UTC, karsa-mistmere commented
Feels a bit medical or religious with the cross on top. 🤔

When the `lectern` issue came to be I did draw these but wasn't super happy with the results, let me know what you think anyway:
![image](https://github.com/lucide-icons/lucide/assets/17746067/13e933e4-4cd0-4ef2-9bef-d3333f530900)
![image](https://github.com/lucide-icons/lucide/assets/17746067/3d5e97f4-c607-44e4-bffe-d194662ce46b)

2024-05-03 15:23 UTC, jguddas commented
> Feels a bit medical or religious with the cross on top. 🤔
> 
> When the `lectern` issue came to be I did draw these but wasn't super happy with the results, let me know what you think anyway: ![image](https://private-user-images.githubusercontent.com/17746067/327802044-13e933e4-4cd0-4ef2-9bef-d3333f530900.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NDk5OTAsIm5iZiI6MTcxNDc0OTY5MCwicGF0aCI6Ii8xNzc0NjA2Ny8zMjc4MDIwNDQtMTNlOTMzZTQtNGNkMC00ZWYyLTliZWYtZDMzMzNmNTMwOTAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDE1MjEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5N2QyZDg1YWZjOTRlNjY1OWEwYzkxMWYxMzIxOGRmYzdjZDgzY2UzNDA5MGE5MjExY2YxN2UwYTM1N2NmZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6gi_LuArhVnw3eQ9oz48tZnlTrpmuaaThvCa1KZWOzU) ![image](https://private-user-images.githubusercontent.com/17746067/327802072-3d5e97f4-c607-44e4-bffe-d194662ce46b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NDk5OTAsIm5iZiI6MTcxNDc0OTY5MCwicGF0aCI6Ii8xNzc0NjA2Ny8zMjc4MDIwNzItM2Q1ZTk3ZjQtYzYwNy00NGU0LWJmZmUtZDE5NDY2MmNlNDZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDE1MjEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5YTg0NmViZWNkM2U3Y2FkY2IxZjVjYzc4NjE4MmU0NGMwZGU4YTU0NWQ5NTkwYmI3YjI5ZTA5YjIwMjk1N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-NY99Ny4MTTkD1w1WgSZbFku5AO8FcaEpUhgjpXpO4I)

It's the same star we use for everything else.

Without it, it looks like a bar chart.

I like the second idea, but it's not very legible.

2024-05-03 15:26 UTC, karsa-mistmere commented
> It's the same star we use for everything else.

Yes, albeit in an entirely different context. 🙂 

> Without it, it looks like a bar chart.

> I like the second idea, but it's not very legible.

I agree with both remarks, hence the whole "not having been super happy about them" thing. 😂

2024-06-12 08:50 UTC, ericfennis commented
Not possible to use a star or a crown?

2024-07-22 13:28 UTC, jamiemlaw commented
A crown might work.

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22m8+3+2+1+2-2+2+2+2-1-1+5H9z%22+/%3E%3Cpath+d=%22M9+16a1+1+0+0+0-1-1H4a1+1+0+0+0-1+1v4a1+1+0+0+0+1+1h16a1+1+0+0+0+1-1v-2a1+1+0+0+0-1-1h-4a1+1+0+0+0-1+1%22+/%3E%3Cpath+d=%22M9+21v-8a1+1+0+0+1+1-1h4a1+1+0+0+1+1+1v8%22+/%3E"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJtOCAzIDIgMSAyLTIgMiAyIDItMS0xIDVIOXoiIC8+CiAgPHBhdGggZD0iTTkgMTZhMSAxIDAgMCAwLTEtMUg0YTEgMSAwIDAgMC0xIDF2NGExIDEgMCAwIDAgMSAxaDE2YTEgMSAwIDAgMCAxLTF2LTJhMSAxIDAgMCAwLTEtMWgtNGExIDEgMCAwIDAtMSAxIiAvPgogIDxwYXRoIGQ9Ik05IDIxdi04YTEgMSAwIDAgMSAxLTFoNGExIDEgMCAwIDEgMSAxdjgiIC8+Cjwvc3ZnPg==.svg"/><br/>Open lucide studio</a>

2024-07-29 14:32 UTC, karsa-mistmere commented
> A crown might work.
> 
> [<img alt="icons" width="120" src="https://camo.githubusercontent.com/3669c7d26e8322cb62a378d93717a9572863029dbf5ab575fb6ed4a0734ba59f/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a776f67494868746247357a50534a6f644852774f693876643364334c6e637a4c6d39795a7938794d4441774c334e325a79494b4943423361575230614430694d6a516943694167614756705a326830505349794e43494b4943423261575633516d393450534977494441674d6a51674d6a5169436941675a6d6c7362443069626d39755a53494b4943427a64484a7661325539496d4e31636e4a6c626e5244623278766369494b4943427a64484a766132557464326c6b64476739496a496943694167633352796232746c4c577870626d566a59584139496e4a766457356b49676f6749484e30636d39725a5331736157356c616d3970626a3069636d3931626d5169436a344b49434138634746306143426b50534a744f43417a494449674d5341794c5449674d694179494449744d533078494456494f586f694943382b4369416750484268644767675a44306954546b674d545a684d534178494441674d4341774c5445744d556730595445674d534177494441674d433078494446324e474578494445674d434177494441674d53417861444532595445674d534177494441674d4341784c5446324c544a684d534178494441674d4341774c5445744d5767744e474578494445674d434177494441744d5341784969417650676f67494478775958526f49475139496b30354944497864693034595445674d534177494441674d5341784c54466f4e474578494445674d434177494445674d534178646a67694943382b436a777663335a6e50673d3d2e737667">Open lucide studio](https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22m8+3+2+1+2-2+2+2+2-1-1+5H9z%22+/%3E%3Cpath+d=%22M9+16a1+1+0+0+0-1-1H4a1+1+0+0+0-1+1v4a1+1+0+0+0+1+1h16a1+1+0+0+0+1-1v-2a1+1+0+0+0-1-1h-4a1+1+0+0+0-1+1%22+/%3E%3Cpath+d=%22M9+21v-8a1+1+0+0+1+1-1h4a1+1+0+0+1+1+1v8%22+/%3E)

Looks fantastic in this size, but at 1x the spikes are quite dense and blurry. 😔

2024-10-31 09:51 UTC, jamiemlaw commented
Throwing some other ideas into the mix:

![image](https://github.com/user-attachments/assets/12ad8f91-6bd4-408a-bf78-2f2202c6413f)

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22m8+2+2+2+2-2+2+2+2-2v6H8z%22+/%3E%3Cpath+d=%22M9+16a1+1+0+0+0-1-1H4a1+1+0+0+0-1+1v4a1+1+0+0+0+1+1h16a1+1+0+0+0+1-1v-2a1+1+0+0+0-1-1h-4a1+1+0+0+0-1+1%22+/%3E%3Cpath+d=%22M9+21v-8a1+1+0+0+1+1-1h4a1+1+0+0+1+1+1v8%22+/%3E"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJtOCAyIDIgMiAyLTIgMiAyIDItMnY2SDh6IiAvPgogIDxwYXRoIGQ9Ik05IDE2YTEgMSAwIDAgMC0xLTFINGExIDEgMCAwIDAtMSAxdjRhMSAxIDAgMCAwIDEgMWgxNmExIDEgMCAwIDAgMS0xdi0yYTEgMSAwIDAgMC0xLTFoLTRhMSAxIDAgMCAwLTEgMSIgLz4KICA8cGF0aCBkPSJNOSAyMXYtOGExIDEgMCAwIDEgMS0xaDRhMSAxIDAgMCAxIDEgMXY4IiAvPgo8L3N2Zz4=.svg"/><br/>Open lucide studio</a>

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M9+16a1+1+0+0+0-1-1H4a1+1+0+0+0-1+1v4a1+1+0+0+0+1+1h16a1+1+0+0+0+1-1v-2a1+1+0+0+0-1-1h-4a1+1+0+0+0-1+1%22+/%3E%3Cpath+d=%22M9+21v-8a1+1+0+0+1+1-1h4a1+1+0+0+1+1+1v8%22+/%3E%3Cpath+d=%22m9+3+2+2+1-2+1+2+2-2v5H9z%22+/%3E"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNOSAxNmExIDEgMCAwIDAtMS0xSDRhMSAxIDAgMCAwLTEgMXY0YTEgMSAwIDAgMCAxIDFoMTZhMSAxIDAgMCAwIDEtMXYtMmExIDEgMCAwIDAtMS0xaC00YTEgMSAwIDAgMC0xIDEiIC8+CiAgPHBhdGggZD0iTTkgMjF2LThhMSAxIDAgMCAxIDEtMWg0YTEgMSAwIDAgMSAxIDF2OCIgLz4KICA8cGF0aCBkPSJtOSAzIDIgMiAxLTIgMSAyIDItMnY1SDl6IiAvPgo8L3N2Zz4=.svg"/><br/>Open lucide studio</a>

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M12+3v1%22+/%3E%3Cpath+d=%22M15+3v4a1+1+0+0+1-1+1h-4a1+1+0+0+1-1-1V3%22+/%3E%3Cpath+d=%22M9+16a1+1+0+0+0-1-1H4a1+1+0+0+0-1+1v4a1+1+0+0+0+1+1h16a1+1+0+0+0+1-1v-2a1+1+0+0+0-1-1h-4a1+1+0+0+0-1+1%22+/%3E%3Cpath+d=%22M9+21v-8a1+1+0+0+1+1-1h4a1+1+0+0+1+1+1v8%22+/%3E%3Cpath+d=%22M9+4h6%22+/%3E"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTIgM3YxIiAvPgogIDxwYXRoIGQ9Ik0xNSAzdjRhMSAxIDAgMCAxLTEgMWgtNGExIDEgMCAwIDEtMS0xVjMiIC8+CiAgPHBhdGggZD0iTTkgMTZhMSAxIDAgMCAwLTEtMUg0YTEgMSAwIDAgMC0xIDF2NGExIDEgMCAwIDAgMSAxaDE2YTEgMSAwIDAgMCAxLTF2LTJhMSAxIDAgMCAwLTEtMWgtNGExIDEgMCAwIDAtMSAxIiAvPgogIDxwYXRoIGQ9Ik05IDIxdi04YTEgMSAwIDAgMSAxLTFoNGExIDEgMCAwIDEgMSAxdjgiIC8+CiAgPHBhdGggZD0iTTkgNGg2IiAvPgo8L3N2Zz4=.svg"/><br/>Open lucide studio</a>

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M11+6h2%22+/%3E%3Cpath+d=%22M12+6V2h-1%22+/%3E%3Cpath+d=%22M9+15a1+1+0+0+0-1-1H4a1+1+0+0+0-1+1v5a1+1+0+0+0+1+1h16a1+1+0+0+0+1-1v-3a1+1+0+0+0-1-1h-4a1+1+0+0+0-1+1%22+/%3E%3Cpath+d=%22M9+21V11a1+1+0+0+1+1-1h4a1+1+0+0+1+1+1v10%22+/%3E"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTEgNmgyIiAvPgogIDxwYXRoIGQ9Ik0xMiA2VjJoLTEiIC8+CiAgPHBhdGggZD0iTTkgMTVhMSAxIDAgMCAwLTEtMUg0YTEgMSAwIDAgMC0xIDF2NWExIDEgMCAwIDAgMSAxaDE2YTEgMSAwIDAgMCAxLTF2LTNhMSAxIDAgMCAwLTEtMWgtNGExIDEgMCAwIDAtMSAxIiAvPgogIDxwYXRoIGQ9Ik05IDIxVjExYTEgMSAwIDAgMSAxLTFoNGExIDEgMCAwIDEgMSAxdjEwIiAvPgo8L3N2Zz4=.svg"/><br/>Open lucide studio</a>

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M12+6V2h-1%22+/%3E%3Cpath+d=%22M9+15a1+1+0+0+0-1-1H4a1+1+0+0+0-1+1v5a1+1+0+0+0+1+1h16a1+1+0+0+0+1-1v-3a1+1+0+0+0-1-1h-4a1+1+0+0+0-1+1%22+/%3E%3Cpath+d=%22M9+21V11a1+1+0+0+1+1-1h4a1+1+0+0+1+1+1v10%22+/%3E"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTIgNlYyaC0xIiAvPgogIDxwYXRoIGQ9Ik05IDE1YTEgMSAwIDAgMC0xLTFINGExIDEgMCAwIDAtMSAxdjVhMSAxIDAgMCAwIDEgMWgxNmExIDEgMCAwIDAgMS0xdi0zYTEgMSAwIDAgMC0xLTFoLTRhMSAxIDAgMCAwLTEgMSIgLz4KICA8cGF0aCBkPSJNOSAyMVYxMWExIDEgMCAwIDEgMS0xaDRhMSAxIDAgMCAxIDEgMXYxMCIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>

First three are more crowns. First is most identifiably a crown but probably too large. Second is similar to my previous attempt but with fewer diagonal lines—probably still too blurry at low resolutions. The third goes more simple, although I'm not sure if it looks more like a castle than a crown. Of the three crowns, it's my favourite.

But then, one unexplored option, is to use a '1' digit. I've got two versions, with and without a lower bar. I think with looks more readable, but at that size there are other instances in Lucide without, e.g. [`calendar-1`](https://lucide.dev/icons/calendar-1), [`repeat-1`](https://lucide.dev/icons/repeat-1)

2024-10-31 10:41 UTC, karsa-mistmere commented
> Throwing some other ideas into the mix:
> 
> ![image](https://private-user-images.githubusercontent.com/956081/381903172-12ad8f91-6bd4-408a-bf78-2f2202c6413f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNzE1MzQsIm5iZiI6MTczMDM3MTIzNCwicGF0aCI6Ii85NTYwODEvMzgxOTAzMTcyLTEyYWQ4ZjkxLTZiZDQtNDA4YS1iZjc4LTJmMjIwMmM2NDEzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQxMDQwMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGE5MmFiNDk5N2I2OGFiMjY5NDE0ZTc2NjNkN2Q5NGEzNGZmODMzNTE1YzUzM2Y4ZjI3NjNjOGM3NzIyMmIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.d6GWIOCVrsBUEDs7MgMrdwGM6pGhDkA4Fh459LLYjw8)
> 
> [<img alt="icons" width="200px" src="https://camo.githubusercontent.com/3159c7aa1930f8afbec5f4ff81612cb9d9cfbc6796363f1bd87a1a3c15c9fe3e/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a776f67494868746247357a50534a6f644852774f693876643364334c6e637a4c6d39795a7938794d4441774c334e325a79494b4943423361575230614430694d6a516943694167614756705a326830505349794e43494b4943423261575633516d393450534977494441674d6a51674d6a5169436941675a6d6c7362443069626d39755a53494b4943427a64484a7661325539496d4e31636e4a6c626e5244623278766369494b4943427a64484a766132557464326c6b64476739496a496943694167633352796232746c4c577870626d566a59584139496e4a766457356b49676f6749484e30636d39725a5331736157356c616d3970626a3069636d3931626d5169436a344b49434138634746306143426b50534a744f434179494449674d6941794c5449674d694179494449744d6e5932534468364969417650676f67494478775958526f49475139496b303549444532595445674d534177494441674d4330784c5446494e474578494445674d434177494441744d534178646a52684d534178494441674d434177494445674d5767784e6d4578494445674d434177494441674d53307864693079595445674d534177494441674d4330784c54466f4c5452684d534178494441674d4341774c5445674d5349674c7a344b49434138634746306143426b50534a4e4f5341794d5859744f474578494445674d434177494445674d533078614452684d534178494441674d434178494445674d5859344969417650676f384c334e325a7a343d2e737667">Open lucide studio](https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22m8+2+2+2+2-2+2+2+2-2v6H8z%22+/%3E%3Cpath+d=%22M9+16a1+1+0+0+0-1-1H4a1+1+0+0+0-1+1v4a1+1+0+0+0+1+1h16a1+1+0+0+0+1-1v-2a1+1+0+0+0-1-1h-4a1+1+0+0+0-1+1%22+/%3E%3Cpath+d=%22M9+21v-8a1+1+0+0+1+1-1h4a1+1+0+0+1+1+1v8%22+/%3E)
> 
> [<img alt="icons" width="200px" src="https://camo.githubusercontent.com/47b0dc497c7d1cf6406680e2352b6dc2f3b9bf043cebfc4ddf2e756465c7214e/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a776f67494868746247357a50534a6f644852774f693876643364334c6e637a4c6d39795a7938794d4441774c334e325a79494b4943423361575230614430694d6a516943694167614756705a326830505349794e43494b4943423261575633516d393450534977494441674d6a51674d6a5169436941675a6d6c7362443069626d39755a53494b4943427a64484a7661325539496d4e31636e4a6c626e5244623278766369494b4943427a64484a766132557464326c6b64476739496a496943694167633352796232746c4c577870626d566a59584139496e4a766457356b49676f6749484e30636d39725a5331736157356c616d3970626a3069636d3931626d5169436a344b49434138634746306143426b50534a4e4f5341784e6d4578494445674d434177494441744d533078534452684d534178494441674d4341774c5445674d585930595445674d534177494441674d4341784944466f4d545a684d534178494441674d434177494445744d5859744d6d4578494445674d434177494441744d53307861433030595445674d534177494441674d433078494445694943382b4369416750484268644767675a44306954546b674d6a46324c5468684d534178494441674d434178494445744d576730595445674d534177494441674d534178494446324f4349674c7a344b49434138634746306143426b50534a744f53417a494449674d6941784c5449674d534179494449744d6e593153446c364969417650676f384c334e325a7a343d2e737667">Open lucide studio](https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M9+16a1+1+0+0+0-1-1H4a1+1+0+0+0-1+1v4a1+1+0+0+0+1+1h16a1+1+0+0+0+1-1v-2a1+1+0+0+0-1-1h-4a1+1+0+0+0-1+1%22+/%3E%3Cpath+d=%22M9+21v-8a1+1+0+0+1+1-1h4a1+1+0+0+1+1+1v8%22+/%3E%3Cpath+d=%22m9+3+2+2+1-2+1+2+2-2v5H9z%22+/%3E)
> 
> [<img alt="icons" width="200px" src="https://camo.githubusercontent.com/8ef4a97965a6305684216cb902d14364898164287c0afb31e1ae2937faabcfda/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a776f67494868746247357a50534a6f644852774f693876643364334c6e637a4c6d39795a7938794d4441774c334e325a79494b4943423361575230614430694d6a516943694167614756705a326830505349794e43494b4943423261575633516d393450534977494441674d6a51674d6a5169436941675a6d6c7362443069626d39755a53494b4943427a64484a7661325539496d4e31636e4a6c626e5244623278766369494b4943427a64484a766132557464326c6b64476739496a496943694167633352796232746c4c577870626d566a59584139496e4a766457356b49676f6749484e30636d39725a5331736157356c616d3970626a3069636d3931626d5169436a344b49434138634746306143426b50534a4e4d5449674d3359784969417650676f67494478775958526f49475139496b30784e53417a646a52684d534178494441674d4341784c5445674d5767744e474578494445674d434177494445744d533078566a4d694943382b4369416750484268644767675a44306954546b674d545a684d534178494441674d4341774c5445744d556730595445674d534177494441674d433078494446324e474578494445674d434177494441674d53417861444532595445674d534177494441674d4341784c5446324c544a684d534178494441674d4341774c5445744d5767744e474578494445674d434177494441744d5341784969417650676f67494478775958526f49475139496b30354944497864693034595445674d534177494441674d5341784c54466f4e474578494445674d434177494445674d534178646a67694943382b4369416750484268644767675a44306954546b674e4767324969417650676f384c334e325a7a343d2e737667">Open lucide studio](https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M12+3v1%22+/%3E%3Cpath+d=%22M15+3v4a1+1+0+0+1-1+1h-4a1+1+0+0+1-1-1V3%22+/%3E%3Cpath+d=%22M9+16a1+1+0+0+0-1-1H4a1+1+0+0+0-1+1v4a1+1+0+0+0+1+1h16a1+1+0+0+0+1-1v-2a1+1+0+0+0-1-1h-4a1+1+0+0+0-1+1%22+/%3E%3Cpath+d=%22M9+21v-8a1+1+0+0+1+1-1h4a1+1+0+0+1+1+1v8%22+/%3E%3Cpath+d=%22M9+4h6%22+/%3E)
> 
> [<img alt="icons" width="200px" src="https://camo.githubusercontent.com/6cd3b0a84b5c526529031a1e496b03294a33a9bedd43653021b4c1b807e68638/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a776f67494868746247357a50534a6f644852774f693876643364334c6e637a4c6d39795a7938794d4441774c334e325a79494b4943423361575230614430694d6a516943694167614756705a326830505349794e43494b4943423261575633516d393450534977494441674d6a51674d6a5169436941675a6d6c7362443069626d39755a53494b4943427a64484a7661325539496d4e31636e4a6c626e5244623278766369494b4943427a64484a766132557464326c6b64476739496a496943694167633352796232746c4c577870626d566a59584139496e4a766457356b49676f6749484e30636d39725a5331736157356c616d3970626a3069636d3931626d5169436a344b49434138634746306143426b50534a4e4d5445674e6d67794969417650676f67494478775958526f49475139496b30784d694132566a4a6f4c5445694943382b4369416750484268644767675a44306954546b674d5456684d534178494441674d4341774c5445744d556730595445674d534177494441674d433078494446324e574578494445674d434177494441674d53417861444532595445674d534177494441674d4341784c5446324c544e684d534178494441674d4341774c5445744d5767744e474578494445674d434177494441744d5341784969417650676f67494478775958526f49475139496b303549444978566a4578595445674d534177494441674d5341784c54466f4e474578494445674d434177494445674d534178646a45774969417650676f384c334e325a7a343d2e737667">Open lucide studio](https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M11+6h2%22+/%3E%3Cpath+d=%22M12+6V2h-1%22+/%3E%3Cpath+d=%22M9+15a1+1+0+0+0-1-1H4a1+1+0+0+0-1+1v5a1+1+0+0+0+1+1h16a1+1+0+0+0+1-1v-3a1+1+0+0+0-1-1h-4a1+1+0+0+0-1+1%22+/%3E%3Cpath+d=%22M9+21V11a1+1+0+0+1+1-1h4a1+1+0+0+1+1+1v10%22+/%3E)
> 
> [<img alt="icons" width="200px" src="https://camo.githubusercontent.com/16de0d598277affa24877dd322863dacfd97531c9a1c972c5b8f0daa69782384/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a776f67494868746247357a50534a6f644852774f693876643364334c6e637a4c6d39795a7938794d4441774c334e325a79494b4943423361575230614430694d6a51694 [...]

2024-10-31 11:34 UTC, jguddas commented
A less dense crown:

![](https://github.com/user-attachments/assets/a3141bf5-de89-45a6-9e62-a651b0a56e93)

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M12+2v2%22+/%3E%3Cpath+d=%22M16+2v5a1+1+0+0+1-1+1H9a1+1+0+0+1-1-1V2%22+/%3E%3Cpath+d=%22M8+4h8%22+/%3E%3Cpath+d=%22M9+16a1+1+0+0+0-1-1H4a1+1+0+0+0-1+1v4a1+1+0+0+0+1+1h16a1+1+0+0+0+1-1v-2a1+1+0+0+0-1-1h-4a1+1+0+0+0-1+1%22+/%3E%3Cpath+d=%22M9+21v-8a1+1+0+0+1+1-1h4a1+1+0+0+1+1+1v8%22+/%3E"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTIgMnYyIiAvPgogIDxwYXRoIGQ9Ik0xNiAydjVhMSAxIDAgMCAxLTEgMUg5YTEgMSAwIDAgMS0xLTFWMiIgLz4KICA8cGF0aCBkPSJNOCA0aDgiIC8+CiAgPHBhdGggZD0iTTkgMTZhMSAxIDAgMCAwLTEtMUg0YTEgMSAwIDAgMC0xIDF2NGExIDEgMCAwIDAgMSAxaDE2YTEgMSAwIDAgMCAxLTF2LTJhMSAxIDAgMCAwLTEtMWgtNGExIDEgMCAwIDAtMSAxIiAvPgogIDxwYXRoIGQ9Ik05IDIxdi04YTEgMSAwIDAgMSAxLTFoNGExIDEgMCAwIDEgMSAxdjgiIC8+Cjwvc3ZnPg==.svg"/><br/>Open lucide studio</a>

2024-11-17 07:13 UTC, karsa-mistmere commented
> A less dense crown:
> 
> ![](https://private-user-images.githubusercontent.com/25524993/381931515-a3141bf5-de89-45a6-9e62-a651b0a56e93.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4Mjc2NzYsIm5iZiI6MTczMTgyNzM3NiwicGF0aCI6Ii8yNTUyNDk5My8zODE5MzE1MTUtYTMxNDFiZjUtZGU4OS00NWE2LTllNjItYTY1MWIwYTU2ZTkzLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA3MDkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNjU2YmQwZGJhN2E4ZmM5MTI4ZmJjNDlhY2E4MDNmOTAzOGJhODY1Y2E1Mjk4ZTRhMWE3M2E5NGFlNmQ0Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xvB9GF7uIhXkl4RxS0vL4EZhkXJB5qgXWIy-5tp7UVE)
> 
> [<img alt="icons" width="200px" src="https://camo.githubusercontent.com/01c39b9acbe40cd4546209374e49df01cd0ef8f16ccd11a8cecb06cc7b959a1b/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a776f67494868746247357a50534a6f644852774f693876643364334c6e637a4c6d39795a7938794d4441774c334e325a79494b4943423361575230614430694d6a516943694167614756705a326830505349794e43494b4943423261575633516d393450534977494441674d6a51674d6a5169436941675a6d6c7362443069626d39755a53494b4943427a64484a7661325539496d4e31636e4a6c626e5244623278766369494b4943427a64484a766132557464326c6b64476739496a496943694167633352796232746c4c577870626d566a59584139496e4a766457356b49676f6749484e30636d39725a5331736157356c616d3970626a3069636d3931626d5169436a344b49434138634746306143426b50534a4e4d5449674d6e59794969417650676f67494478775958526f49475139496b30784e694179646a56684d534178494441674d4341784c5445674d556735595445674d534177494441674d5330784c5446574d6949674c7a344b49434138634746306143426b50534a4e4f434130614467694943382b4369416750484268644767675a44306954546b674d545a684d534178494441674d4341774c5445744d556730595445674d534177494441674d433078494446324e474578494445674d434177494441674d53417861444532595445674d534177494441674d4341784c5446324c544a684d534178494441674d4341774c5445744d5767744e474578494445674d434177494441744d5341784969417650676f67494478775958526f49475139496b30354944497864693034595445674d534177494441674d5341784c54466f4e474578494445674d434177494445674d534178646a67694943382b436a777663335a6e50673d3d2e737667">Open lucide studio](https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M12+2v2%22+/%3E%3Cpath+d=%22M16+2v5a1+1+0+0+1-1+1H9a1+1+0+0+1-1-1V2%22+/%3E%3Cpath+d=%22M8+4h8%22+/%3E%3Cpath+d=%22M9+16a1+1+0+0+0-1-1H4a1+1+0+0+0-1+1v4a1+1+0+0+0+1+1h16a1+1+0+0+0+1-1v-2a1+1+0+0+0-1-1h-4a1+1+0+0+0-1+1%22+/%3E%3Cpath+d=%22M9+21v-8a1+1+0+0+1+1-1h4a1+1+0+0+1+1+1v8%22+/%3E)

Doesn't really look like a crown IMO, more like some weird disjoint rook or castle.

I'm sticking with @jamiemlaw's idea.

2024-12-05 11:53 UTC, ericfennis approved these changes

2024-12-05 12:05 UTC, karsa-mistmere requested changes, later dismissed

2024-12-05 12:05 UTC, karsa-mistmere commented on icons/podium.svg
I still think using a `1` is superior.

![image](https://github.com/user-attachments/assets/69608c11-c24d-4e11-be73-43a9396830be)


<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M12+6V2h-1%22+/%3E%3Cpath+d=%22M9+15a1+1+0+0+0-1-1H4a1+1+0+0+0-1+1v5a1+1+0+0+0+1+1h16a1+1+0+0+0+1-1v-3a1+1+0+0+0-1-1h-4a1+1+0+0+0-1+1%22+/%3E%3Cpath+d=%22M9+21V11a1+1+0+0+1+1-1h4a1+1+0+0+1+1+1v10%22+/%3E"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTIgNlYyaC0xIiAvPgogIDxwYXRoIGQ9Ik05IDE1YTEgMSAwIDAgMC0xLTFINGExIDEgMCAwIDAtMSAxdjVhMSAxIDAgMCAwIDEgMWgxNmExIDEgMCAwIDAgMS0xdi0zYTEgMSAwIDAgMC0xLTFoLTRhMSAxIDAgMCAwLTEgMSIgLz4KICA8cGF0aCBkPSJNOSAyMVYxMWExIDEgMCAwIDEgMS0xaDRhMSAxIDAgMCAxIDEgMXYxMCIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M12+6V2h-1%22+/%3E%3Cpath+d=%22M2+21h20%22+/%3E%3Cpath+d=%22M21+21v-4a1+1+0+0+0-1-1h-4a1+1+0+0+0-1+1%22+/%3E%3Cpath+d=%22M9+15a1+1+0+0+0-1-1H4a1+1+0+0+0-1+1v6%22+/%3E%3Cpath+d=%22M9+21V11a1+1+0+0+1+1-1h4a1+1+0+0+1+1+1v10%22+/%3E"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTIgNlYyaC0xIiAvPgogIDxwYXRoIGQ9Ik0yIDIxaDIwIiAvPgogIDxwYXRoIGQ9Ik0yMSAyMXYtNGExIDEgMCAwIDAtMS0xaC00YTEgMSAwIDAgMC0xIDEiIC8+CiAgPHBhdGggZD0iTTkgMTVhMSAxIDAgMCAwLTEtMUg0YTEgMSAwIDAgMC0xIDF2NiIgLz4KICA8cGF0aCBkPSJNOSAyMVYxMWExIDEgMCAwIDEgMS0xaDRhMSAxIDAgMCAxIDEgMXYxMCIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>

2024-12-05 12:07 UTC, jguddas commented on icons/podium.svg
I am not convinced about either version tbh.

I think [your version](https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M12+6V2h-1%22+/%3E%3Cpath+d=%22M2+21h20%22+/%3E%3Cpath+d=%22M21+21v-4a1+1+0+0+0-1-1h-4a1+1+0+0+0-1+1%22+/%3E%3Cpath+d=%22M9+15a1+1+0+0+0-1-1H4a1+1+0+0+0-1+1v6%22+/%3E%3Cpath+d=%22M9+21V11a1+1+0+0+1+1-1h4a1+1+0+0+1+1+1v10%22+/%3E) is probably the best, but I would still say we should wait for something even better before we merge it.

2024-12-05 12:13 UTC, karsa-mistmere commented on icons/podium.svg
This is a different simplified crown that's more trapezoid based, maybe it's a bit more legible:

![image](https://github.com/user-attachments/assets/04e9a39f-6ab4-4ac1-b374-efe53e835fcd)

2024-12-05 12:18 UTC, jguddas commented on icons/podium.svg
> This is a different simplified crown that's more trapezoid based, maybe it's a bit more legible:
> 
> ![image](https://private-user-images.githubusercontent.com/17746067/392810097-bbc97994-f735-4436-b662-5615938a893d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MDEzNDAsIm5iZiI6MTczMzQwMTA0MCwicGF0aCI6Ii8xNzc0NjA2Ny8zOTI4MTAwOTctYmJjOTc5OTQtZjczNS00NDM2LWI2NjItNTYxNTkzOGE4OTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDEyMTcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlZDAyZmVjZTk4YWJkMjJhNzZmYWJiNzZlZjQyYmVhZGJiNTMxNjA5ZjFjYTYwNDM5MTIxODQ0YWRkNzMwMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.T7-m1uJj9sI34vUx7SGhZdb-WPfFuMjhC8USXXNmLkU)

Not bad but still not really much of a wow.

2024-12-05 22:28 UTC, chessurisme commented
How about this?

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M7+4h3l2-2+2+2h3l-2+4H9z%22+/%3E%3Cpath+d=%22M8+16H4a1+1+0+0+0-1+1v4a1+1+0+0+0+1+1h16a1+1+0+0+0+1-1v-2a1+1+0+0+0-1-1h-4a1+1+0+0+0-1+1%22+/%3E%3Cpath+d=%22M9+22v-9a1+1+0+0+1+1-1h4a1+1+0+0+1+1+1v9%22+/%3E"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNNyA0aDNsMi0yIDIgMmgzbC0yIDRIOXoiIC8+CiAgPHBhdGggZD0iTTggMTZINGExIDEgMCAwIDAtMSAxdjRhMSAxIDAgMCAwIDEgMWgxNmExIDEgMCAwIDAgMS0xdi0yYTEgMSAwIDAgMC0xLTFoLTRhMSAxIDAgMCAwLTEgMSIgLz4KICA8cGF0aCBkPSJNOSAyMnYtOWExIDEgMCAwIDEgMS0xaDRhMSAxIDAgMCAxIDEgMXY5IiAvPgo8L3N2Zz4=.svg"/><br/>Open lucide studio</a>

2025-03-13 15:14 UTC, phips28 commented
can this be merged?

2026-02-08 18:51 UTC, HitogiDev commented
Any updates on merging this?

2026-02-15 05:51 UTC, Spleefies commented
Idea using a flag:
![icon](https://github.com/user-attachments/assets/05892c47-451b-4ff1-a8ea-dac6bc88c6f9)
![icon](https://github.com/user-attachments/assets/8192c8e4-4999-4148-9c16-90e917d13711)

 <a title="Open lucide studio" target="_blank" href="https://studio.lucide.dev/edit?value=%3Cpath+d=%22M+11+12+L+11+3%22+/%3E%3Cpath+d=%22M+11+3+L+17+6%22+/%3E%3Cpath+d=%22M+17+6+L+11+9%22+/%3E%3Cpath+d=%22M9+16a1+1+0+0+0-1-1H4a1+1+0+0+0-1+1v4a1+1+0+0+0+1+1h16a1+1+0+0+0+1-1v-2a1+1+0+0+0-1-1h-4a1+1+0+0+0-1+1%22+/%3E%3Cpath+d=%22M9+21v-8a1+1+0+0+1+1-1h4a1+1+0+0+1+1+1v8%22+/%3E"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNIDExIDEyIEwgMTEgMyIgLz4KICA8cGF0aCBkPSJNIDExIDMgTCAxNyA2IiAvPgogIDxwYXRoIGQ9Ik0gMTcgNiBMIDExIDkiIC8+CiAgPHBhdGggZD0iTTkgMTZhMSAxIDAgMCAwLTEtMUg0YTEgMSAwIDAgMC0xIDF2NGExIDEgMCAwIDAgMSAxaDE2YTEgMSAwIDAgMCAxLTF2LTJhMSAxIDAgMCAwLTEtMWgtNGExIDEgMCAwIDAtMSAxIiAvPgogIDxwYXRoIGQ9Ik05IDIxdi04YTEgMSAwIDAgMSAxLTFoNGExIDEgMCAwIDEgMSAxdjgiIC8+Cjwvc3ZnPg==.svg"/><br/>Open lucide studio</a>

2026-02-17 06:40 UTC, ericfennis commented
@Spleefies Looks not bad. But generally flag is not really used on the podium, more for "goals". 

I think we should go for the icon with the `1` from @karsa-mistmere .

2026-02-27 07:07 UTC, chessurisme commented
Go with 1! It feels simple, not crowded and blurry.

2026-04-24 11:08 UTC, ericfennis commented on icons/podium.svg
> +  <path d="M9 21v-8a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v8" />
From @karsa-mistmere number 1 suggestion
```suggestion
  <path d="M12 6V2h-1" />
  <path d="M9 15a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1v5a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1v-3a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1" />
  <path d="M9 21V11a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v10" />
```

2026-06-13 13:25 UTC, merged