fix(icons): added rounding to `sigma` icon
lucide-icons/lucide pull request #2149
Opened 2024-05-13 17:25 UTC by jguddas

## What is the purpose of this pull request?
- [x] Other: Icon update

### Description
Added rounding

## Before Submitting
- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

2024-05-13 17:45 UTC, karsa-mistmere requested changes

2024-05-13 17:45 UTC, karsa-mistmere commented on icons/sigma.svg
> +  <path d="M18 7V5a1 1 0 0 0-1-1H7a.5.5 0 0 0-.4.8l4.95 6.6a1 1 0 0 1 0 1.2L6.6 19.2a.5.5 0 0 0 .4.8h10a1 1 0 0 0 1-1v-2" />
Pixel perfect version:

```suggestion
  <path d="M18 7V5a1 1 0 0 0-1-1H6.5a.5.5 0 0 0-.4.8l4.5 6a2 2 0 0 1 0 2.4l-4.5 6a.5.5 0 0 0 .4.8H17a1 1 0 0 0 1-1v-2" />
```

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M18+7V5a1+1+0+0+0-1-1H6.5a.5.5+0+0+0-.4.8l4.5+6a2+2+0+0+1+0+2.4l-4.5+6a.5.5+0+0+0+.4.8H17a1+1+0+0+0+1-1v-2%22+/%3E&name=image"><img alt="icons" width="400" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTggN1Y1YTEgMSAwIDAgMC0xLTFINi41YS41LjUgMCAwIDAtLjQuOGw0LjUgNmEyIDIgMCAwIDEgMCAyLjRsLTQuNSA2YS41LjUgMCAwIDAgLjQuOEgxN2ExIDEgMCAwIDAgMS0xdi0yIiAvPgo8L3N2Zz4=.svg"/><br/>Open lucide studio</a>

2024-05-13 17:49 UTC, karsa-mistmere commented on icons/sigma.svg
> +  <path d="M18 7V5a1 1 0 0 0-1-1H7a.5.5 0 0 0-.4.8l4.95 6.6a1 1 0 0 1 0 1.2L6.6 19.2a.5.5 0 0 0 .4.8h10a1 1 0 0 0 1-1v-2" />
Or with a 1px radius central corner:
```suggestion
  <path d="M18 7V5a1 1 0 0 0-1-1H6.5a.5.5 0 0 0-.404.794l4.711 6.616a1 1 0 0 1-.001 1.182L6.093 19.21A.5.5 0 0 0 6.5 20H17a1 1 0 0 0 1-1v-2" />
```

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M18+7V5a1+1+0+0+0-1-1H6.5a.5.5+0+0+0-.404.794l4.711+6.616a1+1+0+0+1-.001+1.182L6.093+19.21A.5.5+0+0+0+6.5+20H17a1+1+0+0+0+1-1v-2%22+/%3E&name=image"><img alt="icons" width="400" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTggN1Y1YTEgMSAwIDAgMC0xLTFINi41YS41LjUgMCAwIDAtLjQwNC43OTRsNC43MTEgNi42MTZhMSAxIDAgMCAxLS4wMDEgMS4xODJMNi4wOTMgMTkuMjFBLjUuNSAwIDAgMCA2LjUgMjBIMTdhMSAxIDAgMCAwIDEtMXYtMiIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>

2024-06-05 21:27 UTC, ericfennis approved these changes

2024-06-06 09:06 UTC, merged