feat(icons): add wifi strength icons
lucide-icons/lucide pull request #2157
Opened 2024-05-18 10:22 UTC by VirtCode

## What is the purpose of this pull request?

- [x] New Icon
- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other:

### Description

Adds a `wifi-zero`, `wifi-low` and `wifi-high` icon, which are all a variant of the `wifi` icon in lucide with a few bars removed. They are similar to the wifi strength indicators used in almost all operating systems, e.g. Android, iOS, Windows, etc.

### Icon use case 

These icons can be used to indicate specifically wifi signal strength in an operating systems UI / desktop environment. The `signal-*` icons often cannot be used for that, as they are usually associated with cellular signal and not wifi.

### Alternative icon designs 

There are no alternative designs as the icons should be "parts" of the original and complete `wifi` icon.

## Icon Design Checklist 

### Concept 

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [ ] The icons are solely my own creation.
- [ ] The icons were originally created in #<issueNumber> by @<githubUser>
- [x] I've based them on the following Lucide icons: `wifi`, inspired by the `signal-*` icons
- [ ] I've based them on the following design: 

### Naming 

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

I tried to keep the naming similar to the `signal-*` icons, so I used the `zero`, `low` and `high` suffixes.

### Design 

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to three points of precision.

I just copied the `wifi` icon and removed the paths that were not needed for the respective icons. Visual center is not relevant in this case.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

2024-06-05 21:25 UTC, ericfennis approved these changes
LGTM!

2024-06-06 14:28 UTC, karsa-mistmere requested changes

2024-06-06 14:28 UTC, karsa-mistmere commented on icons/wifi-high.svg
Should this not be `wifi-medium` with `wifi` geting the `wifi-strong` tag?

2024-06-06 14:34 UTC, VirtCode commented on icons/wifi-high.svg
I was trying to keep the naming similar to the signal icons, where there is [`signal`](https://lucide.dev/icons/signal) and [`signal-high`](https://lucide.dev/icons/signal-high). But then they also have one variant more (5, not 4).

But I don't mind changing `wifi` to `wifi-high` etc. let me know whether I should do that.

2024-06-06 14:37 UTC, karsa-mistmere commented on icons/wifi-high.svg
No, let's definitely keep `wifi` as `wifi`, high should only ever be a tag. But good points, let's first investigate how signal icons are named and tagged.

2024-06-07 08:02 UTC, VirtCode commented on icons/wifi-high.svg
If we want to keep the naming consistent between these two, I would also use the `-zero` tag for the lowest icon (the dot), as is with `signal-zero`. As discussed, we also keep `wifi` as `wifi`. 

So we have three options on how we want to name the two intermediate icons (we have three tags left over to work with from the `signal-*` icons):
- `wifi-low` and `wifi-high` (as it currently is)
- `wifi-low` and `wifi-medium`
- `wifi-medium` and `wifi-high`

Let me know which option you think is best in this case.

2024-07-08 07:05 UTC, VirtCode commented on icons/wifi-high.svg
What do you think, should we leave it as is or rename to something like described above?

2024-07-08 07:35 UTC, merged

2024-07-08 07:35 UTC, karsa-mistmere commented on icons/wifi-high.svg
Let's keep it as is! I've just merged it, since @ericfennis has already approved it.