Adding stretchable alignment icons
lucide-icons/lucide pull request #2181
Opened 2024-06-04 18:42 UTC by MarwanFr

## What is the purpose of this pull request?

- [x] New Icon
- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other:

### Description

Adding Stretchable Alignment Icons (Vertical and Horizontal)

### Icon use case 

* **Align Horizontal Stretch:** This icon could be used to represent horizontal alignment with stretching. For example, it could be used to indicate that an element should stretch horizontally to fill its container.
* **Align Vertical Stretch:** This icon could be used to represent vertical alignment with stretching. For example, it could be used to indicate that an element should stretch vertically to fill its container.

### Alternative icon designs 

## Icon Design Checklist 

### Concept 

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [ ] The icons are solely my own creation.
- [ ] The icons were originally created in #<issueNumber> by @<githubUser>
- [x] I've based them on the following Lucide icons: 
- [move-horizontal](https://lucide.dev/icons/move-horizontal)
- [align-horizontal-space-around](https://lucide.dev/icons/align-horizontal-space-around)

- [ ] I've based them on the following design: 

### Naming 

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design 

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to three points of precision.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

2024-06-04 21:48 UTC, jguddas commented
Use https://lucide-studio.vercel.app to optimize the icon code.

2024-06-04 22:47 UTC, MarwanFr commented
✅

2024-06-05 20:43 UTC, jguddas commented
The icons are a bit big, maybe someone has an idea to get them to be smaller?

2024-06-05 21:12 UTC, MarwanFr commented
> The icons are a bit big, maybe someone has an idea to get them to be smaller?

The icons seem a bit large at the ends of the arrows?

2024-06-05 21:49 UTC, jguddas commented
> > The icons are a bit big, maybe someone has an idea to get them to be smaller?
> 
> The icons seem a bit large at the ends of the arrows?

The bounding box is pretty huge, you can also see it [here](https://github.com/lucide-icons/lucide/pull/2181#issuecomment-2148179469) in the `Preview cohesion`.

2024-06-06 07:33 UTC, MarwanFr commented
> > > The icons are a bit big, maybe someone has an idea to get them to be smaller?
> > 
> > 
> > The icons seem a bit large at the ends of the arrows?
> 
> The bounding box is pretty huge, you can also see it [here](https://github.com/lucide-icons/lucide/pull/2181#issuecomment-2148179469) in the `Preview cohesion`.

So I should tighten the arrow? Because the line size is the same as the other alignment icons.
![image](https://github.com/lucide-icons/lucide/assets/155018178/68592679-9969-499a-9703-9d043fcfe6b2)

2024-06-06 13:58 UTC, jguddas commented
> > > > The icons are a bit big, maybe someone has an idea to get them to be smaller?
> > > 
> > > 
> > > The icons seem a bit large at the ends of the arrows?
> > 
> > 
> > The bounding box is pretty huge, you can also see it [here](https://github.com/lucide-icons/lucide/pull/2181#issuecomment-2148179469) in the `Preview cohesion`.
> 
> So I should tighten the arrow? Because the line size is the same as the other alignment icons. ![image](https://private-user-images.githubusercontent.com/155018178/337165047-68592679-9969-499a-9703-9d043fcfe6b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2ODI0NjYsIm5iZiI6MTcxNzY4MjE2NiwicGF0aCI6Ii8xNTUwMTgxNzgvMzM3MTY1MDQ3LTY4NTkyNjc5LTk5NjktNDk5YS05NzAzLTlkMDQzZmNmZTZiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQxMzU2MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWQ1OWVmYzY0ZDYzMzY2ZDQ5YWU4MmE4YTkwMmUwODQxYmUyMzgwODM4YThjNWI0YTY3ZTY2NWZhMDdkNWU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VUMXHcruv0ZxcS_9Lrud6VKJbcnB0onYljbDw2_5OFk)

It's bigger than https://lucide.dev/icons/align-horizontal-space-between.

And the rule for sizing is to keep it similarly sized to `square` and `circle`.

2024-06-06 14:37 UTC, MarwanFr commented
Okay, I understand the problem now. Is this okay?

> > > > > The icons are a bit big, maybe someone has an idea to get them to be smaller?
> > > > 
> > > > 
> > > > The icons seem a bit large at the ends of the arrows?
> > > 
> > > 
> > > The bounding box is pretty huge, you can also see it [here](https://github.com/lucide-icons/lucide/pull/2181#issuecomment-2148179469) in the `Preview cohesion`.
> > 
> > 
> > So I should tighten the arrow? Because the line size is the same as the other alignment icons. ![image](https://private-user-images.githubusercontent.com/155018178/337165047-68592679-9969-499a-9703-9d043fcfe6b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2ODI0NjYsIm5iZiI6MTcxNzY4MjE2NiwicGF0aCI6Ii8xNTUwMTgxNzgvMzM3MTY1MDQ3LTY4NTkyNjc5LTk5NjktNDk5YS05NzAzLTlkMDQzZmNmZTZiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQxMzU2MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWQ1OWVmYzY0ZDYzMzY2ZDQ5YWU4MmE4YTkwMmUwODQxYmUyMzgwODM4YThjNWI0YTY3ZTY2NWZhMDdkNWU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VUMXHcruv0ZxcS_9Lrud6VKJbcnB0onYljbDw2_5OFk)
> 
> It's 2px wider than https://lucide.dev/icons/align-horizontal-space-between.
> 
> The rule for sizing is to keep it similarly sized to `square` and `circle`.

Ok, I see the problem. Is it good now?

2024-06-09 16:11 UTC, MarwanFr commented
I believe there might be an issue with the verification.

2024-07-23 12:51 UTC, ericfennis requested changes

2024-07-31 14:55 UTC, MarwanFr commented
It's good, I have fixed the indentation.

2024-09-01 19:09 UTC, ericfennis approved these changes

2024-09-01 19:10 UTC, ericfennis commented
Ready to go!

2024-09-01 19:12 UTC, jguddas requested changes
I think it's to dense.

2024-09-01 19:13 UTC, jguddas reviewed
Also naming wise we might need to rethink the alignment icons.

2026-07-09 13:19 UTC, karsa-mistmere commented
The arrows feel quite dense, I'd probably go for something more like these:

<a title="Open lucide studio" target="_blank" href="https://studio.lucide.dev/edit?value=2.m15_9_3_3-3_3Mo21V3M2o21V3M6r2h12m9_9-3_3_3_3"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJtMTUgOSAzIDMtMyAzIiAvPgogIDxwYXRoIGQ9Ik0yIDIxVjMiIC8+CiAgPHBhdGggZD0iTTIyIDIxVjMiIC8+CiAgPHBhdGggZD0iTTYgMTJoMTIiIC8+CiAgPHBhdGggZD0ibTkgOS0zIDMgMyAzIiAvPgo8L3N2Zz4=.svg"/><br/>Open lucide studio</a>

<a title="Open lucide studio" target="_blank" href="https://studio.lucide.dev/edit?value=2.1o6v12m15r5-3_3-3-3m15_9-3-3-3_3M3u2h18M3uh18"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTIgNnYxMiIgLz4KICA8cGF0aCBkPSJtMTUgMTUtMyAzLTMtMyIgLz4KICA8cGF0aCBkPSJtMTUgOS0zLTMtMyAzIiAvPgogIDxwYXRoIGQ9Ik0zIDIyaDE4IiAvPgogIDxwYXRoIGQ9Ik0zIDJoMTgiIC8+Cjwvc3ZnPg==.svg"/><br/>Open lucide studio</a>

2026-08-28 10:51 UTC, closed without merging