feat(icons): added `plane-tickets` icon
lucide-icons/lucide pull request #2196
Opened 2024-06-08 09:23 UTC by jguddas

## What is the purpose of this pull request?

- [x] New Icon
- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other:

### Description

### Icon use case 

### Alternative icon designs 

## Icon Design Checklist 

### Concept 

- [ ] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [x] The icons are solely my own creation.
- [ ] The icons were originally created in #<issueNumber> by @<githubUser>
- [ ] I've based them on the following Lucide icons: 
- [ ] I've based them on the following design: 

### Naming 

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design 

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [ ] I've made sure that the icons look sharp on low DPI displays.
- [ ] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [ ] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to three points of precision.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

2024-06-12 08:58 UTC, ericfennis reviewed
Nice love the icon, clean and simple!

2024-06-12 08:58 UTC, ericfennis commented on icons/plane-tickets.json
> +    "airplane"
Some extra tags to consider:
```suggestion
    "airplane"
    "flight",
    "travel",
    "fly",
    "takeoff",
    "vacation",
    "passenger",
    "pass",
    "check-in",
    "airport"
```

2024-06-14 10:42 UTC, ericfennis approved these changes

2024-07-17 16:04 UTC, karsa-mistmere commented
I think this should be `tickets-plane`, both because it's a ticket variant with a plane on it and because the ticket is larger than the plane itself.

2024-07-17 16:05 UTC, karsa-mistmere requested changes
I think this should be `tickets-plane`, both because it's a ticket variant with a plane on it and because the ticket is larger than the plane itself.

2024-07-17 19:44 UTC, jguddas commented
> I think this should be `tickets-plane`, both because it's a ticket variant with a plane on it and because the ticket is larger than the plane itself.

100% agree.

2024-07-19 16:29 UTC, jguddas commented
> Maybe an idea to add `plane-tickets` as an alias? I can imagine that for some people it can be confusing when used in code.

I'm not a fan of having aliases if we can avoid them.

2024-07-24 12:04 UTC, ericfennis approved these changes

2024-08-16 08:26 UTC, merged