Adding 'scan-qrcode' icon
lucide-icons/lucide pull request #2247
Opened 2024-06-23 08:08 UTC by vexkiddy

## What is the purpose of this pull request?

- [x] New Icon
- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other:

### Description
New scan qr-code icon

### Icon use case 
1. for indicating a scanner feature of qr-codes
2. to differentiate from the qr-code icon that doesn't indicate scanning

## Icon Design Checklist 

### Concept 

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [x] The icons are solely my own creation.
- [ ] The icons were originally created in #<issueNumber> by @<githubUser>
- [ ] I've based them on the following Lucide icons: 
- [ ] I've based them on the following design: 

### Naming 

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design 

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to three points of precision.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

2024-06-23 18:19 UTC, jguddas requested changes
The icon should be renamed to `scan-qr-code`.

2024-06-23 18:19 UTC, jguddas commented on icons/scan-qrcode.svg
> +  <path d="M17 12v3a2 2 0 0 1-2 2h-3" />
I would add a sharper corner radius there.
```suggestion
  <path d="M17 12v4a1 1 0 0 1-1 1h-4" /
```
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M17+12v4a1+1+0+0+1-1+1h-4%22+/%3E%3Cpath+d=%22M17+3h2a2+2+0+0+1+2+2v2%22+/%3E%3Cpath+d=%22M17+8V7%22+/%3E%3Cpath+d=%22M21+17v2a2+2+0+0+1-2+2h-2%22+/%3E%3Cpath+d=%22M3+7V5a2+2+0+0+1+2-2h2%22+/%3E%3Cpath+d=%22M7+17h.01%22+/%3E%3Cpath+d=%22M7+21H5a2+2+0+0+1-2-2v-2%22+/%3E%3Crect+x=%227%22+y=%227%22+width=%225%22+height=%225%22+rx=%221%22+/%3E&dialog=false&name=scan-qr-code"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTcgMTJ2NGExIDEgMCAwIDEtMSAxaC00IiAvPgogIDxwYXRoIGQ9Ik0xNyAzaDJhMiAyIDAgMCAxIDIgMnYyIiAvPgogIDxwYXRoIGQ9Ik0xNyA4VjciIC8+CiAgPHBhdGggZD0iTTIxIDE3djJhMiAyIDAgMCAxLTIgMmgtMiIgLz4KICA8cGF0aCBkPSJNMyA3VjVhMiAyIDAgMCAxIDItMmgyIiAvPgogIDxwYXRoIGQ9Ik03IDE3aC4wMSIgLz4KICA8cGF0aCBkPSJNNyAyMUg1YTIgMiAwIDAgMS0yLTJ2LTIiIC8+CiAgPHJlY3QgeD0iNyIgeT0iNyIgd2lkdGg9IjUiIGhlaWdodD0iNSIgcng9IjEiIC8+Cjwvc3ZnPg==.svg"/><br/>Open lucide studio</a>

2024-06-23 21:28 UTC, vexkiddy commented
hiya @jguddas think i've approved everything.. do i need do anything else ?

2024-06-25 12:54 UTC, vexkiddy commented
@jguddas just nudging this :D

2024-06-25 12:59 UTC, jguddas approved these changes

2024-06-28 12:11 UTC, ericfennis commented on icons/scan-qr-code.json
> +    "development"
Not sure if this is the correct category. This not really associated with development in general
I think these categories fit better:
```suggestion
    "account",
    "shopping",
    "devices",
    "security"
```

2024-07-07 20:12 UTC, ericfennis approved these changes

2024-07-07 20:12 UTC, merged