fix(icons): arcified `ribbon` icon
lucide-icons/lucide pull request #2271
Opened 2024-07-02 17:57 UTC by jguddas

## What is the purpose of this pull request?
- [x] Other: Icon update

### Description
Arcified icon.

## Before Submitting
- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

2024-07-02 20:44 UTC, karsa-mistmere approved these changes
Such simple change and so much improvement.

2024-07-04 07:12 UTC, karsa-mistmere requested changes

2024-07-04 07:12 UTC, karsa-mistmere commented on icons/ribbon.svg
>    <path d="m9.35 14.53 2.64-3.31" />
Let's elongate the bottom strips for better vertical centering:
```suggestion
  <path d="M12 11.22C11 9.997 10 9 10 8a2 2 0 0 1 4 0c0 1-.998 2.002-2.01 3.22" />
  <path d="m12 18 2.57-3.5" />
  <path d="M6.243 9.016a7 7 0 0 1 11.507-.009" />
  <path d="M9.35 14.53 12 11.22" />
  <path d="M9.35 14.53C7.728 12.246 6 10.221 6 7a6 5 0 0 1 12 0c-.005 3.22-1.778 5.235-3.43 7.5l3.557 4.527a1 1 0 0 1-.203 1.43l-1.894 1.36a1 1 0 0 1-1.384-.215L12 18l-2.679 3.593a1 1 0 0 1-1.39.213l-1.865-1.353a1 1 0 0 1-.203-1.422z" />
```
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M12+11.22C11+9.997+10+9+10+8a2+2+0+0+1+4+0c0+1-.998+2.002-2.01+3.22%22+/%3E%3Cpath+d=%22m12+18+2.57-3.5%22+/%3E%3Cpath+d=%22M6.243+9.016a7+7+0+0+1+11.507-.009%22+/%3E%3Cpath+d=%22M9.35+14.53+12+11.22%22+/%3E%3Cpath+d=%22M9.35+14.53C7.728+12.246+6+10.221+6+7a6+5+0+0+1+12+0c-.005+3.22-1.778+5.235-3.43+7.5l3.557+4.527a1+1+0+0+1-.203+1.43l-1.894+1.36a1+1+0+0+1-1.384-.215L12+18l-2.679+3.593a1+1+0+0+1-1.39.213l-1.865-1.353a1+1+0+0+1-.203-1.422z%22+/%3E&name=image"><img alt="icons" width="400" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTIgMTEuMjJDMTEgOS45OTcgMTAgOSAxMCA4YTIgMiAwIDAgMSA0IDBjMCAxLS45OTggMi4wMDItMi4wMSAzLjIyIiAvPgogIDxwYXRoIGQ9Im0xMiAxOCAyLjU3LTMuNSIgLz4KICA8cGF0aCBkPSJNNi4yNDMgOS4wMTZhNyA3IDAgMCAxIDExLjUwNy0uMDA5IiAvPgogIDxwYXRoIGQ9Ik05LjM1IDE0LjUzIDEyIDExLjIyIiAvPgogIDxwYXRoIGQ9Ik05LjM1IDE0LjUzQzcuNzI4IDEyLjI0NiA2IDEwLjIyMSA2IDdhNiA1IDAgMCAxIDEyIDBjLS4wMDUgMy4yMi0xLjc3OCA1LjIzNS0zLjQzIDcuNWwzLjU1NyA0LjUyN2ExIDEgMCAwIDEtLjIwMyAxLjQzbC0xLjg5NCAxLjM2YTEgMSAwIDAgMS0xLjM4NC0uMjE1TDEyIDE4bC0yLjY3OSAzLjU5M2ExIDEgMCAwIDEtMS4zOS4yMTNsLTEuODY1LTEuMzUzYTEgMSAwIDAgMS0uMjAzLTEuNDIyeiIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>

(I've also done some manual optimization or some elliptic arcs and overall better curvature)

2024-07-04 07:32 UTC, karsa-mistmere approved these changes

2024-07-19 09:05 UTC, ericfennis approved these changes

2024-07-19 09:06 UTC, merged