fix(icons): arcified `book-*` icons
lucide-icons/lucide pull request #2274
Opened 2024-07-02 20:20 UTC by jguddas

## What is the purpose of this pull request?
- [x] Other: Icon update

### Description
Arcified book icons.

## Before Submitting
- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

2024-07-02 20:42 UTC, karsa-mistmere requested changes

2024-07-02 20:42 UTC, karsa-mistmere commented on icons/book-dashed.json
> -    "book-template"
Why?

2024-07-02 20:42 UTC, karsa-mistmere commented on icons/book-copy.svg
The book in this one doesn't quite feel like a book anymore. 🤔

2024-07-02 20:44 UTC, jguddas commented on icons/book-copy.svg
I agree, do you have a suggestion?

2024-07-02 21:13 UTC, jguddas commented on icons/book-dashed.json
> -    "book-template"
Oups

2024-07-02 21:16 UTC, karsa-mistmere commented on icons/book-copy.svg
> +  <path d="M22 18H11a2 2 0 1 0 0 4h10.5a.5.5 0 0 0 .5-.5V7a.5.5 0 0 0-.5-.5H11a2 2 0 0 0-2 2v12" />
This became .5px shorter than before, making of off-grid.

2024-07-04 07:33 UTC, karsa-mistmere approved these changes

2024-07-07 19:59 UTC, ericfennis approved these changes
Nice!

2024-07-07 19:59 UTC, merged