fix(icons): changed `delete` icon
lucide-icons/lucide pull request #2279
Opened 2024-07-03 17:53 UTC by jguddas

## What is the purpose of this pull request?
- [x] Other: Icon update

### Description
Arcified icon.

## Before Submitting
- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [ ] I've checked if there was an existing PR that solves the same issue.

2024-07-04 07:41 UTC, karsa-mistmere requested changes

2024-07-04 07:41 UTC, karsa-mistmere commented on icons/delete.svg
> +  <path d="M2.707 11.293a1 1 0 0 0 0 1.414l5.707 5.707A2 2 0 0 0 9.828 19H20a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2H9.828a2 2 0 0 0-1.414.586z" />
I propose to redraw this with grid aligned circles:

```suggestion
  <path d="M10 5a2 2 0 0 0-1.344.519l-6.328 5.74a1 1 0 0 0 0 1.481l6.328 5.741A2 2 0 0 0 10 19h10a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2z" />
  <path d="m12 9 6 6" />
  <path d="m18 9-6 6" />
```

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M10+5a2+2+0+0+0-1.344.519l-6.328+5.74a1+1+0+0+0+0+1.481l6.328+5.741A2+2+0+0+0+10+19h10a2+2+0+0+0+2-2V7a2+2+0+0+0-2-2z%22+/%3E%3Cpath+d=%22m12+9+6+6%22+/%3E%3Cpath+d=%22m18+9-6+6%22+/%3E&name=image"><img alt="icons" width="400" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTAgNWEyIDIgMCAwIDAtMS4zNDQuNTE5bC02LjMyOCA1Ljc0YTEgMSAwIDAgMCAwIDEuNDgxbDYuMzI4IDUuNzQxQTIgMiAwIDAgMCAxMCAxOWgxMGEyIDIgMCAwIDAgMi0yVjdhMiAyIDAgMCAwLTItMnoiIC8+CiAgPHBhdGggZD0ibTEyIDkgNiA2IiAvPgogIDxwYXRoIGQ9Im0xOCA5LTYgNiIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>

2024-07-04 07:45 UTC, karsa-mistmere approved these changes

2024-07-07 19:34 UTC, ericfennis approved these changes

2024-07-09 18:40 UTC, merged