feat(icons): added `user-round-arrow-inwards` icon
lucide-icons/lucide pull request #2283
Opened 2024-07-03 19:27 UTC by jguddas

## What is the purpose of this pull request?
- [x] New Icon

### Description
Added new `user-round-arrow-inwards` icon.

### Icon use case

- Go to user / personal stuff.
- Assign something to user / myself.
- Pointing toward user, like when you point with your finger on your own chest.

### Alternative icon designs

## Icon Design Checklist

### Concept

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [ ] The icons are solely my own creation.
- [ ] The icons were originally created in #<issueNumber> by @<githubUser>
- [ ] I've based them on the following Lucide icons: 
- [ ] I've based them on the following design: 

### Naming

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design

- [ ] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [ ] I've made sure that the icons look sharp on low DPI displays.
- [ ] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [ ] I've made sure that the icons are visually centered.
- [ ] I've correctly optimized all icons to three points of precision.

## Before Submitting
- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [ ] I've checked if there was an existing PR that solves the same issue.

2024-07-04 08:12 UTC, karsa-mistmere commented
How about just `user-round-arrow-in`?

And maybe we could also add matching variants, something like this?
![image](https://github.com/lucide-icons/lucide/assets/17746067/55f92ca8-73c4-45ce-9998-d2168f52770b)

2024-07-14 18:03 UTC, jguddas commented
Up/Down would also be nice for uploading/downloading user related stuff.

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?name=user-round-check&value=%3Cpath+d=%22m16+18+3+3v-8%22+/%3E%3Cpath+d=%22m19+21+3-3%22+/%3E%3Cpath+d=%22M2+21a8+8+0+0+1+12.5-6.612%22+/%3E%3Ccircle+cx=%2210%22+cy=%228%22+r=%225%22+/%3E"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJtMTYgMTggMyAzdi04IiAvPgogIDxwYXRoIGQ9Im0xOSAyMSAzLTMiIC8+CiAgPHBhdGggZD0iTTIgMjFhOCA4IDAgMCAxIDEyLjUtNi42MTIiIC8+CiAgPGNpcmNsZSBjeD0iMTAiIGN5PSI4IiByPSI1IiAvPgo8L3N2Zz4=.svg"/><br/>Open lucide studio</a>

2024-08-02 09:30 UTC, ericfennis commented
I agree with @karsa-mistmere, we can make the name a bit simpler

2024-08-14 15:16 UTC, ericfennis approved these changes

2025-04-18 10:17 UTC, ericfennis commented
@jguddas Wait, should it not be `user-round-arrow-left`? It is more in-line with the other `arrow` naming

2025-06-18 07:20 UTC, ericfennis requested changes
Rename to `user-round-arrow-left` to make it more aligned with other arrow icons.

2025-12-09 16:16 UTC, karsa-mistmere submitted a review, later dismissed
I agree with @ericfennis

2026-06-13 15:35 UTC, ericfennis approved these changes

2026-06-13 15:35 UTC, merged