feat(icons): add peanut icons
lucide-icons/lucide pull request #2340
Opened 2024-07-29 11:21 UTC by karsa-mistmere

closes #2318 

## What is the purpose of this pull request?

- [x] New Icon

### Description
Adds a peanut and a peanut-off icon, as per #2318  and #924 

### Icon use case 
See #2318 

### Alternative icon designs 
See #2318 

## Icon Design Checklist 

### Concept 

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [x] The icons are solely my own creation.

### Naming 

- [ ] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [ ] I've named icons by what they are rather than their use case.
- [ ] I've provided meta JSON files in `icons/[iconName].json`.

### Design 

- [ ] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [ ] I've made sure that the icons look sharp on low DPI displays.
- [ ] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [ ] I've made sure that the icons are visually centered.
- [ ] I've correctly optimized all icons to three points of precision.

## Before Submitting 

- [ ] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [ ] I've checked if there was an existing PR that solves the same issue.

2024-07-30 07:03 UTC, jguddas commented
Feels a little bulbous to me, can we somehow make it cuter?

2024-07-30 07:54 UTC, karsa-mistmere commented
> Feels a little bulbous to me, can we somehow make it cuter?

Do you mean something like this by being less bulbous?

![image](https://github.com/user-attachments/assets/daefd6b2-f5b4-41a7-ba06-e1aa131d09d6)

I purposefully kept it very geometric, I personally find the rounded version cuter, but to each its own, I guess. 😄

2024-10-07 06:02 UTC, jguddas requested changes
It remains a no from me, it feels not penutty enough for me.

2024-10-07 09:37 UTC, karsa-mistmere commented
> It remains a no from me, it feels not penutty enough for me.

Can you respond to my question in https://github.com/lucide-icons/lucide/pull/2340#issuecomment-2257707145 though?

2024-10-07 11:39 UTC, jguddas commented
> > It remains a no from me, it feels not penutty enough for me.
> 
> Can you respond to my question in https://github.com/lucide-icons/lucide/pull/2340#issuecomment-2257707145 though?

I don't know, it just doesn't look like a peanut.

2024-11-09 20:54 UTC, jguddas commented
Simple simple:
![](https://github.com/user-attachments/assets/9c96667f-413a-4ac8-83fa-1433db43cfbc)

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M11.23+6.5a5+5+0+1+1+6.27+6.268c-1.68.702-3.649+1.991-4.354+3.674l-.382+1.077a5+5+0+1+1-8.353-5C6.992+9.519+9+12+10.602+8.263z%22+/%3E"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTEuMjMgNi41YTUgNSAwIDEgMSA2LjI3IDYuMjY4Yy0xLjY4LjcwMi0zLjY0OSAxLjk5MS00LjM1NCAzLjY3NGwtLjM4MiAxLjA3N2E1IDUgMCAxIDEtOC4zNTMtNUM2Ljk5MiA5LjUxOSA5IDEyIDEwLjYwMiA4LjI2M3oiIC8+Cjwvc3ZnPg==.svg"/><br/>Open lucide studio</a>

2026-07-10 23:30 UTC, rrod497 commented
From my drafts:
<table>
  <tbody>
    <tr>
      <td><a title="Open lucide studio" target="_blank" href="https://studio.lucide.dev/edit?value=%3Cpath+d=%22M11+13h.01%22+/%3E%3Cpath+d=%22M14+16a6+6+0+1+1-6-6+2+2+0+0+0+2-2+6+6+0+0+1+6-6h5a1+1+0+0+1+1+1v5a6+6+0+0+1-6+6+2+2+0+0+0-2+2%22+/%3E%3Cpath+d=%22M14+7h.01%22+/%3E%3Cpath+d=%22M18+6h.01%22+/%3E%3Cpath+d=%22M7+14h.01%22+/%3E%3Cpath+d=%22M7+17.732A2+2+0+0+0+9.732+17%22+/%3E&name=peanut"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTEgMTNoLjAxIiAvPgogIDxwYXRoIGQ9Ik0xNCAxNmE2IDYgMCAxIDEtNi02IDIgMiAwIDAgMCAyLTIgNiA2IDAgMCAxIDYtNmg1YTEgMSAwIDAgMSAxIDF2NWE2IDYgMCAwIDEtNiA2IDIgMiAwIDAgMC0yIDIiIC8+CiAgPHBhdGggZD0iTTE0IDdoLjAxIiAvPgogIDxwYXRoIGQ9Ik0xOCA2aC4wMSIgLz4KICA8cGF0aCBkPSJNNyAxNGguMDEiIC8+CiAgPHBhdGggZD0iTTcgMTcuNzMyQTIgMiAwIDAgMCA5LjczMiAxNyIgLz4KPC9zdmc+.svg"/></a></td>
      <td><a title="Open lucide studio" target="_blank" href="https://studio.lucide.dev/edit?value=2.10.75_5.094A6_6b116uh5E11rv5a6_6R3.094_5.25M11r3h.yM14_7h.yM14.586r4.586AF14r6a6_6nr1-6-6_F1.414-.586M18_6h.yme2p20M7r4h.yM7r7.732AF9.73o17&name=peanut"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTAuNzUgNS4wOTRBNiA2IDAgMDExNiAyaDVhMSAxIDAgMDExIDF2NWE2IDYgMCAwMS0zLjA5NCA1LjI1IiAvPgogIDxwYXRoIGQ9Ik0xMSAxM2guMDEiIC8+CiAgPHBhdGggZD0iTTE0IDdoLjAxIiAvPgogIDxwYXRoIGQ9Ik0xNC41ODYgMTQuNTg2QTIgMiAwIDAwMTQgMTZhNiA2IDAgMTEtNi02IDIgMiAwIDAwMS40MTQtLjU4NiIgLz4KICA8cGF0aCBkPSJNMTggNmguMDEiIC8+CiAgPHBhdGggZD0ibTIgMiAyMCAyMCIgLz4KICA8cGF0aCBkPSJNNyAxNGguMDEiIC8+CiAgPHBhdGggZD0iTTcgMTcuNzMyQTIgMiAwIDAwOS43MzIgMTciIC8+Cjwvc3ZnPg==.svg"/></a></td>
    </tr>
  </tbody>
</table>
<img width="79" height="42" alt="image" src="https://github.com/user-attachments/assets/5b50ee76-965b-4398-b4d3-b44e58d3be95" />

2026-07-11 11:02 UTC, karsa-mistmere commented
> From my drafts:
> 
> [<img alt="icons" width="200px" src="https://camo.githubusercontent.com/467d0d4ff9fac30a357e349fabdc13652c72f1a10dec748bd2c0b41fe0a9fda4/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a776f67494868746247357a50534a6f644852774f693876643364334c6e637a4c6d39795a7938794d4441774c334e325a79494b4943423361575230614430694d6a516943694167614756705a326830505349794e43494b4943423261575633516d393450534977494441674d6a51674d6a5169436941675a6d6c7362443069626d39755a53494b4943427a64484a7661325539496d4e31636e4a6c626e5244623278766369494b4943427a64484a766132557464326c6b64476739496a496943694167633352796232746c4c577870626d566a59584139496e4a766457356b49676f6749484e30636d39725a5331736157356c616d3970626a3069636d3931626d5169436a344b49434138634746306143426b50534a4e4d5445674d544e6f4c6a41784969417650676f67494478775958526f49475139496b30784e4341784e6d4532494459674d434178494445744e693032494449674d694177494441674d4341794c5449674e694132494441674d434178494459744e6d6731595445674d534177494441674d534178494446324e574532494459674d434177494445744e694132494449674d694177494441674d433079494449694943382b4369416750484268644767675a443069545445304944646f4c6a41784969417650676f67494478775958526f49475139496b30784f434132614334774d5349674c7a344b49434138634746306143426b50534a4e4e7941784e4767754d4445694943382b4369416750484268644767675a443069545463674d5463754e7a4d79515449674d694177494441674d4341354c6a637a4d6941784e7949674c7a344b5043397a646d632b2e737667">](https://studio.lucide.dev/edit?value=%3Cpath+d=%22M11+13h.01%22+/%3E%3Cpath+d=%22M14+16a6+6+0+1+1-6-6+2+2+0+0+0+2-2+6+6+0+0+1+6-6h5a1+1+0+0+1+1+1v5a6+6+0+0+1-6+6+2+2+0+0+0-2+2%22+/%3E%3Cpath+d=%22M14+7h.01%22+/%3E%3Cpath+d=%22M18+6h.01%22+/%3E%3Cpath+d=%22M7+14h.01%22+/%3E%3Cpath+d=%22M7+17.732A2+2+0+0+0+9.732+17%22+/%3E&name=peanut)	[<img alt="icons" width="200px" src="https://camo.githubusercontent.com/1786c5d143ec43e0be60eee6fb5e29b3c2b49e3c29987cd39a460dcc2fb0ad9f/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a776f67494868746247357a50534a6f644852774f693876643364334c6e637a4c6d39795a7938794d4441774c334e325a79494b4943423361575230614430694d6a516943694167614756705a326830505349794e43494b4943423261575633516d393450534977494441674d6a51674d6a5169436941675a6d6c7362443069626d39755a53494b4943427a64484a7661325539496d4e31636e4a6c626e5244623278766369494b4943427a64484a766132557464326c6b64476739496a496943694167633352796232746c4c577870626d566a59584139496e4a766457356b49676f6749484e30636d39725a5331736157356c616d3970626a3069636d3931626d5169436a344b49434138634746306143426b50534a4e4d5441754e7a55674e5334774f5452424e694132494441674d4445784e694179614456684d534178494441674d444578494446324e574532494459674d4341774d53307a4c6a41354e4341314c6a49314969417650676f67494478775958526f49475139496b30784d5341784d3267754d4445694943382b4369416750484268644767675a443069545445304944646f4c6a41784969417650676f67494478775958526f49475139496b30784e4334314f4459674d5451754e546732515449674d694177494441774d5451674d545a684e694132494441674d5445744e693032494449674d694177494441774d5334304d5451744c6a55344e6949674c7a344b49434138634746306143426b50534a4e4d5467674e6d67754d4445694943382b4369416750484268644767675a443069625449674d6941794d4341794d4349674c7a344b49434138634746306143426b50534a4e4e7941784e4767754d4445694943382b4369416750484268644767675a443069545463674d5463754e7a4d79515449674d694177494441774f5334334d7a49674d5463694943382b436a777663335a6e50673d3d2e737667">](https://studio.lucide.dev/edit?value=2.10.75_5.094A6_6b116uh5E11rv5a6_6R3.094_5.25M11r3h.yM14_7h.yM14.586r4.586AF14r6a6_6nr1-6-6_F1.414-.586M18_6h.yme2p20M7r4h.yM7r7.732AF9.73o17&name=peanut)
> <img alt="image" width="79" height="42" src="https://private-user-images.githubusercontent.com/5318062/620291078-5b50ee76-965b-4398-b4d3-b44e58d3be95.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODM3NjY5ODQsIm5iZiI6MTc4Mzc2NjY4NCwicGF0aCI6Ii81MzE4MDYyLzYyMDI5MTA3OC01YjUwZWU3Ni05NjViLTQzOTgtYjRkMy1iNDRlNThkM2JlOTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDcxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjA3MTFUMTA0NDQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzI4NmY4NzVmYzkyMmI1YjYxMGMwNWIwYTc1YjNhMGI3ZjMwYmE3NDljNjA2Zjk3NTRkOTdhOTBmYzA5NTI0ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmcmVzcG9uc2UtY29udGVudC10eXBlPWltYWdlJTJGcG5nIn0.jW7FX-g0t-biMpUin0B8296xko4Lq_juadB2EJcUZ7U">

There are a few minor gap violations, but I'd be willing to let these slide. The only change I'd probably push for is dropping the 3D-ish arc in favour of yet another dot, as it's not really in line with current Lucide icons depicting similar items: https://lucide.dev/icons/categories#food-beverage (e.g. in `apple` or `egg`)

<a title="Open lucide studio" target="_blank" href="https://studio.lucide.dev/edit?value=2.11r3h.yM14_8h.yM16ua6_6Y6_6_D-e6_6nr06_6_D2-o6_6b06-6V4B0-2-2zM18_6h.yM6r5h.yM9.5r7.5h.y&name=peanut"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTEgMTNoLjAxIiAvPgogIDxwYXRoIGQ9Ik0xNCA4aC4wMSIgLz4KICA8cGF0aCBkPSJNMTYgMmE2IDYgMCAwMC02IDYgMiAyIDAgMDEtMiAyIDYgNiAwIDEwNiA2IDIgMiAwIDAxMi0yIDYgNiAwIDAwNi02VjRhMiAyIDAgMDAtMi0yeiIgLz4KICA8cGF0aCBkPSJNMTggNmguMDEiIC8+CiAgPHBhdGggZD0iTTYgMTVoLjAxIiAvPgogIDxwYXRoIGQ9Ik05LjUgMTcuNWguMDEiIC8+Cjwvc3ZnPg==.svg"/><br/>Open lucide studio</a>


(It also kinda looks like a smiley  <img width="38" height="36" alt="image" src="https://github.com/user-attachments/assets/fa340cf9-2a13-4780-a902-0900d864127f" /> )

2026-07-24 13:14 UTC, ericfennis commented
Closing this one, since it seems still in "exploring" phase. Please continue the discussion in #2318

2026-07-24 13:14 UTC, closed without merging

2026-07-24 15:31 UTC, karsa-mistmere commented
> Closing this one, since it seems still in "exploring" phase. Please continue the discussion in #2318

@ericfennis: I think the last one I posted has minor enough gap violations that the usefulness of the icon supersedes them, peanut is one of the most common food allergies after all.

2026-07-25 11:51 UTC, ericfennis commented
Yeah I'm not against the peanut icon. But since we a linked issue, we should "explore" the design there not in the PR itself.