feat(docs): add standalone example for angular
lucide-icons/lucide pull request #2383
Opened 2024-08-18 08:59 UTC by hiepxanh

add standalone example for angular since it different with current behavior

## What is the purpose of this pull request?

- [ ] New Icon
- [ ] Bug fix
- [ ] New Feature
- [x] Documentation update
- [ ] Other:

### Description
I'm using Lucide with Angular and really love it. I'm using Angular 18 and this update should help standalone user understand how to use it for new standard

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

2024-08-18 09:22 UTC, karsa-mistmere requested changes

2024-08-18 09:22 UTC, karsa-mistmere commented on docs/guide/packages/lucide-angular.md
> +  icons = { File, Home, Menu, UserCheck };
```suggestion
  readonly FileIcon = FileIcon;
```

2024-08-18 09:22 UTC, karsa-mistmere commented on docs/guide/packages/lucide-angular.md
> +import { LucideAngularModule, File, Home, Menu, UserCheck } from 'lucide-angular';
```suggestion
import { LucideAngularModule, FileIcon } from 'lucide-angular';
```

2024-08-18 09:22 UTC, karsa-mistmere commented on docs/guide/packages/lucide-angular.md
> +
```suggestion

```

2024-08-18 09:22 UTC, karsa-mistmere commented on docs/guide/packages/lucide-angular.md
> +<span-lucide [name]="icons.Check" class="my-icon"></span-lucide>
```suggestion
<lucide-angular [img]="FileIcon" class="my-icon"></lucide-angular>
<lucide-icon [img]="FileIcon" class="my-icon"></lucide-icon>
<i-lucide [img]="FileIcon" class="my-icon"></i-lucide>
<span-lucide [img]="FileIcon" class="my-icon"></span-lucide>
```

2024-08-21 07:23 UTC, karsa-mistmere approved these changes

2024-08-21 07:23 UTC, merged

2024-08-21 07:25 UTC, karsa-mistmere commented
> @karsa-mistmere Hi Karsa, I squash new commit follow your suggestion. Please review this one

Hi @hiepxanh, 

Thanks for the work, I've merged it.

p.s. In the future please do not force push, squash merge is on by default.

2024-08-21 12:42 UTC, hiepxanh commented
It my pleasure to contributing.
That auto squash really amazing, thank for your note. Last time I was blame by forgot to squash 😛