feat(icons): added `scan-heart` icon
lucide-icons/lucide pull request #2385
Opened 2024-08-18 10:51 UTC by jguddas

## What is the purpose of this pull request?
- [x] New Icon

### Description
Added new `scan-heart` icon.

### Icon use case

For health checkups.

### Alternative icon designs

## Icon Design Checklist

### Concept

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [ ] The icons are solely my own creation.
- [ ] The icons were originally created in #<issueNumber> by @<githubUser>
- [x] I've based them on the following Lucide icons: `scan-face`
- [ ] I've based them on the following design: 

### Naming

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design

- [ ] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [ ] I've made sure that the icons look sharp on low DPI displays.
- [ ] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [ ] I've made sure that the icons are visually centered.
- [ ] I've correctly optimized all icons to three points of precision.

## Before Submitting
- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [ ] I've checked if there was an existing PR that solves the same issue.

2024-08-18 18:02 UTC, karsa-mistmere commented
Some ideas for similar use cases:

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M15+10.2A2.22+2.22+0+0+0+12.8+8q-1.2+0-1.8.9-.6-.9-1.8-.9A2.22+2.22+0+0+0+7+10.2c0+.6.3+1.2.7+1.6A227+227+0+0+0+11+15a404+404+0+0+0+3.3-3.1+2.4+2.4+0+0+0+.7-1.7%22+/%3E%3Cpath+d=%22m21+21-4.3-4.3%22+/%3E%3Ccircle+cx=%2211%22+cy=%2211%22+r=%228%22+/%3E"><img alt="icons" width="400px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTUgMTAuMkEyLjIyIDIuMjIgMCAwIDAgMTIuOCA4cS0xLjIgMC0xLjguOS0uNi0uOS0xLjgtLjlBMi4yMiAyLjIyIDAgMCAwIDcgMTAuMmMwIC42LjMgMS4yLjcgMS42QTIyNyAyMjcgMCAwIDAgMTEgMTVhNDA0IDQwNCAwIDAgMCAzLjMtMy4xIDIuNCAyLjQgMCAwIDAgLjctMS43IiAvPgogIDxwYXRoIGQ9Im0yMSAyMS00LjMtNC4zIiAvPgogIDxjaXJjbGUgY3g9IjExIiBjeT0iMTEiIHI9IjgiIC8+Cjwvc3ZnPg==.svg"/><br/>Open lucide studio</a>

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M21.75+10.089A5.2+5.2+0+0+0+22+8.5+5.5+5.5+0+0+0+16.5+3c-1.76+0-3+.5-4.5+2-1.5-1.5-2.74-2-4.5-2A5.5+5.5+0+0+0+2+8.5c0+2.3+1.5+4.05+3+5.5l7+7+.575-.575%22+/%3E%3Cpath+d=%22m22+20-1.9-1.9%22+/%3E%3Ccircle+cx=%2218%22+cy=%2216%22+r=%223%22+/%3E"><img alt="icons" width="400px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMjEuNzUgMTAuMDg5QTUuMiA1LjIgMCAwIDAgMjIgOC41IDUuNSA1LjUgMCAwIDAgMTYuNSAzYy0xLjc2IDAtMyAuNS00LjUgMi0xLjUtMS41LTIuNzQtMi00LjUtMkE1LjUgNS41IDAgMCAwIDIgOC41YzAgMi4zIDEuNSA0LjA1IDMgNS41bDcgNyAuNTc1LS41NzUiIC8+CiAgPHBhdGggZD0ibTIyIDIwLTEuOS0xLjkiIC8+CiAgPGNpcmNsZSBjeD0iMTgiIGN5PSIxNiIgcj0iMyIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M2.9+11.45c-1.2-1.2-1.14-2.8-.2-3.73a2.4+2.4+0+0+1+3.44+0l.36.34.34-.34a2.4+2.4+0+0+1+3.45-.009c.95.95+1+2.53-.2+3.74L6.5+15z%22+/%3E%3Cpath+d=%22m21+21-4.3-4.3%22+/%3E%3Cpath+d=%22M9.725+3.101A8+8+0+1+1+8.347+18.55%22+/%3E"><img alt="icons" width="400px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMi45IDExLjQ1Yy0xLjItMS4yLTEuMTQtMi44LS4yLTMuNzNhMi40IDIuNCAwIDAgMSAzLjQ0IDBsLjM2LjM0LjM0LS4zNGEyLjQgMi40IDAgMCAxIDMuNDUtLjAwOWMuOTUuOTUgMSAyLjUzLS4yIDMuNzRMNi41IDE1eiIgLz4KICA8cGF0aCBkPSJtMjEgMjEtNC4zLTQuMyIgLz4KICA8cGF0aCBkPSJNOS43MjUgMy4xMDFBOCA4IDAgMSAxIDguMzQ3IDE4LjU1IiAvPgo8L3N2Zz4=.svg"/><br/>Open lucide studio</a>

2024-12-05 09:03 UTC, karsa-mistmere requested changes

2024-12-05 09:03 UTC, karsa-mistmere commented on icons/scan-heart.svg
> +  <path d="M8.203 9.27a2.4 2.4 0 0 1 3.441 0l.36.34.34-.34a2.4 2.4 0 0 1 3.449-.01c.95.95 1 2.53-.2 3.74l-3.59 3.55-3.6-3.55c-1.2-1.2-1.14-2.8-.2-3.73" />
This is off grid, maybe we can adapt the [`heart` from Lucide12](https://lucide-studio.vercel.app/edit?value=%3Csvg+width=%2212%22+height=%2212%22%3E%3Cpath+d=%22M10.324+6.556A2.75+2.75+0+1+0+6+3.168a2.75+2.75+0+1+0-4.324+3.388l3.57+4.1a1+1+0+0+0+1.508.001z%22+/%3E%3C/svg%3E) here?

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M11.246+16.657a1+1+0+0+0+1.508+0l3.57-4.101A2.75+2.75+0+1+0+12+9.168a2.75+2.75+0+1+0-4.324+3.388z%22+/%3E%3Cpath+d=%22M17+3h2a2+2+0+0+1+2+2v2%22+/%3E%3Cpath+d=%22M21+17v2a2+2+0+0+1-2+2h-2%22+/%3E%3Cpath+d=%22M3+7V5a2+2+0+0+1+2-2h2%22+/%3E%3Cpath+d=%22M7+21H5a2+2+0+0+1-2-2v-2%22+/%3E"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTEuMjQ2IDE2LjY1N2ExIDEgMCAwIDAgMS41MDggMGwzLjU3LTQuMTAxQTIuNzUgMi43NSAwIDEgMCAxMiA5LjE2OGEyLjc1IDIuNzUgMCAxIDAtNC4zMjQgMy4zODh6IiAvPgogIDxwYXRoIGQ9Ik0xNyAzaDJhMiAyIDAgMCAxIDIgMnYyIiAvPgogIDxwYXRoIGQ9Ik0yMSAxN3YyYTIgMiAwIDAgMS0yIDJoLTIiIC8+CiAgPHBhdGggZD0iTTMgN1Y1YTIgMiAwIDAgMSAyLTJoMiIgLz4KICA8cGF0aCBkPSJNNyAyMUg1YTIgMiAwIDAgMS0yLTJ2LTIiIC8+Cjwvc3ZnPg==.svg"/><br/>Open lucide studio</a>

2024-12-05 11:51 UTC, ericfennis approved these changes

2024-12-05 11:56 UTC, merged