lucide-react - Generate types for all exported icons
lucide-icons/lucide pull request #243
Opened 2021-02-27 12:39 UTC by FPDK

Solves the React.js part of issue #226 

The types in LucideProps are declared so they match the props mentioned in https://github.com/lucide-icons/lucide/blob/master/packages/lucide-react/README.md#props. They could be removed, since they're already present in SVGAttributes.

2021-02-27 13:03 UTC, ericfennis commented
@FPDK First of all, welcome to the Lucide Community!
Thanks for this PR, looking good. I will test this soon.

Yes partially, only `strokeWidth` could be removed. `color` and `size` are not SVGAttributes, so we need to keep them.

2021-02-27 14:05 UTC, FPDK commented
@ericfennis Thank you for the warm welcome :)

Please ignore commit 1c42b39 in this pull request. I have created a separate pull request for that issue: https://github.com/lucide-icons/lucide/issues/244

2021-03-02 21:19 UTC, ericfennis requested changes
@FPDK Nice work, thanks for your effort! 
I came across some minor improvements we can make. I did also some learnings from other packages. 

The types were working, I had no errors, but when hovering on the icon, the intellisense in my IDE was still saying: `const Icon: any`.

<img src="https://user-images.githubusercontent.com/11825403/109711337-0ba03f80-7b9f-11eb-822d-adffb62e1142.png" width="320">

Also the IDE don't give suggestions:

<img src="https://user-images.githubusercontent.com/11825403/109712540-6f773800-7ba0-11eb-9ba3-4741b26c3e25.png" width="320">

So I try to figure out the problem, and I found out that the FC is breaking the typescript checking. This article makes it clear to me: [typescript-react-why-i-dont-use-react-fc](https://fettblog.eu/typescript-react-why-i-dont-use-react-fc/)

So I made some code suggestions fixing this.

This is the result:
<img src="https://user-images.githubusercontent.com/11825403/109713315-56bb5200-7ba1-11eb-8d75-50a615f5b561.png" width="320">

IDE also hinting props defined in the LucideProps interface

<img src="https://user-images.githubusercontent.com/11825403/109713461-879b8700-7ba1-11eb-8928-1441e2b35b50.png" width="640">

2021-03-06 12:44 UTC, FPDK commented
@ericfennis Thank you for the information and improvements. I'm gonna add React.FC to my naughty list :)

2021-03-08 13:19 UTC, ericfennis commented
@FPDK Can you also move the `build-types.js` to the `scripts` folder?

`packages/lucide-react/build-types.js` ➡️ `packages/lucide-react/scripts/build-types.js`

2021-03-17 19:35 UTC, ericfennis commented
@FPDK I will merge this, and finish this. I want add to this in the next release.

Thanks for your contribution!

2021-03-17 19:35 UTC, merged

2021-03-18 14:30 UTC, FPDK commented
@ericfennis sorry for not answering, glad you could finish it :)