file-input and file-output
lucide-icons/lucide pull request #251
Opened 2021-03-04 17:39 UTC by Andreto

![image](https://user-images.githubusercontent.com/28541538/110005520-dd466f80-7d18-11eb-9732-2606814576a4.png)
100%
![image](https://user-images.githubusercontent.com/28541538/110005554-e8999b00-7d18-11eb-99dc-b9f768f86a6d.png)

2021-03-07 08:12 UTC, locness3 commented
why not

2021-03-13 21:07 UTC, ericfennis requested changes
Code formatting

2021-03-13 21:07 UTC, ericfennis commented on icons/file-output.svg
> +  <path d="M5 12l-3 3 3 3"></path>
```suggestion
  <path d="M4 22h14a2 2 0 002-2V7.5L14.5 2H6a2 2 0 00-2 2v4" />
  <path d="M14 2v6h6" />
  <path d="M2 15l10-0" />
  <path d="M5 12l-3 3 3 3" />
```

2021-03-13 21:07 UTC, ericfennis commented on icons/file-input.svg
> +  <path d="M9 18l3-3-3-3"></path>
```suggestion
  <path d="M4 22h14a2 2 0 002-2V7.5L14.5 2H6a2 2 0 00-2 2v4" />
  <path d="M14 2v6h6" />
  <path d="M2 15l10-0" />
  <path d="M9 18l3-3-3-3" />
```

2021-03-16 20:14 UTC, merged