fix(icons): changed `shovel` icon
lucide-icons/lucide pull request #2547
Opened 2024-10-21 20:02 UTC by jguddas

## What is the purpose of this pull request?
- [x] Other: Icon update

### Description
Changed size and arcified corners.

## Before Submitting
- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [ ] I've checked if there was an existing PR that solves the same issue.

2024-10-25 09:19 UTC, jamiemlaw commented
Looks a bit off-grid to me, especially that left edge, but also some of the arcs. How about something like:

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M15.914+8.086+9.5+14.5%22+/%3E%3Cpath+d=%22M17.293+2.293a1+1+0+0+1+1.414+0l3+3a1+1+0+0+1+0+1.414l-1.379+1.379a1+1+0+0+1-4.414-4.414z%22+/%3E%3Cpath+d=%22M2+17a2+2+0+0+1+.586-1.414l3.293-3.293a1+1+0+0+1+1.414+0l4.414+4.414a1+1+0+0+1+0+1.414l-3.293+3.293A2+2+0+0+1+7+22H5a3+3+0+0+1-3-3z%22+/%3E"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTUuOTE0IDguMDg2IDkuNSAxNC41IiAvPgogIDxwYXRoIGQ9Ik0xNy4yOTMgMi4yOTNhMSAxIDAgMCAxIDEuNDE0IDBsMyAzYTEgMSAwIDAgMSAwIDEuNDE0bC0xLjM3OSAxLjM3OWExIDEgMCAwIDEtNC40MTQtNC40MTR6IiAvPgogIDxwYXRoIGQ9Ik0yIDE3YTIgMiAwIDAgMSAuNTg2LTEuNDE0bDMuMjkzLTMuMjkzYTEgMSAwIDAgMSAxLjQxNCAwbDQuNDE0IDQuNDE0YTEgMSAwIDAgMSAwIDEuNDE0bC0zLjI5MyAzLjI5M0EyIDIgMCAwIDEgNyAyMkg1YTMgMyAwIDAgMS0zLTN6IiAvPgo8L3N2Zz4=.svg"/><br/>Open lucide studio</a>

45&deg; lines are always a pain, because you have to decide whether you want the lines themselves to follow the pixel grid, or have the arcs sit on pixel boundaries, but you can't have both.

2024-10-25 12:11 UTC, jguddas commented
> 45° lines are always a pain, because you have to decide whether you want the lines themselves to follow the pixel grid, or have the arcs sit on pixel boundaries, but you can't have both.

We should come to an agreement and maybe even update the guidelines about this.

2024-10-25 12:18 UTC, karsa-mistmere commented
> > 45° lines are always a pain, because you have to decide whether you want the lines themselves to follow the pixel grid, or have the arcs sit on pixel boundaries, but you can't have both.
> 
> We should come to an agreement and maybe even update the guidelines about this.

It's the diagonal lines that should be pixel perfect without the shadow of a doubt, arcs will be somewhat blurry anyway.

E.g. perfectly grid-aligned lines vs. perfectly grid-aligned corners:

<img width="991" alt="image" src="https://github.com/user-attachments/assets/721624d8-3e78-4de5-8b74-8a1ac06b2799">


I rest my case :)

2024-10-25 12:24 UTC, jguddas commented
> > > 45° lines are always a pain, because you have to decide whether you want the lines themselves to follow the pixel grid, or have the arcs sit on pixel boundaries, but you can't have both.
> > 
> > 
> > We should come to an agreement and maybe even update the guidelines about this.
> 
> It's the diagonal lines that should be pixel perfect without the shadow of a doubt, arcs will be somewhat blurry anyway.
> 
> E.g. perfectly grid-aligned lines vs. perfectly grid-aligned corners:
> 
> <img alt="image" width="991" src="https://private-user-images.githubusercontent.com/17746067/380155895-721624d8-3e78-4de5-8b74-8a1ac06b2799.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTkzNTQsIm5iZiI6MTcyOTg1OTA1NCwicGF0aCI6Ii8xNzc0NjA2Ny8zODAxNTU4OTUtNzIxNjI0ZDgtM2U3OC00ZGU1LThiNzQtOGExYWMwNmIyNzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDEyMjQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmNGU4MjdjN2YxYzk2MTE5Mjg1MDM4MWM4M2U1OWJmZmJkZGE1YzhjMDkwNDM2MDgxNmIyMTk2MDE1MThiMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rluocyglfRZ0R3A5Ypc8TmivgIPjYV8KAizN5tR46wY">
> I rest my case :)

Hard to argue 👍

2024-10-25 12:39 UTC, jamiemlaw commented
As a corollary of that, I've found when connective two 45&deg; lines with an arc, a radius of a 2.414 (right) looks better to me than exactly 2 (left).

![image](https://github.com/user-attachments/assets/df070671-5ff1-4bd6-9b5b-6ae489be0a7e)

2024-10-25 12:59 UTC, jguddas commented
> As a corollary of that, I've found when connective two 45° lines with an arc, a radius of a 2.414 (right) looks better to me than exactly 2 (left).
> 
> ![image](https://private-user-images.githubusercontent.com/956081/380160656-df070671-5ff1-4bd6-9b5b-6ae489be0a7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NjE0MDUsIm5iZiI6MTcyOTg2MTEwNSwicGF0aCI6Ii85NTYwODEvMzgwMTYwNjU2LWRmMDcwNjcxLTVmZjEtNGJkNi05YjViLTZhZTQ4OWJlMGE3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxMjU4MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjIzMjQ3YmM0OGZmMTk4NWI3NzU0MWUwMjQ4ODQxNTFjZTY5NGM1ZDI5MzI1MTVmYWUzZjU0MDEzMDAyMmJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mh-voETTNQMN8p5LFWxQFkUlIEwlteMdG6ZYbff-zdk)

We also talked about this but kinda gave up on it, it would be a huge change, the 2px rule is also kinda what lucide is.

2024-12-05 11:55 UTC, ericfennis approved these changes

2025-01-06 09:03 UTC, karsa-mistmere requested changes

2025-01-06 09:03 UTC, karsa-mistmere commented on icons/shovel.svg
> +  <path d="M16.293 2.707a1 1 0 0 1 1.414 0l3.586 3.586a1 1 0 0 1 0 1.414 1 1 0 1 1-5-5" />
I think something like this is more in line with pencil etc.

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M16.982+2.278a1+1+0+0+1+1.34+0l3.4+3.4a1+1+0+0+1+0+1.34A3.4+3.4+0+0+1+16+4.648a3.4+3.4+0+0+1+.982-2.37%22+/%3E%3Cpath+d=%22M2+21a1+1+0+0+0+1+1h3.172a2+2+0+0+0+1.414-.586l3.707-3.707a1+1+0+0+0+0-1.414l-3.586-3.586a1+1+0+0+0-1.414+0l-3.707+3.707A2+2+0+0+0+2+17.828z%22+/%3E%3Cpath+d=%22m9.5+14.5+7.482-7.482%22+/%3E&name=hand&base=hand"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTYuOTgyIDIuMjc4YTEgMSAwIDAgMSAxLjM0IDBsMy40IDMuNGExIDEgMCAwIDEgMCAxLjM0QTMuNCAzLjQgMCAwIDEgMTYgNC42NDhhMy40IDMuNCAwIDAgMSAuOTgyLTIuMzciIC8+CiAgPHBhdGggZD0iTTIgMjFhMSAxIDAgMCAwIDEgMWgzLjE3MmEyIDIgMCAwIDAgMS40MTQtLjU4NmwzLjcwNy0zLjcwN2ExIDEgMCAwIDAgMC0xLjQxNGwtMy41ODYtMy41ODZhMSAxIDAgMCAwLTEuNDE0IDBsLTMuNzA3IDMuNzA3QTIgMiAwIDAgMCAyIDE3LjgyOHoiIC8+CiAgPHBhdGggZD0ibTkuNSAxNC41IDcuNDgyLTcuNDgyIiAvPgo8L3N2Zz4=.svg"/><br/>Open lucide studio</a>

2025-04-21 08:17 UTC, ericfennis approved these changes

2025-04-21 09:37 UTC, karsa-mistmere commented
Can't these be a single arc?

![IMG_5764](https://github.com/user-attachments/assets/0e33b605-0020-4be6-9d54-c49696088249)

2025-07-29 07:27 UTC, ericfennis commented
Closed by #3458

2025-07-29 07:27 UTC, closed without merging

2025-07-29 07:37 UTC, karsa-mistmere commented
> Closed by #3458

Ouch, I didn't even remember there already was a PR about this. 🫣