feat(icons): added `calendar-sync` icon
lucide-icons/lucide pull request #2590
Opened 2024-11-08 08:46 UTC by chessurisme

close #2071
## What is the purpose of this pull request?
- [x] New Icon

### Description
Added new `calendar-sync` icon.

### Icon use case

Here are some more use cases:

- Cron jobs scheduling: This could be scheduling a recurring job to handle invalid urls in database.
Recurring Events or Limited time offers or promotions: This could be a flash sale, a seasonal promotion, or a free trial offer.
- Tasks or reminders that need to be repeated: This could be taking medication, watering plants, or walking the dog.
- Loan auto periodic payment This could be for handling loan installments as reminder or auto.

### Alternative icon designs

## Icon Design Checklist

### Concept

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [ ] The icons are solely my own creation.
- [x] The icons were originally created in #<issueNumber> by @danielbayley
- [x] I've based them on the following Lucide icons: `folder-sync`, `calendar-heart`
- [ ] I've based them on the following design: 

### Naming

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to three points of precision.

## Before Submitting
- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

2024-11-08 08:47 UTC, chessurisme commented
Everytime I pushed I have this annoying four first commits. I need to troubleshoot.

2024-11-08 08:58 UTC, jguddas commented
> Everytime I pushed I have this annoying four first commits. I need to troubleshoot.

You just have random stuff in your main branch, just have to force remove it to be the same as the lucide branch.

2024-11-09 20:12 UTC, jguddas requested changes
Has box-select removed in the PR.

2024-11-09 23:35 UTC, chessurisme commented
it is already removed

2024-11-10 08:51 UTC, karsa-mistmere commented
The sync arrows are .5px off grid vertically.

2024-11-10 22:31 UTC, chessurisme commented
> The sync arrows are .5px off grid vertically.

Already fixed!

2024-11-18 11:05 UTC, chessurisme commented
Time to go! 🚀

2024-11-18 11:11 UTC, jguddas requested changes

2024-11-18 11:11 UTC, jguddas commented on icons/calendar-sync.svg
> +  <path d="M21 7.5V6a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h3.5" />
```suggestion
  <path d="M21 8.5V6a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h5" />
```

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M12+10.5v4h4%22+/%3E%3Cpath+d=%22m12+14.5+1.535-1.605a5+5+0+0+1+8+1.5%22+/%3E%3Cpath+d=%22M16+2v4%22+/%3E%3Cpath+d=%22M21+8.5V6a2+2+0+0+0-2-2H5a2+2+0+0+0-2+2v14a2+2+0+0+0+2+2h5%22+/%3E%3Cpath+d=%22m22+18.5-1.535+1.605a5+5+0+0+1-8-1.5%22+/%3E%3Cpath+d=%22M22+22v-4h-4%22+/%3E%3Cpath+d=%22M3+10h5%22+/%3E%3Cpath+d=%22M8+2v4%22+/%3E"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTIgMTAuNXY0aDQiIC8+CiAgPHBhdGggZD0ibTEyIDE0LjUgMS41MzUtMS42MDVhNSA1IDAgMCAxIDggMS41IiAvPgogIDxwYXRoIGQ9Ik0xNiAydjQiIC8+CiAgPHBhdGggZD0iTTIxIDguNVY2YTIgMiAwIDAgMC0yLTJINWEyIDIgMCAwIDAtMiAydjE0YTIgMiAwIDAgMCAyIDJoNSIgLz4KICA8cGF0aCBkPSJtMjIgMTguNS0xLjUzNSAxLjYwNWE1IDUgMCAwIDEtOC0xLjUiIC8+CiAgPHBhdGggZD0iTTIyIDIydi00aC00IiAvPgogIDxwYXRoIGQ9Ik0zIDEwaDUiIC8+CiAgPHBhdGggZD0iTTggMnY0IiAvPgo8L3N2Zz4=.svg"/><br/>Open lucide studio</a>

2024-11-19 12:33 UTC, jguddas requested changes
The refresh icon has a 2px gap violation and is not sympathetical

2024-11-19 12:55 UTC, chessurisme commented
How about this:
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M11+10.5v4h4%22+/%3E%3Cpath+d=%22m11+14.5+1.535-1.605a5+5+0+0+1+8+1.5%22+/%3E%3Cpath+d=%22M16+2v4%22+/%3E%3Cpath+d=%22m21+18.5-1.535+1.605a5+5+0+0+1-8-1.5%22+/%3E%3Cpath+d=%22M21+22v-4h-4%22+/%3E%3Cpath+d=%22M21+9V6a2+2+0+0+0-2-2H5a2+2+0+0+0-2+2v14a2+2+0+0+0+2+2h4%22+/%3E%3Cpath+d=%22M3+10h4%22+/%3E%3Cpath+d=%22M8+2v4%22+/%3E"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTEgMTAuNXY0aDQiIC8+CiAgPHBhdGggZD0ibTExIDE0LjUgMS41MzUtMS42MDVhNSA1IDAgMCAxIDggMS41IiAvPgogIDxwYXRoIGQ9Ik0xNiAydjQiIC8+CiAgPHBhdGggZD0ibTIxIDE4LjUtMS41MzUgMS42MDVhNSA1IDAgMCAxLTgtMS41IiAvPgogIDxwYXRoIGQ9Ik0yMSAyMnYtNGgtNCIgLz4KICA8cGF0aCBkPSJNMjEgOVY2YTIgMiAwIDAgMC0yLTJINWEyIDIgMCAwIDAtMiAydjE0YTIgMiAwIDAgMCAyIDJoNCIgLz4KICA8cGF0aCBkPSJNMyAxMGg0IiAvPgogIDxwYXRoIGQ9Ik04IDJ2NCIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>

2024-11-19 13:02 UTC, jguddas commented
> How about this, I moved the refresh icon so there will be 2px on each sides: [<img alt="icons" width="200px" src="https://camo.githubusercontent.com/1f123ca3b39092d61ce8ce4466c2bf12fbf4452aee63e16b78c1de5afdf0ff46/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a776f67494868746247357a50534a6f644852774f693876643364334c6e637a4c6d39795a7938794d4441774c334e325a79494b4943423361575230614430694d6a516943694167614756705a326830505349794e43494b4943423261575633516d393450534977494441674d6a51674d6a5169436941675a6d6c7362443069626d39755a53494b4943427a64484a7661325539496d4e31636e4a6c626e5244623278766369494b4943427a64484a766132557464326c6b64476739496a496943694167633352796232746c4c577870626d566a59584139496e4a766457356b49676f6749484e30636d39725a5331736157356c616d3970626a3069636d3931626d5169436a344b49434138634746306143426b50534a4e4d5445674d5442324e4767304969417650676f67494478775958526f49475139496d30784d5341784e4341784c6a557a4e5330784c6a59774e574531494455674d434177494445674f4341784c6a55694943382b4369416750484268644767675a4430695454453249444a324e4349674c7a344b49434138634746306143426b50534a744d6a45674d5467744d5334314d7a55674d5334324d4456684e534131494441674d4341784c5467744d5334314969417650676f67494478775958526f49475139496b30794d5341794d6e59744e4767744e4349674c7a344b49434138634746306143426b50534a4e4d6a45674f433431566a5a684d694179494441674d4341774c5449744d6b6731595449674d694177494441674d43307949444a324d5452684d694179494441674d434177494449674d6d67304969417650676f67494478775958526f49475139496b307a49444577614451694943382b4369416750484268644767675a443069545467674d6e59304969417650676f384c334e325a7a343d2e737667">Open lucide studio](https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M11+10v4h4%22+/%3E%3Cpath+d=%22m11+14+1.535-1.605a5+5+0+0+1+8+1.5%22+/%3E%3Cpath+d=%22M16+2v4%22+/%3E%3Cpath+d=%22m21+18-1.535+1.605a5+5+0+0+1-8-1.5%22+/%3E%3Cpath+d=%22M21+22v-4h-4%22+/%3E%3Cpath+d=%22M21+8.5V6a2+2+0+0+0-2-2H5a2+2+0+0+0-2+2v14a2+2+0+0+0+2+2h4%22+/%3E%3Cpath+d=%22M3+10h4%22+/%3E%3Cpath+d=%22M8+2v4%22+/%3E)

That looks pretty good, we should closed the gap at the bottom like this:

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M11+10v4h4%22+/%3E%3Cpath+d=%22m11+14+1.535-1.605a5+5+0+0+1+8+1.5%22+/%3E%3Cpath+d=%22M16+2v4%22+/%3E%3Cpath+d=%22m21+18-1.535+1.605a5+5+0+0+1-8-1.5%22+/%3E%3Cpath+d=%22M21+22v-4h-4%22+/%3E%3Cpath+d=%22M21+8.5V6a2+2+0+0+0-2-2H5a2+2+0+0+0-2+2v14a2+2+0+0+0+2+2h4.3%22+/%3E%3Cpath+d=%22M3+10h4%22+/%3E%3Cpath+d=%22M8+2v4%22+/%3E"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTEgMTB2NGg0IiAvPgogIDxwYXRoIGQ9Im0xMSAxNCAxLjUzNS0xLjYwNWE1IDUgMCAwIDEgOCAxLjUiIC8+CiAgPHBhdGggZD0iTTE2IDJ2NCIgLz4KICA8cGF0aCBkPSJtMjEgMTgtMS41MzUgMS42MDVhNSA1IDAgMCAxLTgtMS41IiAvPgogIDxwYXRoIGQ9Ik0yMSAyMnYtNGgtNCIgLz4KICA8cGF0aCBkPSJNMjEgOC41VjZhMiAyIDAgMCAwLTItMkg1YTIgMiAwIDAgMC0yIDJ2MTRhMiAyIDAgMCAwIDIgMmg0LjMiIC8+CiAgPHBhdGggZD0iTTMgMTBoNCIgLz4KICA8cGF0aCBkPSJNOCAydjQiIC8+Cjwvc3ZnPg==.svg"/><br/>Open lucide studio</a>

2024-11-19 13:02 UTC, chessurisme commented
I also think about that...

2024-11-19 13:15 UTC, jguddas approved these changes

2024-11-25 18:56 UTC, ericfennis approved these changes

2024-11-25 18:56 UTC, merged