feat(icons): added `shield-user` icon
lucide-icons/lucide pull request #2608
Opened 2024-11-12 14:57 UTC by sebinemeth

## What is the purpose of this pull request?
- [x] New Icon

### Description
Added new `shield-user` icon.

### Icon use case

Access to admin area, mark user as admin/elevated access rights

### Alternative icon designs

## Icon Design Checklist

### Concept

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [ ] The icons are solely my own creation.
- [x] The icons were originally created in #2600 by @sebinemeth
- [x] I've based them on the following Lucide icons: `shield`, `user`
- [ ] I've based them on the following design: 

### Naming

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to three points of precision.

## Before Submitting
- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

2024-12-13 09:07 UTC, karsa-mistmere approved these changes

2024-12-13 09:58 UTC, jguddas commented
I would prefer something like this
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M17.116+19a6+6+0+0+0-10.402+0%22+/%3E%3Cpath+d=%22M20+13c0+5-3.5+7.5-7.66+8.95a1+1+0+0+1-.67-.01C7.5+20.5+4+18+4+13V6a1+1+0+0+1+1-1c2+0+4.5-1.2+6.24-2.72a1.17+1.17+0+0+1+1.52+0C14.51+3.81+17+5+19+5a1+1+0+0+1+1+1z%22+/%3E%3Ccircle+cx=%2212%22+cy=%2212%22+r=%224%22+/%3E&name=contact-round"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTcuMTE2IDE5YTYgNiAwIDAgMC0xMC40MDIgMCIgLz4KICA8cGF0aCBkPSJNMjAgMTNjMCA1LTMuNSA3LjUtNy42NiA4Ljk1YTEgMSAwIDAgMS0uNjctLjAxQzcuNSAyMC41IDQgMTggNCAxM1Y2YTEgMSAwIDAgMSAxLTFjMiAwIDQuNS0xLjIgNi4yNC0yLjcyYTEuMTcgMS4xNyAwIDAgMSAxLjUyIDBDMTQuNTEgMy44MSAxNyA1IDE5IDVhMSAxIDAgMCAxIDEgMXoiIC8+CiAgPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iNCIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>

2024-12-13 10:23 UTC, karsa-mistmere commented
> I would prefer something like this [<img alt="icons" width="200px" src="https://camo.githubusercontent.com/67bb2461125c31eac869c9b6532646001c5bedc978c263f9c1ae881e5677e20f/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a776f67494868746247357a50534a6f644852774f693876643364334c6e637a4c6d39795a7938794d4441774c334e325a79494b4943423361575230614430694d6a516943694167614756705a326830505349794e43494b4943423261575633516d393450534977494441674d6a51674d6a5169436941675a6d6c7362443069626d39755a53494b4943427a64484a7661325539496d4e31636e4a6c626e5244623278766369494b4943427a64484a766132557464326c6b64476739496a496943694167633352796232746c4c577870626d566a59584139496e4a766457356b49676f6749484e30636d39725a5331736157356c616d3970626a3069636d3931626d5169436a344b49434138634746306143426b50534a4e4d5463754d54453249444535595459674e694177494441674d4330784d4334304d4449674d4349674c7a344b49434138634746306143426b50534a4e4d6a41674d544e6a4d4341314c544d754e5341334c6a55744e7934324e6941344c6a6b31595445674d534177494441674d5330754e6a63744c6a4178517a63754e5341794d433431494451674d5467674e4341784d315932595445674d534177494441674d5341784c54466a4d694177494451754e5330784c6a49674e6934794e4330794c6a6379595445754d5463674d5334784e794177494441674d5341784c6a5579494442444d5451754e5445674d7934344d5341784e79413149444535494456684d534178494441674d434178494445674d586f694943382b4369416750474e70636d4e735a53426a654430694d54496949474e35505349784d694967636a30694e4349674c7a344b5043397a646d632b2e737667">Open lucide studio](https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M17.116+19a6+6+0+0+0-10.402+0%22+/%3E%3Cpath+d=%22M20+13c0+5-3.5+7.5-7.66+8.95a1+1+0+0+1-.67-.01C7.5+20.5+4+18+4+13V6a1+1+0+0+1+1-1c2+0+4.5-1.2+6.24-2.72a1.17+1.17+0+0+1+1.52+0C14.51+3.81+17+5+19+5a1+1+0+0+1+1+1z%22+/%3E%3Ccircle+cx=%2212%22+cy=%2212%22+r=%224%22+/%3E&name=contact-round)

Feels a bit imbalanced, maybe a smaller user would be more appropriate:

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M17+19.478V19a5+5+0+0+0-10+0l.004.478%22+/%3E%3Cpath+d=%22M20+13c0+5-3.5+7.5-7.66+8.95a1+1+0+0+1-.67-.01C7.5+20.5+4+18+4+13V6a1+1+0+0+1+1-1c2+0+4.5-1.2+6.24-2.72a1.17+1.17+0+0+1+1.52+0C14.51+3.81+17+5+19+5a1+1+0+0+1+1+1z%22+/%3E%3Ccircle+cx=%2212%22+cy=%2211%22+r=%223%22+/%3E&name=square-user-round"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTcgMTkuNDc4VjE5YTUgNSAwIDAgMC0xMCAwbC4wMDQuNDc4IiAvPgogIDxwYXRoIGQ9Ik0yMCAxM2MwIDUtMy41IDcuNS03LjY2IDguOTVhMSAxIDAgMCAxLS42Ny0uMDFDNy41IDIwLjUgNCAxOCA0IDEzVjZhMSAxIDAgMCAxIDEtMWMyIDAgNC41LTEuMiA2LjI0LTIuNzJhMS4xNyAxLjE3IDAgMCAxIDEuNTIgMEMxNC41MSAzLjgxIDE3IDUgMTkgNWExIDEgMCAwIDEgMSAxeiIgLz4KICA8Y2lyY2xlIGN4PSIxMiIgY3k9IjExIiByPSIzIiAvPgo8L3N2Zz4=.svg"/><br/>Open lucide studio</a>

2024-12-13 10:47 UTC, jguddas commented
> > I would prefer something like this [<img alt="icons" width="200px" src="https://camo.githubusercontent.com/67bb2461125c31eac869c9b6532646001c5bedc978c263f9c1ae881e5677e20f/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a776f67494868746247357a50534a6f644852774f693876643364334c6e637a4c6d39795a7938794d4441774c334e325a79494b4943423361575230614430694d6a516943694167614756705a326830505349794e43494b4943423261575633516d393450534977494441674d6a51674d6a5169436941675a6d6c7362443069626d39755a53494b4943427a64484a7661325539496d4e31636e4a6c626e5244623278766369494b4943427a64484a766132557464326c6b64476739496a496943694167633352796232746c4c577870626d566a59584139496e4a766457356b49676f6749484e30636d39725a5331736157356c616d3970626a3069636d3931626d5169436a344b49434138634746306143426b50534a4e4d5463754d54453249444535595459674e694177494441674d4330784d4334304d4449674d4349674c7a344b49434138634746306143426b50534a4e4d6a41674d544e6a4d4341314c544d754e5341334c6a55744e7934324e6941344c6a6b31595445674d534177494441674d5330754e6a63744c6a4178517a63754e5341794d433431494451674d5467674e4341784d315932595445674d534177494441674d5341784c54466a4d694177494451754e5330784c6a49674e6934794e4330794c6a6379595445754d5463674d5334784e794177494441674d5341784c6a5579494442444d5451754e5445674d7934344d5341784e79413149444535494456684d534178494441674d434178494445674d586f694943382b4369416750474e70636d4e735a53426a654430694d54496949474e35505349784d694967636a30694e4349674c7a344b5043397a646d632b2e737667">Open lucide studio](https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M17.116+19a6+6+0+0+0-10.402+0%22+/%3E%3Cpath+d=%22M20+13c0+5-3.5+7.5-7.66+8.95a1+1+0+0+1-.67-.01C7.5+20.5+4+18+4+13V6a1+1+0+0+1+1-1c2+0+4.5-1.2+6.24-2.72a1.17+1.17+0+0+1+1.52+0C14.51+3.81+17+5+19+5a1+1+0+0+1+1+1z%22+/%3E%3Ccircle+cx=%2212%22+cy=%2212%22+r=%224%22+/%3E&name=contact-round)
> 
> Feels a bit imbalanced, maybe a smaller user would be more appropriate:
> 
> [<img alt="icons" width="200px" src="https://camo.githubusercontent.com/282ef298d1819062e2feca07db89cfb7c120f8aa52a4bd23072768d7322ef26a/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a776f67494868746247357a50534a6f644852774f693876643364334c6e637a4c6d39795a7938794d4441774c334e325a79494b4943423361575230614430694d6a516943694167614756705a326830505349794e43494b4943423261575633516d393450534977494441674d6a51674d6a5169436941675a6d6c7362443069626d39755a53494b4943427a64484a7661325539496d4e31636e4a6c626e5244623278766369494b4943427a64484a766132557464326c6b64476739496a496943694167633352796232746c4c577870626d566a59584139496e4a766457356b49676f6749484e30636d39725a5331736157356c616d3970626a3069636d3931626d5169436a344b49434138634746306143426b50534a4e4d5463674d546b754e446334566a4535595455674e534177494441674d4330784d434177624334774d4451754e4463344969417650676f67494478775958526f49475139496b30794d4341784d324d77494455744d793431494463754e5330334c6a5932494467754f5456684d534178494441674d4341784c5334324e7930754d4446444e793431494449774c6a55674e4341784f4341304944457a566a5a684d534178494441674d434178494445744d574d79494441674e4334314c5445754d6941324c6a49304c5449754e7a4a684d5334784e7941784c6a4533494441674d434178494445754e5449674d454d784e4334314d53417a4c6a677849444533494455674d546b674e574578494445674d434177494445674d534178656949674c7a344b4943413859326c795932786c49474e34505349784d69496759336b39496a4578496942795053497a4969417650676f384c334e325a7a343d2e737667">Open lucide studio](https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M17+19.478V19a5+5+0+0+0-10+0l.004.478%22+/%3E%3Cpath+d=%22M20+13c0+5-3.5+7.5-7.66+8.95a1+1+0+0+1-.67-.01C7.5+20.5+4+18+4+13V6a1+1+0+0+1+1-1c2+0+4.5-1.2+6.24-2.72a1.17+1.17+0+0+1+1.52+0C14.51+3.81+17+5+19+5a1+1+0+0+1+1+1z%22+/%3E%3Ccircle+cx=%2212%22+cy=%2211%22+r=%223%22+/%3E&name=square-user-round)

My version is from the `contact-round`, and is consistend with `circle-user` and `square-user`.
So my vote is for my version, for consistency.

2024-12-13 11:12 UTC, karsa-mistmere commented
> My version is from the `contact-round`, and is consistend with `circle-user` and `square-user`. So my vote is for my version, for consistency.

It's not entirely consistent though, since the user shape is 1px lower than in case of `circle/square-user`.

I feel like even with the minor gap guideline violation this one feels better because it's much less bottom-heavy:

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M17.116+18a6+6+0+0+0-10.402+0%22+/%3E%3Cpath+d=%22M20+13c0+5-3.5+7.5-7.66+8.95a1+1+0+0+1-.67-.01C7.5+20.5+4+18+4+13V6a1+1+0+0+1+1-1c2+0+4.5-1.2+6.24-2.72a1.17+1.17+0+0+1+1.52+0C14.51+3.81+17+5+19+5a1+1+0+0+1+1+1z%22+/%3E%3Ccircle+cx=%2212%22+cy=%2211%22+r=%224%22+/%3E"><img alt="icons" width="400px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTcuMTE2IDE4YTYgNiAwIDAgMC0xMC40MDIgMCIgLz4KICA8cGF0aCBkPSJNMjAgMTNjMCA1LTMuNSA3LjUtNy42NiA4Ljk1YTEgMSAwIDAgMS0uNjctLjAxQzcuNSAyMC41IDQgMTggNCAxM1Y2YTEgMSAwIDAgMSAxLTFjMiAwIDQuNS0xLjIgNi4yNC0yLjcyYTEuMTcgMS4xNyAwIDAgMSAxLjUyIDBDMTQuNTEgMy44MSAxNyA1IDE5IDVhMSAxIDAgMCAxIDEgMXoiIC8+CiAgPGNpcmNsZSBjeD0iMTIiIGN5PSIxMSIgcj0iNCIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>

2024-12-13 11:45 UTC, jguddas commented
> > My version is from the `contact-round`, and is consistend with `circle-user` and `square-user`. So my vote is for my version, for consistency.
> 
> It's not entirely consistent though, since the user shape is 1px lower than in case of `circle/square-user`.
> 
> I feel like even with the minor gap guideline violation this one feels better because it's much less bottom-heavy:
> 
> ![image](https://private-user-images.githubusercontent.com/17746067/395539358-72dcd889-e2fd-4a65-b63f-3cdf29e217ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwOTA1NzksIm5iZiI6MTczNDA5MDI3OSwicGF0aCI6Ii8xNzc0NjA2Ny8zOTU1MzkzNTgtNzJkY2Q4ODktZTJmZC00YTY1LWI2M2YtM2NkZjI5ZTIxN2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDExNDQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZWI2Y2NlZjRlYjRhOTE4NDQ5YzU3MjNhMDJiMTY0MTI2MGE5OTU4MDI4YWVlNTcxZGFhM2E5NGE0NmYyMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1tMNu1DZMb-1ycbPZsMheUTBH1h7m5BgMD-jXyEqVn0)
> 
> [<img alt="icons" width="400px" src="https://camo.githubusercontent.com/5d1b49ad262869acf9fac7e7e16e3673b547f87c567c88d87399a734e01008ba/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a776f67494868746247357a50534a6f644852774f693876643364334c6e637a4c6d39795a7938794d4441774c334e325a79494b4943423361575230614430694d6a516943694167614756705a326830505349794e43494b4943423261575633516d393450534977494441674d6a51674d6a5169436941675a6d6c7362443069626d39755a53494b4943427a64484a7661325539496d4e31636e4a6c626e5244623278766369494b4943427a64484a766132557464326c6b64476739496a496943694167633352796232746c4c577870626d566a59584139496e4a766457356b49676f6749484e30636d39725a5331736157356c616d3970626a3069636d3931626d5169436a344b49434138634746306143426b50534a4e4d5463754d54453249444534595459674e694177494441674d4330784d4334304d4449674d4349674c7a344b49434138634746306143426b50534a4e4d6a41674d544e6a4d4341314c544d754e5341334c6a55744e7934324e6941344c6a6b31595445674d534177494441674d5330754e6a63744c6a4178517a63754e5341794d433431494451674d5467674e4341784d315932595445674d534177494441674d5341784c54466a4d694177494451754e5330784c6a49674e6934794e4330794c6a6379595445754d5463674d5334784e794177494441674d5341784c6a5579494442444d5451754e5445674d7934344d5341784e79413149444535494456684d534178494441674d434178494445674d586f694943382b4369416750474e70636d4e735a53426a654430694d54496949474e35505349784d534967636a30694e4349674c7a344b5043397a646d632b2e737667">Open lucide studio](https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M17.116+18a6+6+0+0+0-10.402+0%22+/%3E%3Cpath+d=%22M20+13c0+5-3.5+7.5-7.66+8.95a1+1+0+0+1-.67-.01C7.5+20.5+4+18+4+13V6a1+1+0+0+1+1-1c2+0+4.5-1.2+6.24-2.72a1.17+1.17+0+0+1+1.52+0C14.51+3.81+17+5+19+5a1+1+0+0+1+1+1z%22+/%3E%3Ccircle+cx=%2212%22+cy=%2211%22+r=%224%22+/%3E)

I'm up for this, even with the gap violation, looks nice.

2024-12-18 09:55 UTC, sebinemeth commented
> > My version is from the `contact-round`, and is consistend with `circle-user` and `square-user`. So my vote is for my version, for consistency.
> 
> It's not entirely consistent though, since the user shape is 1px lower than in case of `circle/square-user`.
> 
> I feel like even with the minor gap guideline violation this one feels better because it's much less bottom-heavy:
> 
> ![image](https://private-user-images.githubusercontent.com/17746067/395539358-72dcd889-e2fd-4a65-b63f-3cdf29e217ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MTU5MDUsIm5iZiI6MTczNDUxNTYwNSwicGF0aCI6Ii8xNzc0NjA2Ny8zOTU1MzkzNTgtNzJkY2Q4ODktZTJmZC00YTY1LWI2M2YtM2NkZjI5ZTIxN2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA5NTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5ZGM5M2Y1OTZiYzAxMjQ2YzVhMWJlY2Q2MDVlMDc0MjZmMTBkNjI1YzNhODNkYjcwMzE0ODEwZTNhMGIwNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZMF9UKnyfdf7lj5ws1FUG_aQTT3qrslNf7Ofvqsok1Y)
> 
> [<img alt="icons" width="400px" src="https://camo.githubusercontent.com/5d1b49ad262869acf9fac7e7e16e3673b547f87c567c88d87399a734e01008ba/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a776f67494868746247357a50534a6f644852774f693876643364334c6e637a4c6d39795a7938794d4441774c334e325a79494b4943423361575230614430694d6a516943694167614756705a326830505349794e43494b4943423261575633516d393450534977494441674d6a51674d6a5169436941675a6d6c7362443069626d39755a53494b4943427a64484a7661325539496d4e31636e4a6c626e5244623278766369494b4943427a64484a766132557464326c6b64476739496a496943694167633352796232746c4c577870626d566a59584139496e4a766457356b49676f6749484e30636d39725a5331736157356c616d3970626a3069636d3931626d5169436a344b49434138634746306143426b50534a4e4d5463754d54453249444534595459674e694177494441674d4330784d4334304d4449674d4349674c7a344b49434138634746306143426b50534a4e4d6a41674d544e6a4d4341314c544d754e5341334c6a55744e7934324e6941344c6a6b31595445674d534177494441674d5330754e6a63744c6a4178517a63754e5341794d433431494451674d5467674e4341784d315932595445674d534177494441674d5341784c54466a4d694177494451754e5330784c6a49674e6934794e4330794c6a6379595445754d5463674d5334784e794177494441674d5341784c6a5579494442444d5451754e5445674d7934344d5341784e79413149444535494456684d534178494441674d434178494445674d586f694943382b4369416750474e70636d4e735a53426a654430694d54496949474e35505349784d534967636a30694e4349674c7a344b5043397a646d632b2e737667">Open lucide studio](https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M17.116+18a6+6+0+0+0-10.402+0%22+/%3E%3Cpath+d=%22M20+13c0+5-3.5+7.5-7.66+8.95a1+1+0+0+1-.67-.01C7.5+20.5+4+18+4+13V6a1+1+0+0+1+1-1c2+0+4.5-1.2+6.24-2.72a1.17+1.17+0+0+1+1.52+0C14.51+3.81+17+5+19+5a1+1+0+0+1+1+1z%22+/%3E%3Ccircle+cx=%2212%22+cy=%2211%22+r=%224%22+/%3E)

Thanks guys for the contribution, I also like this version, changing now

2024-12-18 11:53 UTC, jguddas requested changes
<img width="133" alt="image" src="https://github.com/user-attachments/assets/4e818368-5765-4084-a723-2c12a1f646ce" />
There are gaps that need to be closed here.

2024-12-18 11:54 UTC, jguddas requested changes

2024-12-18 11:54 UTC, jguddas commented on icons/shield-user.json
> +    "ksk3110"
This should inherit the contributors from the `shield` and `square-user-round`

2025-01-15 14:57 UTC, sebinemeth commented
> <img alt="image" width="133" src="https://private-user-images.githubusercontent.com/25524993/396895839-4e818368-5765-4084-a723-2c12a1f646ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5NTMyNzEsIm5iZiI6MTczNjk1Mjk3MSwicGF0aCI6Ii8yNTUyNDk5My8zOTY4OTU4MzktNGU4MTgzNjgtNTc2NS00MDg0LWE3MjMtMmMxMmExZjY0NmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE1VDE0NTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyODQ4NTg5OGM2ODJhMzIyNjk5ZDYyNTY1NWYwZGMzOTY3MTkxNmNjOGM0OWIzNWMyMWIyZDEzYzY5N2U4ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kviotBra6Z4_4TnXmK3I_7aAb1jXdupJ9sLun4nq6SI"> There are gaps that need to be closed here.

I think I have managed to do that, please check:

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M18+18.5c-.526-.914-1.587-1.972-2.5-2.5s-2.53-1.008-3.585-1.008S9.413+15.472+8.5+16+6.526+17.586+6+18.5%22+/%3E%3Cpath+d=%22M20+13c0+5-3.5+7.5-7.66+8.95a1+1+0+0+1-.67-.01C7.5+20.5+4+18+4+13V6a1+1+0+0+1+1-1c2+0+4.5-1.2+6.24-2.72a1.17+1.17+0+0+1+1.52+0C14.51+3.81+17+5+19+5a1+1+0+0+1+1+1z%22+/%3E%3Ccircle+cx=%2212%22+cy=%2211%22+r=%224%22+/%3E"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTggMTguNWMtLjUyNi0uOTE0LTEuNTg3LTEuOTcyLTIuNS0yLjVzLTIuNTMtMS4wMDgtMy41ODUtMS4wMDhTOS40MTMgMTUuNDcyIDguNSAxNiA2LjUyNiAxNy41ODYgNiAxOC41IiAvPgogIDxwYXRoIGQ9Ik0yMCAxM2MwIDUtMy41IDcuNS03LjY2IDguOTVhMSAxIDAgMCAxLS42Ny0uMDFDNy41IDIwLjUgNCAxOCA0IDEzVjZhMSAxIDAgMCAxIDEtMWMyIDAgNC41LTEuMiA2LjI0LTIuNzJhMS4xNyAxLjE3IDAgMCAxIDEuNTIgMEMxNC41MSAzLjgxIDE3IDUgMTkgNWExIDEgMCAwIDEgMSAxeiIgLz4KICA8Y2lyY2xlIGN4PSIxMiIgY3k9IjExIiByPSI0IiAvPgo8L3N2Zz4=.svg"/><br/>Open lucide studio</a>

2025-01-15 16:26 UTC, karsa-mistmere approved these changes
Yeah, sorry, my bad, the one I posted was just a rough draft.
This new version LGTM!

2025-01-16 08:13 UTC, jguddas commented
The three splines should be a single arc

2025-01-16 08:22 UTC, sebinemeth commented
> The three splines should be a single arc

I'm sorry, but my SVG editing skills have reached a limit with this one, I can't create a pixel-perfect arc there. Can you help me fix it, please?

2025-01-16 08:34 UTC, karsa-mistmere commented
> > The three splines should be a single arc
> 
> I'm sorry, but my SVG editing skills have reached a limit with this one, I can't create a pixel-perfect arc there. Can you help me fix it, please?

Sure thing:

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M20+13c0+5-3.5+7.5-7.66+8.95a1+1+0+0+1-.67-.01C7.5+20.5+4+18+4+13V6a1+1+0+0+1+1-1c2+0+4.5-1.2+6.24-2.72a1.17+1.17+0+0+1+1.52+0C14.51+3.81+17+5+19+5a1+1+0+0+1+1+1z%22+/%3E%3Cpath+d=%22M6.376+18.91a6+6+0+0+1+11.249.003%22+/%3E%3Ccircle+cx=%2212%22+cy=%2211%22+r=%224%22+/%3E"><img alt="icons" width="400px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMjAgMTNjMCA1LTMuNSA3LjUtNy42NiA4Ljk1YTEgMSAwIDAgMS0uNjctLjAxQzcuNSAyMC41IDQgMTggNCAxM1Y2YTEgMSAwIDAgMSAxLTFjMiAwIDQuNS0xLjIgNi4yNC0yLjcyYTEuMTcgMS4xNyAwIDAgMSAxLjUyIDBDMTQuNTEgMy44MSAxNyA1IDE5IDVhMSAxIDAgMCAxIDEgMXoiIC8+CiAgPHBhdGggZD0iTTYuMzc2IDE4LjkxYTYgNiAwIDAgMSAxMS4yNDkuMDAzIiAvPgogIDxjaXJjbGUgY3g9IjEyIiBjeT0iMTEiIHI9IjQiIC8+Cjwvc3ZnPg==.svg"/><br/>Open lucide studio</a>

---

What I did in FIgma is:

1. Insert a blank `shield` icon:

<img width="371" alt="image" src="https://github.com/user-attachments/assets/c131b71b-ff8d-4941-af51-b2a4dae364d5" />

2. Copy the user from `square-user-round` into it:
<img width="301" alt="image" src="https://github.com/user-attachments/assets/7fcfc6dd-aff3-4664-a081-5686dd7668fb" />

3. Select and copy the intersecting path segments from `shield`

<img width="488" alt="image" src="https://github.com/user-attachments/assets/680a92d6-47cc-4f5e-ae47-107694e6888f" />

4. Paste them inside the arc (could've also used a new blank circle of the same dimensions and placement):

<img width="625" alt="image" src="https://github.com/user-attachments/assets/b7633478-f774-4999-b2ba-5128b1053f5a" />

5. Use the pen tool to add the intersection points:

<img width="601" alt="image" src="https://github.com/user-attachments/assets/467b0c18-4ceb-4781-a4f4-0a22afbad7fd" />

6. Delete any unnecessary path segments:

<img width="612" alt="image" src="https://github.com/user-attachments/assets/ca92fbe9-c6f5-4fd0-b595-6f5e861c3d63" />

7. Copy the frame as SVG and paste into Lucide Studio, then press tidy.

2025-01-16 08:46 UTC, sebinemeth commented
Thank you for the detailed answer! I will remember this. I commited the modified svg.

2025-01-17 10:58 UTC, jguddas approved these changes

2025-02-25 08:13 UTC, ericfennis approved these changes

2025-02-25 08:13 UTC, merged