Add `cloud-check` icon
lucide-icons/lucide pull request #2612
Opened 2024-11-14 16:14 UTC by lscheibel

closes #2564
closes #2160

## What is the purpose of this pull request?

- [x] New Icon
- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other:

### Description

Adds new cloud-check icon

### Icon use case 

My use case is for a "sync with cloud" feature, where I show the icon similar to how Google Docs does it, when the document is in sync with what is stored on the server.

I can't think of other non-arbitrary use cases, but considering the popularity of Google Docs as well as the two related issues, I'd say this is not particularly niche.

### Alternative icon designs 

#2564 contains a few other designs. The icon is very similar to those posted there, especially the one from @jguddas but with the checkmark more balanced within the cloud (imo, of course).

I'm using this design for a project, but since there are other designs available as well feel free to close this PR if it doesn't match your expectations.

## Icon Design Checklist 

### Concept 

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [ ] The icons are solely my own creation.
- [x] The icons were originally created* in #2564 by @jguddas. (*influenced by)
- [x] I've based them on the following Lucide icons: cloud, circle-check
- [ ] I've based them on the following design: 

### Naming 

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design 

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to three points of precision.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

2024-11-15 17:56 UTC, ericfennis approved these changes
Nice work!

2024-11-15 19:59 UTC, jguddas commented
<img width="426" alt="image" src="https://github.com/user-attachments/assets/2a125781-abd8-48aa-aae9-5285f1fa3081">

The cloud is shifted?

2024-11-16 14:50 UTC, lscheibel commented
It's moved one pixel up to make it visually centered by compensating for the "heavy bottom". Otherwise, it looks a bit low when centered next to text.

2024-11-16 15:11 UTC, jguddas commented
> It's moved one pixel up to make it visually centered by compensating for the "heavy bottom". Otherwise, it looks a bit low when centered next to text.

That will make it twitch when used in a toggle state 😢

2024-11-16 16:22 UTC, lscheibel commented
Hm yeah, the way I'm using the icon right now is with the loader-circle and cloud-alert, so there it works.

Here are the groups of icons where the main cloud is aligned:
- cloud, cloud-off
- cloud-cog, cloud-download, cloud-upload and all the weather clouds
- cloudy
- cloud-sun, cloud-sun-rain, cloud-moon, cloud-moon-rain
- cloud-alert, _**cloud-check**_

The question is basically, do we want individual icons centered visually, or should icons always be aligned in the "group" they belong to? The latter would sacrifice visual alignment when the icon is used stand-alone and not next to other icons from the group or as toggle. Either way if we decide to move cloud-check down a pixel, I'd probably also move the cloud-alert icon down a pixel

2024-12-04 09:04 UTC, ericfennis requested changes
The cloud icon should be aligned with the other icons you mentioned from the group.
Consistency is more important than the "visually centered rule" IMO.

2025-01-04 14:45 UTC, jguddas commented
I don't like how the icon looks.

2025-02-07 19:27 UTC, lscheibel commented
@ericfennis @jguddas Are you nonetheless interested in this icon? I could submit a version where the cloud is aligned with the `cloud` and `cloud-off` icon. Otherwise, I'd close the PR

2025-04-18 15:14 UTC, ericfennis commented
@lscheibel Sorry for late reply, super busy at moment.
We are still interested, but need to aligned with the other cloud icons.

2025-05-23 10:31 UTC, ericfennis approved these changes
@lscheibel ok, understood. 
I think this one is good to go

2025-05-23 11:03 UTC, merged