Add reflex to showcase
lucide-icons/lucide pull request #2619
Opened 2024-11-19 00:58 UTC by tgberkeley

## What is the purpose of this pull request?

- [ ] New Icon
- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [x] Other:

### Description
This PR adds the company Reflex (https://reflex.dev) to the Showcase page. This Repo has over 20,000 GitHub stars and uses Lucide icons as its only icon type in the library.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

2024-11-21 23:35 UTC, tgberkeley commented
@jguddas what is the reason for the 👎 above, am I missing something in this PR?

2024-11-21 23:38 UTC, karsa-mistmere commented on docs/public/company-logos/reflex-dark.svg
You've mixed up light with dark:
<img width="626" alt="image" src="https://github.com/user-attachments/assets/b70472d0-2cbb-4aaa-bc82-64d1b5f08eda">
<img width="478" alt="image" src="https://github.com/user-attachments/assets/52741bc4-ece7-41c8-a683-899f8b55bf09">

And maybe "Used in" would be the more appropriate category.

I'll leave the decision up to @ericfennis

2024-11-21 23:43 UTC, tgberkeley commented on docs/public/company-logos/reflex-dark.svg
@karsa-mistmere yes I noticed this and fixed it in a follow up commit

2024-11-22 10:15 UTC, karsa-mistmere commented on docs/public/company-logos/reflex-dark.svg
> @tgberkeley Can you confirm, lucide is part of the tool or is it only used on the docs page?

I think part of the tool: https://reflex.dev/docs/library/data-display/icon/

2024-11-22 11:46 UTC, jguddas commented
> @jguddas what is the reason for the 👎 above, am I missing something in this PR?

They have fewer users than us, so it's more of an advertisement for them than it is for us.

I would rather expect there to be companies such as [adobe](https://github.com/search?q=org%3Aadobe%20lucide&type=code).

But all in all I'm very much against having such a section, it's legally and morally a pretty dark gray area.

2024-11-22 12:13 UTC, ericfennis commented on docs/public/company-logos/reflex-dark.svg
In that case this should be moved to the "used in" section.

2024-11-22 12:13 UTC, ericfennis requested changes
Should be moved to the "Used in" section.

2024-11-25 19:15 UTC, tgberkeley commented
@ericfennis just moved it to the used in section

2024-12-03 21:51 UTC, tgberkeley commented
@ericfennis is there anything else here that I need to edit to get this PR approved?

2024-12-04 08:40 UTC, ericfennis approved these changes
LGTM!

2024-12-04 08:56 UTC, merged