feat(icons): added `droplet-off` icon
lucide-icons/lucide pull request #2632
Opened 2024-11-21 13:38 UTC by Footagesus

## What is the purpose of this pull request?
- [x] New Icon

### Description
Added new `droplet-off` icon.

### Icon use case

Water shut-off, humidity control, fluid management, leak control, filtration, water flow monitoring, environmental systems, irrigation systems, household appliances, condensation prevention.

### Alternative icon designs

## Icon Design Checklist

### Concept

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [ ] The icons are solely my own creation.
- [x] The icons were originally created in #<issueNumber> by @Footagesus
- [x] I've based them on the following Lucide icons: `saturn`
- [ ] I've based them on the following design: 

### Naming

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design

- [ ] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [ ] I've made sure that the icons look sharp on low DPI displays.
- [ ] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [ ] I've made sure that the icons are visually centered.
- [ ] I've correctly optimized all icons to three points of precision.

## Before Submitting
- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [ ] I've checked if there was an existing PR that solves the same issue.

2024-11-25 19:29 UTC, ericfennis approved these changes
LGTM

2024-11-25 22:19 UTC, jguddas commented on icons/droplet-off.json
> +    "Footagesus"
Should inherit the contributors.

2024-11-25 22:21 UTC, jguddas requested changes
The icon has also shifted, we should fix that.

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M18.84+13.36C18.5+12.2+18+11+16+9.5c-2-1.6-3.5-4-4-6.5+0+.6-.8+2.4-.82+2.46%22+/%3E%3Cpath+d=%22M22+22+2+2%22+/%3E%3Cpath+d=%22M8.8+8.8c-3+2.3-3.82+4.4-3.8+6.2a7+7+0+0+0+13.18+3.18%22+/%3E"><img alt="icons" width="100%" src="https://lucide.dev/api/gh-icon/diff/droplet/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTguODQgMTMuMzZDMTguNSAxMi4yIDE4IDExIDE2IDkuNWMtMi0xLjYtMy41LTQtNC02LjUgMCAuNi0uOCAyLjQtLjgyIDIuNDYiIC8+CiAgPHBhdGggZD0iTTIyIDIyIDIgMiIgLz4KICA8cGF0aCBkPSJNOC44IDguOGMtMyAyLjMtMy44MiA0LjQtMy44IDYuMmE3IDcgMCAwIDAgMTMuMTggMy4xOCIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>

2024-11-25 22:28 UTC, jguddas commented
Here is the autogenerated one from a long time ago, please don't add me as a contributor, for this.

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M18.715+13.186C18.29+11.858+17.384+10.607+16+9.5c-2-1.6-3.5-4-4-6.5a10.7+10.7+0+0+1-.884+2.586%22+/%3E%3Cpath+d=%22m2+2+20+20%22+/%3E%3Cpath+d=%22M8.795+8.797A11+11+0+0+1+8+9.5C6+11.1+5+13+5+15a7+7+0+0+0+13.222+3.208%22+/%3E&name=droplet&base=droplet"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/diff/droplet/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTguNzE1IDEzLjE4NkMxOC4yOSAxMS44NTggMTcuMzg0IDEwLjYwNyAxNiA5LjVjLTItMS42LTMuNS00LTQtNi41YTEwLjcgMTAuNyAwIDAgMS0uODg0IDIuNTg2IiAvPgogIDxwYXRoIGQ9Im0yIDIgMjAgMjAiIC8+CiAgPHBhdGggZD0iTTguNzk1IDguNzk3QTExIDExIDAgMCAxIDggOS41QzYgMTEuMSA1IDEzIDUgMTVhNyA3IDAgMCAwIDEzLjIyMiAzLjIwOCIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>

2024-11-26 13:32 UTC, Footagesus commented
🤔🤔

2024-11-26 14:29 UTC, closed without merging