feat(icons): adds triangle-dashed icon
lucide-icons/lucide pull request #2652
Opened 2024-11-30 20:09 UTC by Yohh

## What is the purpose of this pull request?

- [x] New Icon
- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other:

### Description

adds triangle-dashed icon

### Icon use case 

I maintain an Obsidian drawing tool plugin, simple-sketch.
I'm going to allow users to draw dashed shapes, I can already add tool-buttons for circle and squares but not for triangles.

### Alternative icon designs 

## Icon Design Checklist 

### Concept 

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [ ] The icons are solely my own creation.
- [ ] The icons were originally created in #<issueNumber> by @<githubUser>
- [x] I've based them on the following Lucide icons:  triangle
- [ ] I've based them on the following design: 

### Naming 

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design 

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to three points of precision.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

2024-12-02 16:00 UTC, jguddas commented
You should throw this into https://lucide-studio.vercel.app and press the tidy button.

2024-12-02 21:58 UTC, Yohh commented
> You should throw this into https://lucide-studio.vercel.app and press the tidy button.



> You should throw this into https://lucide-studio.vercel.app and press the tidy button.

nice, thank you! it's done

2025-01-03 07:26 UTC, Yohh commented
comment to remove stale label

2025-01-03 07:57 UTC, karsa-mistmere approved these changes

2025-01-03 13:41 UTC, Yohh commented
thanks @karsa-mistmere , do I need to do anything else for this pr to be merged?

2025-01-03 17:01 UTC, jguddas requested changes

2025-01-03 17:01 UTC, jguddas commented on icons/triangle-dashed.svg
> +  <path d="m8.102 7.743-1 1.732" />
```suggestion
  <path d="M10.17 4.193a2 2 0 0 1 3.666.013" />
  <path d="M14 21h2" />
  <path d="m15.874 7.743 1 1.732" />
  <path d="m18.849 12.952 1 1.732" />
  <path d="M21.824 18.18a2 2 0 0 1-1.835 2.824" />
  <path d="M4.024 21a2 2 0 0 1-1.839-2.839" />
  <path d="m5.136 12.952-1 1.732" />
  <path d="M8 21h2" />
  <path d="m8.102 7.743-1 1.732" />
```

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M10.17+4.193a2+2+0+0+1+3.666.013%22+/%3E%3Cpath+d=%22M14+21h2%22+/%3E%3Cpath+d=%22m15.874+7.743+1+1.732%22+/%3E%3Cpath+d=%22m18.849+12.952+1+1.732%22+/%3E%3Cpath+d=%22M21.824+18.18a2+2+0+0+1-1.835+2.824%22+/%3E%3Cpath+d=%22M4.024+21a2+2+0+0+1-1.839-2.839%22+/%3E%3Cpath+d=%22m5.136+12.952-1+1.732%22+/%3E%3Cpath+d=%22M8+21h2%22+/%3E%3Cpath+d=%22m8.102+7.743-1+1.732%22+/%3E"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTAuMTcgNC4xOTNhMiAyIDAgMCAxIDMuNjY2LjAxMyIgLz4KICA8cGF0aCBkPSJNMTQgMjFoMiIgLz4KICA8cGF0aCBkPSJtMTUuODc0IDcuNzQzIDEgMS43MzIiIC8+CiAgPHBhdGggZD0ibTE4Ljg0OSAxMi45NTIgMSAxLjczMiIgLz4KICA8cGF0aCBkPSJNMjEuODI0IDE4LjE4YTIgMiAwIDAgMS0xLjgzNSAyLjgyNCIgLz4KICA8cGF0aCBkPSJNNC4wMjQgMjFhMiAyIDAgMCAxLTEuODM5LTIuODM5IiAvPgogIDxwYXRoIGQ9Im01LjEzNiAxMi45NTItMSAxLjczMiIgLz4KICA8cGF0aCBkPSJNOCAyMWgyIiAvPgogIDxwYXRoIGQ9Im04LjEwMiA3Ljc0My0xIDEuNzMyIiAvPgo8L3N2Zz4=.svg"/><br/>Open lucide studio</a>

2025-01-03 17:35 UTC, Yohh commented on icons/triangle-dashed.svg
> +  <path d="m8.102 7.743-1 1.732" />
done

2025-01-03 17:35 UTC, Yohh commented on icons/triangle-dashed.json
> +    "Yohh"
of course, it's done

2025-01-03 17:49 UTC, jguddas approved these changes

2025-01-06 10:50 UTC, Yohh commented
@jguddas thanks for your approval, can I or do I need to update branch? do you prefer merge or rebase?

2025-01-06 11:06 UTC, jguddas commented
> @jguddas thanks for your approval, can I or do I need to update branch? do you prefer merge or rebase?

@ericfennis is gonna fly by at some point and update + merge this for us, maybe we can also get @karsa-mistmere your approval?

2025-01-06 13:26 UTC, ericfennis approved these changes
Awesome work @Yohh !

2025-01-06 13:49 UTC, Yohh commented
thanks @ericfennis , sorry for the bad indent, I didn't see it, you've fixed it before I was ready to push 😆

2025-01-10 13:36 UTC, merged