fix: add unique keys to iconNode and children to resolve React errors
lucide-icons/lucide pull request #2655
Opened 2024-12-01 18:21 UTC by hypervisor

## What is the purpose of this pull request?

- [ ] New Icon
- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other:

### Description

This PR resolves the missing `key` warnings in the `Icon` component by adding unique `key` props to the elements created from `iconNode` and `children`.

Closes #2654

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

2024-12-19 13:52 UTC, ericfennis approved these changes

2024-12-19 13:55 UTC, jguddas requested changes
I don't think that's a good idea, using indexes as keys is not something we should do.

2024-12-20 09:33 UTC, ericfennis commented
@jguddas This is only when custom icons are added. The icon nodes we provide have random keys generated based on the content.

2024-12-20 10:01 UTC, jguddas commented
My opinion stays the same, we should not do this. If you want to fix the error add keys to your custom icon data, https://lucide-studio.vercel.app does it automatically already.

2025-01-20 09:14 UTC, closed without merging