feat(@lucide/astro): add lucide package for Astro
lucide-icons/lucide pull request #2665
Opened 2024-12-05 21:07 UTC by MoustaphaDev

TODOs:
- [x] @lucide/astro package
- [x] Testing
- [x] Docs page
- [x] Framework logo
- [x] Homepage icon
- [x] Package logo (both light and dark)
- [x] Add "Lucide Astro" in the left sidebar
- [x] Add workflows for package publishing and testing
- [x] Update demo project to only include `@lucide/astro` and revise PR description after

## What is the purpose of this pull request?

- [ ] New Icon
- [ ] Bug fix
- [x] New Feature
- [ ] Documentation update
- [ ] Other

### Description

Add a new package for first-class Astro support.

(outdated) Here's the demo project using both the legacy and rewritten package: [demo project](https://stackblitz.com/github/MoustaphaDev/lucide-astro-next-demo)

See https://github.com/lucide-icons/lucide/pull/2665#issuecomment-2562872802 for more details.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

2024-12-05 23:26 UTC, MoustaphaDev commented on scripts/render/processSvg.mjs
> +import DEFAULT_ATTRS from '../../tools/build-icons/render/default-attrs.json' with { type: 'json' };
I wonder how this worked for anyone previously, I had to make this change for the script to run.

2024-12-07 04:12 UTC, MoustaphaDev commented on scripts/render/processSvg.mjs
> +import DEFAULT_ATTRS from '../../tools/build-icons/render/default-attrs.json' with { type: 'json' };
Ah, I just found out that this was valid syntax in v20 and earlier

2024-12-07 09:36 UTC, realguse commented
Is it just me, or is the astro icon a bit too big
![image](https://github.com/user-attachments/assets/bb42d932-3c7e-41f1-9f0d-d37f38071631)

2024-12-07 19:26 UTC, MoustaphaDev commented
Yeah it's definitely bigger than the other icons, I'll fix that @realguse

2024-12-07 19:30 UTC, realguse commented
Remember to update the table in the main readme as well, nice work whatsoever though!

2024-12-08 19:26 UTC, MoustaphaDev commented
Well shoot, I just realized `lucide-astro` is already taken on npm.

We could just rename the package to something like `lucide-astrojs`, however Astro dropped the "dot js" part from its branding long ago. Or we could kindly ask to be given ownership of it.

Pinging @ericfennis if he (or anyone) has recommendations/ideas on what we could do.

2024-12-08 19:47 UTC, realguse commented
It seems like lucide-astro is an unofficial port, I've sent a name despute

2024-12-08 20:00 UTC, realguse commented
@MoustaphaDev, should i change something or included anything more?

![screencapture-support-github-contact-npm-name-disputes-2024-12-08-20_57_57 (1)-min](https://github.com/user-attachments/assets/e59e408d-1b68-473a-9d1a-0f070b052c9c)

2024-12-09 09:18 UTC, Aviortheking commented
Hi, I'm the current owner of `lucide-astro` I'm totally not against moving the ownership of the package to you !
I would just want to make sure of 2-3 things :
1. The package keep old versions
2. the package is backward-compatible with previous version
3. (Optional but appreciated) a ref of the previous maintainer of the package

What do you think about these ?

2024-12-09 13:05 UTC, realguse commented
Thank you for your response and willingness. We are more than happy to meet your conditions:

- We'll ensure that all existing versions remain available on npm.

- The package will maintain backward compatibility with the current implementation.

- We'll also include a reference to you as the original maintainer in the README and/or changelg.


Let us know if there's anything else you'd like us to address before proceeding.

2024-12-09 13:19 UTC, Aviortheking commented
I'm happy with the current elements !

As soon as the new lib feels ready I'll check it on my existing projects to validate it and then transfer the ownership to the group !

2024-12-09 13:33 UTC, realguse commented
That sounds great! Thank you so much again! We will ping you when it's ready, which i would say it already is, so if you could just check over everything.

2024-12-10 07:03 UTC, realguse commented
@MoustaphaDev, I found another thing that needs to be changed: there is a worflow called `labeler.yaml`, thats what responsible for automatically adding labels to stuff. So if you could go to the `.github/labeler.yml` and add another record for the astro pkg, that would be great! Thanks again!

2024-12-10 07:11 UTC, realguse requested changes
Add astro pkg label to `.github/labeler.yml`

2024-12-13 00:36 UTC, MoustaphaDev commented
Sorry for the late response y'all. I've been quite busy this week unfortunately.

Btw thanks so much @realguse for chiming in and taking the lead, and thanks @Aviortheking for your willingness.

As @realguse said, we're happy to meet your conditions!
I'll try to get this over the line this weekend when I have some time.

2024-12-13 05:05 UTC, realguse commented
I absolutely understand, this is no rush so only when you're ready

2024-12-20 09:23 UTC, ericfennis reviewed
@MoustaphaDev Concrats, really well done!!
This package is welcome to the stack.
Nice you reused all the utilities and build tooling.

I'm fine with taking over the name of `lucide-astro`.
We eventually want to move to scoped packages `@lucide/*`, but not sure if this is the time.

So let's check what we need to do before merging this.

TODOs:
- [x] Manual testing package on an Astro project
- [ ] Transfer NPM package to me `ericfennis`
- [x] Revert changes in `/icons/*`
- [x] Reviewing docs
- [ ] Release a RC, to check if working with older projects

2024-12-22 09:53 UTC, realguse requested changes
Revert changes

2024-12-22 09:56 UTC, realguse commented
Sorry don't know what happend there, i meant revert the `icons/picture-in-picture.svg`, `icons/grid-2x2-x.json` and `icons/grid-2x2-check.json`

2024-12-25 09:42 UTC, realguse commented
@ericfennis, changes in `icons/` have been reverted, please check it on the list

2024-12-26 15:07 UTC, MoustaphaDev commented
The PR is ready to be reviewed

Here's the demo project using both the legacy and rewritten package

https://stackblitz.com/github/MoustaphaDev/lucide-astro-next-demo

Here are the differences between the legacy package and the new package:
- An `Icon` component export that renders icon nodes
- An `icons` namespace export containing all icons
When importing all components, you should use the `icons` exports instead of a namespaced import, as the `Icon` component doesn't have the same interface as the lucide icons.
 ```jsx
 ---
 import * as icons from "lucide-astro" // ❌ wrong way, can't render this in a loop as it will contain other symbols than components
 import { icons } from "lucide-astro" // ✅ right way, this will import only icons
 ---
 ```

- Bumped one major, to avoid breaking current users' sites.

2024-12-27 21:28 UTC, realguse commented
This looks epic, hope you're pleased with how it turned out!

2025-01-10 11:21 UTC, ericfennis reviewed
Nice work @MoustaphaDev! 
We are almost good to go!
If @Aviortheking also approves this PR and is ready to transfer the ownership of the NPM package we can start publishing!

2025-01-10 11:21 UTC, ericfennis commented on packages/lucide-astro/tests/utils/render.ts
> +import { parseHTML } from 'linkedom';
Nice work 😎

2025-02-11 20:28 UTC, MoustaphaDev commented
Friendly bump on this @Aviortheking

2025-02-27 16:43 UTC, SupianIDz commented
Is there any update on this merger? It has been almost 1.5 months without any further progress.

2025-03-06 20:52 UTC, MoustaphaDev commented
Since @Aviortheking seems unavailable, could we maybe publish the package as `lucide-astro-next`, and rename it to `lucide-astro` when/if he give you ownership of the package?

I'm in no rush, I just want to know your thoughts about an alternative path to get this over the line.

cc @ericfennis

2025-03-06 21:32 UTC, ericfennis commented
No I'm thinking of releasing it with the lucide scope anyways.
So it will be `@lucide/astro`.

2025-03-06 23:56 UTC, MoustaphaDev commented
Even better 😄 So I'll work on replacing mentions of the package to `@lucide/astro` this weekend!

2025-03-07 12:43 UTC, ericfennis commented
@MoustaphaDev Awesome!

2025-03-14 15:59 UTC, ericfennis requested changes
Nice almost ready!
Some paths need some adjustment with the new naming

2025-03-14 15:59 UTC, ericfennis commented on .github/labeler.yml
> +          - 'packages/lucide-astro/*'
This should be updated to the correct path

2025-03-14 15:59 UTC, ericfennis commented on .github/workflows/lucide-astro.yml
> +      - packages/lucide-astro/**
Path need to be updated

2025-03-14 15:59 UTC, ericfennis commented on .github/workflows/lucide-astro.yml
> +        run: pnpm --filter lucide-astro build
```suggestion
        run: pnpm --filter @lucide/astro build
```

2025-03-14 15:59 UTC, ericfennis commented on .github/workflows/lucide-astro.yml
> +        run: pnpm --filter lucide-astro test
```suggestion
        run: pnpm --filter @lucide/astro test
```

2025-03-14 15:59 UTC, ericfennis commented on .github/workflows/release.yml
> +            'lucide-astro',
```suggestion
            '@lucide/astro',
```

2025-03-14 15:59 UTC, ericfennis commented on docs/guide/index.md
> +Lucide's official packages are designed to work on different platforms, making it easier for users to integrate icons into their projects. The packages are available for various technologies, includi
Looking at the markdown file it should be `lucide-astro`
```suggestion
Lucide's official packages are designed to work on different platforms, making it easier for users to integrate icons into their projects. The packages are available for various technologies, including [Web (Vanilla)](https://lucide.dev/guide/packages/lucide), [React](https://lucide.dev/guide/packages/lucide-react), [React Native](https://lucide.dev/guide/packages/lucide-react-native), [Vue](https://lucide.dev/guide/packages/lucide-vue), [Vue 3](https://lucide.dev/guide/packages/lucide-vue-next), [Svelte](https://lucide.dev/guide/packages/lucide-svelte), [Preact](https://lucide.dev/guide/packages/lucide-preact), [Solid](https://lucide.dev/guide/packages/lucide-solid), [Angular](https://lucide.dev/guide/packages/lucide-angular), [Astro](https://lucide.dev/guide/packages/lucide-astro), [NodeJS](https://lucide.dev/guide/packages/lucide-static#nodejs) and [Flutter](https://lucide.dev/guide/packages/lucide-flutter).
```

2025-03-14 15:59 UTC, ericfennis commented on .github/labeler.yml
> +          - 'packages/lucide-astro/*'
```suggestion
          - 'packages/astro/*'
```

2025-03-23 21:56 UTC, MoustaphaDev commented
Made the suggested chages!

2025-03-24 22:59 UTC, dotspencer commented
@MoustaphaDev I noticed that the "Guide" link on the [/packages](https://lucide-787jvme1o-lucide.vercel.app/packages) page in the preview build links to `/guide/packages/@lucide/astro` when it looks like the guide actually lives at `/guide/packages/lucide-astro`
 
<img src="https://github.com/user-attachments/assets/f517767c-ec5e-49f6-a6d9-0c6afc4a9942" width="350"/>

2025-03-25 09:28 UTC, MoustaphaDev commented
Good catch @dotspencer! Gonna fix that now

2025-03-31 14:20 UTC, ericfennis approved these changes
Awesome work @MoustaphaDev ! 
Ready to go!

2025-03-31 14:20 UTC, merged

2025-03-31 16:50 UTC, dotspencer commented
Excited to see this go out! 🎉

@ericfennis The package link redirects me to the npm login page. Curious if the publishing is still in progress or if it's set to private or something?

https://www.npmjs.com/package/@lucide/astro

2025-04-01 09:49 UTC, ericfennis commented
@dotspencer Let me check!

2025-04-01 21:15 UTC, negativems commented
> @ericfennis The package link redirects me to the npm login page. Curious if the publishing is still in progress or if it's set to private or something?


For me too. It looks like the package is private.

2025-04-02 07:37 UTC, ericfennis commented
Should be working now!

2025-04-02 12:33 UTC, realguse commented
The table is currently broken, a fix is present in #2976