feat: add `cup-to-go` icon
lucide-icons/lucide pull request #2702
Opened 2024-12-20 23:45 UTC by realguse

Closes #2701

## What is the purpose of this pull request?
- [x] New Icon

### Description
Merges the `cup-to-go` icon from lucide lab into the main repo, extra info in issue (#2701)

## Before Submitting
- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

2024-12-21 06:13 UTC, jguddas requested changes
**Optimized paths:**
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M18+18H6l-1-7h14z%22+/%3E%3Cpath+d=%22m18.2+11+.8-4-.8-4A1.19+1.19+0+0+0+17+2H7a1.19+1.19+0+0+0-1.2+1L5+7l.8+4%22+/%3E%3Cpath+d=%22M4+7h16%22+/%3E%3Cpath+d=%22m7.2+18+.6+3A1.19+1.19+0+0+0+9+22h6a1.19+1.19+0+0+0+1.2-1l.6-3%22+/%3E"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTggMThINmwtMS03aDE0eiIgLz4KICA8cGF0aCBkPSJtMTguMiAxMSAuOC00LS44LTRBMS4xOSAxLjE5IDAgMCAwIDE3IDJIN2ExLjE5IDEuMTkgMCAwIDAtMS4yIDFMNSA3bC44IDQiIC8+CiAgPHBhdGggZD0iTTQgN2gxNiIgLz4KICA8cGF0aCBkPSJtNy4yIDE4IC42IDNBMS4xOSAxLjE5IDAgMCAwIDkgMjJoNmExLjE5IDEuMTkgMCAwIDAgMS4yLTFsLjYtMyIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>

**Optimized paths + Arcified corners:**
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22m18.2+11+.722-3.608a2+2+0+0+0+0-.784L18.2+3A1.19+1.19+0+0+0+17+2H7a1.19+1.19+0+0+0-1.2+1l-.722+3.608a2+2+0+0+0+0+.784L5.8+11%22+/%3E%3Cpath+d=%22M4+7h16%22+/%3E%3Cpath+d=%22M5.163+12.141A1+1+0+0+1+6.153+11h11.694a1+1+0+0+1+.99+1.141l-.714+5a1+1+0+0+1-.99.859H6.867a1+1+0+0+1-.99-.859z%22+/%3E%3Cpath+d=%22m7.2+18+.6+3A1.19+1.19+0+0+0+9+22h6a1.19+1.19+0+0+0+1.2-1l.6-3%22+/%3E"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJtMTguMiAxMSAuNzIyLTMuNjA4YTIgMiAwIDAgMCAwLS43ODRMMTguMiAzQTEuMTkgMS4xOSAwIDAgMCAxNyAySDdhMS4xOSAxLjE5IDAgMCAwLTEuMiAxbC0uNzIyIDMuNjA4YTIgMiAwIDAgMCAwIC43ODRMNS44IDExIiAvPgogIDxwYXRoIGQ9Ik00IDdoMTYiIC8+CiAgPHBhdGggZD0iTTUuMTYzIDEyLjE0MUExIDEgMCAwIDEgNi4xNTMgMTFoMTEuNjk0YTEgMSAwIDAgMSAuOTkgMS4xNDFsLS43MTQgNWExIDEgMCAwIDEtLjk5Ljg1OUg2Ljg2N2ExIDEgMCAwIDEtLjk5LS44NTl6IiAvPgogIDxwYXRoIGQ9Im03LjIgMTggLjYgM0ExLjE5IDEuMTkgMCAwIDAgOSAyMmg2YTEuMTkgMS4xOSAwIDAgMCAxLjItMWwuNi0zIiAvPgo8L3N2Zz4=.svg"/><br/>Open lucide studio</a>

**Optimized paths + Arcified corners + Changed border radius from 1.19 px to 1px:**
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22m18.2+11+.722-3.608a2+2+0+0+0+0-.784l-.761-3.804A1+1+0+0+0+17.18+2H6.82a1+1+0+0+0-.98.804l-.762+3.804a2+2+0+0+0+0+.784L5.8+11%22+/%3E%3Cpath+d=%22M4+7h16%22+/%3E%3Cpath+d=%22M5.163+12.141A1+1+0+0+1+6.153+11h11.694a1+1+0+0+1+.99+1.141l-.714+5a1+1+0+0+1-.99.859H6.867a1+1+0+0+1-.99-.859z%22+/%3E%3Cpath+d=%22m7.2+18+.64+3.196a1+1+0+0+0+.98.804h6.36a1+1+0+0+0+.98-.804L16.8+18%22+/%3E"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJtMTguMiAxMSAuNzIyLTMuNjA4YTIgMiAwIDAgMCAwLS43ODRsLS43NjEtMy44MDRBMSAxIDAgMCAwIDE3LjE4IDJINi44MmExIDEgMCAwIDAtLjk4LjgwNGwtLjc2MiAzLjgwNGEyIDIgMCAwIDAgMCAuNzg0TDUuOCAxMSIgLz4KICA8cGF0aCBkPSJNNCA3aDE2IiAvPgogIDxwYXRoIGQ9Ik01LjE2MyAxMi4xNDFBMSAxIDAgMCAxIDYuMTUzIDExaDExLjY5NGExIDEgMCAwIDEgLjk5IDEuMTQxbC0uNzE0IDVhMSAxIDAgMCAxLS45OS44NTlINi44NjdhMSAxIDAgMCAxLS45OS0uODU5eiIgLz4KICA8cGF0aCBkPSJtNy4yIDE4IC42NCAzLjE5NmExIDEgMCAwIDAgLjk4LjgwNGg2LjM2YTEgMSAwIDAgMCAuOTgtLjgwNEwxNi44IDE4IiAvPgo8L3N2Zz4=.svg"/><br/>Open lucide studio</a>

2024-12-21 19:50 UTC, jguddas requested changes

2024-12-21 19:50 UTC, jguddas commented on icons/cup-to-go.json
> +    "danielbayley"
```suggestion
    "danielbayley",
    "jguddas"
```

2025-01-10 15:50 UTC, realguse commented
@jguddas Is there any hope of getting this merge?

2025-01-13 16:14 UTC, jguddas approved these changes

2025-02-10 22:36 UTC, closed without merging