Add the settings-2 icon
lucide-icons/lucide pull request #296
Opened 2021-04-22 23:30 UTC by delnyn

Hello, just adding this file because I personally don't really like the original settings icon. I used SVGOMG, changed the color to "currentColor" and put all metadata in the <svg> tag. This is how it looks
![image](https://user-images.githubusercontent.com/45879791/115797093-5f771a00-a3d3-11eb-87c6-064d305d1b09.png)
and the 100% scale 
![settings-2](https://user-images.githubusercontent.com/45879791/115797137-79b0f800-a3d3-11eb-8894-1a8704322129.png)

2021-04-23 17:08 UTC, mittalyashu commented
After optimising

```svg
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <path d="M11.967 2h-.434a2 2 0 00-2 2v.18a2 2 0 01-.999 1.731l-.435.252a2 2 0 01-2.003 0l-.144-.084a2 2 0 00-2.735.733l-.22.383a2 2 0 00.73 2.73l.155.088a2 2 0 01.998 1.732v.51a2 2 0 01-.998 1.731l-.154.09a2 2 0 00-.732 2.73l.221.382a2.001 2.001 0 002.735.733l.144-.084a2 2 0 012.003 0l.435.252a2 2 0 01.999 1.731V20a2 2 0 002 2h.434a2 2 0 002-2v-.18a2 2 0 01.999-1.731l.435-.252a2 2 0 012.003 0l.144.084a2.002 2.002 0 002.735-.733l.22-.383a2 2 0 00-.73-2.73l-.155-.088a2 2 0 01-.998-1.732v-.51a2 2 0 01.998-1.731l.154-.09a2 2 0 00.732-2.73l-.221-.382a1.999 1.999 0 00-2.735-.733l-.144.084a2 2 0 01-2.003 0l-.435-.252a2 2 0 01-.999-1.731V4a2 2 0 00-2-2v0z" />
  <path d="M11.75 14a2.25 2.25 0 100-4.5 2.25 2.25 0 000 4.5z" />
</svg>

```

2021-04-24 13:16 UTC, delnyn commented
I already optimized it.

2021-04-25 11:08 UTC, mittalyashu commented
@delnyn The icon should have `path` tag, not circle.

2021-04-25 18:30 UTC, ericfennis commented
@delnyn @mittalyashu I think this icon is too similar with the current settings icon. So I'm more for a replacement instead of a second one.

Can you maybe post an a side-by-side image with the two settings icons?

2021-04-26 11:12 UTC, mittalyashu commented
@ericfennis After looking at this icon I think this looks more cleaner with less curvy lines and it will even look better when `stroke-width` is increased.

2021-04-28 09:37 UTC, delnyn commented
![image](https://user-images.githubusercontent.com/45879791/116382333-16c9c180-a816-11eb-8beb-06f3588ec090.png)

2021-04-29 20:18 UTC, ericfennis commented
I agree with you @mittalyashu this icon is much cleaner. Also better for lower resolution screens.
I think the icon look a bit better by increasing the circle in the middle, but I don't know what you think.
![image](https://user-images.githubusercontent.com/11825403/116612843-4c66cb80-a938-11eb-83c8-9cb3607bfd25.png)
@delnyn I noticed that the code of the icon, the icon is a bit shifted to left. You can also see that in the preview you posted.

2021-04-30 20:29 UTC, delnyn commented
> I think the icon look a bit better by increasing the circle in the middle, but I don't know what you think.
Yes, I had that idea too!
> I noticed that the code of the icon, the icon is a bit shifted to left. You can also see that in the preview you posted.
Actually it's because the outside path is 20h x 19.5w and that's pretty hard to deal with, I'll try to change that

2021-04-30 20:46 UTC, delnyn commented
I made the icon centered, the circle 6px wide, removed settings-2 tags, made the attributes cleaner, and replaced settings with settings-2

2021-05-01 06:15 UTC, mittalyashu commented
To decrease the size of first node, I tried to split into 4 `path`, it didn't work.

<img width="354" alt="CleanShot 2021-05-01 at 11 44 57@2x" src="https://user-images.githubusercontent.com/29014463/116773390-c26f4d80-aa72-11eb-8018-f54b5d2fc41c.png">

2021-05-03 20:28 UTC, ericfennis requested changes
Code improvements

2021-05-03 20:28 UTC, ericfennis commented on icons/settings.svg
> +<path d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/>
```suggestion
  <path d="M12.22 2h-.44a2 2 0 00-2 2v.18a2 2 0 01-1 1.73l-.43.25a2 2 0 01-2 0l-.15-.08a2 2 0 00-2.73.73l-.22.38a2 2 0 00.73 2.73l.15.1a2 2 0 011 1.72v.51a2 2 0 01-1 1.74l-.15.09a2 2 0 00-.73 2.73l.22.38a2 2 0 002.73.73l.15-.08a2 2 0 012 0l.43.25a2 2 0 011 1.73V20a2 2 0 002 2h.44a2 2 0 002-2v-.18a2 2 0 011-1.73l.43-.25a2 2 0 012 0l.15.08a2 2 0 002.73-.73l.22-.39a2 2 0 00-.73-2.73l-.15-.08a2 2 0 01-1-1.74v-.5a2 2 0 011-1.74l.15-.09a2 2 0 00.73-2.73l-.22-.38a2 2 0 00-2.73-.73l-.15.08a2 2 0 01-2 0l-.43-.25a2 2 0 01-1-1.73V4a2 2 0 00-2-2z" />
  <circle cx="12" cy="12" r="3" />
```

2021-05-05 20:32 UTC, delnyn commented
> To decrease the size of first node, I tried to split into 4 `path`, it didn't work.

WDYM by "It didn't work"? What didn't work?

2021-05-06 03:24 UTC, mittalyashu commented
@delnyn This is what I mean.

![CleanShot 2021-05-06 at 08 53 17@2x](https://user-images.githubusercontent.com/29014463/117237421-93792300-ae48-11eb-9faa-211c2056146a.png)

Split into 4 different `path`.

2021-05-15 19:51 UTC, ericfennis approved these changes

2021-05-16 10:27 UTC, merged