add circle-cross icon
lucide-icons/lucide pull request #303
Opened 2021-05-01 09:54 UTC by mittalyashu

| Preview |
| --- |
| <img width="297" alt="CleanShot 2021-05-01 at 15 16 56@2x" src="https://user-images.githubusercontent.com/29014463/116778714-3f112480-aa91-11eb-8c51-9a9ad81ee841.png"> |

2021-05-03 20:13 UTC, ericfennis requested changes
@mittalyashu Nice icon!

Small code improvement

2021-05-03 20:13 UTC, ericfennis commented on icons/circle-cross.svg
> +  <path d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10z" />
```suggestion
  <circle cx="12" cy="12" r="10" />
```

2021-05-05 05:56 UTC, locness3 commented
Use case?

2021-05-16 15:36 UTC, mittalyashu commented
Use cases

* Game over
* No entry / do not enter

@locness3

2021-05-16 15:40 UTC, locness3 commented
I'm not sure about it but I think Lucide is suited for user interface icons. And I don't really see in what kind, context of UI this icon could fit.

2021-06-16 03:21 UTC, mittalyashu commented
Okay, I will close this PR.

2021-06-16 03:21 UTC, closed without merging