Refactor the archive icon
lucide-icons/lucide pull request #365
Opened 2021-08-02 13:13 UTC by delnyn

Hello,  
I saw that the `archive` icon is breaking the "1 pixel padding within the canvas" rule and the "border radius of 2 pixels" rule.  
I made it a little smaller and added the border radius.  
This is how it looks now  
![image](https://user-images.githubusercontent.com/45879791/127867309-7dc7e51f-0870-4699-97b8-2f85569767c3.png)
and this is how it looks at 100% scale  
![archive-png](https://user-images.githubusercontent.com/45879791/127867429-ce5814c1-8f26-4e25-bde0-530023009726.png)

2021-08-02 19:02 UTC, locness3 commented
Could you show a preview alongside other icons? (and could you use the PR template next time?)

2021-08-02 21:17 UTC, delnyn commented
This is how it looks
![image](https://user-images.githubusercontent.com/45879791/127924623-3502a6b7-9725-4767-ae35-761d2578da2d.png)
*Also sorry, I clicked the PR button from my fork (in the "delnyn/lucide:master is 1 commit ahead of lucide-icons/lucide:master" box) and it didn't propose me to use a template*

2021-08-03 08:27 UTC, locness3 requested changes
Please format your svg, otherwise lgtm

2021-08-03 20:02 UTC, ericfennis commented
@delnyn Nice icon!

Can you format the svg?
If you need any help with that let us know!

2021-08-03 20:16 UTC, delnyn commented
> Please format your svg, otherwise lgtm

I did

2021-08-03 20:17 UTC, delnyn commented
I used SVGOMG to optimize it and then applied the "generic" tags (in the icon designing guide)

2021-08-03 20:19 UTC, delnyn commented
oooooh no my bad I misunderstood  
yeah ofc

2021-08-06 07:39 UTC, delnyn commented
I formatted the SVG

2021-08-06 08:14 UTC, locness3 approved these changes
Looks like you're a @ghost now. LGTM.

2021-08-06 21:35 UTC, delnyn commented
what?

2021-08-07 06:46 UTC, locness3 commented
Just a mobile app glitch, nevermind.

2021-08-08 19:00 UTC, merged