Created selection-flag start and end flag
lucide-icons/lucide pull request #380
Opened 2021-08-10 18:41 UTC by tidoni

I use it for selecting the starttime and endtime in an audio file.

2021-08-11 14:40 UTC, ericfennis commented
Nice icon!

2021-08-11 14:45 UTC, ericfennis requested changes
Seems like there is a random square in the svg.
The rect element can be removed.
Can you also add a new line add the end of the files.

2021-08-11 14:47 UTC, ericfennis commented on icons/selection-flag-end.svg
> +</svg>
```suggestion
  <path d="M17 22 17 2 7 7 17 12" />
</svg>

```

2021-08-11 14:47 UTC, ericfennis commented on icons/selection-flag-start.svg
> +</svg>
```suggestion
  <path d="M7 22 7 2 17 7 7 12" />
</svg>

```

2021-08-12 07:29 UTC, locness3 requested changes
What about `triangle-flag-{left,right}`?

2021-08-12 07:47 UTC, ericfennis commented
I agree with @locness3, with generalizing the name. We make it more multy-purpose. Fits well with our other names.
I like `flag-triangle-{left,right}` more, because `flag` is the icon and `triangle` is the variation.

2021-09-05 10:59 UTC, merged