new cursor icon
lucide-icons/lucide pull request #454
Opened 2021-12-15 13:40 UTC by pandrr

![Screenshot 2021-12-15 at 14 39 58](https://user-images.githubusercontent.com/98792/146196865-64be5360-1b4f-42f9-a227-9854b5abde1e.png)

a text cursor icon

2021-12-29 16:50 UTC, mittalyashu commented
@pandrr Can you please rename it to `text-cursor`?

2021-12-29 20:36 UTC, pandrr commented
@mittalyashu done!

2022-01-01 14:09 UTC, Andreto commented
@pandrr this path needs to be cleaned up. 
![image](https://user-images.githubusercontent.com/28541538/147852376-064bbcdd-9de4-4a76-a2dd-f6816dc43781.png)

And also, try to keep things aligned, evenly spaced, and with proper distance to the edge.
[ICON DESIGN GUIDE](https://github.com/lucide-icons/lucide/blob/master/docs/ICON_DESIGN_GUIDE.md)

2022-01-02 14:25 UTC, ericfennis commented
Also the dash in the middle looks a bit weird to me, or is that me?

2022-01-02 15:09 UTC, Andreto commented
> Also the dash in the middle looks a bit weird to me, or is that me? @ericfennis 

I use windows and have only ever seen this one: ![image](https://user-images.githubusercontent.com/28541538/147879763-370ba623-706b-4ff0-9157-261285ebb95d.png)
But googling "text cursor icon" a lot of the results do have this line.

On Font awesome its called `i-cursor`: ![image](https://user-images.githubusercontent.com/28541538/147879912-f919056a-28a2-40ca-ac15-8dbceac4a944.png)
Is it perhaps a mac thing? I don't know?

Also, something like this could perhaps be useful as a `rename` or `edit-text` icon:
![image](https://user-images.githubusercontent.com/28541538/147880040-2ec20f6c-bec3-446f-9622-b3637514cff9.png)

2022-01-02 15:28 UTC, Andreto commented
![image](https://user-images.githubusercontent.com/28541538/147880530-6cd1ad8b-4c06-41c1-81be-9a14b3d635e6.png)![image](https://user-images.githubusercontent.com/28541538/147880542-9aacb883-56a5-4aaf-a30a-b95c0283c41e.png)
![image](https://user-images.githubusercontent.com/28541538/147880561-bf3d867b-86ba-4c35-87c4-d4377eef8e5c.png)

2022-01-03 09:48 UTC, pandrr commented
yes on mac there is this little line in the middle

2022-01-05 18:49 UTC, ericfennis commented
@pandrr Oh wow didn't see that ! just noticed it.
But I think we need to keep it simple as possible.

2022-01-10 15:13 UTC, dudumaluf commented
[cursor_and_rename_icons_24px.zip](https://github.com/lucide-icons/lucide/files/7839780/cursor_and_rename_icons_24px.zip)
Cleaned the cursor icon path according to the guideline and also created the "rename" icon as @Andreto Andreto suggested.

2022-01-11 07:19 UTC, pandrr commented
we cleaned up the icons and added a rename.svg as requested.
i hope those are fine now. let me know

2022-01-11 08:19 UTC, mittalyashu commented
@pandrr We've a optimise script in `package.json` can you run that on those 2 icons?

2022-01-15 22:35 UTC, ericfennis requested changes
Some code formatting

2022-01-15 22:35 UTC, ericfennis commented on icons/text-cursor.svg
> +<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" x="0" y="0" viewBox="0 0 24 24" style="enable-background:new 0 0 24 24" xml:space="preserve"><style>.st1{fill:none;stroke:#000;strok
```suggestion
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <path d="M17 22h-1a4 4 0 0 1-4-4V6a4 4 0 0 1 4-4h1" />
  <path d="M7 22h1a4 4 0 0 0 4-4v-1" />
  <path d="M7 2h1a4 4 0 0 1 4 4v1" />
</svg>
```

2022-01-15 22:35 UTC, ericfennis commented on icons/rename.svg
> +<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" x="0" y="0" viewBox="0 0 24 24" style="enable-background:new 0 0 24 24" xml:space="preserve"><style>.st1{fill:none;stroke:#000;strok
```suggestion
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <path d="M5.3 4h.9C7.7 4 9 5.3 9 6.7m0 0v10.5c0 1.6-1.1 2.7-2.7 2.7h-1M9 6.7v10.6a2.6 2.6 0 0 0 2.7 2.7h1M9 6.7C9 5.2 10.2 4 11.8 4h.9" />
  <path d="M13.1 7.9h6.8c1.1 0 2.1 1 2.1 2.1v4c0 1.1-.9 2.1-2.1 2.1h-6.8" />
  <path d="M4.8 16.1h-.7C3 16.1 2 15.1 2 14v-4c0-1.1 1-2.1 2.1-2.1h.7" />
</svg>
```

2022-01-16 12:23 UTC, Andreto commented
@pandrr 
Keep separate lines as separate shapes for ease of editing.
This is both on the main cursor and the text box.

The cursor shape should probably also be cut up into three parts to avoid overlapping lines. Something like this:
![image](https://user-images.githubusercontent.com/28541538/149659621-7730a9cf-205c-45d1-acc2-d5831bf82b14.png)

And there is no reason to not align these lines to the grid:
![image](https://user-images.githubusercontent.com/28541538/149659709-609fc49e-f213-4cf2-805f-c318b8fe18f4.png)

2022-01-16 12:48 UTC, ericfennis commented
@pandrr @Andreto I fixed that in the formats, see suggestions.

2022-01-19 09:40 UTC, pandrr commented
thanks i commited those requests.

2022-01-19 13:37 UTC, ericfennis approved these changes
@pandrr Awesome work!

2022-01-19 13:38 UTC, ericfennis commented
@locness3 You ok with the naming of the files?

2022-01-27 20:33 UTC, merged