Add Subscript icon
lucide-icons/lucide pull request #459
Opened 2021-12-27 08:57 UTC by nabanita-sarkar

### Subscript icon 
![image](https://user-images.githubusercontent.com/36895154/147454179-704a5ccd-e8aa-419d-8329-8faf4ec93bd7.png)

### Icon request
Closes #431 
### Original icon request from feather
https://github.com/feathericons/feather/issues/511#issue-389037358

2021-12-27 21:40 UTC, ericfennis requested changes
Nice work, small optimisations for the code to make it smaller

2021-12-27 21:40 UTC, ericfennis commented on icons/subscript.svg
> +	<path d="M20 19L16 19C16 17.5 16.4417 17 17.5 16.5C18.5583 16 20 15.3338 20 14.0015C20.0007 13.5295 19.8294 13.0725 19.5163 12.7115C19.2033 12.3504 18.7688 12.1086 18.2897 12.0288C17.8106 11.949 17.
Formatting and minifying path
```suggestion
  <path d="m4 5 8 8" />
  <path d="m12 5-8 8" />
  <path d="M20 19h-4c0-1.5.44-2 1.5-2.5S20 15.33 20 14c0-.47-.17-.93-.48-1.29a2.11 2.11 0 0 0-2.62-.44c-.42.24-.74.62-.9 1.07" />
```

2021-12-28 05:30 UTC, nabanita-sarkar commented
Thanks. I will optimize in future

2021-12-29 16:21 UTC, ericfennis approved these changes
Awesome!

2021-12-30 18:45 UTC, nabanita-sarkar commented
Is there something else for me to do so that this pr can be merged?

2021-12-31 07:53 UTC, mittalyashu commented
@ericfennis Should we also add "math" tag?

2022-01-01 10:20 UTC, merged

2022-01-04 19:01 UTC, ericfennis commented
@mittalyashu I'm not exactly sure what you mean. Not the sigma (SUM) icon right?
https://lucide.dev/icon/sigma