feat: add dice icons
lucide-icons/lucide pull request #468
Opened 2022-01-11 08:37 UTC by mittalyashu

| Preview |
| --- |
|  <img width="417" alt="CleanShot 2022-01-11 at 14 03 05@2x" src="https://user-images.githubusercontent.com/29014463/148908610-451be3ce-9c5d-47cd-81d8-5b83eeafa875.png"> |

2022-01-11 08:38 UTC, mittalyashu commented
My first thoughts are the dice (1-6) after quite thin. What do you guys think?

2022-01-15 22:23 UTC, ericfennis commented
@mittalyashu Nice icons, yeah the dots lookes a bit thin.

Did you saw @johnletey s icon from feather [#918](https://github.com/feathericons/feather/pull/918/files?short_path=3795b10#diff-3795b1030c559e2db335c718b2c7ad01ab25caf531433fdda69dae4212e13d66)?

2022-01-20 19:05 UTC, mittalyashu commented
@ericfennis I don't see much difference except the width/height is 18px. 🤔

2022-02-01 16:42 UTC, ericfennis commented
Width of the box needs to be 18 to match with the rectangle icon.

Maybe use the dots from `divide`?

2022-02-04 15:32 UTC, mittalyashu commented
Using the dot from `divide` will not work either 😂 

<img width="101" alt="CleanShot 2022-02-04 at 21 02 03@2x" src="https://user-images.githubusercontent.com/29014463/152556559-de4c63e7-a41e-4d03-8da7-08a0018f0b24.png">

2022-02-05 11:23 UTC, ericfennis commented
@mittalyashu Ok never mind, the other ones looks better 😆 .
But keep the 18 px rectangle, I think that will look fine.

2022-03-15 19:27 UTC, ericfennis requested changes

2022-03-15 19:27 UTC, ericfennis commented on icons/dice-1.svg
> +  <path d="M21 4.8A1.8 1.8 0 0019.2 3H4.8A1.8 1.8 0 003 4.8v14.4A1.8 1.8 0 004.8 21h14.4a1.8 1.8 0 001.8-1.8V4.8z" />
```suggestion
  <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />
```

2022-03-15 19:27 UTC, ericfennis commented on icons/dice-2.svg
> +  <path d="M21 4.8A1.8 1.8 0 0019.2 3H4.8A1.8 1.8 0 003 4.8v14.4A1.8 1.8 0 004.8 21h14.4a1.8 1.8 0 001.8-1.8V4.8z" />
```suggestion
  <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />
```

2022-03-15 19:27 UTC, ericfennis commented on icons/dice-3.svg
> +  <path d="M21 4.8A1.8 1.8 0 0019.2 3H4.8A1.8 1.8 0 003 4.8v14.4A1.8 1.8 0 004.8 21h14.4a1.8 1.8 0 001.8-1.8V4.8z" />
```suggestion
  <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />
```

2022-03-15 19:27 UTC, ericfennis commented on icons/dice-4.svg
> +  <path d="M21 4.8A1.8 1.8 0 0019.2 3H4.8A1.8 1.8 0 003 4.8v14.4A1.8 1.8 0 004.8 21h14.4a1.8 1.8 0 001.8-1.8V4.8z" />
```suggestion
  <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />
```

2022-03-15 19:27 UTC, ericfennis commented on icons/dice-5.svg
> +  <path d="M21 4.8A1.8 1.8 0 0019.2 3H4.8A1.8 1.8 0 003 4.8v14.4A1.8 1.8 0 004.8 21h14.4a1.8 1.8 0 001.8-1.8V4.8z" />
```suggestion
  <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />
```

2022-03-15 19:27 UTC, ericfennis commented on icons/dice-6.svg
> +  <path d="M21 4.8A1.8 1.8 0 0019.2 3H4.8A1.8 1.8 0 003 4.8v14.4A1.8 1.8 0 004.8 21h14.4a1.8 1.8 0 001.8-1.8V4.8z" />
```suggestion
  <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />
```

2022-03-19 10:42 UTC, ericfennis commented
@mittalyashu Thanks for changing, can you add some tags as well?

2022-03-19 14:17 UTC, Bowero commented
<img width="910" alt="Screenshot 2022-03-19 at 15 09 43" src="https://user-images.githubusercontent.com/14151691/159124693-51072f4b-38a0-47b5-beaf-cfecc1f3c333.png">

I made a version with thicker dots. Personally I think that fits the style better.

Also, a proposal for the tags:

```json
"dice-1": [
  "dice",
  "random",
  "tabletop"
],
"dice-2": [
  "dice",
  "random",
  "tabletop"
],
"dice-3": [
  "dice",
  "random",
  "tabletop"
],
"dice-4": [
  "dice",
  "random",
  "tabletop"
],
"dice-5": [
  "dice",
  "random",
  "tabletop"
],
"dice-6": [
  "dice",
  "random",
  "tabletop"
],
```

2022-03-20 06:30 UTC, mittalyashu commented
@Bowero We've to keep the width and height of the square at `18px`.

2022-03-26 20:33 UTC, ericfennis approved these changes

2022-03-26 20:33 UTC, merged

2026-02-05 13:03 UTC, Spleefies commented
I think that the version with bigger dots looks better.