add package plus, minus, x, search, check icons
lucide-icons/lucide pull request #474
Opened 2022-01-14 12:44 UTC by Reund0

adding package group icons  including:

package-plus icon,

![package-plus](https://user-images.githubusercontent.com/52788288/149517210-b801a9f4-2d9d-4884-ab6d-40e811bae517.png)

package-minus icon,

![package-minus](https://user-images.githubusercontent.com/52788288/149517205-098b7254-0ef8-4723-909c-8552420c25ac.png)

package-search icon,

![package-search](https://user-images.githubusercontent.com/52788288/149517215-c4b919e3-4e53-471d-b1d2-05b0ed594d3c.png)

package-x icon,

![package-x](https://user-images.githubusercontent.com/52788288/149517219-005180b5-bb3f-4ed0-9909-9f7d7cc8d6de.png)

package-check icon.

![package-check](https://user-images.githubusercontent.com/52788288/149517221-eacde687-965b-4a44-8d83-ed4986790435.png)

2022-01-15 08:08 UTC, bennetfabian approved these changes

2022-01-15 22:19 UTC, ericfennis requested changes
@Reund0 Nice icons! These are really welcome.

Did you read the  [Lucide Icon Design guide](https://github.com/lucide-icons/lucide/blob/master/docs/ICON_DESIGN_GUIDE.md)?
We like to see 1px padding of the 24x24 pixel grid. I see there is some place to move the icon a bit to the right to center it.

![image](https://user-images.githubusercontent.com/11825403/149639246-55156e5d-d65f-4251-b48d-94525c57ba81.png)
Also maybe you can try to increase the sub-icons in the corner a bit if it fits. 
If you need any help let me know.

Other things we like to see is that the icon if formatted like all the other icons. See [Global Attributes](https://github.com/lucide-icons/lucide/blob/master/docs/ICON_DESIGN_GUIDE.md#global-attributes) in icon design guide, or look a an other icon in the icons directory.

And at least please add some tags to the `tags.json`  located in the root directory. This improves the search engine on the website. So other devs and designers will find your beautiful icons!

2022-01-20 19:09 UTC, mittalyashu commented
The package search icon seems a bit congested.

@Reund0 Can you try increase the size of circle of magnifying glass?

2022-01-21 04:08 UTC, Reund0 commented
> The package search icon seems a bit congested.
> 
> @Reund0 Can you try increase the size of circle of magnifying glass?

Is it okay to not have 2px spacing?

2022-01-23 14:20 UTC, mittalyashu commented
@Reund0 

> Is it okay to not have 2px spacing?

Ah! I see, what you mean. That will be bit tricky 😞 

@ericfennis Do you think it would be good idea to keep the package icon edge to edge that way the children icon (not just search other icons as well) will get more space.

2022-01-25 19:31 UTC, ericfennis commented
@mittalyashu I think it's better to leave it centered, that matches better it the current package icon if used together.

2022-01-25 19:32 UTC, ericfennis commented
@Reund0 Can you also increase the size of the X a bit in the package-x icon?

2022-02-04 08:34 UTC, Reund0 commented
> @Reund0 Can you also increase the size of the X a bit in the package-x icon?

I increased its size from 4x4 to 4.5x4.5 but again is it okay to ignore 2px spacing?

2022-02-05 12:10 UTC, ericfennis requested changes
The svgs shouldn't contain any "combined" paths. This renders not well in design programs like figma.
**Screenshot:**
<img width="523" alt="image" src="https://user-images.githubusercontent.com/11825403/152641411-f0b8021a-70c3-4840-8292-78dac425350c.png">

I added some suggestion to fix it!

2022-02-05 12:10 UTC, ericfennis commented on icons/package-search.svg
> +</svg>
```suggestion
  <path d="M21 10V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l2-1.14" />
  <path d="M16.5 9.4 7.55 4.24" />
  <path d="M12 12v10M3.29 7 12 12 3.29 7ZM12 12l8.71-5L12 12Z" />
  <circle cx="18.5" cy="15.5" r="2.5" />
  <path d="M20.27 17.27 22 19" />
</svg>

```

2022-02-05 12:10 UTC, ericfennis commented on icons/package-x.svg
> +</svg>
```suggestion
  <path d="M21 10V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l2-1.14" />
  <path d="M16.5 9.4 7.55 4.24" />
  <path d="M3.29 7 12 12m0 0 8.71-5M12 12v10" />
  <path d="m17 13 5 5m-5 0 5-5" />
</svg>

```

2022-02-05 12:10 UTC, ericfennis commented on icons/illustrator_x.svg
> +<svg
I think this file shouldn't be here. Probably copy of `package-x`

2022-02-22 20:51 UTC, merged