add business icon
lucide-icons/lucide pull request #496
Opened 2022-02-04 21:30 UTC by maxim-s-barabash

![company_3_1](https://user-images.githubusercontent.com/2724325/152605452-844ecbed-e34e-4896-9b47-90f1309f628f.png)

Icon Requests from Feather #119

2022-02-05 11:19 UTC, ericfennis commented
Welcome to the lucide community @maxim-s-barabash!
Is this not a duplicate of [`building`](https://lucide.dev/icon/building) ?

2022-02-05 16:02 UTC, maxim-s-barabash commented
no.  this icon is associated with companies and businesses

2022-02-07 11:41 UTC, maxim-s-barabash commented
@ericfennis, what are the chances that he will be accepted?

2022-02-09 19:14 UTC, ericfennis commented
hmm. I think this feels a bit as a second building icon to me.
What do you think @locness3

2022-03-10 18:08 UTC, mittalyashu commented
This gives more of an enterprise feeling 😅

2022-03-19 13:50 UTC, Bowero commented
Personally I agree that this has different use cases than `building`.

2022-03-28 16:16 UTC, maxim-s-barabash commented
I renamed the icon

2022-03-28 21:05 UTC, delnyn commented
Welcome! Thanks for your contribution. But the icon violates the guidelines. We can probably make it slightly different to make it stick to the guidelines?

2022-03-30 18:12 UTC, delnyn commented
![image](https://user-images.githubusercontent.com/45879791/160903115-b6d13cec-00e5-43e3-96f5-362244fa4e19.png)
here are some ideas

2022-03-31 19:01 UTC, ericfennis commented
@delnyn Can you try make a variant with a line on the bottom.

2022-04-02 21:41 UTC, delnyn commented
![image](https://user-images.githubusercontent.com/45879791/161402090-98e22e8b-9cb7-4c82-a574-d5d50d15fea6.png)
Like this?

2022-04-03 15:52 UTC, ericfennis commented
Niceee, I think these icons will match better with the existing "building" icons. What do you think @maxim-s-barabash @delnyn ?

2022-04-03 21:34 UTC, delnyn commented
totally agree

2022-04-09 18:07 UTC, ericfennis requested changes

2022-04-09 18:07 UTC, ericfennis commented on icons/building-2.svg
> +</svg>
```suggestion
<svg 
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <path d="M6 22V4c0-.27 0-.55.07-.82.07-.27.2-.52.4-.72.19-.2.44-.32.7-.39C7.46 2 8.73 2 9 2h7c.27 0 .55 0 .82.07.27.07.52.2.72.4.2.19.32.44.39.7.07.28.07.56.07.83v18H6Z" />
  <path d="M2 14v6c0 1.1.9 2 2 2h2V12H4c-.27 0-.55 0-.82.07-.27.07-.52.2-.72.4-.19.19-.32.44-.39.71A3.4 3.4 0 0 0 2 14Z" />
  <path d="M20.82 9.07A3.4 3.4 0 0 0 20 9h-2v13h2a2 2 0 0 0 2-2v-9c0-.28 0-.55-.07-.82-.07-.27-.2-.52-.4-.72-.19-.19-.44-.32-.71-.39Z" />
  <path d="M10 6h4" />
  <path d="M10 10h4" />
  <path d="M10 14h4" />
  <path d="M10 18h4" />
</svg>
```

2022-04-12 18:42 UTC, ericfennis approved these changes

2022-04-12 18:42 UTC, merged