Center tag icon
lucide-icons/lucide pull request #523
Opened 2022-03-14 22:59 UTC by aa0-fyi

Resolve issue #504.

2022-03-15 18:54 UTC, ericfennis requested changes
You moved the icon a bit. What feels like the solution but there is problem by doing this. By centering the icon the path will add some decimals to some points. If rendered on low pixel displays the icon will appear blurry. (See screenshot, left is yours). We can fix this by keep the points rounded. I fixed it by extended the `tag` icon so it centered again, but keeping the icon pixel perfect.

<img width="541" alt="Screenshot 2022-03-15 at 19 43 15" src="https://user-images.githubusercontent.com/11825403/158449848-2bbd4ff5-d7bc-491d-b804-6d1d1c86ad7a.png">

2022-03-16 21:18 UTC, aa0-fyi commented on icons/tag.svg
> +  <line x1="7.417" x2="7.427" y1="7.42" y2="7.42"/>
Excellent catch.

2022-03-16 21:54 UTC, aa0-fyi commented on icons/tag.svg
> +  <line x1="7.417" x2="7.427" y1="7.42" y2="7.42"/>
A new problem appears to be the left-center point of the outside of the tag. That point is no longer rounded on full resolution. I attempted to resolve this but was unsuccessful while maintaining pixel perfection.

2022-03-19 10:41 UTC, ericfennis commented on icons/tag.svg
> +  <line x1="7.417" x2="7.427" y1="7.42" y2="7.42"/>
I think this is the best solution. Most important thing is that the icon not look blurry on low resolution screens

2022-03-19 10:41 UTC, merged