feat: add frame icon
lucide-icons/lucide pull request #553
Opened 2022-04-09 13:59 UTC by Bowero

This PR adds a frame icon, as discussed in #531.

The chosen implementation is frame 1.

![image](https://user-images.githubusercontent.com/14151691/162577454-fe79a49f-8abd-4b81-a1c0-f6f8a49f57f3.png)

2022-04-09 18:00 UTC, ericfennis requested changes
@Bowero Nice work!!
One change requested.

2022-04-09 18:00 UTC, ericfennis commented on icons/frame.svg
> +    <path d="M7 4v16M17 4v16M4 7h16M4 17h16" />
Can you split up the path in separate paths. Combined paths will sometimes render weirdly in  design programs.

2022-04-11 19:01 UTC, karsa-mistmere commented
I'd suggest for this to have the same dimensions as `crop`:
![image](https://user-images.githubusercontent.com/17746067/162810824-7bf3e113-5a11-4032-b920-cc0e0d3f31dd.png)

2022-04-12 07:41 UTC, karsa-mistmere requested changes

2022-04-12 07:41 UTC, karsa-mistmere commented on icons/frame.svg
> +    <path d="M7 4v16M17 4v16M4 7h16M4 17h16" />
```suggestion
  <line x1="22" y1="6" x2="2" y2="6"/>
  <line x1="22" y1="18" x2="2" y2="18"/>
  <line x1="6" y1="2" x2="6" y2="22"/>
  <line x1="18" y1="2" x2="18" y2="22"/>
```

2022-04-12 18:56 UTC, merged