Fixes `cpu`
lucide-icons/lucide pull request #572
Opened 2022-04-12 14:47 UTC by karsa-mistmere

This PR fixes design guideline violations of the `cpu` icon.
![image](https://user-images.githubusercontent.com/17746067/162989617-2af84dc5-9c54-43c7-9f85-11f3f0933a9b.png)
(Note: the central rectangle remains unrounded)

2022-04-15 10:25 UTC, ericfennis commented
What do you think of this?
<img width="339" alt="image" src="https://user-images.githubusercontent.com/11825403/163560225-6c61d094-1ff1-455d-afaf-33b4abc2d2b0.png">

2022-04-16 15:58 UTC, karsa-mistmere commented
Yeah, that also LGTM.

2022-04-19 19:05 UTC, ericfennis commented
@karsa-mistmere I think we need some more opinions on this. Curious what other people think. I'm fine with both 😆

2022-04-20 10:12 UTC, karsa-mistmere commented
This is also maybe an option:
![image](https://user-images.githubusercontent.com/17746067/164205004-03a595a3-b6dd-4095-8622-e2cfe81e4e94.png)

100%:
![image](https://user-images.githubusercontent.com/17746067/164205329-b00a60b7-37a1-4326-9a97-20b3f8f5358d.png)

200%:
![image](https://user-images.githubusercontent.com/17746067/164205276-2e1868e7-2787-4817-a8d6-42cbd9e4c2cf.png)



Right now, I think `cpu-2` (yours) looks best compared to square for example.

2022-04-24 10:14 UTC, ericfennis commented
yeah you right, its nice to have it consistant.

2022-04-24 10:18 UTC, ericfennis requested changes
Here you go.

2022-04-24 10:18 UTC, ericfennis commented on icons/cpu.svg
> +  <rect x="5" y="5" width="14" height="14" rx="2" ry="2" />
```suggestion
  <rect x="4" y="4" width="16" height="16" rx="2" ry="2" />
```

2022-04-24 10:18 UTC, ericfennis commented on icons/cpu.svg
> +  <line x1="2" y1="14" x2="5" y2="14" />
```suggestion
  <line x1="9" y1="2" x2="9" y2="4" />
  <line x1="15" y1="2" x2="15" y2="4" />
  <line x1="9" y1="21" x2="9" y2="22" />
  <line x1="15" y1="20" x2="15" y2="22" />
  <line x1="20" y1="9" x2="22" y2="9" />
  <line x1="20" y1="14" x2="22" y2="14" />
  <line x1="2" y1="9" x2="4" y2="9" />
  <line x1="2" y1="14" x2="4" y2="14" />
```

2022-05-02 19:53 UTC, ericfennis approved these changes

2022-05-07 15:07 UTC, merged