Added `sailboat`
lucide-icons/lucide pull request #665
Opened 2022-05-10 16:19 UTC by karsa-mistmere

closes #616

2022-07-19 09:32 UTC, karsa-mistmere commented
Yeah, I think we should probably go with this one. I had my reservations a month ago, but it definitely looks much more recognisable than mine.

2022-07-31 17:44 UTC, ericfennis requested changes

2022-07-31 17:44 UTC, ericfennis commented on icons/sailboat.svg
> +  <path d="M10 18V2" />
Allright here is the path!

```suggestion
  <path d="M22 18H2a4 4 0 0 0 4 4h12a4 4 0 0 0 4-4Z" />
  <path d="M10 14V2l11 12H10Z" />
  <path d="M10 14V2L3 14h7Z" />
  <path d="M10 2v16" />
```

2022-08-18 07:58 UTC, karsa-mistmere commented on icons/sailboat.svg
> +  <path d="M10 2v16" />
```suggestion
  <path d="M22 18H2a4 4 0 0 0 4 4h12a4 4 0 0 0 4-4Z"/>
  <path d="M21 14 10 2 3 14h18Z"/>
  <path d="M10 2v16"/>
```

2022-08-18 16:20 UTC, ericfennis approved these changes

2022-08-18 16:20 UTC, merged