Add `cloud-sun-rain`
lucide-icons/lucide pull request #673
Opened 2022-05-15 10:49 UTC by it-is-not

<img src="https://user-images.githubusercontent.com/72697755/168468726-5d33feb4-c068-4b9f-9ec6-8b3d2dc3f32e.png" alt="">
<img src="https://user-images.githubusercontent.com/72697755/168468726-5d33feb4-c068-4b9f-9ec6-8b3d2dc3f32e.png" alt="" width="74">

2022-05-16 08:35 UTC, karsa-mistmere commented on icons/cloud-sun-rain.svg
> +  <path d="M7.5 18v3"/>
The NW and NE strokes are a bit off compared to the rest:
```suggestion
  <path d="M12 2v2" />
  <path d="m4.93 4.93L6.34 6.34" />
  <path d="M20 12h2" />
  <path d="M15.97 12.5A4 4 0 0 0 9.5 8.88" />
  <path d="M17.66 6.34L19.07 4.93" />
  <path d="M15.54 22a3.4 3.4 0 0 0-1.88-6.2h-1.35a5.3 5.3 0 0 0-5.46-3.78 5.24 5.24 0 0 0-4.8 4.6 5.33 5.33 0 0 0 1.46 4.4" />
  <path d="M11.5 19v3" />
  <path d="M7.5 18v3" />
```

2022-05-30 15:37 UTC, ericfennis approved these changes
The drops looks a bit weird to me. But I see there is no room to move them a bit to the bottom. So it ok for now. Maybe can take a look later

2022-06-12 14:47 UTC, ericfennis commented
@it-is-not I will say the first one.

2022-06-16 07:07 UTC, ericfennis requested changes
@it-is-not Can you update the icon?

2022-06-17 08:18 UTC, ericfennis approved these changes

2022-06-17 08:18 UTC, merged