Fixes various weather icon guideline violations
lucide-icons/lucide pull request #695
Opened 2022-05-30 11:59 UTC by karsa-mistmere

This PR attempts to fix various design guideline violations found in weather icons, mostly relating to the position and size of diagonal rays of sun icons & as well as making the shape consistent and pixel perfect across all cloud icons.

![image](https://user-images.githubusercontent.com/17746067/170987746-da7a3528-ce8f-4cc4-8832-3bc824813452.png)
![weather-fixes](https://user-images.githubusercontent.com/17746067/170987875-6f07e47d-eaca-4802-8b86-81ba7cfe2cc5.png)

2022-05-30 13:09 UTC, karsa-mistmere commented
Note: #673 is related, since it adds icons containing these corrected shapes.

2022-05-30 15:25 UTC, ericfennis commented
@karsa-mistmere Awesome work!

2022-06-16 07:08 UTC, ericfennis requested changes
conflicts

2022-06-17 08:20 UTC, ericfennis approved these changes

2022-06-17 08:21 UTC, merged