Add table-2 icon
lucide-icons/lucide pull request #726
Opened 2022-06-14 14:38 UTC by abejenaru

Merge from upstream Feather project

2022-06-14 15:12 UTC, karsa-mistmere commented
@abejenaru: Nice to have this! 😊
Could you update the `tags.json` file with this new icon?

2022-06-14 15:39 UTC, karsa-mistmere requested changes
I think we could also add `spreadsheet` as a tag.

2022-06-14 15:39 UTC, karsa-mistmere commented on tags.json
>      "grid"
```suggestion
    "grid",
    "spreadsheet"
```

2022-06-16 11:44 UTC, ericfennis approved these changes

2022-06-16 11:58 UTC, karsa-mistmere approved these changes

2022-06-16 11:59 UTC, merged