Add building icon
lucide-icons/lucide pull request #91
Opened 2020-10-11 13:00 UTC by delnyn

The  building icon. *(cf #78)*

2020-10-11 21:29 UTC, ericfennis requested changes
🚀 Nice work @delnyn .

I have some small code improvements.

2020-10-11 21:29 UTC, ericfennis commented on building.svg
> +<path d="M4 4C4 2.89543 4.79594 2 5.77778 2H18.2222C19.2041 2 20 2.89543 20 4V20C20 20.5304 19.8127 21.0391 19.4793 21.4142C19.1459 21.7893 18.6937 22 18.2222 22H5.77778C5.30628 22 4.8541 21.7893 4.5
```suggestion
  <rect x="4" y="2" width="16" height="20" rx="2" ry="2" />
```

2020-10-11 21:29 UTC, ericfennis commented on building.svg
> +<path d="M8 14H8.01" stroke="black" stroke-width="2" stroke-linecap="round"/>
```suggestion
  <path d="M9 22v-4h6v4" />
  <path d="M8 6h.01" />
  <path d="M16 6h.01" />
  <path d="M12 6h.01" />
  <path d="M12 10h.01" />
  <path d="M12 14h.01" />
  <path d="M16 10h.01" />
  <path d="M16 14h.01" />
  <path d="M8 10h.01" />
  <path d="M8 14h.01" />
```

2020-10-11 21:29 UTC, ericfennis commented on tags.json
> +  "building": ["organisations"],
I prefer singular, because the object is singular as well.
```suggestion
  "building": ["organisation"],
```

2020-10-12 17:16 UTC, delnyn commented
OK,  commited every changes 👍

2020-10-13 06:46 UTC, ericfennis commented
@delnyn Awesome work!

2020-10-13 06:46 UTC, merged

2020-10-13 15:38 UTC, locness3 commented
Nice work!

2020-10-13 16:24 UTC, delnyn commented
Oops! Something is wrong, the icon is directly in the root of the repo 😓 sorry, I'm going to fix that...