Adds `nfc` icons
lucide-icons/lucide pull request #960
Opened 2023-02-28 15:05 UTC by karsa-mistmere

closes #938

2023-03-05 10:48 UTC, jguddas requested changes

2023-03-05 10:48 UTC, jguddas commented on icons/nfc.svg
> +  <path d="M16.37 2A20.16 20.16 0 0 1 19 12c0 3.65-.96 7.07-2.63 10"/>
```suggestion
  <path d="M12.91 4.1a15.91 15.91 0 0 1 .01 15.8"/>
  <path d="M16.37 2a20.16 20.16 0 0 1 0 20"/>
```

2023-03-05 10:48 UTC, jguddas commented on icons/smartphone-nfc.svg
> +  <path d="M19.91 4.1A15.91 15.91 0 0 1 22 12c0 2.88-.76 5.58-2.08 7.9" />
```suggestion
  <path d="M16.46 6.21a11.76 11.76 0 0 1 0 11.58" />
  <path d="M19.91 4.1a15.91 15.91 0 0 1 .01 15.8" />
```

2023-03-06 20:08 UTC, ericfennis approved these changes

2023-03-06 20:11 UTC, merged