Adds `parking-*` and `parking-*-off` icons
lucide-icons/lucide pull request #972
Opened 2023-02-28 16:56 UTC by karsa-mistmere

closes #901

2023-03-04 09:57 UTC, jguddas requested changes

2023-03-04 09:57 UTC, jguddas commented on icons/parking-circle.svg
> +  <path d="M9 17v-4m0 0V7h4a3 3 0 0 1 3 3v0a3 3 0 0 1-3 3H9Z" />
```suggestion
  <path d="M9 17V7h4a3 3 0 0 1 0 6H9" />
```

2023-03-04 09:57 UTC, jguddas commented on icons/parking-square.svg
> +  <path d="M9 17v-4m0 0V7h4a3 3 0 0 1 3 3v0a3 3 0 0 1-3 3H9Z" />
```suggestion
  <path d="M9 17V7h4a3 3 0 0 1 0 6H9" />
```

2023-03-20 19:42 UTC, ericfennis approved these changes

2023-03-20 19:42 UTC, merged