Add `atom`ic icon
lucide-icons/lucide pull request #991
Opened 2023-03-28 20:12 UTC by danielbayley

![atom](https://user-images.githubusercontent.com/7797479/228355818-77201130-13a1-4a8a-8f0e-5079859dc506.png)

2023-03-29 06:38 UTC, karsa-mistmere commented
Oh, cool, I wanted to add an atom icon a while back, but my design was always too dense because of the 6-fold rotational symmetry, and since I didn't think it could work (i.e. still be recognisable as an atom) with 4-fold symmetry, I didn't even try. What a bummer, it very clearly does work. 😅 

One thing though, I think we should go for a perfectly symmetric version (this also solves the issue of the <2px gap between the atom core and the electron cloud):
![atom](https://user-images.githubusercontent.com/17746067/228446184-8845b3dc-eaed-4d68-b9b6-46d7709f25a6.svg)

2023-03-29 09:51 UTC, danielbayley commented
> I think we should go for a perfectly symmetric version

@karsa-mistmere Do you mean make the electrons orbit at a 90° angle to each other? (they’re currently ~45°…)

2023-03-29 09:55 UTC, karsa-mistmere commented
> @karsa-mistmere Do you mean make the electrons orbit at a 90° angle to each other? (they’re currently ~45°…)

I mean like this (having 4-fold rotational symmetry instead of just 2-fold):
![atom](https://user-images.githubusercontent.com/17746067/228446184-8845b3dc-eaed-4d68-b9b6-46d7709f25a6.svg)

2023-03-29 12:15 UTC, karsa-mistmere commented on icons/atom.svg
> +  <ellipse transform="matrix(0.7071 -0.7071 0.7071 0.7071 -4.9706 12)" cx="12" cy="12" rx="12" ry="5.4" />
While pretty neat, I'm afraid we don't support transforms, so they'll have to be removed. :(
```suggestion
  <path d="M20.2 20.2c2.04-2.03.02-7.36-4.5-11.9-4.54-4.52-9.87-6.54-11.9-4.5-2.04 2.03-.02 7.36 4.5 11.9 4.54 4.52 9.87 6.54 11.9 4.5Z" />
  <path d="M15.7 15.7c4.52-4.54 6.54-9.87 4.5-11.9-2.03-2.04-7.36-.02-11.9 4.5-4.52 4.54-6.54 9.87-4.5 11.9 2.03 2.04 7.36.02 11.9-4.5Z" />
```

2023-03-29 12:19 UTC, karsa-mistmere requested changes

2023-03-29 12:19 UTC, karsa-mistmere commented on icons/atom.json
> +    "physics"
```suggestion
    "physics",
    "particle",
    "element",
    "molecule"
```

2023-03-29 15:49 UTC, danielbayley commented
@karsa-mistmere Also, a couple of alternates…

<img width="384" alt="Artboard 1@30x" src="https://user-images.githubusercontent.com/7797479/228595014-23a78635-0ff9-4081-a876-dcd58aac0c67.png">

2023-03-29 16:30 UTC, karsa-mistmere commented
We don't support fills, so there's that. 😅 

Not sure about the alternate design you pushed, I'd more likely think of that as orbiting planets not as an atom.

2023-03-29 17:01 UTC, danielbayley commented
> We don't support fills

They aren’t fills 😉 (those are just 2 strokes…)

2023-03-29 17:03 UTC, karsa-mistmere commented
> They aren’t fills 😉 (those are just 2 strokes…)

That's kind of even worse, since we do want to keep support for customizable stroke width. :)

2023-03-29 17:08 UTC, danielbayley commented
> > They aren’t fills 😉 (those are just 2 strokes…)
> 
> That's kind of even worse, since we do want to keep support for customizable stroke width. :)

I see, makes sense… Just the top row is relevant then… Could be renamed as `orbit` and moved to a different PR…?

2023-04-09 09:53 UTC, ericfennis approved these changes

2023-04-09 09:54 UTC, merged