Improve `inbox` icon and add `inbox-full` icon
lucide-icons/lucide pull request #998
Opened 2023-03-29 17:36 UTC by danielbayley

![inbox-full](https://user-images.githubusercontent.com/7797479/228621658-28c0170c-c4d3-4da9-b298-67db5cd4ccd4.png)

2023-03-30 00:29 UTC, danielbayley commented
Potentially more…

<img width="384" alt="inboxes" src="https://user-images.githubusercontent.com/7797479/228697495-b7a3eb13-b0e2-41c9-b470-b34ec05cb43f.png">

2023-03-30 07:03 UTC, karsa-mistmere commented
Not quite sure about the flat design. Our current `inbox` icon surely is an odd one out (we don't normally use 3D-ish perspectives), but if we go for a rectangular design, it must not by any larger than `square` is, and I think a more traditional notch is probably more recognisable:
![image](https://user-images.githubusercontent.com/17746067/228755425-85f72b15-f6b4-4e7c-a591-8aaa5f2071b0.png)

This, however, does not solve the issues above, I'm afraid. :)
Sidenote-ish: what exactly would be the use cases for these extra icons?

2023-03-30 17:06 UTC, danielbayley commented
> what exactly would be the use cases for these extra icons?

Mostly for `git stash` and `git pop stash`, like for example in _[GitKraken](https://gitkraken.com)_ (below), but I thought they should probably be a set, related to todos/mail/notifications/whatever the use case is for the existing `inbox` icon…

<img width="599" alt="Screenshot 2023-03-30 at 5 54 44 pm" src="https://user-images.githubusercontent.com/7797479/228909734-f1383b7e-8ba3-4463-898e-a279899e822b.png">


> I think a more traditional notch is probably more recognisable

I though more rounded fits better with the rest of the set being very round in general…

<img width="256" alt="inbox-stash-3d" src="https://user-images.githubusercontent.com/7797479/228912010-136c096a-7d3e-420f-b622-c205223f1775.png">

<img width="256" alt="inbox-stash-tile" src="https://user-images.githubusercontent.com/7797479/228912031-90e15eb3-01f7-4da7-ba56-e1a7a3fd8a5c.png">

2023-03-30 17:20 UTC, karsa-mistmere commented
It's mostly the size that's the issue: square icons should not be larger than `square` itself to keep things looking consistent.

I'd be fine with the circular notch, it's just that it doesn't fit that well with the down pointing arrow. :)

2023-03-30 17:54 UTC, danielbayley commented
> It's mostly the size that's the issue: square icons should not be larger than `square` itself to keep things looking consistent.

![Artboard 1@10x](https://user-images.githubusercontent.com/7797479/228922533-ac0ec56a-f282-4031-88a8-63988a0af76b.png)

2023-03-31 13:37 UTC, karsa-mistmere commented
Not bad, although I'm still not absolutely sold about the flat inbox design, as said, it's maybe a better fit for Lucide in particular, but much less obvious than the very standard inbox shape we currently have.

How about a very slight redesign of the current inbox icon and using the same arrow shape as in `file/folder-in` and `file/folder-out`?
![image](https://user-images.githubusercontent.com/17746067/229133981-73465382-4508-4482-9c1b-38af69a92d72.png)

2023-04-03 19:29 UTC, danielbayley commented
> Added or changed icons
> 
> <img alt="icons/inbox-empty.svg" width="400" src="https://camo.githubusercontent.com/fc4f247f5dd5a8d98f28f14bd295abf1e33cde0b2227a4756bbe30808059986f/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a7a34674943413862476c755a5342344d5430694d54556949486b7850534935496942344d6a30694f53496765544939496a6b694943382b4943416750484268644767675a443069545463754d697730517a59754e5377304c4455754f4377304c6a51734e5334304c4455754d55777a4c44457a646a5a6a4d4377784c6a45734d4334354c4449734d69777961444530597a45754d5377774c4449744d4334354c4449744d6e59744e6d77744d6934314c5463754f574d744d43347a4c5441754e7930784c5445754d5330784c6a67744d533478494567334c6a4a364969417650694167494478736157356c4948677850534934496942354d5430694d544d69494867795053497a496942354d6a30694d544d694943382b4943416750477870626d556765444539496a4532496942354d5430694d544d6949486779505349794d53496765544939496a457a4969417650694167494478775958526f49475139496b30784e6977784d324d774c4449754d6930784c6a67734e4330304c44527a4c5451744d5334344c5451744e4349674c7a34675043397a646d632b49413d3d2e737667"> <img alt="icons/inbox-full.svg" width="400" src="https://camo.githubusercontent.com/376a09f4d5ac1b8bc566408cc0fefc4d2e4b7f7ddb4b76669ed15cbe0df24c6d/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a7a34674943413862476c755a5342344d5430694f43496765544539496a457a496942344d6a30694d79496765544939496a457a4969417650694167494478736157356c49486778505349784e69496765544539496a457a496942344d6a30694d6a456949486b79505349784d7949674c7a346749434138634746306143426b50534a4e4d5459734d544e6a4d4377794c6a49744d5334344c4451744e437730637930304c5445754f4330304c5451694943382b4943416750484268644767675a443069545463754d697730517a59754e5377304c4455754f4377304c6a51734e5334304c4455754d55777a4c44457a646a5a6a4d4377784c6a45734d4334354c4449734d69777961444530597a45754d5377774c4449744d4334354c4449744d6e59744e6d77744d6934314c5463754f574d744d43347a4c5441754e7930784c5445754d5330784c6a67744d533478494567334c6a4a3649694176506941384c334e325a7a34672e737667"> <img alt="icons/inbox-in.svg" width="400" src="https://camo.githubusercontent.com/72522dba1c600f4a41c3805b2887bccb582e40dae2a010e8d42b9f4e92f3167c/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a7a34674943413862476c755a5342344d5430694f43496765544539496a457a496942344d6a30694d79496765544939496a457a4969417650694167494478736157356c49486778505349784e69496765544539496a457a496942344d6a30694d6a456949486b79505349784d7949674c7a346749434138634746306143426b50534a4e4d5459734d544e6a4d4377794c6a49744d5334344c4451744e437730637930304c5445754f4330304c5451694943382b4943416750484268644767675a443069545467734e4567334c6a4a444e6934314c4451734e5334344c4451754e4377314c6a51734e53347854444d734d544e324e6d4d774c4445754d5377774c6a6b734d6977794c444a6f4d54526a4d5334784c4441734d6930774c6a6b734d69307964693032624330794c6a55744e793435597930774c6a4d744d4334334c5445744d5334784c5445754f4330784c6a4567534445324969417650694167494478776232783562476c755a53427762326c7564484d39496a6b734f4341784d6977784d5341784e5377344969417650694167494478736157356c49486778505349784d69496765544539496a516949486779505349784d69496765544939496a457849694176506941384c334e325a7a34672e737667"> <img alt="icons/inbox-out.svg" width="400" src="https://camo.githubusercontent.com/33123cc7bf76b5a76eac8fb81c4c2136a41a672d1bc298f0f139b9fd11781875/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a7a346749434138634746306143426b50534a4e4f437730534463754d6b4d324c6a55734e4377314c6a67734e4334304c4455754e4377314c6a464d4d7977784d335932597a41734d5334784c4441754f5377794c4449734d6d67784e474d784c6a45734d4377794c5441754f5377794c544a324c545a734c5449754e5330334c6a6c6a4c5441754d7930774c6a63744d5330784c6a45744d5334344c5445754d5342494d5459694943382b4943416750477870626d556765444539496a676949486b78505349784d79496765444939496a4d6949486b79505349784d7949674c7a34674943413862476c755a5342344d5430694d54596949486b78505349784d79496765444939496a4978496942354d6a30694d544d694943382b4943416750484268644767675a443069545445324c44457a597a41734d6934794c5445754f4377304c5451734e484d744e4330784c6a67744e4330304969417650694167494478776232783562476c755a53427762326c7564484d39496a45314c446b674d5449734e6941354c446b694943382b4943416750477870626d556765444539496a4579496942354d5430694d544d6949486779505349784d69496765544939496a59694943382b4944777663335a6e5069413d2e737667">

Cool! Super useful bot. Nice work @jguddas!

2023-04-05 10:22 UTC, ericfennis submitted a review, later dismissed
LGTM!

2023-04-06 15:36 UTC, karsa-mistmere requested changes

2023-04-06 15:36 UTC, karsa-mistmere commented on icons/inbox-full.svg
> +  <path d="M7.2,4C6.5,4,5.8,4.4,5.4,5.1L3,13v6c0,1.1,0.9,2,2,2h14c1.1,0,2-0.9,2-2v-6l-2.5-7.9c-0.3-0.7-1-1.1-1.8-1.1 H7.2z" />
Three of these paths could be merged (both here and in every other icon):
```suggestion
  <path d="M3 13h5c0 2.2 1.8 4 4 4s4-1.8 4-4h5" />
  <path d="M7.2 4c-.7 0-1.4.4-1.8 1.1L3 13v6c0 1.1.9 2 2 2h14a2 2 0 0 0 2-2v-6l-2.5-7.9c-.3-.7-1-1.1-1.8-1.1H7.2Z" />
```

2023-04-06 15:36 UTC, karsa-mistmere commented on icons/inbox-in.svg
Still not really a fan of how the arrow's head and the corners of the notch meet, how about maybe introducing a tiny bit of rounding to the corners to somewhat mitigate that sharpness?

![image](https://user-images.githubusercontent.com/17746067/230427797-813966a3-0172-4545-afd6-5eab3645b0f2.png)

(√2/2 px rounding in this instance)

2023-04-06 15:43 UTC, danielbayley commented on icons/inbox-empty.svg
Ah yeah, good catch. They’re simply the wrong way around. Too many tabs open… 🙈

2023-04-09 11:42 UTC, karsa-mistmere requested changes
I feel bad, for not approving this already, but there are still a few issues. 🙈 
1) There's a sharp corner in the top left corner that I believe was unintentional.
2) All of them are slightly off center to the bottom, I'd prefer if they were perfectly centered like our current inbox icon is.

2023-04-09 15:16 UTC, danielbayley commented
> I feel bad, for not approving this already, but there are still a few issues. 🙈
> 
> 1. There's a sharp corner in the top left corner that I believe was unintentional.
> 2. All of them are slightly off center to the bottom, I'd prefer if they were perfectly centered like our current inbox icon is.

Not sure what happened… Illustrator seems to introduce problems at times.

2023-04-14 20:46 UTC, karsa-mistmere requested changes
Hm... these appear the same to me, maybe I'm miscommunicating.

What I mean is that this new inbox is not vertically centered:
![image](https://user-images.githubusercontent.com/17746067/232151260-337c6a28-5b0a-4106-baa2-875f7b1a28c1.png)

The sharp corner is also still there:
![image](https://user-images.githubusercontent.com/17746067/232151432-f6efdef5-2146-4983-81a0-d140949552ef.png)

2023-04-15 09:36 UTC, danielbayley commented
> The sharp corner is also still there:

Fixed. Not sure what happened there…

> this new inbox is not vertically centered:

Well it’s 18x17px (to fit nicely around the inside elements), so there’s a decision to make… Unless you’re suggesting to move it up 0.5px? (surely not)

1. Make it 18x18px by extending the top area by 1px
2. Make it 18x18px by extending the bottom area by 1px
3. Leave it 18x17px and either leave it as is, or move the whole thing up by 1px… still not vertically centered

Here’s what those look like:

<img width="377" alt="Untitled" src="https://user-images.githubusercontent.com/7797479/232205108-3ce5e77b-dfda-4c43-937b-6ac2b5712c7b.png">

I think:

1. Messes up the inside elements, as they don’t fit as nicely
2. Makes the base look too chunky

What do you think?

2023-04-16 15:53 UTC, ericfennis commented
@danielbayley Let's go for a squared icon. so 18x18 (top or bottom-right). Half pixels is not an option that will look blurry on low-resolution screens.

2023-04-16 15:56 UTC, karsa-mistmere commented
@ericfennis: We could also maybe go for one that's 20x18?

![image](https://user-images.githubusercontent.com/17746067/232324933-daef994a-bc75-4ba9-9458-04bbe39c0753.png)
![inbox](https://user-images.githubusercontent.com/17746067/232324953-4c25bb32-8317-46c9-816a-e060b342a798.svg)

2023-04-17 17:34 UTC, ericfennis commented
@karsa-mistmere oh yeah that's also possible!

2023-04-17 21:13 UTC, danielbayley commented
20x18 version pushed… @karsa-mistmere @ericfennis See what you think?

2023-04-18 19:50 UTC, jguddas commented
You can use a single arc with a `4px` radius instead of the two curves `M15.7 13.5a4 4 0 0 1-7.4 0`

<img width="48%" src="http://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTUuNyAxMy41YTQgNCAwIDAgMS03LjQgMCIgLz4KPC9zdmc+.svg"/> <img width="48%" src="http://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNIDE1LjcgMTMuNSBDMTUuMSAxNSAxMy43IDE2IDEyIDE2Ii8+CiAgPHBhdGggZD0iTSAxMiAxNiBDMTAuMyAxNiA4LjkgMTUgOC4zIDEzLjUiLz4KPC9zdmc+.svg"/>

2023-04-19 13:05 UTC, danielbayley commented
> You can use a single arc with a `4px` radius instead of the two curves `M15.7 13.5a4 4 0 0 1-7.4 0`

These links are broken… Can you post the full `path`?

2023-04-19 13:20 UTC, karsa-mistmere commented
@jguddas: I'm afraid that path you posted is not quite right, it makes the path not pixel perfect anymore:
![image](https://user-images.githubusercontent.com/17746067/233087529-0651076c-bd02-4d9b-86b9-b96fcf33eb71.png)

2023-04-19 22:49 UTC, danielbayley commented
> > @jguddas: I'm afraid that path you posted is not quite right, it makes the path not pixel perfect anymore:
> Oh no, you are right 😞

Can that not be done then? Leaving this one ready to go…?

2023-04-27 16:41 UTC, karsa-mistmere requested changes
`inbox-in` and `inbox-out` have different arrow sizes, let's make them the same size (either 6x6 or 6x8 both).

2023-04-27 19:13 UTC, danielbayley commented
> `inbox-in` and `inbox-out` have different arrow sizes, let's make them the same size (either 6x6 or 6x8 both).

So here are possible options, as far as I can tell… Unfortunately, they all have trade-offs: 😞

<img width="176" alt="Untitled" src="https://user-images.githubusercontent.com/7797479/234966830-207d1fcd-9518-4eec-ada2-f7f82582d0e8.png">

<img width="90" alt="Untitled" src="https://user-images.githubusercontent.com/7797479/234966289-6ca8f8cb-543f-4770-b1ab-dec1d6d2b1bf.png">

Row:
1. (existing): Arrows fit nice and snug, but are _slightly_ different lengths
2. (6x8): Arrows equal length, but spoils `inbox-out` tray base shape
3. (6x7): Compromise, but `inbox-in` doesn’t line up nicely
4. (6x6): Arrows equal length, but `inbox-in` doesn’t line up nicely at the top, plus `inbox-out` arrow doesn’t fit nicely at the bottom now either
5. (6x8): Arrows equal length, but I think a slight violation with `inbox-out`

@karsa-mistmere @ericfennis @jguddas What do we think?

Personally I went for option (row) 1…

2023-04-27 20:49 UTC, ericfennis commented
I agree with @karsa-mistmere. I think it's more important the the arrows are on smart place. And equal then other arrow icons.

2023-04-28 16:02 UTC, danielbayley commented
Hmm, ok well if we are going with 6x6px arrows, that actually opens up a bunch of other possibilities… 🙈

Like matching the `square` icon base shape better…

<img width="132" alt="Untitled" src="https://user-images.githubusercontent.com/7797479/235195847-b6e448f8-67fa-4217-b118-6c70c19e7ca4.png">

<img width="257" alt="Untitled" src="https://user-images.githubusercontent.com/7797479/235196158-dd7bc941-d3ec-43f2-a458-e6515988253a.png">

<img width="173" alt="Untitled" src="https://user-images.githubusercontent.com/7797479/235195953-1298c999-2246-4124-92b1-4c184c44e060.png">

<img width="338" alt="Untitled" src="https://user-images.githubusercontent.com/7797479/235196248-6d2c8e8c-d216-4141-b745-ef15518bb687.png">

@karsa-mistmere @ericfennis Thoughts on these?

2023-04-29 09:21 UTC, ericfennis commented
@danielbayley Nice designs, I really like the first set, just simple and nice to look at.

2023-05-03 12:52 UTC, karsa-mistmere commented
@danielbayley: Hard to compare these without 100% views. Can you provide one with one row for each version of icons?

2023-05-04 12:03 UTC, danielbayley commented
> @danielbayley: Hard to compare these without 100% views. Can you provide one with one row for each version of icons?

Sure:

<img width="336" alt="Untitled" src="https://user-images.githubusercontent.com/7797479/236197764-8cd860e5-dad8-40bb-9e08-07e4d661c17a.png">

Rows 1 & 2 are 18x16px, slightly different variations. Row 3 is 20x16px, row 4 is 20x18px, and row 5 is 18x18px…

<img width="666" alt="Untitled" src="https://user-images.githubusercontent.com/7797479/236197912-478dc585-1c6e-4b65-95b2-f51ecf0ea11e.png">

2023-05-06 05:39 UTC, karsa-mistmere commented
Thanks, but this isn't at 100%. 😅
By a 100% view we mean one where 1px is literally 1px, so icons are rendered at 24by24px.

2023-05-06 18:12 UTC, danielbayley commented
> By a 100% view we mean one where 1px is literally 1px, so icons are rendered at 24by24px.

@karsa-mistmere I was just taking screenshots at 100% (‘actual size’) in Illustrator, but it’s actually double size… Anyway, see updated https://github.com/lucide-icons/lucide/pull/998#issuecomment-1534652733 …

2023-05-06 19:16 UTC, karsa-mistmere commented
> > By a 100% view we mean one where 1px is literally 1px, so icons are rendered at 24by24px.
> 
> @karsa-mistmere I was just taking screenshots at 100% (‘actual size’) in Illustrator for convenience, but it’s actually double size in practice… Anyway, see updated [#998 (comment)](https://github.com/lucide-icons/lucide/pull/998#issuecomment-1534652733)

That's very definitely still not at 100%, I'm afraid. 😕 
Instead of making a screenshot of your Illustrator page, you're going to have to export it (that will also get rid of artboard outlines).

> Hopefully #1180 being `merge`d will reduce the need for screenshots anyway…

Well, in general surely, in this scenario, not really, since you normally wouldn't have 4 or 5 versions for each icon in a PR.

2023-05-06 20:05 UTC, jguddas commented
Before the refine it looked perfect, now it feels too small IMO.

2023-05-06 20:17 UTC, danielbayley commented
> That's very definitely still not at 100%, I'm afraid.

It definitely is showing as 24x24px for me (@2x, so 48x48, as I’m on a ‘retina’ device… It renders for me the same as the [preview](https://github.com/lucide-icons/lucide/pull/998#issuecomment-1494857232) bot now)… But here is the direct export anyway…

![Artboard 1](https://user-images.githubusercontent.com/7797479/236644910-4e120270-076b-4a8f-b622-c3dcaf44f18a.png)

2023-05-06 20:25 UTC, danielbayley commented
> Before the refine it looked perfect, now it feels too small IMO.

Think iv’e laid out all the possible options here https://github.com/lucide-icons/lucide/pull/998#issuecomment-1534652733 and here https://github.com/lucide-icons/lucide/pull/998#issuecomment-1537216126 … Which row do you think? @jguddas

2023-05-06 20:29 UTC, jguddas commented
> Which row do you think?

3

2023-05-07 12:13 UTC, karsa-mistmere commented
Thanks, this works. :)

Looking at the 100% (or 1x) versions, I still feel like the arrows are a bit weak and also that maybe the `inbox-in`/`inbox-out` use cases aren't as apparent as they should be, since the arrows don't actually point from and to the outside of the inbox.

How about something like this?

![image](https://user-images.githubusercontent.com/17746067/236676337-e59953bc-748e-45a7-8d55-408a8ae8cfc3.png)
![Artboard 1](https://user-images.githubusercontent.com/7797479/236644910-4e120270-076b-4a8f-b622-c3dcaf44f18a.png)
(other iterations for comparison)

2023-05-07 16:46 UTC, danielbayley commented
> I still feel like the arrows are a bit weak
> the arrows don't actually point from and to the outside of the inbox.

Probably because they were shrunk to 6x6px… :)

> How about something like this?

Not sure about the version without any sides… it looks too much like a phone (`phone-incoming`/`outgoing`…) and also feels out of place with the others.

I think putting aside the arbitrary restriction of the 6x6px arrow frees up some potentially better options…

![Artboard 1](https://user-images.githubusercontent.com/7797479/236690688-da27d662-f903-48e6-bf18-ccd25573ec69.png)

<img width="106" alt="Artboard 1@2x" src="https://user-images.githubusercontent.com/7797479/236690699-2795f535-cbd5-4d38-aad2-8ab4572c0e43.png">

![Artboard 1@4x](https://user-images.githubusercontent.com/7797479/236690931-9e065af9-9099-44c7-9c61-930089dae323.png)

2023-06-17 10:28 UTC, danielbayley commented
> This PR is stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 5 days.

😢

2023-06-17 10:57 UTC, jguddas commented
> > This PR is stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 5 days.
> 
> cry

@karsa-mistmere deserves the break. @ericfennis what about working on the [bus-factor](https://en.wikipedia.org/wiki/Bus_factor) for the reviews?

2023-06-17 11:16 UTC, danielbayley commented
> @karsa-mistmere deserves the break. @ericfennis …

No doubt! Maybe the `stale` bot is a bit too enthusiastic…?

2023-06-18 07:52 UTC, ericfennis commented
@danielbayley @jguddas Sorry guys. I got so much work lately. Full-time job and lot things to do beside that. I hope next week I will get some more time to complete some PRs.

So I'm not hit by a bus 😅.

2023-06-18 08:30 UTC, danielbayley commented
> Sorry guys…

@ericfennis No worries! Tell me about it… Part of my motivation to get all these drafts over the line is for other projects… Trying to focus more on one thing at a time, rather than always being spread too thin.

> So I'm not hit by a bus 😅.

Ha remember to look both ways! 🚌👀

2023-07-17 09:55 UTC, karsa-mistmere commented
To be honest, I wanted to give this one some rest, as I was and still am less than enthusiastic about these changes, and I still feel like something like this would just work better for `in` and `out`:

![inboxes](https://github.com/lucide-icons/lucide/assets/17746067/548532d6-3dfd-46dc-b0da-264494c5f6f8)

(Note that these are the same arrows as in `file-in` and `folder-in`)

2023-12-25 09:10 UTC, karsa-mistmere commented
We should also take into consideration that `inbox` currently uses the exact same shape as `hard-drive`.

2023-12-29 22:52 UTC, danielbayley commented
> We should also take into consideration that `inbox` currently uses the exact same shape as `hard-drive`.

Agreed the outer shape should match `hard-drive`. But also for consistency, the bevel should match [`wallet-cards`](https://lucide.dev/icons/wallet-cards)—as was the original intent… The more jagged edges don’t really fit the curvature of all the other icons either.

2024-01-13 10:17 UTC, ericfennis commented
The icons don't look very consistent with each other.

I think we could improve this by using the same place as the dot for all the `plus` and `min` icons. And for the `inbox-in` and `inbox-out` use the same arrow as the `phone-forwarded`.

<img width="684" alt="image" src="https://github.com/lucide-icons/lucide/assets/11825403/36a15232-906c-40d9-ab3a-4b4a0592aad6">

2024-05-18 19:39 UTC, closed without merging